### ISSUE TITLE
How to sync with node http request

### ISSUE THREAD

**Issue by Awakening-j** [NodeRedis/node_redis#1001]
How to let http response sync with `redis` query response.  
at present, http response return before redis callback  

![2016-03-07 15 45 45](https://cloud.githubusercontent.com/assets/8085088/13563312/ae881f3a-e47b-11e5-87b2-07f27cd60d13.png)
![2016-03-07 15 46 41](https://cloud.githubusercontent.com/assets/8085088/13563330/d13c7d28-e47b-11e5-9419-b868ba272d92.png)

**Comment by BridgeAR** [comment]
The API is async and the question is not specific to node_redis. As this is something fundamental in NodeJS, I recommend to read something about that [topic](http://book.mixu.net/node/ch7.html) (I just googled for something and that came up).

You'll have to change your getData function to receive a callback and in that callback you return the data.

**Comment by Awakening-j** [comment]
@BridgeAR thanks, I write the `res.send` in redis callback, then it works
