### ISSUE TITLE
Redis client doesn't try to reconnect

### ISSUE THREAD

**Issue by noppanit** [NodeRedis/node_redis#1007]
I'm trying to use the example of retry_strategy but it seems like my client just crash without trying to reconnect..

* **Version**: 2.5.0-1
* **Platform**: What platform / version? I'm using nodejs 4.2.2, Redis 3.0.7
* **Description**: Redis client doesn't reconnect

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

Here's my code

```
'use strict';

var redis = require('redis');
var config = require('../config');

var state = {
  db: null
};
module.exports = {
  connect: function connect(done) {
    if (state.db) {
      return done();
    }
    var client = redis.createClient({
      host: config.redis.url,
      port: config.redis.port,
      retry_strategy: function retry(options) {
        console.log(options);
        if (options.error.code === 'ECONNREFUSED') {
          console.log('connection refused');
        }
        if (options.total_retry_time > 1000 * 60 * 60) {
          return new Error('Retry time exhausted');
        }

        return Math.max(options.attempt * 100, 2000);
      }
    });

    client.on('error', function error(err) {
      console.log('error');
    });

    client.on('reconnecting', function reconnecting() {
      console.log('Connection reestablished');
    });

    client.on('connect', function connect() {
      console.log('connecting');
    });

    client.on('ready', function ready() {
      state.db = client;
    });

  },

  get: function get() {
    return state.db;
  },

  close: function close(done) {
    if (state.db) {
      state.db.quit();
      return done();
    }
  }
}
```

Here's the error I got

```
Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by BridgeAR** [comment]
@noppanit I tried to reproduce the error but for me it works fine with the code you provided. I just switched the port to a nonexistent one. Would you be so kind to also post a stack trace?

And I don't see any place in your code where this error could be printed, since you print "error" in the error listener.

Please be aware, that commands can still be rejected with that error in their callback if the command was fired before the connection dropped but did not answer yet.

**Comment by noppanit** [comment]
There's an error on my end. Sorry for confusion and thanks for your reply. I'll close the issue now.
