### ISSUE TITLE
Get ' ERR wrong number of arguments for 'info' command ' when using simple.js

### ISSUE THREAD

**Issue by theFool32** [NodeRedis/node_redis#1008]
* **Version**: 2.5.1
* **Platform**: NodeJS v4.2.4 on Centos 6.6 32 bit
* **Description**:  get `Error Error: Ready check failed: ERR wrong number of arguments for 'info' command` when using the simple.js from Usage in README.md. However, it's satisfied with `createClient({no_ready_check: true})`.

**Comment by BridgeAR** [comment]
@theFool32 I'm able to run the example without any issues. What redis version do you use? My best guess is that a older redis version did not support the default argument and it's not fully documented that way. Would you be so kind and run the same code with 2.5.0 to verify my guess?

**Comment by theFool32** [comment]
@BridgeAR Thx!  The redis server I use is v2.4.10. I have tried node_redis@2.5.0 and it works.

**Comment by BridgeAR** [comment]
I recommend to update to a newer redis version but nevertheless, this should work properly with 2.4 again. 2.5.1 should not have broken anyone's code.

**Comment by BridgeAR** [comment]
@theFool32 @iefserge it would be great if you could verify that v.2.5.2 fixes your issue :)

**Comment by theFool32** [comment]
@BridgeAR v.2.5.2 fixes it. Thank you for updating.
