### ISSUE TITLE
Values for client.server_info get not updated

### ISSUE THREAD

**Issue by boristian** [NodeRedis/node_redis#1011]
* **Version**: 
  * node_redis: 2.5.2
  * redis: 3.0.7
* **Platform**: 
 * Node.js v4.4.0 (LTS)
* **Description**: In contrast to [changelog.md](https://github.com/NodeRedis/node_redis/blob/fc9967a14000dc871deeec3956d447afd61ec9c4/changelog.md), the values for ```client.server_info``` get not updated. In the minimal example ```uptime_in_seconds``` will stick to the initial value.
* **Minimal example**:
```javascript
const redis = require('redis')

const client = redis.createClient()

client.on('connect', () => {
  setInterval(() => {
    console.log(client.server_info.uptime_in_seconds)
  }, 2000)
})

// output:
// 1611
// 1611
// 1611
// ... and so on
```
Everybody who worked on this software, thank you for sharing your work. It's awesome.

Greetz,
boristian

**Comment by BridgeAR** [comment]
Hey @boristian. Thanks for your concerns but in this example the `info` command is very likely only called once. It is triggered right after the connect, before the first interval of two seconds has ended and then you do not call info ever again, so the data in the `server_info` is going to stay the same.

If you want to see this working your interval should look something like:
```js
setInterval(() => {
    client.info((err, res) => {
        console.log(client.server_info.uptime_in_seconds);
    });
}, 2000);
```

**Comment by boristian** [comment]
@BridgeAR Thank you for your answer, i didn't think of that.
