### ISSUE TITLE
Combination of .keys and .del together isn't obvious with prefix

### ISSUE THREAD

**Issue by glenswift** [NodeRedis/node_redis#1012]
* **Version**: node_redis v2.5.1 and redis v3.0.7
* **Platform**: node.js v5.6.0 under ubuntu 14.04
* **Description**: 

I've spent several hours trying to achieve why my simple combination of `.keys` and `.del` is not working. The fact is when you're passing prefix with options to `createClient` behavior of functions is slightly different.

Here's my non working code (sorry for generator):

    const client = redis.createClient({
      host: 'localhost',
      port: 6379,
      prefix: 'blah:'
    });

    /* ... */

    /* the purpose of the code is to delete all keys matching prefix from configuration */
    suspend.run(function* () {
      const rows = yield client.keys('*', suspend.resume());
      // matches ALL keys including ones without prefix, i.e. ["foo", "blah:bar"]
      for (let row of rows) {
        yield client.del(row, suspend.fork());
        // appends prefix before deletion trying to delete "blah:foo" and "blah:blah:bar"
      }
      yield suspend.join();
    });

So, as you can see `.keys` doesn't work with prefix and `.del` does. I'm not sure if it is by design or bug but if you have only keys with prefix in database as I do, it's pretty tricky to get why the code isn't working. If it is by design it would be great to have at least mention about this in readme.

**Comment by vanjavanjavanja** [comment]
Starting with redis 2.6.0, you can run lua scripts, which execute atomically. I have never written one, but I think it would look something like this:
`EVAL "return redis.call('del', unpack(redis.call('keys', ARGV[1])))" 0 prefix:*`

**Comment by BridgeAR** [comment]
This is by design. The reason is, that keys have to return the "real" value, otherwise you can't determine what keys exist on the sever. Therefor that command is not prefixed.

I can imagine that it is not always intuitive and therefor I guess it would be nice to document that properly. @glenswift would you be up for such a PR? :-)
