### ISSUE TITLE
Idle event deprecated

### ISSUE THREAD

**Issue by ianmaddox** [NodeRedis/node_redis#1014]
The code is tossing a warning that idle events are deprecated and will be removed. We have a decent use case for workers who read off of a list with brpop. Waiting for idle before firing off another brpop command is a very low overhead and clean means of implementing a queue:

    function getWork() {
        console.log("Waiting for work...");
        // Watch the work queue for new jobs
        redis.brpop("queue", 0, (e,o) => {
            // We got a job. Decode the payload.
            var payload = JSON.parse(o[1]);

            // DO WORK HERE
            var response = {};

            // The incoming request is expecting a payload delivered to the key they provided. Do not disappoint.
            redis.lpush(payload.key, response);
        });
    }
    redis.on("idle",()=>{getWork()});

**Comment by mranney** [comment]
You can get the same effect by putting a call to getWork() as the last line of the brpop callback. I think that's how most people do it.

**Comment by BridgeAR** [comment]
If you put the recursive call in a nextTick you won't reach the maximum call stack in a long running app.

As no one else had any use case I'm going to close this.
