### ISSUE TITLE
Unable to connect to different db-numbers from url 

### ISSUE THREAD

**Issue by kishor-bhatt** [NodeRedis/node_redis#1025]
Hi,
I want to connect to non default ( db != 0) redis instances.
I called createClient() as -
     redis.createClient({'url':'redis://xxx.xx.xx.xxx:6379/1'});
but everything connects to default db-number  ie '0'
I wrote a sample to get keys count for different db-numbers,but in every case gives same count 2790
If same is done in redis-cli gives count 2790 for DB '0' and for other db-numbers gives empty list,which is correct behaviour.
How to do the same here in redis module, is there anything i am missing ??
Thanks a lot in advance.

My sample is -
var redis = require('redis');
redisClient.on('error', function (err) {
    console.log('Error ' + err);
});

redisClient.on('connect', function () {
    console.log('Redis is ready');
    redisClient.keys('*',function(err,result){
        console.log('Key 0:'+result[0]);
        console.log('Keys count:'+result.length);
        redisClient.end();
    });
});

configuration in redis.conf server file is 
 databases 16

**Comment by BridgeAR** [comment]
Please format your code with the [github markdown](https://help.github.com/articles/basic-writing-and-formatting-syntax/) and fill out the [issue template](https://github.com/NodeRedis/node_redis/blob/master/.github/ISSUE_TEMPLATE.md) as it was provided to you when you opened the issue.

My best guess is that you use a older version that does not support this yet.

**Comment by kishor-bhatt** [comment]
Please get version details 
#### redis 
--[ Redis 3.0.3 ] Release date: 17 Jul 2015

#### node_redis
"version": "2.4.2"

#### node version
v5.0.0

#### OS
CentOS Linux release 7.0.1406 (Core)

#### code -
var redis = require('redis');
var redisClient = redis.createClient({'url':'redis://x.x.x.x:6379/1'});

 redisClient.on('error', function (err) {
     console.log('Error ' + err);
 });

 redisClient.on('connect', function () {
      console.log('Redis is ready');
     redisClient.keys('*',function(err,result){
         console.log('Key 0:'+result[0]);
         console.log('Keys count:'+result.length);
         redisClient.end();
     });
 });

I am going to try with latest node_redis version 2.6.0-0

**Comment by kishor-bhatt** [comment]
It was a version issue and working fine after updating node_redis version to 2.6.0-0

Thanks BridgeAR !!

**Comment by BridgeAR** [comment]
I'm glad I could help. As a hint: you can format your code by using three backticks infront of your code and after cour code. And you can also highlight language specific coloring by adding the language after the opening backticks as in (the comments infront of the backticks have to be removed):

```js
// ```js
// Place your code in here
var foo = 'bar';
// ```
```

**Comment by kishor-bhatt** [comment]
Thanks again, will use it henceforth :)
