### ISSUE TITLE
this.stream undefined (2.6.0-1)

### ISSUE THREAD

**Issue by ifavo** [NodeRedis/node_redis#1030]
Hi there!

We have a setup that uses fakeredis which works with `redis@2.6.0-0` but fails in combination with version `2.6.0-1`.

Here's the failed test:

	  1) actionhero Tests "before all" hook:
		 Uncaught TypeError: Cannot call method 'write' of undefined
		  at RedisClient.write (node_modules/actionhero/node_modules/fakeredis/node_modules/redis/index.js:891:43)
		  at RedisClient.internal_send_command (node_modules/actionhero/node_modules/fakeredis/node_modules/redis/index.js:849:14)
		  at RedisClient.(anonymous function).RedisClient.(anonymous function) (node_modules/actionhero/node_modules/fakeredis/node_modules/redis/lib/commands.js:45:25)
		  at Object.api.redis.subscribe (node_modules/actionhero/initializers/redis.js:102:28)
		  at node_modules/actionhero/initializers/redis.js:188:17
		  at node_modules/actionhero/initializers/redis.js:79:11

In that very line it checks for `this.stream.writeable` where `this.stream` does not exist.

    if (this.ready === false || this.stream.writable === false) {

The issue itself is within the redis module which expects a stream property at that position. I don't know what changed between `2.6.0-0` and `2.6.0-1` but it seems that some code shuffle in commit c2e25a7f7157431597651ebf6866bdbe3c061134 might be the reason.

Cheers,
 Mario

**Comment by BridgeAR** [comment]
The reason here is that fakeredis mocks a internal function and that function changed. I actually want to make all internal functions truly internal (private) to prevent exactly such things but on the other hand I can't think of a decent way how to make a mock similar to fakeredis possible afterwards.

Anyhow, this has to be fixed in fakeredis and I'm going to open a PR for 2.6. Thanks a lot for pointing this out!

**Comment by BridgeAR** [comment]
I decided against fixing this in fakeredis. The lib pinned node_redis to the last version without that change and works therefore again. 
Currently fakeredis mocks a couple internal functions and this is something that no one should rely on. 

Instead it would absolutely be fine to mock the stream and handle it from there on. Not node_redis should be mocked but Redis. fakeredis could read the data provided by node_redis throughout the stream and return the data to the client by returning it to the stream again. That way the user would be safe to use any client that uses a stream that can be mocked and no internals would behave any different and most important: no monkey patching would be needed.
