### ISSUE TITLE
WATCH/UNWATCH Support

### ISSUE THREAD

**Issue by zpappa** [NodeRedis/node_redis#1042]
* **Version**: node_redis 2.6.0-1, redis v 3.06
* **Platform**: Node v4.4.2
What node_redis and what redis version is the issue happening on?
* **Platform**: Node v4.4.2
* **Description**: How does one perform a un-watch on a key after an exec using this API or is that transparent? 

WATCH <key>
MULTI
...
EXEC
UNWATCH

I don't see support for the UNWATCH command  - assuming this is by design and is either transparently set or perhaps not needed? Can you please clarify? Thanks!

**Comment by BridgeAR** [comment]
Calling `multi ... exec` results in unwatching all keys automatically.
Please have a look at the [transactions documentation](http://redis.io/topics/transactions).
