### ISSUE TITLE
ZREM no working, Hi am trying to remove my set form  User Key, but it's not deleting. Returning 0 every time.

### ISSUE THREAD

**Issue by anup36** [NodeRedis/node_redis#1045]
This is the syntax am writing.
 client.zrem("u:9980a8a7-dae8-4ac1-8a8d-5c002132e3dc", "65MEL5eSLQjOKea0ao1wQX:",);

**Comment by BridgeAR** [comment]
Likely the member does not exist and therefore 0 is returned in the (here missing?) callback. This does definitely work in node_redis.
