### ISSUE TITLE
Is there a way to increment hashes?

### ISSUE THREAD

**Issue by adamgajzlerowicz** [NodeRedis/node_redis#1046]
Why is there no way to increment hashes please?
Seems like this is one of the most basics features of Redis and its missing. Unless it is there but I am unable to find it in the documentation. 
I definitely think that this  is a must have feature.

* **Version**: 2.6.0-1
* **Platform**: Ubuntu 14.04

**Comment by dirkbonhomme** [comment]
Can't you do this?
```
redis.hincrby(hashkey, field, 1)
```

**Comment by dirkbonhomme** [comment]
The documentation only describes a few Redis commands. Afaik all commands are supported and they all follow the same kind of implementation as documented in the README :)

**Comment by adamgajzlerowicz** [comment]
That's great - I will test it soon.

I am wondering if other people are also getting discouraged from using the software because of this? Would it be worth while writing a full doc with all features?

Thanks for your help!

**Comment by BridgeAR** [comment]
@adamgajzlerowicz the [README](https://github.com/NodeRedis/node_redis#sending-commands) states multiple times to check the [commands reference](http://redis.io/commands) for a complete list of possible commands. The only documented commands in the README are and should be the ones that are handled special / need some further explanation on how to use them. If you have the feeling that the README is not obvious enough, I'd be glad to receive a pull request to improve it further.
