### ISSUE TITLE
Redis execution context

### ISSUE THREAD

**Issue by sandro-pasquali** [NodeRedis/node_redis#1048]
redis: 3.0.6 / node_redis: 2.42
node: 5.11.0

Context of call site for client command seems to affect functionality. 

`this` in /commands.js:45:24 is correctly set here:

```
BluebirdPromise.then(args => {
  client.delAsync(args);
});
```
But the following construct throws the error below:
```
BluebirdPromise.then(client.delAsync);
```

  TypeError: Cannot read property 'send_command' of undefined
    at RedisClient.(anonymous function).RedisClient.(anonymous function) (/Users/sandro/Desktop/develop/github/taggy/node_modules/redis/lib/commands.js:45:24)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

... where `this` is undefined (hence `this.send_command` throws)

Obviously I can manage call scope at the implementation level, but wondering if the lib should guard against this?

**Comment by BridgeAR** [comment]
To set the context to client can use the [bind](http://bluebirdjs.com/docs/api/promise.bind.html) function. 
This is not specific to node_redis but how promises work in general, so there's nothing wrong here.

You can write:
```js
BluebirdPromise.bind(client).then(client.delAsync);
```

**Comment by sandro-pasquali** [comment]
Thanks for responding. 

The question isn't about how scope works in JS. What I'm interested in is why the api object allows the external world to set its internal scope (which is this case causes a fatal exception using a pretty innocuous and natural language construct).

Anyway, good to know at least.

**Comment by BridgeAR** [comment]
How would you guard against this but binding every function in advance?
