### ISSUE TITLE
Error event streams not showing up on redis.client.on('error');

### ISSUE THREAD

**Issue by ngoctranfire** [NodeRedis/node_redis#1059]
This is happening on mac osx, node_redis 2.6.0-2
var redis = require("redis"),
  client = redis.createClient({
    retry_strategy: function (options) {
      console.log(options);
      return new Error('The server refused the connection');
    },
    port: 80
  });

client.on("error", function (err) {
  console.log("Error " + err);
});

In the past, version(2.5.3), this would emit an error, however, now, after the upgrade, no error is emitted. Instead, just the "end" event is emitted. Is that supposed to be how it works...?

**Comment by BridgeAR** [comment]
Hm, this was an intended change but I guess it's to much of a BC to keep it for the actual release. I tried to prevent any error being emitted as long as it is handled otherwise and in this case you already know that you end the connection, as the retry_strategy returns an error and therefore node_redis is always going to close the connection and stop retrying.

**Comment by ngoctranfire** [comment]
I think that may not be a good assumption right? What if you are already connected and then you get a hset error for some reason. Shouldn't that throw an error? I noticed that its not doing that if the retry_strategy is set too....

**Comment by BridgeAR** [comment]
@ngoctranfire that should not throw an error. The command errors should be handled in the callback and not being emitted. This is only the case if you did not set a callback but a Redis error is returned to make sure the user is able to notice such an error. And this does not change with retry_strategy used or not. The only thing that changes in that case is that a retry is not going to emit an error anymore but return it in that very function.
Therefore there's a very explicit way how to handle those.

**Comment by ngoctranfire** [comment]
@BridgeAR That makes a lot of sense now. I was using the promise versions and then combining it with async/await in the ES7 babel version. The errors were just not thrown and I need to use try{}catch{} statements. That was my issue. Thanks for the clarifications!
