### ISSUE TITLE
hgetall returns object without hasOwnProperty  i.e. Object.create(null)

### ISSUE THREAD

**Issue by edgework** [NodeRedis/node_redis#1062]
* **Version**: 2.6.0-2
* **Platform**: Node.js 0.10 on CentOS
* **Description**: hgetall returns an object not using the Object prototype and therefore does not implement hasOwnProperty.

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by Piefayth** [comment]
Any passerby having trouble, we are currently using this as a workaround.

`Object.prototype.hasOwnProperty.call(obj, prop)`
