### ISSUE TITLE
Invalid function name exported

### ISSUE THREAD

**Issue by LinusU** [NodeRedis/node_redis#1075]
* **Version**: 2.6.0
* **Platform**: Node.js 6.2.0 on OS X 10.11.4
* **Description**: Commit ffaaf0f broke co-redis (mciparelli/co-redis#16) because one of the functions that you export are now named `restore-asking` which is an invalid function name. This is due to a "bug" in thenify which uses the function name inside some `eval`ed code (thenables/thenify#20). I think it would be vice to not export invalid function names...

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by amit777** [comment]
having same issue with co-redis, node 6.2.0 on centos7:
```
SyntaxError: Unexpected token -
    at thenify (/nodeuser/app/node_modules/thenify/index.js:17:15)
```
reverting to 2.6.0-1 fixes it.

**Comment by BridgeAR** [comment]
Fixed in v.2.6.1. @LinusU @amit777 thanks for reporting it and thanks @danmactough for fixing it right away :+1:
