### ISSUE TITLE
Storing Objects and numbers as value of a key in Redis

### ISSUE THREAD

**Issue by sam1111** [NodeRedis/node_redis#1078]
Can I store objects without using JSON.stringify() or Numbers without using number.toString() in redis using node_redis?

**Comment by vitaliylag** [comment]
Redis store data binary safed. You can store data in any format you want. Node_redis allow to work with binary data using buffers.

**Comment by BridgeAR** [comment]
As stated in the README you can only store objects without stringify by using `hmset` currently. No other command accepts this. But it is planned to add transformers to allow this for any command you personally wish.
Numbers are always accepted without converting them to a string beforehand.
