### ISSUE TITLE
Conversion of KEYS to SCAN in the background.

### ISSUE THREAD

**Issue by cv711** [NodeRedis/node_redis#1079]
Hi!

Original issue:

* **Version**: node_redis:2.6.0-2
* **Platform**: Node.js 4.4.2
* **Description**: 
While inspecting with `MONITOR`, when issuing the following commands:
```
client.keys("a:6:*")
// or
client.multi([['keys', 'a:6:*']]).exec()
```
they get converted in the background to: 
`"scan" "0" "MATCH" "a:6:*" "COUNT" "100000"` 
which also alters the format of the expected response from multi.

* **Version**: node_redis:2.6.1
* **Platform**: Node.js 4.4.2
* **Description**: 
While inspecting with `MONITOR`, issuing a `KEYS` command from inside multi does the right thing whereas the vanilla `KEYS` command still suffers that switch.
```
client.keys("a:6:*")
// still becomes
"scan" "0" "MATCH" "a:6:*" "COUNT" "100000"
```

Thanks, 
Chris

**Comment by BridgeAR** [comment]
@cv711 this looks really weird. Would you be so kind and activate the debug mode and show me some code? I can't reproduce this as it is very specific to what code you execute at that point of time.

**Comment by BridgeAR** [comment]
If this really happens, it is very likely that this is either done in your own code or that you use a library that switches to scan.

**Comment by BridgeAR** [comment]
Please reopen if you are sure there is a error with node_redis.

**Comment by cv711** [comment]
@BridgeAR No you were right the library that is using node_redis was overriding the `keys` call with its own implementation, hence the scan issue. I guess it's an optimisation from their perspective.

Thanks for the prompt response.
