### ISSUE TITLE
Publish issues

### ISSUE THREAD

**Issue by ghost** [NodeRedis/node_redis#108]
Hi, I am getting issues when publishing large amounts of data in a publish command. I have attached the stack-trace below:
I believe it to be the size and something happening with the buffering, any help much appreciated!

DEBUG: {}

node_redis: no callback to send error: ERR unknown command '3'
node_redis: no callback to send error: ERR unknown command '$7'
node_redis: no callback to send error: ERR wrong number of arguments for 'publish' command
node_redis: no callback to send error: ERR unknown command '$59'
node_redis: no callback to send error: ERR unknown command 'username=&type=image%2Fjpeg&size=11210848&name=largeimage.jpg'
node_redis: no callback to send error: ERR unknown command '$44764'
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ERR unknown command \'3\'' }
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ERR unknown command \'$7\'' }
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ERR wrong number of arguments for \'publish\' command' }
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ERR unknown command \'$59\'' }
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ERR unknown command \'username=&type=image%2Fjpeg&size=11210848&name=largeimage.jpg\'' }
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ERR unknown command \'$44764\'' }
^C

**Comment by sebs** [comment]
Sitting over this late night, I had the same problem. 
I did not pass a string message, but a object. Changed to string, worked.
