### ISSUE TITLE
Multi exec callback regression

### ISSUE THREAD

**Issue by gillesdemey** [NodeRedis/node_redis#1083]
* **Version**: What node_redis and what redis version is the issue happening on?

node_redis >= 2.6.0, does **not** occur on 2.6.0-2 and 2.6.0-1 though
redis 3.2.0

* **Platform**: What platform / version?

Node 6.2.0 / OSX  10.11.15 (El Capitan)

* **Description**: Description of your issue, stack traces from errors and code that reproduces the issue

The following piece of code should demonstrate the issue:

```javascript
var redis = require('redis')

var client = redis.createClient()

client.multi()
  .keys('*', (err, keys) => {
    console.log('floop')
  })
  .exec((err, replies) => {
    console.log('blergh')
    client.quit()
  })
```

With 2.6.0 it echoes 
`blergh`

With 2.6.0-2 it echoes 
```
floop
blergh
```

So it seems that a recent change no longer calls the callbacks individually for each command in the multi chain.

EDIT: it appears that the `Multi.exec_atomic` command is the one you have to call to make the commands execute atomically and thus trigger the callbacks before exec triggers (not using transactions).

I'm not sure why this was working before the 2.6.0 release, and I couldn't find a reference to it in the release logs — but this solves my issue 😅

**Comment by BridgeAR** [comment]
@gillesdemey that behavior should definitely not change with the new version. Multi.exec and Multi.exec_atomic have the same internal logic for the return values and only differ in case you have no or one command.
The output is working correct for me too in v.2.6.1.

**Comment by gillesdemey** [comment]
You're seeing 

```
floop
blergh
```

with version 2.6.1 when you run the repro?

**Comment by BridgeAR** [comment]
Yes
