### ISSUE TITLE
Redis connection to xyz:6379 failed - connect ECONNREFUSED

### ISSUE THREAD

**Issue by ksushilmaurya** [NodeRedis/node_redis#1084]
I am using node redis in my project and hosted on aws server. I disabled two commands FLUSHALL and FLUSHDB through config file and restart the redis server without using sudo and it is working fine but when I start redis through sudo redis-server & and when I am going to start npm start it is throwing error  "Redis connection to xyz:6379 failed - connect ECONNREFUSED". Please suggest a solution.

**Comment by BridgeAR** [comment]
`ECONNREFUSED` stands for "connection refused by server". So please check if you configured your connection settings correct. You might need another port / host and or tls settings.
