### ISSUE TITLE
ZADD with NX Option

### ISSUE THREAD

**Issue by darksigma** [NodeRedis/node_redis#1085]
Does ZADD in `"redis": "^2.5.1",` of the library come with NX flag support? If not what's the best way to use ZADD with NX?

**Comment by BridgeAR** [comment]
@darksigma this is supported in almost all node_redis versions. Flags are always immediately supported. You can easily test this by running something like:

```js
var redis = require('redis')
var client = redis.createClient()
client.zadd('key', 'NX', 2, 'member', console.log)
```

**Comment by luongs3** [comment]
Hi guys, Could anyone help? How to add option 'NX' now?
Redis ^4.6.5
I've tried redisClient.zAdd(REDIS_SORTED_SET, 'NX', [{ score: value, value: key }])
But it didn't work

**Comment by leibale** [comment]
@luongs3
```javascript
redisClient.zAdd(REDIS_SORTED_SET, [{ score: value, value: key }], { NX: true })
```
