### ISSUE TITLE
[Question] - Broadcast all

### ISSUE THREAD

**Issue by Dillybob92** [NodeRedis/node_redis#1092]
Hey guys,

Is it possible to send a `redis.publish` to all the active channels? Like a broadcast to all type of method? I know we could keep track of the instances redis is running on, but was just curious if there is some type of internal broadcast to all redis channels command? Thx

-- Btw, been using this for our action rpg for months. Great npm module and never had any issues. So I do appreciate it!

**Comment by BridgeAR** [comment]
I think you're looking for the [pubsub](http://redis.io/commands/pubsub) command.

**Comment by Dillybob92** [comment]
@BridgeAR This doesn't broadcast to all though, only 1 channel

**Comment by BridgeAR** [comment]
The pubsub command itself does not broadcast anything. But you can receive all active channels and call the publish command for all those channels:

```js
const redis = require('./')
const client = redis.createClient()
const importantMessage = 'foo bar'

client.pubsub('channels', (err, res) => {
  if (err) {
    throw err
  }
  if (res) {
    res.forEach(channel => {
      client.publish(channel, importantMessage)
    })
  }
})
```

I hope this helps :-)
