### ISSUE TITLE
Lock Key if someone else is reading it

### ISSUE THREAD

**Issue by GJ2511** [NodeRedis/node_redis#1096]
Hi I am using this module, 
I want some functionality like if I one person is reading data from key others cannot read data from the same key until first one finishes (i.e, some kind of locking to the key which will set when one is reading and after reading lock is released and the key is available to others).

Any suggestion or solutions guys ......

**Comment by BridgeAR** [comment]
This is not a question about node_redis. You find information about Redlock on the Redis page: http://redis.io/topics/distlock
