### ISSUE TITLE
SPOP returns undefined

### ISSUE THREAD

**Issue by ricogabunada** [NodeRedis/node_redis#1097]
* **Version**: 2.6.2
* **Platform**: node v6.2.0/Windows 10
* **Description**: spop returns undefined 

Hi! :D So, I'm new with node redis and I have this problem. I want to use the spop and it returns undefined. But if I do sismember using the same data I used in the parameter for spop, it returns 1 which means it can see the data. Is there any wrong with my implementation or syntax ? Below is my snippet:

```
redis._CLIENT.smembers( 'someKey', ( err, res ) => {
   res.forEach( ( result ) => {
      let parsed = JSON.parse( result );
      if ( parsed.someId === someObject.someId ) {
         redis._CLIENT.spop( 'someKey', result, ( spoperr , spoprep ) => {
            console.log( 'spoprep: ', spoprep );
	        console.log( 'spoperr: ', spoperr );
         } );
      }
   } );
} );
```
```
//output
spoprep:  undefined
spoperr:  { ReplyError: ERR value is not an integer or out of range
    at parseError (C:\wamp\www\socket-server\node_modules\redis-parser\lib\parser.js:161:12)
    at parseType (C:\wamp\www\socket-server\node_modules\redis-parser\lib\parser.js:222:14)
  command: 'SPOP',
  args:
   [ 'someKey',
     '{"a":"someText","b":"someText2","c":"someText3"}' ],
  code: 'ERR' }
```
THANK YOU VERY MUCH ! :D 

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
@ricogabunada as you can see in your output, Redis returned an error and not undefined. [SPOP](http://redis.io/commands/spop) count argument ("result") is ambiguous. It should be a number instead of a string.

**Comment by ricogabunada** [comment]
@BridgeAR  I see. Thank you for the response! :D
