### ISSUE TITLE
node_redis: Deprecated: The HSET command contains a "undefined" argument.

### ISSUE THREAD

**Issue by jonahzheng** [NodeRedis/node_redis#1102]
node_redis: Deprecated: The HSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.

how to deal with this.

**Comment by BridgeAR** [comment]
Please check where you use the `HSET` command. It seems like you pass undefined values to Redis and they are saved as a string with the value "undefined".
