### ISSUE TITLE
Incorrect hash keys returned when using return_buffers = true;

### ISSUE THREAD

**Issue by aclelland** [NodeRedis/node_redis#1105]
* **2.6.2**: What node_redis and what redis version is the issue happening on?
* **Node v4.2.1 & v6.0.0 - Ubuntu**: What platform / version? (For example Node.js 0.10 or Node.js 5.7.0 on Windows 7 / Ubuntu 15.10 / Azure)
* **Description**: If the Keys of a hash contain unicode characters the library will return the names of the keys incorrectly if the client is created with return_buffers set to true.

**return_buffers = false**
```
var redis = require('redis');
    var client = redis.createClient();
    client.hset("test", "ÿKEYNAME", true);
    client.hgetall("test", (err, result) => {
        console.log(result);
    });
```
> { 'ÿKEYNAME': 'true' } //this is the expected output

**return_buffers = true**
```
var redis = require('redis');
    var client = redis.createClient({ return_buffers: true  });
    client.hset("test", "ÿKEYNAME", true);
    client.hgetall("test", (err, result) => {
        console.log(result);
    });
```
>  'Ã¿KEYNAME': <Buffer 74 72 75 65> } //not the expected output

We encountered this issue when we moved to using Buffers to allow us to save binary data through this library. Some of our tests failed because certain keys couldn't be found for certain users.

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
I know this is inconvenient but this is not going to change soon. At some point you're going to be able to set the return value on your own, but I have little time currently.

The reason that this will not change is that utf-8 can't handle latin-1. But you're able to change latin-1 encoded values to utf-8 ones. If you always want to have utf-8 keys returned, you have to do something like this:

```js
oldObj = Object.keys(oldObj).reduce((obj, key) => {
  obj[new Buffer(key, 'binary')] = oldObj[key]
  return obj
}, {})
```

This is going to convert all latin-1 keys to utf-8 keys by creating a new object that replaces the old one.

**Comment by aclelland** [comment]
Hi,

Thanks for getting back and for the example.

Regards,
Alan
