### ISSUE TITLE
Domain handling regression since 2.5.3

### ISSUE THREAD

**Issue by syrnick** [NodeRedis/node_redis#1106]
- **Version**: node_redis version 2.6.2, redis_version:2.8.19
- **Platform**: OsX; Node 4.3.0
- **Description**: The domain of the domain of the command callback does not match the domain when it the command was issued. That happens despite explicit domain binding in `internal_send_command` . This issue is NOT present in 2.5.3.

Test case:

```
const redis = require('redis');                                                                                                                                
const domain = require('domain');                                                                                                                              
const assert = require('assert');                                                                                                                              

const redisClient = redis.createClient();                                                                                                                      

const testDomain = domain.create();                                                                                                                            
testDomain.run(function() {                                                                                                                                    
    redisClient.spop(`FOOBAR`, function() {                                                                                                                    
        assert(process.domain === testDomain);                                                                                                                 
        console.log('We are good');                                                                                                                            
        process.exit(0);                                                                                                                                       
    });                                                                                                                                                        
}); 
```

**Comment by syrnick** [comment]
That's happening because `process.domain.bind` was moved after handle_offline command call. 

https://github.com/NodeRedis/node_redis/blob/master/index.js#L877

v.s. 

https://github.com/NodeRedis/node_redis/blob/v.2.5.3/index.js#L766

If the client is offline, the domain will unexpectedly switch to the domain that was active when redisClient was created. In the test above it's undefined, but it can also be some other domain.

If domains are used to keep track of req/res in express, it will cause pretty unexpected errors down the chain.

**Comment by syrnick** [comment]
Does this change look reasonable? https://github.com/Hyperbase/node_redis/commit/31f4a86c8848b02580700f5170dd7a4444cf4f7e I couldn't run the test suite on my mac; I'm a bit uneasy about changing the command_obj like that. Is there a better way?

**Comment by BridgeAR** [comment]
@syrnick thanks for the hint and sorry that it took so long. I'll release 2.6.3 in a few minutes
