### ISSUE TITLE
Can't install via NPM

### ISSUE THREAD

**Issue by JayKan** [NodeRedis/node_redis#1112]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/JayKan/.nvm/versions/node/v6.2.0/bin/node',
1 verbose cli   '/Users/JayKan/.nvm/versions/node/v6.2.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'redis',
1 verbose cli   '--save' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData redis
8 silly fetchNamedPackageData redis
9 silly mapToRegistry name redis
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'redis',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'redis',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/redis
14 verbose request uri https://registry.npmjs.org/redis
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:28:27 PM
17 verbose request using bearer token for auth
18 verbose request id c91fea9b4bf451a7
19 verbose etag "CPWFWX5KMA6KE0LHSRS432NLM"
20 http request GET https://registry.npmjs.org/redis
21 http 304 https://registry.npmjs.org/redis
22 verbose headers { 'cache-control': 'max-age=300',
22 verbose headers   'accept-ranges': 'bytes',
22 verbose headers   date: 'Thu, 21 Jul 2016 05:28:28 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-sjc3121-SJC',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1469078907.917995,VS0,VE89',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { 'cache-control': 'max-age=300',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Thu, 21 Jul 2016 05:28:28 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sjc3121-SJC',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1469078907.917995,VS0,VE89',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/redis from cache
25 verbose get saving redis to /Users/JayKan/.npm/registry.npmjs.org/redis/.cache.json
26 verbose correctMkdir /Users/JayKan/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Starting
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: Refusing to install redis as a dependency of itself
44 verbose stack     at checkSelf (/Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/install/validate-args.js:53:14)
44 verbose stack     at Array.<anonymous> (/Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
44 verbose stack     at LOOP (/Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
44 verbose stack     at chain (/Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
44 verbose stack     at /Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/install/validate-args.js:16:5
44 verbose stack     at /Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
44 verbose stack     at Array.forEach (native)
44 verbose stack     at /Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
44 verbose stack     at Array.forEach (native)
44 verbose stack     at asyncMap (/Users/JayKan/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
45 verbose cwd /Users/JayKan/Projects/open-source/experiments/redis
46 error Darwin 15.5.0
47 error argv "/Users/JayKan/.nvm/versions/node/v6.2.0/bin/node" "/Users/JayKan/.nvm/versions/node/v6.2.0/bin/npm" "install" "redis" "--save"
48 error node v6.2.0
49 error npm  v3.8.9
50 error code ENOSELF
51 error Refusing to install redis as a dependency of itself
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

Can't install redis via npm, I've pasted the debug log, any ideas on what's going on here?

**Comment by BridgeAR** [comment]
The reason why it fails is in the error message itself:

```
51 error Refusing to install redis as a dependency of itself
```
