### ISSUE TITLE
getAsync problem

### ISSUE THREAD

**Issue by jbehrouzi** [NodeRedis/node_redis#1120]
HI guys !
i try to use getAsync method but i got " getAsync is not a function error " 
this is my code 
` var temp = redis.createClient();
   temp.getAsync('key').then(function (repl) {
console.log(repl);
}`
can any one help me ?

**Comment by stockholmux** [comment]
Are you `promisifyAll` with bluebird?

**Comment by stockholmux** [comment]
Feel free to reopen if `promisifyAll` doesn't solve your issue.

**Comment by knoxcard** [comment]
promisifyAll fixed it for me...

This is what I did

      app.redis = require('redis').createClient()
      app.redis.on('connect', () => {
        console.log('[PASS]'.green + ' Redis Connected')
        require('bluebird').promisifyAll(app.redis)
        callback()
      })

**Comment by tanvirstreame** [comment]
> redis.on('connect', () => {
>     console.log('[PASS]'.green + ' Redis Connected')
>     require('bluebird').promisifyAll(app.redis)
>   })

Yes, that helped
