### ISSUE TITLE
TypedArray Support

### ISSUE THREAD

**Issue by timoxley** [NodeRedis/node_redis#1125]
The client will happily accept `Buffer` objects for keys and values, but it complains about `TypedArray` objects:

``` js
 db.set('buffer', new Buffer([104, 105]), redis.print);
 db.set('typedarray', new Uint8Array([104, 105]), redis.print);
// => node_redis: Deprecated: The SET command contains a argument of type Uint8Array…
```

Given that `TypedArray` objects are the _native_ container for binary data, it perhaps makes sense to treat them the same as `Buffer` values. Perhaps.

edit: I guess this is only really saving the user from doing a `Buffer.from(typedArray)` around the value they're passing so maybe it's not worth it. I suggest perhaps mentioning coercion to `String` or `Buffer` in the deprecation message.

**Comment by BridgeAR** [comment]
I had another look into this while working on something else and decided against implementing this at the moment.

Currently it's not possible to pass a plain Uint8Array to a stream and as you already mentioned on your own it's easy to do this before passing the value to the client.

The message should be improved though.
