### ISSUE TITLE
Does this library have `eval` and related commands?

### ISSUE THREAD

**Issue by jameshfisher** [NodeRedis/node_redis#1128]
I've searched in https://github.com/NodeRedis/node_redis and in https://www.npmjs.com/package/redis but I can't see any mention of `eval`, `evalsha`, or any of the `script *` commands.

**Comment by BridgeAR** [comment]
node_redis supports all of these commands. They are handled in the redis-commands dependency.

**Comment by jameshfisher** [comment]
Thanks @BridgeAR. Could the supported commands be added to the documentation? I couldn't find them. Alternatively a section could be added describing how I am supposed to find them.

**Comment by jameshfisher** [comment]
Alternatively, is there a way for me to bypass the "Each Redis command is exposed as a function on the client object"? E.g.

```
   client.command("get", "foo");
```

This seems much simpler to me than looking up a command in a list in a different package.

**Comment by BridgeAR** [comment]
All commands should be supported. It's the second sentence in the readme stating that.

And you can already do
```
client.send_command('get', 'foo'[, callback])
```
But this is actually calling the exported function and the only difference for you is you always have to add the "send_command" in addition to everything else.

**Comment by jameshfisher** [comment]
@BridgeAR ah great, thanks! The `send_command` API makes more sense to me, so I'll use that.
