### ISSUE TITLE
Bitfield support

### ISSUE THREAD

**Issue by Flarp** [NodeRedis/node_redis#1130]
Bitfield is an epic command that came out in Redis 3.2.0, and it looks like it's not supported here. Could this be added? It's incredibly useful. [Here's the documentation for it.](http://redis.io/commands/bitfield)

**Comment by Flarp** [comment]
Found out how, if anyone is interested, using ```client.send_command("bitfield", [arr of args])``` does the trick.

**Comment by BridgeAR** [comment]
This is now fixed in [redis-commands](https://github.com/NodeRedis/redis-commands/releases/tag/v.1.3.0). You just have to update the peer dependency.
