### ISSUE TITLE
Not connecting inside docker container

### ISSUE THREAD

**Issue by qwemaze** [NodeRedis/node_redis#1133]
Version 2.6.2
Platform Docker Ubuntu 16.04

```js
var redis = require("redis").createClient({
  host: 'redis',
  port: 6379
});
```
```
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

And redis-cli is fine
```
root@588bcf39d941:/# redis-cli -h redis -p 6379
redis:6379> 
```

**Comment by shivpatel** [comment]
@qwemaze Have you found a solution for this? I've got the same issue where it connects fine outside of a Docker container, but not in the container.

Side note: I'm also referencing an externally hosted Redis where host is not another container's link name, but rather a domain (or IP).

**Comment by shivpatel** [comment]
To anyone else who ends up on this thread: Make sure you're not providing incorrect Redis connection info anywhere else in your app. I was providing it for a socket.io cluster module that used Redis.

**Comment by jmenglis** [comment]
Interesting @shivpatel running into the same issue.  Inside the container I can run redis-cli and connect via 'redis' but nothing else.

**Comment by BridgeAR** [comment]
@jmenglis are you certain you used the correct connection info?

**Comment by jmenglis** [comment]
Disregard.  [Kue](https://github.com/Automattic/kue) was the culprit.
