### ISSUE TITLE
Calling commands dynamically

### ISSUE THREAD

**Issue by jameshfisher** [NodeRedis/node_redis#1138]
When trying to find out which redis commands are available under which names, I was advised to look at the `redis-commands` package to get a list of commands.

A much simpler approach IMO is for me to just pass a string to the `node_redis` library, just like I do to `redis-cli`, or like I do in a Lua script. That is I want to do something like:

```
client.cmd("set", "foo", "bar");
client.cmd("get", "foo");
```

Is this possible? If so, how?

**Comment by BridgeAR** [comment]
Please check the [README](https://github.com/NodeRedis/node_redis/blob/master/README.md). Every command is supported and you do not have to look it up.
