### ISSUE TITLE
The PUBLISH command contains a "undefined" - just no way..

### ISSUE THREAD

**Issue by Kamil93** [NodeRedis/node_redis#1144]
```
node_redis: Deprecated: The PUBLISH command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```

it just appeared 19 times in my log (as a background I publish and subscribe huge amount of messages)

```
Redis server v=3.0.7 sha=00000000:0 malloc=libc bits=64 build=6a622ee4d7201331
node_redis 3.9.2
Node v4.4.7 on FreeBSD 10.3-STABLE

```
There is absolutely no way that I send undefined with PUBLISH command.
Because this is how I always send something:

```
redis.emit = function(channel, name, data) {
	this._pub.publish( channel, JSON.stringify({name: name, data: data}) );
}
```

there always is stringify, so always String with PUBLISH, no undefined.

**Comment by muhammadalie** [comment]
any solution ?

**Comment by BridgeAR** [comment]
@Kamil93 @muhammadalie the warning is only triggered if there is indeed a `undefined` value in the call. In your case the channel may be undefined and therefor the warning is printed.
