### ISSUE TITLE
Commands return numbers as strings, even with string_numbers set to false.

### ISSUE THREAD

**Issue by bokisa12** [NodeRedis/node_redis#1147]
const db = redis.createClient({
	    password: 'PASS',
	    string_numbers: false
    }); 
    db.on('error', console.log);
    db.hgetAsync('currencyUser:XWhatevs', ['bal']).then(bal => console.log(typeof bal));

The code above logs `string`. The value of `currencyUser:XWhatevs -> bal` is `1234`, so it should return a number?

node_redis version: ^2.6.2
node version: v6.6.0
platform: osx 10.11.6

**Comment by BridgeAR** [comment]
@bokisa12 as you can see in the [documentation](http://redis.io/commands/hget) Redis returns a String, so it's always going to be a string if you use hget.
