### ISSUE TITLE
Is there an implementation for HGet?

### ISSUE THREAD

**Issue by camdenorrb** [NodeRedis/node_redis#1150]
I use HSet to set my values and not I want to recieve them, but there doesn't appear to be a HGet?

**Comment by stockholmux** [comment]
`hget` is absolutely included in the module.

` client.hget(key,field,callback);`

I'm am curious where you got the idea that the module doesn't implement `hget` but I'm going to go ahead and close this.

**Comment by camdenorrb** [comment]
There is simply no documentation about it.

**Comment by stockholmux** [comment]
Second sentence of the readme (emphasis added):

> It supports **all Redis commands** and focuses on high performance.

But, yeah, I do get it on some level. Documentation on other modules is often explicit about what is supported and what is not.
