### ISSUE TITLE
redis connection to <ip>:<port> failed- connect ETIMEDOUT <ip>:<port>

### ISSUE THREAD

**Issue by ktkaushik** [NodeRedis/node_redis#1152]
* **Version**: 
node_redis: **2.6.2**
redis version: Redis server v=3.2.1 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=984eb7a74066f119

* **Platform**: Node.js v5.1.1 on Debian 8.3
* **Description**: 
Since the last 2 days, i am randomly getting the below error. I restart my application server with pm2 and here are the logs below - 

```
cron.production-1 (out): 2016-10-01 12:14 -04:00: Error Error: Redis connection to 188.166.179.153:6009 failed - connect ETIMEDOUT 188.166.179.153:6009

cron.production-1 (out): 2016-10-01 12:14 -04:00: Error AbortError: Redis connection lost and command aborted. It might have been processed.
```

Can you please let me what would be the issue? 

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by ktkaushik** [comment]
@shubham1208

**Comment by stockholmux** [comment]
Looks like network connectivity issues - I don't think this has anything to do with the library itself.

**Comment by ktkaushik** [comment]
Looks likely but it happened right after i did a npm install

**Comment by BridgeAR** [comment]
The connection issue might be with your Redis server. There is very likely nothing that we can do for you. Please try debugging your connection to the Redis server.
