### ISSUE TITLE
 GET can't be processed. The connection is already closed.

### ISSUE THREAD

**Issue by Fov6363** [NodeRedis/node_redis#1157]
```
Unhandled rejection AbortError: GET can't be processed. The connection is already closed.
    at handle_offline_command (/data1/baas/nodejs_api_pub_test/node_modules/redis/index.js:843:15)
    at RedisClient.internal_send_command (/data1/baas/nodejs_api_pub_test/node_modules/redis/index.js:873:9)
    at RedisClient.get (/data1/baas/nodejs_api_pub_test/node_modules/redis/lib/commands.js:62:25)
    at RedisClient.tryCatcher (/data1/baas/nodejs_api_pub_test/node_modules/bluebird/js/release/util.js:16:23)
    at RedisClient.ret [as getAsync] (eval at <anonymous> (/data1/baas/nodejs_api_pub_test/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at /data1/baas/nodejs_api_pub_test/lib/include_user.js:83:46
    at Array.map (native)
    at /data1/baas/nodejs_api_pub_test/lib/include_user.js:66:38
    at Function.co.asyncSeries (/data1/baas/nodejs_api_pub_test/lib/assists.js:45:9)
    at Object.Include.counter (/data1/baas/nodejs_api_pub_test/lib/include_user.js:64:8)
    at Object.Include.resolve (/data1/baas/nodejs_api_pub_test/lib/include_user.js:256:17)
    at /data1/baas/nodejs_api_pub_test/routers/user.js:96:32
```
- unkown how to happen
- why redis connection be closed
- my config

```
var options = {
        host: host,
        port: port,
        retry_strategy: function (options) {
            if(options.error && options.error.code == 'ECONNREFUSED'){
                //console.log('Redis connection to ' + host + ':' + port + ' failed,The server refused the connection');
                return new Error('The server refused the connection');
            }
            if (options.total_retry_time > 1000 * 60 * 60) {
                // End reconnecting after a specific timeout and flush all commands with a individual error
                return new Error('Retry time exhausted');
            }
            if (options.times_connected > 10) {
                // End reconnecting with built in error
                return undefined;
            }
            // reconnect after
            return Math.max(options.attempt * 100, 3000);
        }
    };
```

**Comment by polyma** [comment]
+1

**Comment by shuaiming** [comment]
+1

**Comment by BridgeAR** [comment]
You might have either called `quit` or `end` and closed the connection on your end or the connection could not be established (in your config reconnecting 11 times in a row will end retrying) and the connection stays closed.

There is little I can do about this on my end. You should check your that Redis is up and running and reachable by the app.

If you have any further information that might indicate any faulty behavior, feel free to reopen.

**Comment by aftdotleo** [comment]
+1

**Comment by SomaliaDev** [comment]
+1

**Comment by fott1** [comment]
+1

**Comment by BridgeAR** [comment]
As I tried to point out earlier:

Check if you closed the Redis connection. Any command executed after the connection is closed is going to result in this error message because it will not be processed anymore.

**Comment by JeremyCraigMartinez** [comment]
@BridgeAR how do you check if the connection is closed?

**Comment by KateJun** [comment]
@JeremyCraigMartinez  how do you check if the connection is closed? 
Did  you  solve the  problem?  if  redis throw：AbortError: The connection is  already  closed.

**Comment by KateJun** [comment]
Actually   I  did not  execute   redis.quit() or  redis.end()  in   my code.

**Comment by imbyungjun** [comment]
How can i check if the connection is closed?
I'm trying to prevent error case that the connection is closed unfortunately but, try-catch block cannot handle the exception. `AbortError: SET can't be processed. The connection is already closed.`

**Comment by imbyungjun** [comment]
I solved the connection closed issue by checking `client.connected`

**Comment by RomanSolianik** [comment]
why do I get this error? maybe it is not mandatory to have live connection to redis from my application, but I got this error for all my endpoints when redis is down...

**Comment by stockholmux** [comment]
@RomanSolianik Sounds like you're not managing your connection (previously closed) or you have a misunderstanding about the Redis connection model (which always maintains a live connection).

**Comment by RomanSolianik** [comment]
@simontabor okay, but it does not solve my issue. I shut down redis manually and want my application to work as previously (except  of course part related to redis). I tried to call quit() in the 'error', 'end', 'reconnecting' event callbacks, but the behavior is the same - all my app endpoint got this 'NR_CLOSED' error. What I am doing wrong?

**Comment by stockholmux** [comment]
as imbyungjun suggested, you can check `client.connected` before running the command.
