### ISSUE TITLE
Node-Redis support sharding?

### ISSUE THREAD

**Issue by alvinyoong2001** [NodeRedis/node_redis#116]
If Node-Redis didn't support sharding. Do you have any concept on that ?

**Comment by BridgeAR** [comment]
Reference #574

**Comment by ppsreejith** [comment]
In case anyone is still interested in the `RedisShardingClient`, I've published a [module](https://github.com/ppsreejith/node-redis-shard) to transparently distribute requests over multiple Redis instances. Works with `mget`, `mset`, `multi` commands, and It's compatible with `node-redis`. Suggestions for the module and advice on how to integrate with this project (if still needed) would be welcome.
