### ISSUE TITLE
ReplyError: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by akshaykumar12527** [NodeRedis/node_redis#1162]
This is the error you get if you do not authenticate with node_redis. According to the documentation, the options passed to createClient() may include a password property. According to docs:

password: null; If set, client will run redis auth command on connect. Alias auth_pass
With release 2.4.2, this definitely does not happen. If your redis server requires authorization, you must call redisClient.auth(password) as the first call after createClient().

my code:
var redis = require('redis');

var redisClient = redis.createClient({
	host: process.env.REDIS_SERVER,
	port: '6379',
        password: process.env.REDIS_PASS
});
redisClient.auth(process.env.REDIS_PASS);

I have checked my password like millions of time but still got error of NOAUTH Authentication required.Can you please explain why its happening.

**Comment by BridgeAR** [comment]
Please check the Readme. For versions < 2.5 you have to use `auth_pass` instead of `password`.

**Comment by akshaykumar12527** [comment]
Thanks for reply but sir i have already used auth_pass and using version 2.6.2 but still threw error

**Comment by mariothedev** [comment]
Why is this ticket closed ? Problem is still happening ..

**Comment by BridgeAR** [comment]
@mariothedev @akshaykumar12527 please provide some further information, such as debug output. It is difficult to know what happened otherwise. Please use a temporary password or remove the credentials from the log output.

**Comment by mariothedev** [comment]
@BridgeAR  - my fault dude. It turns out using redis & bee-queue(queue using redis) was the source of my problem. I isolated the script and noticed redis itself was working just fine..it's the bee-queue library giving me the issue. 


Here's my working code:

```
const client = redis.createClient({
  host: "35.XXX.XXX.X",
  port: 6379,
  no_ready_check: true,
  auth_pass: 'somepass'
});
```
