### ISSUE TITLE
How to set expiry for Redis cache

### ISSUE THREAD

**Issue by arjungowdaa** [NodeRedis/node_redis#1163]
Hi,
I use the Redis cache via NodeJS app.
Can I know how to set an expiry for Redis cache?

~AG.

**Comment by arjungowdaa** [comment]
@BridgeAR: Can you someone give me some suggestions?

**Comment by BridgeAR** [comment]
@arjungowdaa https://github.com/NodeRedis/node_redis/issues/1000#issuecomment-193155582
