### ISSUE TITLE
ERR wrong number of arguments for 'get' command

### ISSUE THREAD

**Issue by panchalneel** [NodeRedis/node_redis#1175]
Hello,

I am getting error while retriving striing from redis.
var client = redis.createClient();
client.set(channel, channel_subscribers_count);
client.get(channel, function (err, message) {
        console.log('Get value of channel : ' + message);
    });
Error ReplyError: ERR wrong number of arguments for 'get' command

I am using redis npm version 2.6.3 and redis server version 3.2.5

**Comment by BridgeAR** [comment]
Can't reproduce and as a very basic feature, this is very unlikely that the client made a mistake here.

Are you certain the error is coming from this code? Would you be so kind and show the whole part? And are you certain channel is a String? As an addition: you can activate the debug mode and get good stack traces. That way you can check if the error is indeed coming from that line of code.

**Comment by panchalneel** [comment]
[sc-simple-broker.zip](https://github.com/NodeRedis/node_redis/files/618483/sc-simple-broker.zip)

In this zip file index.js contain code

In subClient.on('subscribe', function (channel, count) {}) function client.get() is working perfectly but when i try to get value in  SCSimpleBroker.prototype.unsubscribeSocket() then i am getting Error ReplyError: ERR wrong number of arguments for 'get' command

**Comment by BridgeAR** [comment]
As you can see in the arguments of that function it should receive the socket, the channel name that you want to unsubscribe from and optional the callback:

```js
SCSimpleBroker.prototype.unsubscribeSocket = function (socket, channel, callback) { /* ... */ }
``` 

If you do not pass the channel name and no callback to the function node_redis is going to think you did not pass any arguments at all and does not warn. Currently it is not really possible to improve this and warn in your case as some people pass an explicit `undefined` as callback to node_redis and we can't distinguish this case from yours.

**Comment by panchalneel** [comment]
Ok Thanks :+1:
