### ISSUE TITLE
Deprecated: The AUTH command contains a "null" argument.

### ISSUE THREAD

**Issue by renanalfarth** [NodeRedis/node_redis#1176]
* **Version**: Node redis 2.6.3
* **Platform**: NodeJS 4.4.7 on CentOS Linux release 7.2.1511 (Core) 

In my pm2 log appears the errors bellow:

API-4 (err): node_redis: Deprecated: The AUTH command contains a "null" argument.
API-4 (err): This is converted to a "null" string now and will return an error from v.3.0 on.
API-4 (err): Please handle this in your code to make sure everything works as you intended it to.

I'm using redis to save the auth token of my application like below:

config.redis = {
		host : 'host',
		port  : 6379,
		password	: pwd',
		db: 0,
		socket_keepalive : true
};

redis = rds.createClient(config.redis);

redis.set('authtoken:' + auth_token, JSON.stringify(object));

@mslucas

**Comment by renanalfarth** [comment]
@mslucas

**Comment by BridgeAR** [comment]
@renanalfarth this seems to be an issue with your password. It seems like you provide `null`. Your example does not trigger that warning btw. (and please only use fully self contained examples) so if you have a example that really triggers the error feel free to reopen.
