### ISSUE TITLE
Callback not called on ETIMEDOUT

### ISSUE THREAD

**Issue by jiri-smolik** [NodeRedis/node_redis#1180]
node_redis versions 2.6.2 and 2.6.3
Node v5.5.0
OS Win 10

Hi, I am having problems with getting a key using either client.get or promisified client.getAsync. When redis server host is unreachable, callback is not called /or promise is not ever resolved/rejected, although hooked function on client.on('error', ...) is called with following error stack:

```
Error: Redis connection to ...  failed - connect ETIMEDOUT ...
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
```

Wouldn't be useful to also throw this error to the .get method?

**Comment by BridgeAR** [comment]
@jiri-smolik the reason is that the function itself is never called. I know this is inconvenient but there is no nice solution for this right now. If you want the command to fail right away, please deactivate the offline queue.
