### ISSUE TITLE
AUTH sent for every request

### ISSUE THREAD

**Issue by tmpfs** [NodeRedis/node_redis#1183]
redis@2.6.3, node v6.1.0, ubuntu 16.04

Currently it appears that the AUTH command is sent for every MULTI request.

I notice this when I issue the MONITOR command I can see AUTH being sent. The AUTH command only needs to be sent *once* when the connection is established afterwards the server will consider the client authenticated.

Because we have to choose *very* strong passwords this is unnecessary overhead.

If you would be willing to accept a PR on this I am happy to look into it further.

**Comment by stockholmux** [comment]
Hi tmpfs-

I tried to re-create the issue but couldn't get the results you were describing. Here is what I did:

```
var
  redis   = require('redis'),
  client  = redis.createClient({
    port      : 6371,
    password  : "1234"
  }),
  doAMulti = function() {
    client
      .multi()
      .set('test',1)
      .exec(function(err) {
        if (err) { throw err; }
      })
  };
setTimeout(doAMulti, 1000);
setTimeout(doAMulti, 1500);
setTimeout(function() {
  client.quit();
}, 2000);
```
and my monitor output was:
```
1483365486.196369 [0 127.0.0.1:55801] "auth" "1234"
1483365486.197126 [0 127.0.0.1:55801] "info"
1483365487.198091 [0 127.0.0.1:55801] "multi"
1483365487.198114 [0 127.0.0.1:55801] "set" "test" "1"
1483365487.198124 [0 127.0.0.1:55801] "exec"
1483365487.697004 [0 127.0.0.1:55801] "multi"
1483365487.697024 [0 127.0.0.1:55801] "set" "test" "1"
1483365487.697032 [0 127.0.0.1:55801] "exec"
```

Could you provide the code and the version of the module you are using?

**Comment by BridgeAR** [comment]
@tmpfs please have a look at the code that executes the multi command. It is very likely, that each time you use a multi command a new Redis instance is created before firing the multi command.

**Comment by tmpfs** [comment]
@BridgeAR you are completely correct, my connection caching logic was bad; I do apologize, sorry!
