### ISSUE TITLE
Listening to a specific channel using only one connection

### ISSUE THREAD

**Issue by http91** [NodeRedis/node_redis#1185]
I asked [this](http://stackoverflow.com/questions/41525616/listening-to-a-specific-channel-using-node-redis) on StackOverflow yesterday but haven't got any responses, so I decided to take my chances here.

Version : 2.6.3
Platform : Node.js 7.0.0 on Mac OS X El Capitan
Description : I'm trying to get it to listen to a specific channel.

[Here's the example](https://github.com/NodeRedis/node_redis#publish--subscribe) given on the docs, I changed it a little.

```
var sub = redis.createClient(), pub = redis.createClient();

sub.on("subscribe", function (channel, count) {
  pub.publish("first", "first channel");
  pub.publish("second", "second channel");
});

sub.on("message", function (channel, message) {
  console.log("sub channel " + channel + ": " + message);
});

sub.subscribe("first");
sub.subscribe("second");
```

In this example, sub.on() receives all messages from all channels. How can I set it to listen to a specific channel? This is probably a simple question, but I don't know how to do that.

Here's an example of what I'm trying to achieve in redis-cli. I want to do this in node_redis. Note that when you PUBLISH something to redischat1, only redischat1 is notified, I can see it on the terminal tab 1.

```
SUBSCRIBE redischat1 (terminal tab 1)
PUBLISH redischat1 "this is for redischat1 only" (terminal tab 2)

SUBSCRIBE redischat2 (terminal tab 3)
PUBLISH redischat2 "this is for redischat2 only" (terminal tab 4)
```

**Comment by BridgeAR** [comment]
`sub.on` only receives messages from channel first and second as the client only subscribed to those channels.
