### ISSUE TITLE
HEXIST not working

### ISSUE THREAD

**Issue by maseruka** [NodeRedis/node_redis#1187]
**Version**:  node_redis:2.6.3 , redis:3.2(latest) compiled from source
* **Platform**: Node.js 0.10.25 on Ubuntu 15.10 
* **Description**: am trying to check if a key exists in a harsh with this code 
`client.hexists('member name', function(err, result){
               console.log(err, result);
});`
But its giving me error `{ command: 'HEXISTS', args: [ 'member name' ], code: 'ERR' }`
Note: when i try "HEXISTS member name" in redis-cli, it replies 1 which means that key name exists in harsh member.

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
The redis-client interprets the space as delimiter. 
`Hexists` receives two arguments but you only provide one. Please write `client.hexists('member', 'name', callback)`

**Comment by maseruka** [comment]
Sorry i have figured out the error, i just had to seperate the arguments. So code becomes `client.hexists('member', 'name', function(err, result){ console.log(err, result); });`
