### ISSUE TITLE
JavaScript parser performance issue with MULTI EXEC replies compared to hiredis

### ISSUE THREAD

**Issue by mudge** [NodeRedis/node_redis#1191]
**Version**: node_redis 2.6.5, Redis 3.2.6

**Platform**: Node 6.9.4, macOS Sierra 10.12.2

**Description**: See https://github.com/NodeRedis/node-redis-parser/pull/29 for a benchmark that shows a significant performance regression parsing nested arrays with the new JavaScript parser compared to hiredis.

This has a serious impact on our application due to our usage of `MULTI...EXEC` blocks to perform operations such as `SORT` which cause the reply to include large nested arrays, causing one of our endpoints to take over 10 seconds rather than the previous 2.

For now, we can work around this by explicitly setting `{ parser: 'hiredis' }` when creating a Redis client but this issues a deprecation warning.

Before this is resolved, would it be possible to hold off on fully removing support for hiredis as a parser as the new parser is not universally faster as [described in the changelog](https://github.com/NodeRedis/node-redis-parser/releases/tag/v.2.0.0)?

**Comment by stockholmux** [comment]
Could you tell us a bit more your situation? The 2 to 10 seconds situation sounds very unusual. 

If you have anything that could help us recreate the circumstances, that would be useful.

**Comment by mudge** [comment]
Our problem seems to be particularly bad because it pushes on the weakest part of the new JavaScript parser: big arrays.

I get the following results from `node-redis-parser`'s benchmarks locally (note the significant drop in ops/sec):

```HIREDIS: * nested array x 285 ops/sec ±1.52% (83 runs sampled)
HIREDIS BUF: * nested array x 61.04 ops/sec ±7.56% (55 runs sampled)
JS PARSER: * nested array x 14.15 ops/sec ±1.81% (39 runs sampled)
JS PARSER BUF: * nested array x 14.20 ops/sec ±2.16% (39 runs sampled)

HIREDIS: * big array x 336 ops/sec ±1.03% (87 runs sampled)
HIREDIS BUF: * big array x 158 ops/sec ±1.45% (56 runs sampled)
JS PARSER: * big array x 0.40 ops/sec ±1.32% (5 runs sampled)
JS PARSER BUF: * big array x 0.39 ops/sec ±5.06% (5 runs sampled)
```

As our actual production code isn't easily extracted, here's a high-level overview of the operations we are performing:

1. Given a list of integer IDs (e.g. `1, 2, 3, 4, 5`) and a series of hashes already in Redis of the form `foo_1`, `foo_2`, `foo_3`, etc.
2. Begin a transaction with `MULTI`
3. Store the given IDs in a temporary set with `SADD` (e.g. `SADD foo 1 2 3 4 5`)
4. Use those IDs to fetch multiple fields from the series of hashes with `SORT` (e.g. `SORT foo BY nosort GET foo_*->name GET foo_*->age GET foo_*->height`)
5. Delete the temporary set
6. End the transaction with `EXEC` receiving a multi-bulk reply which will be an array of field values for the given IDs

I suspect our reliance on nested, large arrays of strings might be the issue here?

**Comment by stockholmux** [comment]
That's a pretty common pattern I've personally used with decent performance. Can you give us an idea what the `scard` on _foo_ is?

**Comment by mudge** [comment]
For the 2 -> 10 second call:

* The cardinality of `foo` is 25,000 members
* There are 68 `GET foo_*->` clauses in the `SORT`
* The array reply contains 850,000 values

**Comment by BridgeAR** [comment]
Using sort with multi does indeed not work nicely right now. I'll have a look at it soon.
