### ISSUE TITLE
Improve documentation of renamed commands

### ISSUE THREAD

**Issue by askdesigners** [NodeRedis/node_redis#1192]
The "renamed commands" part of the documentation is very unclear. After spending about 3 hours tracking down strange issues while using Bull (thinking it was an error in my code) I discovered that I had not set the commands option correctly. 

Please make an example in that part of the documentation showing the correct way to set that. Currently it only says `an object with renamed commands` but doesn't mention if the original command or the renamed command should be the key. The source code is also not overly helpful. 

Thanks!

**Comment by stockholmux** [comment]
That's fair - it could use an example and more description. I'll work on it later this week or I welcome a PR.

**Comment by BridgeAR** [comment]
Ping @stockholmux

**Comment by stockholmux** [comment]
Sorry. Got lost in the shuffle. I'll attend to this soon.
