### ISSUE TITLE
duplicate code in commands.js

### ISSUE THREAD

**Issue by leibale** [NodeRedis/node_redis#1193]
There is duplicate code in `commands.js` that convert call to client (`RedisClient` or `Multi`) to a `Command` ([line 32](https://github.com/leibale/node_redis/blob/master/lib/commands.js#L32), [line 74](https://github.com/leibale/node_redis/blob/master/lib/commands.js#L74)).

**Comment by BridgeAR** [comment]
This is intended as otherwise the arguments would leak.
