### ISSUE TITLE
issue with "sadd" within event listener

### ISSUE THREAD

**Issue by siveba** [NodeRedis/node_redis#1196]
I have simple code :
```
var events = require('events'),util = require('util');
	var testingredis = function(){
		var redis = require("redis"), client = redis.createClient();
		var self = this;
		self.on('new_surname', function() { 
			if(client.sadd('surname', 'smith')===true){
					console.log('surname added');
				}else{
					console.log("surname exists");
			}
		});
		setInterval(function(){
			self.emit('new_surname');
		},1000);
	}
	
testingredis.prototype = new events.EventEmitter;
new testingredis();
```

but "client.sadd('surname', 'smith')" is returning TRUE on every event call. I always see "surname added" message, but it should be showed only once. Is it nodejs or redis issue?

**Comment by BridgeAR** [comment]
It is neither a Node.js, nor a Redis issue. Please read the documentation and also read about async functions in Javascript. This is fundamental for programming with JS.
