### ISSUE TITLE
Store object in key with "object key" 's value is an object

### ISSUE THREAD

**Issue by sandangel** [NodeRedis/node_redis#1203]
Version: node_redis 2.6.5
Platform: Arch linux 64bit
Description:

I want to store an object like this:

var object = {
  subKey: {
      grandChildKey: 'value'
  }
}

I use hset like this:

client.hset('key', object, function(err, reply) {
  if (err) {
    console.log(err);
  }
});

but it throw an error:

{ ReplyError: ERR wrong number of arguments for 'hset' command
    at parseError (/home/sand/Local/bluetooth-control/node_modules/redis-parser/lib/parser.js
:181:12)
    at parseType (/home/sand/Local/bluetooth-control/node_modules/redis-parser/lib/parser.js:
291:14)
  command: 'HSET',
  args: [ 'key', { 'subKey': [Object] } ],
  code: 'ERR' }

I tried hmset too but it not worked. 

command: 'HMSET',
  args: [ 'key', 'subKey', { grandChildKey: 'value' } ],
  code: 'WRONGTYPE' }

Any idea?

**Comment by BridgeAR** [comment]
@sandangel you have to stringify (JSON.stringify) the object if you want to use grand child keys. Redis can't handle the data otherwise.
