### ISSUE TITLE
Connection with password

### ISSUE THREAD

**Issue by jgranduel** [NodeRedis/node_redis#1207]
Hi, 

not so much familiar with Redis and even less with node_redis, I spent a lot of time with a "parse error" when I added password.

I got the message: 

>ReplyError
>at parseError ([....path\to]\node_modules\redis\node_modules\redis-parser\lib\parser.js:181:12)
>at parseType ([....path\to]\node_modules\redis\node_modules\redis-parser\lib\parser.js:291:14)

which happened with an upgrade of Redis ([Windows OpenTech 3.2.100](https://github.com/MSOpenTech/redis/releases/tag/win-3.2.100)) for adding to confusion...

Could the response be more meaningful as Redis replies, I guess, "(error) NOAUTH Authentication required."?

Could something like
>node> redis.createClient({ port: 6379, password: "mypassword" })

be clearly written, not to be mistaken with client.auth() method.

Thanks for any precision that could be added into  README if you want to.
Best Regards

**Comment by BridgeAR** [comment]
@jgranduel Thanks for bringing this to my attention. The error message should indeed be visible next to the stack trace. I'm going to fix that soon.

The error message does exist but it currently is not printed and this is obviously not good.

Providing a password in the createClient function does internally call auth. Redis does not provide any other way to authenticate, so it's just a convenient method for the users for automatically calling auth while reconnecting.

**Comment by jgranduel** [comment]
Thanks!

**Comment by BridgeAR** [comment]
Fixed in [v.2.7.0](https://github.com/NodeRedis/node_redis/releases/tag/v.2.7.0)
