### ISSUE TITLE
Monitor mode still does not support IPv6 properly

### ISSUE THREAD

**Issue by qix** [NodeRedis/node_redis#1208]
* **Version**: master
* **Platform**: all
* **Description**:

The regular expression for detecting a monitor line is not all inclusive.

The current version is:
/^[0-9]{10,11}\.[0-9]+ \[[0-9]{1,3} (.(?!\]))+.\]( ".+?")+$/

An example line that my local redis (3.0.6) outputs:
1489434066.308193 [0 [::ffff:172.17.0.1]:43346] "get" "..."

We have a hacked version we use locally, to fix the monitoring I changed the regular expression to something much more general. I'm not making a pull request because I'm unsure of the implications of the more general regexp:
/^[0-9]{10,11}\.[0-9]+ \[[0-9]{1,3} .+.\]( ".+?")+$/

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
@qix thanks a lot for reporting this! Your solution seems just fine. So please feel free to open a PR with that change.

**Comment by qix** [comment]
See PR

**Comment by BridgeAR** [comment]
I just released v.2.7.1. Thanks again
