### ISSUE TITLE
Can't create a redis Client under Node v7.7+

### ISSUE THREAD

**Issue by BarryCarlyon** [NodeRedis/node_redis#1210]
* **Version**: 2.7.0
* **Platform**: Ubuntu Xenial - Node v7.7.
* **Description**: redis_client = redis.createClient(); results in a fatal error
[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

Repro:

```
redis_client = redis.createClient();
```

Output:

```
4|5003 Shi | TypeError: "listener" argument must be a function
4|5003 Shi |     at Socket.once (events.js:307:11)
4|5003 Shi |     at Socket.connect (net.js:943:10)
4|5003 Shi |     at Socket.connect (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:76:27)
4|5003 Shi |     at Object.exports.connect.exports.createConnection (net.js:76:35)
4|5003 Shi |     at RedisClient.create_stream (/home/fredaldo/white_screens/5003_shipnet/shipnet/node_modules/redis/index.js:251:31)
4|5003 Shi |     at new RedisClient (/home/fredaldo/white_screens/5003_shipnet/shipnet/node_modules/redis/index.js:159:10)
4|5003 Shi |     at Object.exports.createClient (/home/fredaldo/white_screens/5003_shipnet/shipnet/node_modules/redis/index.js:1084:12)
4|5003 Shi |     at Object.magento.redis (/home/fredaldo/white_screens/5003_shipnet/shipnet/interface/modules/magento.js:177:26)
4|5003 Shi |     at module.exports (/home/fredaldo/white_screens/5003_shipnet/shipnet/interface/modules/magento.js:264:13)
4|5003 Shi |     at Object.<anonymous> (/home/fredaldo/white_screens/5003_shipnet/shipnet/interface/server.js:461:43)
```

**Comment by BarryCarlyon** [comment]
Running without PM2 I get a error elsewhere:

```
node .
[2017-03-14 09:52:19.713] [INFO] [default] - Booting a Redis connection (well and the shipping loop)
[2017-03-14 09:52:19.750] [INFO] [default] - listening on *:5003
events.js:307
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at Socket.once (events.js:307:11)
    at Socket.connect (net.js:943:10)
    at Connection.connectOnPort (/home/fredaldo/white_screens/5003_shipnet/shipnet/node_modules/tedious/lib/connection.js:429:19)
    at /home/fredaldo/white_screens/5003_shipnet/shipnet/node_modules/tedious/lib/connection.js:411:27
    at Socket.onMessage (/home/fredaldo/white_screens/5003_shipnet/shipnet/node_modules/tedious/lib/instance-lookup.js:28:14)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:546:8)
```

So I'm still digging

**Comment by BarryCarlyon** [comment]
Looks like something has changed in node 7.7, works fine again under node 7.6

Running via node instead of a pm2 start call just means that another module trips before redis does I think?

**Comment by BarryCarlyon** [comment]
Cross linking - https://github.com/tediousjs/tedious/issues/532
Should be fixed in node 7.7.3 https://github.com/nodejs/node/pull/11762

**Comment by BridgeAR** [comment]
That is a Node.js [bug](https://github.com/nodejs/node/issues/11761).

Please always check the stack traces to determine the original of the error.

**Comment by BarryCarlyon** [comment]
No argument there, I just opened the issue, whilst I was working through the problem and didn't self close to leave a trace issue for others until Node 7.7.3 drops

**Comment by BarryCarlyon** [comment]
Tediuous made this change: https://github.com/tediousjs/tedious/commit/ba01a853c211d31292ddafc0da13e6403f4348e5 to combat the node bug.

Is it worth making the same/similar socket fix in case this a is node deprecation possibility in the future @BridgeAR

**Comment by BridgeAR** [comment]
@BarryCarlyon thanks for the hint. I do not have any time to look into this right now. If you find a way to have a work around for the bug, please feel free to open a pull request for it :-)
