### ISSUE TITLE
Add support for GEO* commands

### ISSUE THREAD

**Issue by hrastnik** [NodeRedis/node_redis#1212]
* **Version**: 3.2.0+
* **Platform**: Independent
* **Description**: Add support for following commands
```
GEOADD
GEODIST
GEOHASH
GEOPOS
GEORADIUS
GEORADIUSBYMEMBER
```

I'm getting around this issue using `send_command` but official support would be very much appreciated.

**Comment by BridgeAR** [comment]
@hrastnik they are all officially supported. Are you using a very old version?
