### ISSUE TITLE
ZADD/HMGET limit on the number of parameters

### ISSUE THREAD

**Issue by adriano-di-giovanni** [NodeRedis/node_redis#1217]
I'd like to use single ZADD or HMGET commands instead of a MULTI/EXEC. 

Is there any limit on the number of (score, member) tuples that ZADD can handle?

Is there any limit on the number of fields that HMGET can handle?

**Comment by BridgeAR** [comment]
@adriano-di-giovanni I am not aware of one. Please consult the official docs ([zadd](https://redis.io/commands/zadd), [hmget](https://redis.io/commands/hmget)) for these things.
