### ISSUE TITLE
Error: Redis connection - getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by betimer** [NodeRedis/node_redis#1219]
Error: Redis connection to my-remote-host:6379 failed - getaddrinfo ENOTFOUND my-remote-host my-remote-host:6379

* **Version**: 2.6.5
* **Platform**: node 6.10.1 x64 on Windows 10 )
* **Description**: Only that error log, no other exception; and it seems it did not crash the node server

Not sure this following log is related or not:
at errnoException (dns.js:28:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by rockroller** [comment]
Is this Redis Issue?
Doesn't it look more like your node **my-remote-host my-remote-host** was not available at that tiny moment?
Later error refers to same, It could not resolve your hostname.
Check also [options.lazyConnect] depending what is the purpose.

**Comment by BridgeAR** [comment]
Exactly what @rockroller says. Thanks for that!

**Comment by natotthomer** [comment]
I'm sorry to re-open this, but I'm getting the exact same error (on High Sierra). I don't see the answer provided by @rockroller.

**Comment by stockholmux** [comment]
@natotthomer ENOTFOUND is a connection issue - your node script is not able to connect to the Redis server at the specified address - check your redis server as said by the ghost user (@rockroller evidently left github).

**Comment by natotthomer** [comment]
@stockholmux Thanks! That was exactly the problem.
