### ISSUE TITLE
redis client support es7 async/await feature?

### ISSUE THREAD

**Issue by villins** [NodeRedis/node_redis#1222]
I try the following code:
```
await redis.get(key)
```
always return true value

**Comment by andreagentili** [comment]
Hi @villins, I got the same issue, how did you solve it?
`await redis.hget('something', key);` always return true.

**Comment by andreagentili** [comment]
In case anyone has the same issue: after promisifying with bluebird, call the *Async function signature (e.g. `await redis.getAsync(key)`).

**Comment by villins** [comment]
@andreagentili try this (co-redis)[https://github.com/mciparelli/co-redis] to wrap redis client

**Comment by byk04712** [comment]
+1
