### ISSUE TITLE
ltrim and del cause reids list error during push to list

### ISSUE THREAD

**Issue by dayuanyuan1989** [NodeRedis/node_redis#1224]
I design two task. One, to push data into redis list with rpush,, another to use the redis list data, and then drop the used data. I use ltrim [key] 1 -1 or ltrim [key] [used len of list] -1  or del [key].

When data is too fast to push, and the another task to handle drop used data job, it can cause trim or del length of redis list to a inconrrect value.

task1：rpush [tempkey] [value]   get many http request, push request data into redis list
task2：lrange [tempkey] 0 -1 to get all redis list
            //{use redis list of tempkey, list size is templist}
            ltrim [tempkey] 1 -1  or   ltrim [templist] -1  or  del [templist]

task1 is receicing lots of request, to push list, not stop.
task2 is to do job per 1 second. task2 is used node-schdule

**Comment by dayuanyuan1989** [comment]
If I use 5 threads, to request 20,000 http requests, it cannot cause this error, but if I use 200-500 threads, to request 20,000 requests, the error occur.

**Comment by BridgeAR** [comment]
Please describe a error you're encountering. 

For me it's not clear what issue you have right now. When using multiple threats they can interfere with each other with concurrent access. So the order might not be as expected.
