### ISSUE TITLE
node_redis try reconnecting only once

### ISSUE THREAD

**Issue by abbas-babiker** [NodeRedis/node_redis#1232]
node_redis try to reconnect only once if I started app while Redis server is stopped.
if I stopped Redis server while app is running, it will not stop retrying, which good for me.

console logs (starting app while Redis server is stopped):
**error**: _Redis error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379_
**info**: _Redis ended!_
**info**: _Redis is reconnecting_
**error**: _Redis error: AbortError: Stream connection ended and command aborted. It might have been processed_.

**Comment by BridgeAR** [comment]
I am not sure I fully understand your issue.

node_redis is going to try to connect to your server until an option prevents it from further reconnecting. No matter if Redis is running or not.

The AbortError indicates that a command was fired while trying to connect and it could not be processed, as the connection failed.

**Comment by abbas-babiker** [comment]
Hello BrefgeAR,
found that I was calling client.end(false);  on authentication error

Thanks
