### ISSUE TITLE
Could you change text color of menu on document?

### ISSUE THREAD

**Issue by TonyPythoneer** [NodeRedis/node_redis#1234]
I think the text color is too bright. It makes me hard to read. Especially, when the cursor is on an item of the menu, I am not sure what I click. It should improve the reading experience.

I know this issue is not related to `node_redis` library itself. If other guys have the same issue, please express your recognition.

**Comment by stockholmux** [comment]
Which url are you exactly talking about?

**Comment by TonyPythoneer** [comment]
It's here.

![image](https://cloud.githubusercontent.com/assets/10459119/26435121/83650242-413f-11e7-9ff5-6a939474e859.png)

**Comment by BridgeAR** [comment]
This is a known issue. @TonyPythoneer do you have time to look into this and be so kind and see how to change the colors?

**Comment by TonyPythoneer** [comment]
@BridgeAR It's OK. Where is the document path or repo?

**Comment by TonyPythoneer** [comment]
This changed demo shows on my browser. I suggest list element should be `#00009E` which look darker than before. And then, I also adjust hover effect whose color is `#3ac`, it can make obvious change when  cursor is on the list element. For your reference, I hope you like it.

![image](https://cloud.githubusercontent.com/assets/10459119/26479425/b64deb80-4205-11e7-880b-64db74c015d1.png)

**Comment by BridgeAR** [comment]
Please check the `gh-pages` branch. That's where the website code can be found.

The color seems to be a improvement over the way it was, so I'm fine with that. I guess the hover color should just be a darker tone of the chosen color and maybe add a underline as well?

We also use similar colors to the currently used menu colors in some parts of the text and they might also be changed? :-)

**Comment by BridgeAR** [comment]
Fixed by #1246
