### ISSUE TITLE
send_command not case insensitive for multi/MULTI

### ISSUE THREAD

**Issue by Ramzeus** [NodeRedis/node_redis#1237]
* **Version**: 2.7.1
* **Platform**: Node 7.9.0 on Windows
* **Description**: All commands except for MULTI can be in what ever case I want, but MULTI is compared against 'multi' at https://github.com/NodeRedis/node_redis/blob/master/lib/extendedApi.js#L39

This caused me some trouble and is quite annoying... Would it be possible to do a case insensitive comparison instead?

**Comment by BridgeAR** [comment]
The docs originally said that this is always lower cased. The other commands actually did not fully work before either or they might at least had side effects depending on the options used.

This is now changed and you can use what ever case you want even though I recommend to use camelCase.
