### ISSUE TITLE
node_redis client.set() function hangs forever. Callback was never called. 

### ISSUE THREAD

**Issue by kattakarthik** [NodeRedis/node_redis#1240]
node_redis client.set() function hangs forever. Callback was never called. 

Test case : Invoking client.set() multiple times. Randomly the issue occurs.  

Test code : 
///////////////////////////////////////////////////////////////////////
var client = this.redis_client(key);
client.set(key, value, callback);
//////////////////////////////////////////////////////////////////////

No error logs were seen. The redis server was up and responding when the issue occurred.

* **Version**:   node_redis (latest available) / redis 2.6.5
* **Platform**:  Node v4.2.6 / Ubuntu Ubuntu 16.04.2 LTS

As per my debugging, there is no response coming from the redis server. Hence no reply is sent and callback is not called. 

    this.stream.on('data', function (buffer_from_socket) {
        // The buffer_from_socket.toString() has a significant impact on big chunks and therefore this should only be used if necessary
        debug('Net read ' + self.address + ' id ' + self.connection_id ); //+ ': ' + buffer_from_socket.toString());
        self.reply_parser.execute(buffer_from_socket);
        self.emit_idle();
    });

**Comment by BridgeAR** [comment]
@kattakarthik I am quite certain that the client could not reach your server and that the command landed in the offline queue and was never executed. Therefore the callback was also not called.

You can either deactivate the offline queue (in that case all commands will fail right away if not connected) or check if the client is ready connected.
