### ISSUE TITLE
TTL

### ISSUE THREAD

**Issue by sumanganguly** [NodeRedis/node_redis#1241]
How can we mention TTL of the object stored in Redis

**Comment by murbanowicz** [comment]
How to pass it with the node-redis? It got closed but there is no answer in docs

**Comment by stockholmux** [comment]
@murbanowicz Nothing special - In the case of SET, each argument of the function maps to the argument in Redis. Otherwise, EXPIRE is a command in Redis that will set the TTL of any key.
