### ISSUE TITLE
Internal error on setex call

### ISSUE THREAD

**Issue by matheus-lima92** [NodeRedis/node_redis#1243]
*Version: Redis 2.7.1
*Platform:  Node.js 6.10.3 on Windows 10
*Description: 

Hello, we recently started facing un unexpected error on setex calls. We have a call like this:

client.setex(redis_key,60,JSON.stringify(data));

and we get

TypeError: Cannot read property 'pubsubBound' of undefined
    at RedisClient.originalRedis.RedisClient.internal_send_command (C:\Users\Casanova\Desktop\Aktienow\catalogoservicosapiazure\node_modules\diagnostic-channel-publishers\.dist\src\redis.pub.js:12:22)
    at RedisClient.setex (C:\Users\Casanova\Desktop\Aktienow\catalogoservicosapiazure\node_modules\redis\lib\commands.js:62:25)

To make sure we weren't using bad parameters, we even made a test like this

client.setex("test",60,"test");

and we get the same error. We are using the latest version 2.7.1 and even if we point our createClient() method to a different redis server we still get the same error. Do you have any clue of what could possibly be happening here?

´Thanks

**Comment by stockholmux** [comment]
I think this error is actually in your `diagnostic-channel-publishers.dist` module based on the error output.

**Comment by matheus-lima92** [comment]
I don't think so stockholmux, we aren't even using this package

**Comment by BridgeAR** [comment]
@matheus-lima92 there is no `pubsubBound` property in the code of node_redis and it does seem like you use the mentioned module:

(C:\Users\Casanova\Desktop\Aktienow\catalogoservicosapiazure\node_modules\\__diagnostic-channel-publishers.dist__\\src\redis.pub.js:12:22)
