### ISSUE TITLE
Manual reconnect

### ISSUE THREAD

**Issue by AuspeXeu** [NodeRedis/node_redis#1244]
This is kind of a feature request. Is there any way to manually trigger a reconnect attempt instead of waiting for the timeout defined by the retry strategy?

Many thanks,
Chris

**Comment by jdegger** [comment]
In your retry strategy you can return `0` to immediately try again or `undefined` top stop the retry strategy. I would not recommend trying to reconnect immediately but wait at least 100ms and look at the reason why the connection failed. You can always just write logic into your application to do connection attempts manually.

You can keep track of the connection status through the events if you desire so. I don't think the current implementation lacks any feature going on the description of your issue. 

Let me know if we can be of any help.

**Comment by AuspeXeu** [comment]
How do I trigger a manual reconnect?

**Comment by jdegger** [comment]
The easiest way would be to rewrite logic into the retry strategy which satisfies your needs.

**Comment by AuspeXeu** [comment]
But once I have returned 5000 for instance, I have to wait 5000 until I can reconnect. There is no way to do it any time earlier, right?

**Comment by jdegger** [comment]
When the retry delay is running, the internal function does not allow to be called since it could result in multiple connection attempts.

Could you elaborate on your use case? I am having trouble understanding the use case for your problem.

**Comment by AuspeXeu** [comment]
If you consider using redis to store express session tokens, it would be quite helpful if you for instance trigger a reconnect whenever a request comes in or every n-th request instead of not having the login working for a certain amount of time specified by the `retry_strategy`. I assume a manual attempt could just clear the `setTimeout` in case it leads to a successful connection, no?

**Comment by jdegger** [comment]
You could implement an [Exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) strategy to have faster reconnects but honestly, in normal production ready environments the use case you describe should not really be a problem. It might be worth the effort to find out why your Redis server drops connections so many times when it becomes an apparent problem.

**Comment by AuspeXeu** [comment]
Yeah, I agree. I'll have to invest some time in finding the cause for this. Maybe a manual reconnect is not needed at the moment.
