### ISSUE TITLE
It is not possible to handle errors on providing an invalid connection URL format

### ISSUE THREAD

**Issue by Nysosis** [NodeRedis/node_redis#1245]
* **Version**: 2.7.1
* **Platform**: Node.js v7.6.0 on Windows 7
* **Description**: This is similar to (or potentially a duplicate of) #728, however this is specifically about when you provide an explicit options item of `url` with a url that isn't a valid IANA url.

Replicating code:

```
const redis = require('redis')

const client = redis.createClient({
	url: 'a'
})

client.on('error', (err) => {
	console.error('I was unable to connect')
})
```

Expected output:
Application remains running and has written `I was unable to connect` to stderr

Actual output:
Application crashes with `` C:\Program Files\nodejs\node.exe: src\pipe_wrap.cc:168: Assertion `args[1]->IsString()' failed. ``

I understand that the actual connection error is nodes internal net.js failing, but I would have expected it to fail earlier in the chain with a nicer error.

(Actual calling line in node_redis is https://github.com/NodeRedis/node_redis/blob/master/index.js#L251)

**Comment by BridgeAR** [comment]
Fixed in 2.8.0
