### ISSUE TITLE
How could I execute 'CLIENT SETNAME' ?

### ISSUE THREAD

**Issue by lasting0001** [NodeRedis/node_redis#1248]
* **Version**: 2.7.1
* **Platform**:  Node.js 6.950 on Windows 7 x64
* **Description**: I could't found a appropriate way to execute 'CLIENT SETNAME' command.
Code: client.send_command('CLIENT SETNAME', ['test'], function (err, res) {
    console.log(arguments);
});
It will be error:
{ '0': 
   { ReplyError: ERR unknown command 'CLIENT SETNAME'
       at parseError (D:\Documents\H5\Chat\node_modules\redis-parser\lib\parser.js:193:12)
       at parseType (D:\Documents\H5\Chat\node_modules\redis-parser\lib\parser.js:303:14) command: 'CLIENT SETNAME', args: [ 'test' ], code: 'ERR' },
  '1': undefined }

**Comment by jdegger** [comment]
Hi @lasting0001 the correct syntax would be

```javascript
client.send_command('CLIENT', ['SETNAME', 'test'], function(err, res) {
  console.log(arguments);
});
```

or simply


```javascript
client.client('SETNAME', 'test', function(err, res) {
  console.log(arguments);
});
```
