### ISSUE TITLE
Client subscriptions get dropped

### ISSUE THREAD

**Issue by iamjem** [NodeRedis/node_redis#1249]
* **node_redis Version:** 2.7.1
* **Redis Version:** 3.2.6
* **Platform:** Node.js 6.9.4 on Heroku
* **Description**: Subscriptions eventually disappear, and we consequently stop receiving messages. I am able to confirm that subscriptions no longer exist by executing `PUBSUB NUMSUB CHANNEL_NAME` against the redis server.

The code for setting up the subscriptions looks something like this:
``` javascript
const updateChannel = 'update:channel';
const destroyChannel = 'destroy:channel';
redisSubscriber.subscribe(updateChannel);
redisSubscriber.subscribe(destroyChannel);
redisSubscriber.on('message', this.handleRedisMessage);
```

I can then periodically publish messages to these channels from a separate process. For some period of time, I see logs from the node subscriber process indicating its receiving the messages, and then eventually it stops receiving them. The subscriber process itself is still trucking along emitting other  output. There is never an explicit call to unsubscribe from these channels. Once log output stops from the message handler, I can then confirm that there are no more subscribers from the redis server by using `PUBSUB NUMSUB CHANNEL_NAME`.

I have an `error` event handler attached to the `redisSubscriber` as well, but I have not seen any output from it.

I've begun looking more at the internals of this package to see if there's anything else I could be doing to debug the issue further but would welcome some additional advice.

I'll also note that we use Babel with this project to use some more modern Javascript syntax.

**Comment by iamjem** [comment]
Wanted to update this. I've done a fair amount of additional debugging, and this is looking more like one of two things (maybe even some of both):
1. Heroku Redis has a default idle timeout of 5min. The redis channels I was subscribing to could go 10min or more without getting any messages published and the connection itself would get closed constantly. We are using the [redis buildpack](https://github.com/heroku/heroku-buildpack-redis) which creates a stunnel to keep communications secure, and it typically handles these closed connections automatically by re-connecting. These reconnect don't even seem to surface inside the node process itself (the `reconnecting` event doesn't fire, there's no `error` events, etc). I would see one of my error logs `redis subscriber error error={ Error: Redis connection to 127.0.0.1:6371 failed - read ECONNRESET` occasionally, followed by a `reconnecting` event (which seemed to succeed). I did some isolated testing and idle connection timeouts, or even manual killing of the connection from the redis end (via `CLIENT KILL ...`) recovered and behaved as expected. However, there were cases where my `message` event handler would eventually go quiet, and the redis client itself seemed to be connected (or think it was connected). This leads to the next item ...
2. We are running in Heroku Private Spaces, and there appears to be some known issues with pipes, and unexpected status 141 exit codes crashing processes. After my `message` handlers go quiet, often several hours pass, and then the process crashes from one of these errors. Its possible whatever the underlying issue is with that is the root cause of this, but there's nothing conclusive at this point.

The current solution we're exploring is having a separate publisher client in our node processes that publish heartbeat messages to a heartbeat channel every X seconds. The subscriber client then subscribes to that heartbeat channel, ultimately ignoring the messages, but this keeps the connections active so they don't get closed, and these transient connectivity issues are reduced.

Closing this, if I have more details in the future I'll update here.

**Comment by jdegger** [comment]
Thanks for your detailed followup @iamjem, it's really appreciated.

> However, there were cases where my message event handler would eventually go quiet, and the redis client itself seemed to be connected (or think it was connected). 
I think this part is crucial. If the connection has been established correctly but the subscription still fails we might need to reopen this as a bug.

Is there any way you can verify if the connection is still working? Possibly trying to execute a command like `ECHO` just to verify the connection has been established?

**Comment by iamjem** [comment]
Thats a good idea. I ran my fix with the publisher over night, and because of those constant messages over a heartbeat channel my subscriber continued to receive new messages as far as I can tell.

If the symptoms return, I will try adding a periodic echo on the subscriber as well. Right now I'm working with the team who manages the private spaces runtime to see if we can find more details with the underlying cause.
