### ISSUE TITLE
executing redis eval command to run Lua script in nodeJS

### ISSUE THREAD

**Issue by amit-upadhyay-IT** [NodeRedis/node_redis#1250]
In Redis I run a Lua script through CLI like this:-

        $ redis-cli --eval debug_script.lua key1 key2 key3 key4 , arg1 arg2

So, my Lua script accepts 4 keys and 2 arguments.

Now I want to run the same script in Node.js.

I am using this library for importing Redis in my app.

I didn't find any example which tells about the arguments of redisClient.eval(...) function for executing the Lua script.

Thus I am just hitting something random that might work. But nothing seems to work.

My question: How to execute below command using node.js, so that it returns the same thing as it does when executed through CLI(command-line-interface).

        $ redis-cli --eval debug_script.lua key1 key2 key3 key4 , arg1 arg2

**Comment by jdegger** [comment]
`--eval` is no 'real' redis command but just an extra option of redis-cli. However it's still possible to do what you want:

```javascript
'use strict'
const redis = require('redis')
const client = redis.createClient()
const fs = require('fs')

client.eval(fs.readFileSync('./test.lua'), 2, 'key1', 'key2', 'first', 'second', function(err, res) {
  console.log(arguments);
});
```

Keep in mind that you might wanna do some security checks and that `EVAL` requires more options than `--eval`. Read more about the difference between `--eval` and `EVAL` here: https://redis.io/topics/rediscli#running-lua-scripts

**Comment by martinamunoz** [comment]
Alternatively you can do:
```
  const fileWithScript = fs.readFileSync('./pathToFile.lua') 
  const result = await client.eval(fileWithScript, {
      keys: [key, increment.toString()],
  })
```

**Comment by martianmartian** [comment]
> Alternatively you can do:
> 
> ```
> const fileWithScript = fs.readFileSync('./script.lua') 
> const result = await client.eval(fileWithScript, {
>     keys: ['key1', 'key2'],
> })
> ```

how do you add args in this way?

**Comment by martianmartian** [comment]
.eval(script,{
    keys: ['key1','key2'],
    arguments: ['bitch']
  });

hey Author, you got the key word wrong. it's written in document: arguments not args
