### ISSUE TITLE
publish socket ?

### ISSUE THREAD

**Issue by queenk** [NodeRedis/node_redis#1251]
I`d like to use node redis to pulish a socket object,is that Possible?
```
server.on('connection', function(socket) {
	redisClient.publish("ProxyServer",socket);//
});
```

**Comment by jdegger** [comment]
That would inherently not work. See [this page](https://redis.io/topics/pubsub) for documentation on `pubsub`. 

You could JSON encode an object and then send it over Redis *but* you'd lose all functions included in the object and thus rendering it useless.
