### ISSUE TITLE
Can't upload file more than 1MB suddenly

### ISSUE THREAD

**Issue by tim7004** [NodeRedis/node_redis#1256]
Dear All,
Today I found that some of my files that more than 1MB can't be upload to my s3 bucket. It worked a week ago. Please Help! Thank you!

`
....
function createClient() {
        return require('s3').createClient({
            maxAsyncS3: 20, 
            s3RetryCount: 30, 
            s3RetryDelay: 60000,
            multipartUploadThreshold: 209715200,
            multipartUploadSize: 157286400, 
            s3Options: options
        });
    }
var client = createClient(20);
var params = { localDir: lambdaTmp + '/content', s3Params: { Bucket: exportBucket, Prefix: "content/" } };
console.log('start');
var uploader = client.uploadDir(params);
console.log(uploader);
uploader.on('error', function(err) { console.log(err);
    reject(); });
uploader.on('progress', function() { console.log("progress", uploader.progressMd5Amount, uploader.progressAmount, uploader.progressTotal); });
uploader.on('end', function() { console.log('end');
    resolve(); });
....
`

**Comment by jdegger** [comment]
This does not seem related to node_redis. Please submit your issue to a related repository (like the s3 repo)
