### ISSUE TITLE
set command doesn't override value

### ISSUE THREAD

**Issue by jmejiaz** [NodeRedis/node_redis#1262]
* **Version**: 2.7.1
* **Platform**: Ubuntu
* **Description**:Hi I'm setting a value,  `redisClient.set(1,true)` after some operations I have to reset that key  to `redisClient.set(1,false)` . But when I retrieve the value, it is the same as the initial value `true`.

The return after each operation is `OK`
and the monitor show this log.

```
1501010391.888643: set,1,true
1501010399.513003: set,1,false
1501011626.978686: get,1
```
the client is configured like this 

```
var redis  = require('redis');
var client = redis.createClient();
```

Thanks in advance

**Comment by stockholmux** [comment]
Sounds like a problem with your callbacks, but it's hard to tell. I'm 99.999% sure that this not a problem with the module.

**Comment by BridgeAR** [comment]
@jmejiaz please show a stand alone test case. As already pointed out, this is likely an issue with your calls.

**Comment by jmejiaz** [comment]
@BridgeAR  thanks for your reply. Maybe I'm missing something important here.  Im not using callbacks at all, I'm using it in a synchronous way.

**Comment by BridgeAR** [comment]
@jmejiaz there is no synchronous Redis call. You either have to use callbacks or promises and wait for the result.

**Comment by jmejiaz** [comment]
@BridgeAR Totally my bad, works perfect using  callbacks. Thank you  so much
