### ISSUE TITLE
hincrby produced discrepancies

### ISSUE THREAD

**Issue by ZeroHackeR** [NodeRedis/node_redis#1263]
* **Version**: Redis 2.8.4 / Node_Redis 2.3.0
* **Platform**: Node 4.6.2  / Ubuntu 14.04

I'm having some issues.
I will try my best to explain the issues.
So, please bare with me.

Here's the abstract codes:

	addCredit = function( amount, description, ref, reply ){
		// db is a redis client
		db.hincrby(uid_key, 'credit', amount, function(err, ret){		
			if(err) 
				reply(500, 'db err');
			else { 
				reply(0, {credit: ret});
				
				// send to logger to save
				var before_amount = ret - amount;
				var data = [ uid, description, ref, before_amount, amount, ret ];
				pub.publish('log:credit', data.join("|") );			
			}
		});
		
	};

**Logic**:
1) increase the a user's credit by the amount
2) if success, 
 a) reply with updated amount
 b) log the transaction

Everything went well during our testing. 
But, on production (with 3000 concurrent users), a few users reported discrepancies.

eg: Here's what I found in log for this particular user.

![image](https://user-images.githubusercontent.com/3157700/28819927-c7d2aeae-76d5-11e7-99f1-9a770ae9391e.png)

**How to Read**:
1) Please read from the bottom (easier to understand that way).
2) Before is credit amount before the adjustment is made.
3) Adjust is the adjustment amount
4) After is the amount after the adjustment. 
5) They are recorded after redis's hincrby is called and success
6) eg: for log id 415937417, the user had 740 credit and we made -20 adjustment and final amount was 720.

**The Problem**:
1) As highlighted in Yellow, there is a discrepancy recorded in log. 
2) They are not random values. 

Here's what we found out:
![image](https://user-images.githubusercontent.com/3157700/28820620-563c6ffc-76d8-11e7-97be-f69c95551ce9.png)

1) I think, log id 416111227 is not recorded in redis or some how missing in reids. However, hincrby still returned as success with a return value (that's why we can see it in the log).
2) As we can see at log id 416111915, the value stored in redis and the value returned from nodejs's DB instance are not the same 

So, how can I solve the issue?

**Comment by jdegger** [comment]
Might this be a problem in your server or cluster configuration?

The values you log are the returned values by Redis, those are basically untouched by Node Redis. If the command failed, the log item would not know `ret` with the correct value right so it would not be possible to log that item 'correctly' without it being sent to Redis by Node Redis successfully?

**Comment by jdegger** [comment]
I see you also found this: https://github.com/antirez/redis/issues/2129, is it possible that what they mention is true and your application is modifying the same key at the same time more than once?

**Comment by ZeroHackeR** [comment]
I've reported to Redis and they just said it's application error. :( 
The code is very simple and straight-forward. 
And 99% of the times, there is no issue at all. 

https://github.com/antirez/redis/issues/2129#issuecomment-319331573

> modifying the same key at the same time more than once

@jdegger according to the log, 841 and 839 were recorded at the same time. But, again, redis returned success.

**Comment by stockholmux** [comment]
Well, the obvious thing here is that your logging is not actually connected to Redis - another part of the application (or someone at `redis-cli`, etc. ) could have modified the value between the two actions. Or your application could have died between after a command was sent to Redis but before it could be logged.

A little inefficient, but you could do a `multi` and have a `hget` then a `hincrby` to get the true before and after. This will show a true irregularity with more confidence.

**Comment by ZeroHackeR** [comment]
@stockholmux  Thanks for your inputs.

1) Yes, logging system is using redis pub/sub to get the update events. So, log system will get notified whenever there is a update and it dumps the data to MySQL for reporting/supporting.

2) Nothing is modifying the 'credit' value other than above function. In fact, we are processing about 1,000-3,000 redis messages per second. Among them, only less than 1% of the users are having this discrepancy issue.  

![image](https://user-images.githubusercontent.com/3157700/28831112-bf31761c-76fe-11e7-9176-57b94139153f.png)

3) App didn't die too. Otherwise, we will not even get the callback from `hincrby` and in that case, there will be no log. Now, we got return values from redis and we could log them. 

4) Regarding using `hget` before `hincrby`, my understanding was `hincrby` will return the value after that hincrby operation. So, it isn't the **true**-after-value?

So, what I wanted to know is; as @jdegger suggested, what would happen if the application is modifying the same key at the same time more than once?

**Comment by ZeroHackeR** [comment]
Just received a new case:

![image](https://user-images.githubusercontent.com/3157700/28832457-7df735e8-7702-11e7-8515-be7f43582795.png)


My finding:

![image](https://user-images.githubusercontent.com/3157700/28832633-057dc57c-7703-11e7-85b0-ffd86b57188b.png)

**Comment by jdegger** [comment]
> App didn't die too. Otherwise, we will not even get the callback from hincrby and in that case, there will be no log. Now, we got return values from redis and we could log them.
Might it be time to start logging errors too? For all we know there might have been some faulty commands which _did_ edit the result but with errors but those are not logged, is that an option?

**Comment by jdegger** [comment]
>So, what I wanted to know is; as @jdegger suggested, what would happen if the application is modifying the same key at the same time more than once?

Per https://github.com/antirez/redis/issues/2129, that's not really possible as the process runs single threaded and fully atomic. 

Is `amount` calculated based on a Redis value from the same hget? That might cause problems when it's edited from multiple processes at the same time.

**Comment by ZeroHackeR** [comment]
@jdegger actually this is an online game.

Error logging is already there and running, using pm2. There were no restarts reported by pm2. If the app was crashed, all players would be logged out as well and there would have been complaints by players. Thusfar, this is not the case.

`amount` is not being modified. they are coming from game itself, and not related to redis or hget. 

only `credit` is being updated in redis form multiple sources (eg: player himself earns credit or a friend transfers credit to him).

What puzzled me is the `ret` values of `hincrby` (or we can say `after` column in my log table). they are directly from redis and they kept changing without being modified in-between. Again, after studying a few cases, the values were kinda always rollback to a previous value (so, I think, it's not due to something updated the credit value and not appeared in log, because over-written value is always a recent-previous value, not a random value). 

Is there any auto rollback feature in redis? 

Once again, thank you very much and my hairs are standing now. T.T

**Comment by jdegger** [comment]
Does your error logger pick up on the `reply(500, 'db err');`?
Does your server run in a cluster with a custom configuration?

**Comment by ZeroHackeR** [comment]
Actually codes is something like this. I've stripped for the sake of simplicity.
![image](https://user-images.githubusercontent.com/3157700/28837043-5b99b1ce-7711-11e7-8d89-30d17dd31792.png)

So, whatever we write to console will be logged (written to a file) by pm2.
There is no error logged.

Not using node or pm2's cluster to scale. 
We are running multiple instances of the same app which are being load-balanced by another app.

**Comment by ZeroHackeR** [comment]
Another update:

This time, I made sure 
- to call `hget` before calling `hincrby` 
- and to call `hget` again after calling `hincrby`

So, now we can confirm clearly that there is an issue .
![image](https://user-images.githubusercontent.com/3157700/28841007-db9fd86e-771e-11e7-9ccb-152bcae5591a.png)

Again, `hincrby` is using a previous value (instead of the latest value).
![image](https://user-images.githubusercontent.com/3157700/28841202-7260135e-771f-11e7-8ada-49eb26e4fbe7.png)

**Comment by stockholmux** [comment]
@ZeroHackeR 
1. You're logging (possibly) is unreliable in this case. You're relying on pub/sub there is no guarantee of delivery - loss is a reality. 
2. There is no way to know that `credit` isn't being modified by anything else based on your code.

It may be difficult to do at scale, but you might want to verify what is going on with MONITOR.

3. Your app could have died. Here is where:
```
addCredit = function( amount, description, ref, reply ){
	// db is a redis client
	db.hincrby(uid_key, 'credit', amount, function(err, ret){		
		if(err) 
			reply(500, 'db err');
		else { 
                        /* possible death starting here */
			reply(0, {credit: ret});
			
			// send to logger to save
			var before_amount = ret - amount;
			var data = [ uid, description, ref, before_amount, amount, ret ];
                        /* possible death ending here */
			pub.publish('log:credit', data.join("|") );			
		}
	});
	
};
```
In that case, you would have unrecorded `hincrby` in your log that would then throw off subsequent log items. If there was an `hincrby` after 416111915 that made the balance back to 10301.

4. Second look at your `hincrby` code I think you're ok - no need for the additional `hget`. I miss took what you were trying to accomplish.

I would definitely take a look at that monitor - you'll be able to see more clearly what is happening. I am very suspicious of your logging being accurate - there is so much that could prevent it from actually recording the correct values in the right order (looks like your timestamp is coming from MySQL too - another variable that could be a problem).

Can you confirm you're running a single instance of OSS Redis? No Redis Cluster?

**Comment by ZeroHackeR** [comment]
@stockholmux  Thanks for your suggestion. As I said there were no issues while running on our development machine or test server. Only on production server, it's happening. Again, production is processing 1000-3000 messages per second, it's not possible to use `monitor` command at this moment.

Actually, to eliminate the doubt of other codes updating `credit` value. I did another app which watches the credit value of a user every 10th of a second. 

	var previousCredit;

	function monitor(){
		db.hget("user:#52", 'credit', function(err3, ret3){
			if(!err3){
				if(ret3 != previousCredit){
					previousCredit = ret3;
					console.log(previousCredit);
				}
			}
		});
	}

	setInterval(monitor, 100);

Here's the output for above log.

	115473081
	115472981 <-- ** this one was used for calculation **
	115463938 <-- was updated in redis and gone
	115454985 <-- was updated in redis and gone
	115472971 <-- **expected 115454975**
	115464108
	115455333

The output aligned with log.
There is no missing entries so far in log.
And nothing updated `credit` in-between as per the output.

As I said, it's not getting replaced with a random value.
`hincrby` is calculating using a recent previous value (rather than the latest value).

Using `hget` showed a clearer picture. 
Please check log id: 416758882 - 4.
I now logging additional records for hget values of before and after calling hincreby

The redis server on a single server and I think, it's single instance.
When I ran, `cluster info` i got `ERR unknown command 'cluster'`

**Comment by ZeroHackeR** [comment]
here's the updated `addCredit` codes with hget logging:

	if(gamer.uid == 52){
		db.hget(uid_key, 'credit', function(err3, ret3){
			if(!err3){
				var data3 = [gamer.uid, "hget:before", "", ret3, 0, 0];
				pub.publish('log:credit', data3.join("|") );
			}
		});
	}
		
	db.hincrby(uid_key, 'credit', amount, function(err, ret){		
		if(err) reply(500, 'db err');
		else { 
			gamer.credit = ret;
			reply(0, {credit: ret});
			
			// send to logger to save
			var before_amount = ret - amount;
			var data = [gamer.uid, description, ref, before_amount, amount, ret];
			pub.publish('log:credit', data.join("|") );	

			if(gamer.uid == 52){
				db.hget(uid_key, 'credit', function(err2, ret2){
					if(!err2){
						var data2 = [gamer.uid, "hget:after", "", 0, 0, ret2];
						pub.publish('log:credit', data2.join("|") );
					}
				});
			}			
		}
	});

**Comment by jdegger** [comment]
Could you move your `hincrby` inside the clalback of the `hget:before` and reconfirm your findings?

**Comment by ZeroHackeR** [comment]
After debugging for 8 hours , I think, I found a possible lead. 

I found a code which is overwriting `credit` value.

![image](https://user-images.githubusercontent.com/3157700/28843999-392eb8e2-7729-11e7-8f80-5d1e1400052e.png)

Please allow me some more times.
I will keep you posted!

**Comment by jdegger** [comment]
Closing this issue as it seems clear this at least not a Node Redis bug.

**Comment by ZeroHackeR** [comment]
@jdegger @stockholmux  thanks guys!
