### ISSUE TITLE
Injection attacks against redis

### ISSUE THREAD

**Issue by dacappo** [NodeRedis/node_redis#1265]
Given some preconditions (usage of body-parser or qs module), an attacker may be able to inject arugments into driver invocations: 
`redis.set(req.body.key, "hardcoded_value")` 
will become 
`redis.set(["key", "evil_value"], "hardcoded_value")`
and `key=evil_value` will be stored in the database. 

In general, comma separated arguments can be overwritten when an attacker is able to replace a preceding argument with an array.

[Detailed explanation](http://bit.ly/2hMUQtt)

I am aware that this behavior won't be easy to fix, but maybe this issue should at least be mentioned in your documentation.

Cheers,
Patrick

**Comment by stockholmux** [comment]
Thanks patrick - note added.

**Comment by BridgeAR** [comment]
This is not limited to the body-parser or the qs module. Any user input should be handled with care no matter what database you use. I am a bit surprised that a comment is required for this at all.

**Comment by BridgeAR** [comment]
@dacappo about a fix: I want to flatten arrays in the future but this would be a breaking change right now. But that is actually not enough because if you accept a user input without checking the value a user could still do lots of malicious things depending on the used command (or worse: if `send_command` is used).

**Comment by stockholmux** [comment]
@BridgeAR I agree - this is, ultimately, on the person implementing the app, not the Redis client.

On the subject of array flattening, perhaps it could be a option/flag when you create the client? I would guess 90% of users wouldn't notice if we flatten arrays, 10% would have a break.
