### ISSUE TITLE
receiving data on subscribed channel is wonky

### ISSUE THREAD

**Issue by pmtolk** [NodeRedis/node_redis#1270]
I have a node application which is successfully receiving a request from a publish from redis

redis_client1.on("message", function (channel, message) {

     logger.debug("sub channel " + channel + ": " + message);

 which correctly logs

> 20:23:15 - debug: sub channel LoginChannel: {'username': u'user6',
> 'user_id': 9}

and if I JSON.stringify it also correctly logs

> 20:23:15 - debug: Login from redis, adding user to users "{'username':
> u'user6', 'user_id': 9}"

but when I log the keys

    logger.silly(Object.keys(message));

I get this weird output and I cannot access the json object like this message.username which used to be working until I updated node to version 8.2.1

> 20:23:15 - silly:  0=0, 1=1, 2=2, 3=3, 4=4, 5=5, 6=6, 7=7, 8=8, 9=9,
> 10=10, 11=11, 12=12, 13=13, 14=14, 15=15, 16=16, 17=17, 18=18, 19=19,
> 20=20, 21=21, 22=22, 23=23, 24=24, 25=25, 26=26, 27=27, 28=28, 29=29,
> 30=30, 31=31, 32=32, 33=33, 34=34, 35=35, 36=36, 37=37, 38=38, 39=39,
> 40=40, 41=41, 42=42, 43=43, 44=44, 45=45, 46=46, 47=47, 48=48, 49=49,
> 50=50, 51=51, 52=52, 53=53, 54=54, 55=55, 56=56, 57=57, 58=58, 59=59,
> 60=60, 61=61, 62=62, 63=63, 64=64, 65=65, 66=66, 67=67, 68=68, 69=69,
> 70=70, 71=71, 72=72, 73=73, 74=74, 75=75, 76=76, 77=77, 78=78, 79=79,
> 80=80, 81=81, 82=82, 83=83, 84=84, 85=85, 86=86, 87=87, 88=88, 89=89,
> 90=90, 91=91, 92=92, 93=93, 94=94, 95=95, 96=96, 97=97, 98=98, 99=99,
> 100=100, 101=101, 102=102, 103=103, 104=104, 105=105, 106=106,
> 107=107, 108=108, 109=109, 110=110, 111=111, 112=112, 113=113,
> 114=114, 115=115, 116=116, 117=117, 118=118, 119=119, 120=120,
> 121=121, 122=122, 123=123, 124=124, 125=125, 126=126, 127=127,
> 128=128, 129=129, 130=130, 131=131, 132=132, 133=133, 134=134,
> 135=135, 136=136, 137=137, 138=138, 139=139, 140=140, 141=141,
> 142=142, 143=143, 144=144, 145=145, 146=146, 147=147, 148=148,
> 149=149, 150=150, 151=151, 152=152, 153=153, 154=154, 155=155

* **Version**: What node_redis and what redis version is the issue happening on?
v2.8.0
* **Platform**: What platform / version? (For example Node.js 0.10 or Node.js 5.7.0 on Windows 7 / Ubuntu 15.10 / Azure)
centos node 8.x node 6.x does not work, node 0.12.x working
* **Description**: Description of your issue, stack traces from errors and code that reproduces the issue
https://stackoverflow.com/questions/45930282/node-keys-wonky-cannot-access-json-object-via-key-after-upgrade?noredirect=1#comment78855719_45930282

I tried a typeof and received string, however, I cannot JSON.parse because I get a SyntaxError: Unexpected token ' in JSON at position 1

**Comment by BridgeAR** [comment]
Please show a non working test case. First of all what you log in the beginning does not seem to be valid JSON because there is a 'u' infront of the username value. Second the output of the keys looks like the keys of an array. Overall it has to do with the way you stringify and parse your in and output. You're likely using a library and that might be broken.

It is very unlikely an issue with node_redis and I am therefore closing this.
