### ISSUE TITLE
How to call OBJECT IDLETIME

### ISSUE THREAD

**Issue by bhartsb** [NodeRedis/node_redis#1272]
Can someone provide an example of how to call OBJECT IDLETIME?

See: https://stackoverflow.com/questions/26245623/get-the-last-time-a-given-redis-key-was-accessed

Thanks.

**Comment by BridgeAR** [comment]
Please have a look at [the documentation](https://github.com/NodeRedis/node_redis#multi-word-commands).

**Comment by bhartsb** [comment]
I did look at the documentation and I tried but failed to get what I thought would work to work can't you provide an example?

**Comment by BridgeAR** [comment]
`client.object('idletime', key, callback);`

**Comment by bhartsb** [comment]
That is what I tried.  I'll retry.

On Sat, Sep 2, 2017 at 10:20 AM, Ruben Bridgewater <notifications@github.com
