### ISSUE TITLE
This is some bug with the method of punsubscribe.

### ISSUE THREAD

**Issue by lovepluskaka** [NodeRedis/node_redis#1273]
This is my code:
```
const redis = require('redis');
let sub =  redis.createClient(opts);
let pub = redis.createClient(opts);
sub.on("message",(channel, message)=>{
      console.log('channel',channel);//channel0
      console.log('message',message);//  This is my message  
 })

sub.subscribe("channel0");
sub.subscribe("channel1");
sub.subscribe("channel2");

sub.punsubscribe(["channel2"],function(channel,count){
    console.log(channel);// null
    console.log(count);// channel2
});
pub.publish("channel0","This is my message");
```
The message event is also be emitted,and the `punsubscribe`  callback function parameters value  are   `null` and `channel2`.

**Comment by jdegger** [comment]
1. The correct callback format is `(err, reply[, reply...])` so the first argument (defined by you as `channel` is the actual `error` argument being `null`.
2. Why wouldn't the message be emitted? JS is async so the publish is called immediately after all blocking events.

This doesn't seem to be a bug to me, closing this issue for now.
