### ISSUE TITLE
Setters and deletes always return false

### ISSUE THREAD

**Issue by MrMaximus** [NodeRedis/node_redis#1279]
The functions i'm experiencing this with is `hset`, `hdel` and `del` though it could be an issue with others too. They always return false, redis cli returns 1 if the set/delete was successful and 0 if there was nothing to set/delete. It would make sense to do the same with booleans

**Comment by stockholmux** [comment]
You'll get the 1/0 response in the callback, not as a returned value.
```
client.del('something',function(err,resp) {
  //`resp` will be 1 if something existed, 0 if it didn't.
});
```
