### ISSUE TITLE
publish Buffer data

### ISSUE THREAD

**Issue by ghostyu** [NodeRedis/node_redis#1285]
Version: v2.8
Platform: windows

well, it is a string  char missing
var buf = new Buffer([0x08, 0x90, 0x4e]);

redis.publish("ch",buf); // the buf will toString convert

so, when i receive subscribe message
var bufRcv = new Buffer(message,'ascii')

the bufRcv is <Buffer 08 fd 4e>

**Comment by stockholmux** [comment]
That's pretty weird.

Could you give us the connection options (minus passwords, IPs, etc)?

**Comment by ghostyu** [comment]
I think it is a Buffer and String convert problem with some "hex" ascii
0x00~0x7F, Buffer and String convert bothway is ok
but, 0x80~0xFF, will missing

you can test this code
```
var buffer = new Buffer([0x01,0x50,0x7F]);
console.log(buffer); // <Buffer 01 50 7f>
var string = buffer.toString();
var bufBack = new Buffer(string,'ascii');
console.log(bufBack); // <Buffer 01 50 7f>
```
now test 0x80~0xFF
```
var buffer = new Buffer([0x80,0x90,0xFA]);
console.log(buffer); // <Buffer 80 90 fa>
var string = buffer.toString();
var bufBack = new Buffer(string,'ascii');
console.log(bufBack); // <Buffer fd fd fd>
```

**Comment by stockholmux** [comment]
Yup. From the [Buffer](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array) documentation:

```
'ascii' - For 7-bit ASCII data only. This encoding is fast and will strip the high bit if set.
```

Which is pretty weird because I tend to think of ASCII as 8-bit, but not according to the docs. So, not a node_redis issue.
