### ISSUE TITLE
Never expire SET Key

### ISSUE THREAD

**Issue by drugcss** [NodeRedis/node_redis#1287]
When we used `client.set("key", value)` with any expire time option, It has been deleted in a little time. How much time default time is set in this library?. How can i use this "**PERSIST**" command in node_redis?
Link: https://redis.io/commands/persist . So i wanna to make this set command to hasn't timeout- never expire.

**Comment by dirkbonhomme** [comment]
Keys you set with the `set` command never expire. Maybe your Redis server is running out of memory and its eviction policy kicks in?
https://redis.io/topics/lru-cache

To set a key *with* an expire time, use `setex` or `psetex` https://redis.io/commands/psetex

**Comment by BridgeAR** [comment]
@dirkbonhomme thanks for answering the question :-)
