### ISSUE TITLE
Can we support `redis://UNIX_SOCKET` url?

### ISSUE THREAD

**Issue by jokester** [NodeRedis/node_redis#1289]
Test case:  `redis.createClient("redis:///tmp/redis.sock") ` does not connect to server providing that socket.
Version: `redis (the npm package) v2.8.0`

It seems that the current code will use the whole url as path. Do you think we should recognize the "schema + path", and connect with the path part?

IIRC this is not uncommon, sidekiq (ruby) supports this too.

**Comment by stockholmux** [comment]
I believe you can do this just without the 'redis://' prefix.

**Comment by jokester** [comment]
Yes, but sometimes this convention may be used by a fixed component (I myself encountered this in heroku's Redis addon).

**Comment by stockholmux** [comment]
@jokester So you're getting `redis:///tmp/redis.sock` from heroku through an environment var or something?

**Comment by jokester** [comment]
Oops my bad. Heroku does not uses a `redis://   +  unix socket` URL. The url I encountered was from a local heroku-like environment. Still I think it may be useful for someone  :o

**Comment by stockholmux** [comment]
The `redis://` bit is a standard, so I'm hesitant to extend it or add non-standard bits.

But otherwise, your'e good?

**Comment by jokester** [comment]
Totally fine if we choose to not support this non-standard convention 👍  .

**Comment by BridgeAR** [comment]
Passing a unix socket in the url is a bad idea. This mixes two very different things. You can use the unix socket path directly and everything works fine. There should not be any need for this.
