### ISSUE TITLE
ReplyError: Ready check failed: ERR max number of clients reached

### ISSUE THREAD

**Issue by sharathm89** [NodeRedis/node_redis#1290]
I get this error after approximately 30 to 40 minutes and crashes the server. I am using pm2 module so it restarts once it crashes.

Node Version : 8.9.1
Redis Version : 4.0.2

From the redis terminal checking for redis clients connected it shows approximately 8500 and keeps increasing and once it reaches 10000 it gives the error and again restarts from 0 resulting in a crash.

Below is my code. Please let me know if any changes needs to be done to avoid this issue as its running in a production environment.

```
var Promise = require('bluebird');
var Redis = Promise.promisifyAll(require('redis'));

// Global (Avoids Duplicate Connections)
var redisClient = null;
var redisMultiClient = null;

// Make the below functions as private
function openRedisConnection() {
    if (redisClient && redisClient.connected)
        return redisClient;

    if (redisClient)
        redisClient.end(); // End and open once more

    redisClient = Redis.createClient(6379,process.env.REDIS_URL);
    redisClient.selected_db = 1;
    return redisClient;
}

function openMultiRedisConnection() {
    if (redisMultiClient && redisMultiClient._client.connected) {
        redisMultiClient._client.selected_db = 0;
        return redisMultiClient;
    }

    if (redisMultiClient)
        redisMultiClient.quit(); // End and open once more

    redisMultiClient = Redis.createClient(6379,process.env.REDIS_URL).multi();
    redisMultiClient._client.selected_db = 0;
    return redisMultiClient;
}

function getExpiryTime(key) {
    return 120; // testing
}

module.exports = {
   
    getRedisValue: function (keys) {
        return openRedisConnection().mgetAsync(keys);
    },
 
    setRedisValue: function (key, value) {
        return openRedisConnection()
            .setAsync(key, value, 'EX', getExpiryTime(key))
            .then(function (result) {
                return Promise.resolve(result);
            });
    },

    getV2MultiRedisValue: function (keyList) {
        let redisMultiClientObj = openMultiRedisConnection();
        redisMultiClientObj._client.selected_db = 2;

        redisMultiClientObj.hgetallAsync(keyList);

        return redisMultiClientObj.execAsync()
            .then(function (results) {
                return Promise.resolve(results);
            });
    },

    setV2MultiRedisValue: function (key, redisList) {
        let expiryTime = getExpiryTime(key);
        let redisMultiClientObj = openMultiRedisConnection();
        redisMultiClientObj._client.selected_db = 2;

        for (let item of redisList) {
            redisMultiClientObj.hmsetAsync(item.key, item.value);
            redisMultiClientObj.expireAsync(item.key, expiryTime);
        }
        return redisMultiClientObj.execAsync()
        .then(function (results) {
            return Promise.resolve(results);
        });
    }
};
```

**Updated Code which works correctly.**

```
var Promise = require('bluebird');
var Redis = Promise.promisifyAll(require('redis'));

// Global (Avoids Duplicate Connections)
var redisClient = null;

// Make the below functions as private
function openRedisConnection() {
    if (redisClient && redisClient.connected)
        return redisClient;

    if (redisClient)
        redisClient.end(); // End and open once more

    redisClient = Redis.createClient(6379,process.env.REDIS_URL);
    return redisClient;
}


function getExpiryTime(key) {
    return 120; // testing
}

module.exports = {
   
    getRedisValue: function (keys) {
        return openRedisConnection().mgetAsync(keys);
    },
 
    setRedisValue: function (key, value) {
        return openRedisConnection().setAsync(key, value, 'EX', getExpiryTime(key));
    },

    getV2MultiRedisValue: function (keyList) {
        let redisMultiClientObj = openRedisConnection().multi();
        redisMultiClientObj.hgetallAsync(keyList);
        return redisMultiClientObj.execAsync();
    },

    setV2MultiRedisValue: function (key, redisList) {
        let expiryTime = getExpiryTime(key);
        let redisMultiClientObj = openRedisConnection().multi();
        for (let item of redisList) {
            redisMultiClientObj.hmsetAsync(item.key, item.value);
            redisMultiClientObj.expireAsync(item.key, expiryTime);
        }
        return redisMultiClientObj.execAsync();
    }
};
```

**Comment by sharathm89** [comment]
can someone please reply to this post..

**Comment by stockholmux** [comment]
A few things:

1. What is your crash error message? 
2. What is the need to open a new client for a Multi? This is generally not required.

Looking over the code a few times, I think you may be misunderstanding the connection model of Redis in general. Most code just opens a (single) persistent connection and does everything on that - there is no need to open it multiple times (with a few exceptions, none of which I see in your code). node_redis also provides connection buffering, so if you execute a command and the connection is not yet ready, it will just buffer until it is. All that being said, the above module seems like unnecessary abstraction after getting over that misunderstanding.

**Comment by sharathm89** [comment]
Hi @stockholmux I have just updated with post providing the code which works correctly for me. I tested the server for 5 days it never crashed even once.
When info is executed in redis terminal the below results are displayed.

![redis](https://user-images.githubusercontent.com/17666778/33871364-3d4c873e-df38-11e7-884a-c8dec0184594.png)

Please check and let me know if the approach is correct.

**Comment by stockholmux** [comment]
I don't think your `openRedisConnection` is really needed. That being said, if it works and you're satisfied with it - it's your call.

I've previously solved this problem like this:
```
var
  client;

...

module.exports = {
 setClient : function(inClient) { client = inClient; },
 ...
}
```
(you may need to `promisifyAll` either in the `setClient` function or in the script running the module)

Then you could write your code like this:
```    
    getRedisValue: function (keys) {
        return client.mgetAsync(keys);
    },
```

This method helps in a couple of ways:
1) The function call to `openRedisConnection` is being run every time you use redis. You don't really need to do this - so why do it? It takes up some amount of overhead. Using `client` is simpler and faster way of achieving the same goal.
2) Your configuration is locked in your module (aside from the environment variable reference). Doing your connection and configuration outside of a module is a good idea - the module is more portable.

**Comment by sharathm89** [comment]
Yes `openRedisConnection` is not required but as per your below code.
when should the setClient function be called ?
Is it when server starts so that object is set only once ?
If its set only once then don't we need to check `client.connected` is true of false ?
I also need to select db's since i have keys with same name so using Database 1 and 2 so my question is can we create 2 redis client objects dealing for each database or else during runtime change the selected_db number ?

```
var client;
...
module.exports = {
 setClient : function(inClient) { client = inClient; },
 ...
}
```
