### ISSUE TITLE
Stacking strings with nets and nodejs

### ISSUE THREAD

**Issue by renanmoraes** [NodeRedis/node_redis#1291]
I am having problems with redis, the documentation is not being clear to me and all my efforts to try to make a simple stack has gone awry.

I use `nodejs` as a server and` redis` together with `socket` I need to make a list of a specific type of users the relation between them and the rooms is many to many, like this:

    MEMBERS <-----> ROOMS

Several members may be in several rooms, and several rooms may have several members.

All this information was being allocated in memory, it brought a lot of unnecessary weight, hence the idea of ​​using redis to manage these types of connections.

In my code I'm doing this:

Start the service like this:

    const io = require ('socket.io'). listen (http);
    const redisSocket = require ('socket.io-redis');
    const redis = require ("redis");

I get the connections in the `socket`:

    io.sockets.on ('connection', (socket) => {my _functions});

And I get in a `socket.on` the members I need to work with

    socket.on ('ioUpdateLocation', (data) => {
        // Send the location to the devices in the room
        io.sockets.to (data.room) .emit ('ioReceiveLocation', date);
        addRoom (data.room, socket.id);

        // Emits the location for line X destination Y
        io.sockets.to (data.room + data.destiny) .emit ('ioReceiveLocation', data);
        addRoom (data.room + data.destiny, socket.id);
    });

And so I plan to put that socket in the room like this:

    const addRoom = (room, socketId) => {
        console.log ('room% s socket% s', room, socketId);

        redisClient.lpush (room, socketId, function (err, reply) {
            console.log ('err', err); // prints 2
            console.log ('reply', reply); // prints 2
        });
      }

My idea is like this:

    ROOMS | MEMBERS
    123 | ['member01', 'member02', 'member03']
    123A | ['member01']
    
So using `redis` I hope to` add` and `remove` members from a room, and` check` if that member is in a room for example X.

**BUSINESS RULES**

 1. MEMBER can be in several rooms
 2. The room can not have 2 equal members

With the attempts was made:

    1- client.set ();
    2- client.hmset ();
    3- client.rpush ();
    4- client.sadd ();

None successfully. At first it replaced the value in the example would look like this (the same values ​​were inserted in the following order member01, member02, member03):

    ROOMS | MEMBERS
    123 | 'member04'
    123A | 'member01'

In attempts 2,3,4 the result was an error:

> {ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
    at new Command (/var/www/lb-api-geolocation/node_modules/redis/lib/command.js:12:22)
    at RedisClient.lpush (/var/www/lb-api-geolocation/node_modules/redis/lib/commands.js:58:47)
    at addRoom (/var/www/lb-api-geolocation/src/socket/connect.js:144:17)
    at Socket. <anonymous> (/var/www/lb-api-geolocation/src/socket/connect.js:94:9)
    at emitOne (events.js: 115: 13)
    at Socket.emit (events.js: 210: 7)
    at /var/www/lb-api-geolocation/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal / process / next_tick.js: 131: 7)
    at process._tickDomainCallback (internal / process / next_tick.js: 218: 9)
  command: 'RPUSH',
  args: ['59c54ace9e450c004ad4c90etripA', 'E4NXUZ417M2UwUxDAAAC'],
  code: 'WRONGTYPE'}

How to solve this?

**Comment by stockholmux** [comment]
This is more of a data modeling question than a specific node_redis issue (WRONGTYPE is an error directly from Redis, so it would occur in redis-cli too).

Generally, though, you'll probably want a set of rooms:
```
SADD rooms room:123
SADD rooms room:123A
```

and then you want to add members to each room set:
```
SADD room:123 member04
SADD room:123A member01
```
Because you're dealing with the Redis set type, duplicates won't be allowed. The other thing to keep in mind is that there is no concept of relationships in Redis, so finding the uses that `member04` is in would require an additional step:

```
SADD member04 room:123
SADD member01 room:123A
```

Hope this helps.
