### ISSUE TITLE
on redis 3.2.6.  modify value of Json string from list. but the Json string change to binary when save the value to list again

### ISSUE THREAD

**Issue by AbnerGC** [NodeRedis/node_redis#1294]
before the value  like this: {"status":1,...}".

modify value of 'status' field to 2 and save to list by 'lset' comm . after the vlaue like this: {"status":2\x00\x00\x00  

what is happen ?  anyone know how to solve this problem? thx.

PS : json object to json string  i use JSON.parse and JSON.stringify, node_redis i use 2.6.5 version.

**Comment by BridgeAR** [comment]
I am sorry but the current information is not enough to fully understand what you are doing. Do you have a minimally code example that reproduces your issue?

It is likely that somewhere a manipulation happens in your code that you are not aware of. node_redis does not manipulate the input.

**Comment by AbnerGC** [comment]
@BridgeAR ok. below is my  process:
1. first  i have an `list`  data structure, and i push below data to list:
var key = 'testList';
var data= {
        "id":"12"
	"status": 1,
	"created_time": 1515398400,
};
redisClient.rpush(key,JSON.stringify(data),function(err,result){...})
2. Now i need to change value of data.status  to 2 ok, so i use `lrange` comm get data:
    redisClient.lrange(key,0,-1,function(err,result){
       if(err){ 
          console.log(err);
       }
       result.forEach(function(){})
    })

**Comment by AbnerGC** [comment]
@BridgeAR    Below is my process .

1. first i created a `list ` data structure use `rpush`:
```var redis = require('redis');
  var redisClient = redis.createClient();`
  var key = "testList";`
  var data = {
       "status": 1,
       "created_time": 1515398400,
    }
  redisClient.rpush(key,data,function(err,result){...});
```
2.Now i need to change value of data.status to 2 . So i use `lrange` comm to get data:
```
 redisClient.lrange(key,0,-1,function(err,result){
      if(err){
         console.log(err)
      }
      result.forEach(function(item,index){
          item = JSON.parse(item);
          item.status = 2;
          redisClient.lset(key,index,JSON.stringify(item),function(err,setResult){})
    });
      
})
```
3.  I go to check my data in redis i get an binary data not a string. like:
{"status":2\X00&] , but this issue not  often occur . so i have no idea . what do you think ? thx !!!

**Comment by SkymaxPlay** [comment]
try convert created_time's value to string

**Comment by BridgeAR** [comment]
@AbnerGC your example does not seem to be complete. You could activate the debug mode to see what data is actually transferred. This is very likely not an issue with node_redis though and I'm closing this as question.

@SkymaxPlay `data` as a whole would have to be stringified in the example. The number property as such is not the issue.
