### ISSUE TITLE
Listening to a specific channel : How to do it?

### ISSUE THREAD

**Issue by http91** [NodeRedis/node_redis#1295]
I'm using Redis 4.0.6

I want to use a better way than the way I achieved below (it feels tacky), how can I make it listen to a specific channel rather than using if statements to determine the channel name? I've read the [documentation][1] but I couldn't understand how to apply the pattern.

pubsub.js

    var redis = require("redis");
    var subscriber = redis.createClient();
    var publisher = redis.createClient();
    
    subscriber.auth("mypassword", function (callback) {
      console.log("subscriber is connected");
    });
    
    publisher.auth("mypassword", function (callback) {
      console.log("publisher is connected");
    });
    
    module.exports = {
      publisher: publisher,
      subscriber: subscriber
    };

test.js

    var express = require('express');
    var router = express.Router();
    var path = require("path");
    var async1 = require("async");
    var client = require("../databases/redis/redis.js").client;
    
    var subscriber = require("./realtime/operations/pubsub").subscriber;
    var publisher = require("./realtime/operations/pubsub").publisher;
    
    subscriber.subscribe("test1");
    subscriber.subscribe("test2");
    
    subscriber.on("message", function (channel, message) {
    
      if (channel == "test1") {
        console.log("test1 " + message);
      }
    
      if (channel == "test2") {
        console.log("test2 " + message);
      }
    
    });
    
    router.get('/pubsubTest', function (req, res, next) {
      async1.waterfall([
        function (callback) {
    
          publisher.publish("test1", "test1 - message 1");
          publisher.publish("test2", "test2 - message 1");
          publisher.publish("test1", "test1 - message 2");
    
          callback(null, 'done!');
    
        }
      ], function (err, result) {
        res.sendStatus(200);
      });
    
    });
    
    module.exports = router;

  [1]: https://github.com/NodeRedis/node_redis#pmessage-pattern-channel-message

**Comment by BridgeAR** [comment]
While only having a glimpse at it, it seems to me that you did the right thing already.

If you want a dedicated function per channel you can easily implement it like this:

```js
const channels = {
  test1(message) { /* do stuff */ },
  test2(message) { /* do stuff */ }
}

subscriber.on("message", function (channel, message) {
  if (!channels[channel])
    throw new Error('Channel not implemented')
  channels[channel](message)
})
```
