### ISSUE TITLE
Documentation for geo functions

### ISSUE THREAD

**Issue by manafzar** [NodeRedis/node_redis#1296]
I was looking through codes for some guidance on how to use geo functions but couldn't find any. the geo functions are available on redis-commands package so they are available as owner pointed out too but searching for how to use them wasn't successful. Except GEOADD function which was used in a test, So having a cheat sheet on how to use other commands like GEORADIOUS too will be useful.

**Comment by stockholmux** [comment]
Hi Manafzar,

All commands are supported in node_redis. To prevent re-inventing the wheel (with the documentation at [redis.io](http://redis.io/commands/)), we have chosen not to document individual commands unless there is some notable exception in how they work from `redis-cli`.

**Comment by manafzar** [comment]
Thanks i know redis documentation. but for example how geoRadius arguments should be separated? There is options argument that could have either WITHDIST, WITHCOORD, WITHHASH and a previous argument for unit (m,km,etc.). should they all be in a single string or seperate each one on an argument?

**Comment by BridgeAR** [comment]
@manafzar each should be separate. This applies to all commands.

**Comment by manafzar** [comment]
All right thanks a lot :)
