### ISSUE TITLE
Is there echo command?

### ISSUE THREAD

**Issue by cemtopkaya** [NodeRedis/node_redis#1297]
I needed to use echo command now.
I found it in ioredis repo.According to that package we can create echo command using by lua script.
Is there any way like this or how can I put echo command into this package?

**Comment by stockholmux** [comment]
Yep. There is an `echo` command. We Redis support every command.

```
var
  redis   = require('redis'),
  client  = redis.createClient();

client.echo('hi',function(err,resp) {
  if (err) { throw err; }
  console.log(resp); //'hi'
  client.quit();
})
```
