### ISSUE TITLE
Raw / unparsed reply?

### ISSUE THREAD

**Issue by lukajandric** [NodeRedis/node_redis#130]
Hi all

I can't find a way to access raw reply stream. Basically on_data value in debug mode.

The thing is I need data from redis both on my nodejs server and forwarded on to my c++ client, which will use hiredis parsing for itself. I figure best way would be just to forward the raw reply. (maybe zlib it first). 

Thanks in advance.
Luka

**Comment by BridgeAR** [comment]
@lukajandric there is no way to filter a single command as this is not how streams work. There might be other commands in the same reply as the one you want. This is always automatically converted to a JS reply.

I'm also not sure I understood what your intention really is... You can simply connect one node_redis client and a c++ client.
