### ISSUE TITLE
PubSub and Store Connections

### ISSUE THREAD

**Issue by loretoparisi** [NodeRedis/node_redis#1305]
In my application I have at least three different connections:

- one for the store;
- one for the PubSub publisher;
- one for the PubSub subscriber;

where I have different prefix for the `store` and the `pubsub` connections

I would like to reduce this to two connections, so the idea was to have like

- one for the Redis Store and publisher connection
- keep one for the PubSub subscriber;

Of course the three connections would share the same `prefix`. Would it work in this way?

**Comment by stockholmux** [comment]
`publish` is just a command like any other. There is no advantage of having a store and one for the PubSub publisher, I think you can you can safely remove the extra connection.
