### ISSUE TITLE
Question: node_redis & ioredis merge status

### ISSUE THREAD

**Issue by ccs018** [NodeRedis/node_redis#1306]
What's the status of the merging of node_redis and ioredis?

**Comment by BridgeAR** [comment]
Thanks for asking. In general: I must work again on node_redis and I hope to find time soon for it again. There must be another major version with more features in here before that can progress much further.

So currently there is no specific timeframe.

**Comment by ccs018** [comment]
I was hoping that cluster support was being added to node_redis.  I've started to use redis clusters with ioredis and have run into a number of disturbing issues.  @luin has not been responding to any recent issues logged, so I am rather concerned about the continued viability of that library.

**Comment by BridgeAR** [comment]
I am soon going to work on cluster support here. So stay tuned :-) it will not happen in the next two weeks though.

**Comment by stockholmux** [comment]
@BridgeAR I have time soon (also I work at Redis Labs now, so if we have any questions I have a direct line to experts ;) )

**Comment by mike-aungsan** [comment]
Any update?
