### ISSUE TITLE
Trying to delete multiple keys at once results in an error

### ISSUE THREAD

**Issue by Ohems** [NodeRedis/node_redis#1308]
* **Version**: node_redis v2.8.0, Redis v3.x 
* **Platform**: Node v8.9.4, macOS Sierra 10.12.3
* **Description**: Calling `client.del([key1, key2, key3], callback)` results in an error
```
    ReplyError: ERR wrong number of arguments for 'del' command
      at parseError (node_modules/redis-parser/lib/parser.js:193:12)
      at parseType (node_modules/redis-parser/lib/parser.js:303:14)
```
even though this appears to be supported by [the specification](https://redis.io/commands/del).

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
Please activate the debug mode to see what is wrong. The error is returned by Redis and the client supports using an array as is done here. There is also a test that does exactly this and it works fine. This is definitely an issue with the data passed to node_redis. Please check closely what you really pass in.

**Comment by Ohems** [comment]
Indeed, this was my mistake. Thanks for the quick answer!
