### ISSUE TITLE
in addition to node_redis, please publish redis client script based on browser!

### ISSUE THREAD

**Issue by anlexN** [NodeRedis/node_redis#1309]
* **Version**: both are the latest
* **Platform**: node 9 latest on Windows 10
* **Description**: i hepe redis client script focuse on browser, please publish browser build. or say web build. it can reduce my bundle size.

**Comment by stockholmux** [comment]
Redis is decidedly **not** a client side technology. It would be a huge security risk to connect directly to a Redis server from the browser - I can't see us making any browser/web builds for this module. Sorry!
