### ISSUE TITLE
The PUBLISH command contains a "undefined" - just no way..

### ISSUE THREAD

**Issue by xzk821649509** [NodeRedis/node_redis#1312]
```
The PUBLISH command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```
I publish and subscribe huge amount of messages to solve `socket.io` distributed deployment
how to solve this problem

**Comment by BridgeAR** [comment]
Seems like you passed `undefined` to node_redis. I do not know how your code looks like, so please check where that happens to solve that. I am sorry that I can not do much more without seeing your code and that is probably not possible.

**Comment by xzk821649509** [comment]
The problem is the introduction of  `node_redis` undefined ?

**Comment by BridgeAR** [comment]
So what happens is you pass `undefined` values to node_redis as in:

```js
client.publish(channel, message, callback)
```

Either `channel` or `message` are undefined in your case.

**Comment by xzk821649509** [comment]
My project is to use the `redis` `PUBLIC` and `SUBSCRIBE`  to solve `socket.io` distributed deployment. I use two devices here, one device using the `reids` function is normal, but another device using `redis` `PUBLIC` function then the error occurs. The same set of code. The problem may be related to the two devices connected?

**Comment by BridgeAR** [comment]
I can not tell. What you can do is to verify the input values and throw in case `undefined` is passed in. That way you get a stack trace and see where the value comes from.

**Comment by xzk821649509** [comment]
Thank you for your advice, I will try it out

**Comment by BridgeAR** [comment]
It was a pleasure :)
