### ISSUE TITLE
LREM

### ISSUE THREAD

**Issue by TomPed** [NodeRedis/node_redis#1313]
Hello, Redis now supports `LREM`: https://redis.io/commands/lrem

How can we go about implementing this?

**Comment by stockholmux** [comment]
Already supported. We support all Redis commands.

**Comment by TomPed** [comment]
Okay cool! So sorry about that 😄.

**Comment by stockholmux** [comment]
@TomPed Out of curiosity, how did you come to the conclusion that it wasn't supported?

**Comment by TomPed** [comment]
1. I looked in `README.md` and did not see any usage of `lrem`
2. I searched the repo for `lrem`, and found this issue: https://github.com/NodeRedis/node_redis/issues/888
3. Noticed it was an old issue, and took a quick look at http://redis.js.org, found nothing quick about `lrem`
4. Did some Googling, found nothing
5. Then I came to the conclusion that it wasn't supported.

I think that's about it 😃.

**Comment by TomPed** [comment]
@stockholmux

1. I looked in `README.md` and did not see any usage of `lrem`
2. I searched the repo for `lrem`, and found this issue: https://github.com/NodeRedis/node_redis/issues/888
3. Noticed it was an old issue, and took a quick look at http://redis.js.org, found nothing quick about `lrem`
4. Did some Googling, found nothing
5. Then I came to the conclusion that it wasn't supported.

I think that's about it 😃.

**Comment by stockholmux** [comment]
Thanks, @TomPed.

The first line of the readme is:

"This is a complete and feature rich Redis client for node.js. **It supports all Redis commands** and focuses on high performance."

I don't say this because I'm trying to rub in that you didn't see it, but this is not the first issue of this type that we've received and I'm wondering if our documentation isn't effective because we aren't explicitly saying every command we support.

**Comment by TomPed** [comment]
Yeah I gotcha, no worries. I did read that, but to be honest it did not give me the confidence that it was support, even though you state that it support *all* Redis commands. I think a Wiki on the API for the client would be useful, just so it shows what is supported and the expected commands. I did not know the commands to provide (even though it's in the exact same order as Redis' command) so I ended up Googling that too.

**Comment by dirkbonhomme** [comment]
Maybe we can add all Redis commands in very small letters at the bottom of the readme?

e.g. "`Yes, we support all commands: set, lrem, hget, ...`"

**Comment by TomPed** [comment]
If you say this has happens often before I don't know if putting it in very small letters at the bottom of the readme would do much. Why not have like a Usage header, or a wiki page that has the list of the actual function calls.

**Comment by TomPed** [comment]
But yeah that would be better than not.
