### ISSUE TITLE
Efficient way to delete keys by pattern

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [NodeRedis/node_redis#1314]
I'm working on a big project and in some places, I have to delete keys by a pattern, for example, I want to delete all the keys that start with `filterProducts`

I made a Google search and found some methods to do so like, for example, the method in [this article](http://athlan.pl/redis-delete-keys-prefix-nodejs/)

But I don't know what is the efficient one for a big project, could you please help me?

* **Version**: 2.8.0
* **Platform**: Linux Mint 18.2(Built on Ubuntu 16.04)

**Comment by stockholmux** [comment]
The method you linked to is a pretty terrible way of going about it. `KEYS` is a no-go for production and DEL is also pretty inefficient. I would check into using [`SCAN`](https://redis.io/commands/scan) and [`UNLINK`](https://redis.io/commands/unlink) in a Lua script. This way you can delete a handful of keys at a time without tying up Redis.

All that being said, that type of script is up to you and beyond the scope of the client library. I'm going to close the issue.

**Comment by dirkbonhomme** [comment]
@MohammedAl-Mahdawi I have a similar use case in one of my projects and use the `scanStream` implementation offered by ioredis. This basically an easier way to use the `scan` command: https://github.com/luin/ioredis#streamify-scanning

If you use `SCAN`and `UNLINK` like @stockholmux already mentioned, you should be able to remove any number of keys without blocking Redis.

**Comment by MohammedAl-Mahdawi** [comment]
@dirkbonhomme Thank you so much for your help, I really appreciate that.

I followed your advice and used ioredis and created the following functions, could you please just tell me for big projects is the following the most efficient way for doing so or not:

```
//key example "prefix*"
function getKeysByPattern(key) {
    return new Promise((resolve, reject) => {
        var stream = redis.scanStream({
            // only returns keys following the pattern of "key"
            match: key,
            // returns approximately 100 elements per call
            count: 100
        });

        var keys = [];
        stream.on('data', function (resultKeys) {
            // `resultKeys` is an array of strings representing key names
            for (var i = 0; i < resultKeys.length; i++) {
                keys.push(resultKeys[i]);
            }
        });
        stream.on('end', function () {
            resolve(keys)
        });
    })
}

//key example "prefix*"
function deleteKeysByPattern(key) {
    var stream = redis.scanStream({
        // only returns keys following the pattern of "key"
        match: key,
        // returns approximately 100 elements per call
        count: 100
    });

    var keys = [];
    stream.on('data', function (resultKeys) {
        // `resultKeys` is an array of strings representing key names
        for (var i = 0; i < resultKeys.length; i++) {
            keys.push(resultKeys[i]);
        }
    });
    stream.on('end', function () {
        redis.unlink(keys)
    });
}
```

**Comment by dirkbonhomme** [comment]
@MohammedAl-Mahdawi looks good to me. Only possible issue is that you will load all matching keys into memory at once. If that's a problem, you could remove them in batches as soon as they come in:

```
stream.on('data', function (resultKeys) {
        if (resultKeys.length) {
              redis.unlink(resultKeys);
        }
    });
```

**Comment by stockholmux** [comment]
@dirkbonhomme and @MohammedAl-Mahdawi This method has atomicity issues that could bite you in production.

**Comment by MohammedAl-Mahdawi** [comment]
@stockholmux Thank you for your help, so what is the right solution to this problem, please?

**Comment by MohammedAl-Mahdawi** [comment]
For anyone that looking for the final result that we until now reached to and believe it is the most efficient way is the following:

```
//key example "prefix*"
function getKeysByPattern(key) {
    return new Promise((resolve, reject) => {
        var stream = redis.scanStream({
            // only returns keys following the pattern of "key"
            match: key,
            // returns approximately 100 elements per call
            count: 100
        });

        var keys = [];
        stream.on('data', function (resultKeys) {
            // `resultKeys` is an array of strings representing key names
            for (var i = 0; i < resultKeys.length; i++) {
                keys.push(resultKeys[i]);
            }
        });
        stream.on('end', function () {
            resolve(keys)
        });
    })
}

//key example "prefix*"
function deleteKeysByPattern(key) {
    var stream = redis.scanStream({
        // only returns keys following the pattern of "key"
        match: key,
        // returns approximately 100 elements per call
        count: 100
    });

    var keys = [];
    stream.on('data', function (resultKeys) {
        // `resultKeys` is an array of strings representing key names
        for (var i = 0; i < resultKeys.length; i++) {
            keys.push(resultKeys[i]);
        }
    });
    stream.on('end', function () {
        redis.unlink(keys)
    });
}

//key example "prefix*"
function batchDeletionKeysByPattern(key) {
    var stream = redis.scanStream({
        // only returns keys following the pattern of "key"
        match: key,
        // returns approximately 100 elements per call
        count: 100
    });

    stream.on('data', function (resultKeys) {
        if (resultKeys.length) {
            redis.unlink(resultKeys);
        }
    });
}
```

Please if you are someone that knows a better way of doing so please don't hesitate to share.

**Comment by matt212** [comment]
@MohammedAl-Mahdawi  , 
i am getting this error any ideas on same 
codebase:
```
let redisDel = () => {
    var key="employees*"
    
    return new Promise((resolve, reject) => {
        
        var stream = redis.scanStream({
            // only returns keys following the pattern of "key"
            match: key,
            // returns approximately 100 elements per call
            count: 100
        });
    
        stream.on('data', function (resultKeys) {
            if (resultKeys.length) {
                console.log(resultKeys)
                redis.unlink(resultKeys);
            }
        });
        stream.on('end', function (resultKeys) {
            resolve()
        })
        
    })
}
```



![screenshot from 2019-03-05 19 28 10](https://user-images.githubusercontent.com/1698139/53810409-e0b58d80-3f7c-11e9-935f-6fb30094dc8e.png)

**Comment by siddhkadam1881** [comment]
anyone give perfect solution here?

**Comment by dirkbonhomme** [comment]
@siddhkadam1881 The unlink command is only available since Redis 4 https://redis.io/commands/unlink
You are probably running an older version. Try `del` instead.

**Comment by Biboswan** [comment]
I want to understand how the scanning is done?. I think in the solution by @MohammedAl-Mahdawi if deletion happens in batches, is there a possibility that new keys added in that time which we don't wish to delete, will be scanned and deleted. How about a lua script ?

**Comment by selected-pixel-jameson** [comment]
Anyone have any ideas why this solution wouldn't work on a very simple 1 instance ElastiCache server, but does work locally? I'm able to clear keys normally, but if I try to use the stream implementation it just never returns any keys on ElastiCache.

**Comment by justinasit** [comment]
@selected-pixel-jameson Did you ever find a solution to your problem? I'm having the exact same issue!

**Comment by selected-pixel-jameson** [comment]
@justinasit Unfortunately no. I had to revert to deleting specific keys or clearing the entire cache.

**Comment by EssaadaniYounes** [comment]
I tried this in express and it's working fine:
`const deleteKeysByPattern = async (pattern: string) => {
   const keys = await client.keys("user*");
   !!keys.length && client.unlink(keys);
   const newKeys = await client.keys("user*");
}`
references : https://redis.io/commands/unlink/

**Comment by yshrsmz** [comment]
KEYS command might cause performance issues.

> Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using [SCAN](https://redis.io/docs/latest/commands/scan/) or [sets](https://redis.io/docs/latest/develop/data-types/sets/).

https://redis.io/docs/latest/commands/keys/

**Comment by sohebcakewalk** [comment]
```
export async function deleteKeysByPattern(pattern: any) {
    let cursor = '0';
    let deletedCount = 0;

    do {
        const [newCursor, keys] = await redisClient.scan(cursor, 'MATCH', pattern, 'COUNT', 100);
        cursor = newCursor;

        if (keys.length > 0) {
            const pipeline = redisClient.pipeline();
            keys.forEach(key => pipeline.del(key));
            const results = await pipeline.exec();
            if (results) {
                deletedCount += results.length;
            }
        }
    } while (cursor !== '0');

    return { deletedCount };
}
```
