### ISSUE TITLE
How to get back values from hashes and sets into one json object

### ISSUE THREAD

**Issue by imar26** [NodeRedis/node_redis#1317]
Hello everyone,

I have one JSON document which I need to decompose and store it in redis as hashmap.
Format of the JSON document is as follows,

```
{
"property": {
"property": "string",
"property": "string",
"property": "string"
},
"property": [{
"property": {
"property": "string",
"property": "string",
"property": "string"
},
"property": {
"property": "string",
"property": "string",
"property": "string"
},
"property": "string",
"property": "string",
"property": "string"
},{
"property": {
"property": "string",
"property": "string",
"property": "string"
},
"property": {
"property": "string",
"property": "string",
"property": "string"
},
"property": "string",
"property": "string",
"property": "string"
}],
"property": "string",
"property": "string",
"property": "string"
}
```

As you can see, I have one object, one array of objects which further has 2 objects and few properties and some more primitive properties at the end. I am able to decompose this entire object into hashmap. Also, the hashmap created for the simple properties which are there inside the array of objects are further stored inside the set,

Now, the problem I am facing is, how can I get all these separate hashes and sets in to one JSON document and pass it into the response.

Any sort of help is appreciated. Thanks in advance.

**Comment by stockholmux** [comment]
That's not something that this module takes care of - as you know Hashmaps are a single level and this module doesn't do much to manipulate your data - that's up to you. So, I'm going to close this issue.

My advice to you: Use the [ReJSON](http://rejson.io) module which can natively store JSON in Redis. There are bindings that work with this module so it's a first-class citizen at a syntax level.
