### ISSUE TITLE
nodejs server crash (event if error handler installed)

### ISSUE THREAD

**Issue by bushev** [NodeRedis/node_redis#1318]
Hello!

**Expected**: Catch error and printout it with console log
**Actual**: NodeJS process crash
**Test scenario**: Try to connect to Redis. Redis is not available on `127.0.0.1:6379`

My code:

```javascript
const redis       = require('redis');
const redisClient = redis.createClient(URL);

redisClient.on('error', err => {
    console.log(`Redis error: ${err.message}`);
});
```

I get a crash with error:

```
Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
```

* **Version**: 2.8.0

**Comment by BridgeAR** [comment]
I guess you use Node.js 0.10.x? This is a long outdated and unmaintained Node.js version. Newer Node.js versions do not have this problem.
