### ISSUE TITLE
Atomic read/update is not atomic

### ISSUE THREAD

**Issue by pavelsc** [NodeRedis/node_redis#1320]
* **Version**: redis_version: 3.2.1, node_redis 2.8.0
* **Platform**: Node.js v.8.9.1
* **Description**:  atomic read/update does not work as expected

```
    var client = redis.createClient();
    
    function updateKey() {
        var key;
        key = 'testkey';
        client.watch(key);
        client.get(key, (err, reply) => {
            var val;
            if (!reply) {
                reply = 1;
            }
            val = reply * 2;
            console.log("Value: ", val);
            client.multi().set(key, val, 'EX', 3600).exec((err, reply) => {
                console.log("redis multi reply");
                console.log(err);
                console.log(reply);
            });
        });
    }
    
    for (var i = 0; i < 3; i++) {
        updateKey();
    }

```
Let's put a testkey and set it's value as 2 and then run this code. Honestly it is based on this [comment](https://github.com/NodeRedis/node_redis/issues/545#issuecomment-212398998) by @BridgeAR. Output will be:
```
 Value:  4
 Value:  4
 Value:  4
 redis multi reply
 null
 [ 'OK' ]
 redis multi reply
 null
 [ 'OK' ]
 redis multi reply
 null
 [ 'OK' ]
```
It does not seem this is an atomic since the get is a synchronous command and first multi/exec in a callback unwatch the key. Is this an issue or it could be resolved by node_redis itself (i mean several updates in a row)?

**Comment by BridgeAR** [comment]
Hey @pavelsc thanks for the issue. The problem here is that each atomic call needs a new client. Otherwise this is not possible. It should also try again in case a call fails.

So the function should actually be:

```js


function updateKey(callback) {
  const client = redis.createClient();
  const key = 'testkey';
  var count = 0;

  function atomic() {
    client.watch(key);
    client.get(key, (err, reply) => {
      if (err) return callback(err);
      if (!reply) {
        reply = 1;
      }
      const val = reply * 2;
      client.multi().set(key, val, 'EX', 3600).exec((err, reply) => {
        if (err) return callback(err);
        if (reply) return callback(null, val);
        if (count++ < 10) atomic();
        else callback(new Error('Atomic read write failed'));
      });
    });
  }
  atomic();
}

for (var i = 0; i < 10; i++) {
  updateKey(console.log);
}
```

**Comment by pavelsc** [comment]
Thanks @BridgeAR for quick reply and clarifying. The first thing that came to my mind was "How it will behave in terms of memory leaks if we create too many clients?", and the second was that we definitely need a locking. I took an evening to sort it out and found a redlock approach, it also has a nodejs library. Just want to share my experience with it:
```javascript
var client = redis.createClient();
var redlock = new Redlock([client], {
    driftFactor: 0.01, // time in ms
    retryCount: 10,
    retryDelay: 200, // time in ms
    retryJitter: 200 // time in ms
});

function updateKey() {
    var key, deferred;
    key = 'testkey';
    deferred = Q.defer();
    redlock.lock(`lock:${key}`, 1e3, (err, lock)=> {
        if (err) {
            deferred.reject(err);
            return;
        }
        client.watch(key);
        client.get(key, (err, reply) => {
            if (err) {
                deferred.reject(err);
                return;
            }
            var val;
            if (!reply) {
                reply = 1;
            }
            val = reply * 2;
            console.log("Value: ", val);
            client.multi().set(key, val, 'EX', 3600).exec((err, reply) => {
                lock.unlock().catch((err)=>  {
                    console.error(err);
                });
                if (err) {
                    deferred.reject(err);
                    return;
                }
                deferred.resolve(reply);
            });
        });
    });
    return deferred.promise.then((res) => {
        return res;
    }).catch((err) => {
        throw err;
    });
}

Q.async(function*() {
    for (var i = 0; i < 10; i++) {
        yield updateKey();
    }
})().done(null, (err)=> {
    console.error(err);
});
```

**Comment by ThatBrianDude** [comment]
Whats the locking for? Doesnt watch itself make sure its atomic?

**Comment by funny-falcon-at-joomcode** [comment]
https://redis.io/topics/transactions
> Redis scripting and transactions
> A Redis script is transactional by definition, so everything you can do with a Redis transaction, you can also do with a script, and usually the script will be both simpler and faster.

**Comment by funny-falcon-at-joomcode** [comment]
> Doesnt watch itself make sure its atomic?

Redis is connection-oriented server when "blocking" or "atomic" commands are used.
That means, redis expects that between WATCH and MULTI no non-exactly-this-transaction related commands are came from connection.

node_redis multiplexes single connection between many concurrent control flows in a process. And it is really good strategy, because it has much greater performance than "call-reply" behavior of "connection-pool" based redis connectors. But this strategy fails if you use blocking calls and/or WATCH.

IMHO, it is Redis's failure. But doubtfully Redis will switch to fully asynchronous protocol (that requires concept of "request id"). So, we have to live with what we have.
