### ISSUE TITLE
Expected behavior of multi command with node_redis

### ISSUE THREAD

**Issue by krishnanms** [NodeRedis/node_redis#1322]
I tried asking this question in Gitter, no response for more than 2 days. 

* **Version**: 0.12.1
* **Platform**: Ubuntu 14.04.5 LTS (trusty)
* **Description**: Do we need to always use a new node_redis connection instance before calling MULTI/EXEC 

Explanation:
1) Output for the below snippet: Both the transactions (t1, t2) pass `null, [‘OK’, ‘OK’]` .. which is probably not the expected behavior.
```javascript
'use strict';

const client = require('redis').createClient();

function t1() {
   client.watch('foo');
   client.watch('t1');
   let multi = client.multi();
   multi.set('foo', 'one');
   multi.set('t1', true);
   setTimeout(() => {
      multi.exec((err, res) => {
         console.log(err, res);
      });
   }, 3000);
}

function t2() {
   client.watch('foo');
   client.watch('t2');
   let multi = client.multi();
   multi.set('foo', 'two');
   multi.set('t2', true);
   multi.exec((err, res) => {
      console.log(err, res);
   });
}

t1();
t2();
```
2) Output for the below snipper: t2: `null [ 'OK', 'OK' ]` passes but t1: `null null` fails .. which is the expected behavior ..

```javascript
'use strict';

const redis = require('redis');

function t1() {
   const client = redis.createClient();
   client.watch('foo');
   client.watch('t1');
   let multi = client.multi();
   multi.set('foo', 'one');
   multi.set('t1', true);
   setTimeout(() => {
      multi.exec((err, res) => {
         console.log(err, res);
      });
   }, 3000);
}

function t2() {
   const client = redis.createClient();
   client.watch('foo');
   client.watch('t2');
   let multi = client.multi();
   multi.set('foo', 'two');
   multi.set('t2', true);
   multi.exec((err, res) => {
      console.log(err, res);
   });
}

t1();
t2();
```
In sum, is it required to explicitly create a new instance of the node_redis client connection for multi to get the expected behavior?

Looks like a new Queue object gets created for every multi() call: https://github.com/NodeRedis/node_redis/blob/master/lib/multi.js#L9

Any reasons why the snippet 1) doesn’t work as expected or perhaps I am not using the library in the correct way? Thanks!

**Comment by stockholmux** [comment]
Sorry to have missed this. Run your examples with `MONITOR` in `redis-cli` and I think you'll see what's going on. I think the misunderstand here is how `node_redis` manages `MULTI`(auto pipelining) and the single threaded nature of both Redis and Node. Effectively, from the first example you would get:
```
WATCH foo //from t1
WATCH t1 //from t1 - the MUTI/EXEC block is queued up until the exec is called from JS
WATCH foo //from t2
WATCH t2 //from t2
MULTI //from t2
SET foo two //from t2
SET t2 1 //from t2
EXEC //from t2
MULTI //from t1
SET foo one //from t1
SET t1 1 //from t1
EXEC //from t1
```

So, yes, if I understand what you're trying to do, you would want multiple clients (also, take a look at `client.duplicate`) and this is expected behaviour.

**Comment by krishnanms** [comment]
Thanks a lot for the reply @stockholmux. Yes I figured out I would have to use `client.duplicate`. If thats the case, then I also have to probably manage connection open/close (perhaps using a connection pool ?). Is there any inbuilt support for connection pooling in node_redis?

**Comment by stockholmux** [comment]
No built-in pooling support - only a handful of cases need pools with Redis (and it's a bad practice when you don't need it). I've not used it with `node_redis` but [generic-pool](https://github.com/coopernurse/node-pool) would probably work. I've never personally used it with Redis, however.

**Comment by BridgeAR** [comment]
Pooling would indeed be useful in this case. The main point here is to use a atomic operation by using `WATCH`. In this case a individual command could be added that hides the necessary logic and automatically pools as well.

**Comment by krishnanms** [comment]
@BridgeAR / @stockholmux : Thanks for the responses. @BridgeAR, could you elaborate on: 
>In this case a individual command could be added that hides the necessary logic and automatically pools as well.

Thanks!

**Comment by BridgeAR** [comment]
That was just a brainstorming on how to implement something like this as a feature in node_redis.
