### ISSUE TITLE
client.hset with 'EX' doesn't work properly

### ISSUE THREAD

**Issue by senseluo** [NodeRedis/node_redis#1324]
My intention is to add expiration for **hset** 
`client.hset(key, field, value, 'EX', 10)`
but looks it doesn't work for me.

Interestingly, when i tried to use set, it works!!
`client.set(key, value, 'EX', 10)`

Does anyone experienced that before?

Thanks!

* **Version**: node_redis (2.8.0)  redis server (4.0.8) 
* **Platform**: macOS High Sierra

**Comment by stockholmux** [comment]
In Redis itself, there is no support for an `EX` option on (HSET)[https://redis.io/commands/hset] - so the client can't provide something the database itself can't do.
