### ISSUE TITLE
Running this redis-cli bash command in node.js?

### ISSUE THREAD

**Issue by peppies** [NodeRedis/node_redis#1326]
Greetings,

I'm trying to run this redis command in node.js:

redis-cli --scan --pattern 'sockets:*' | xargs redis-cli del

When my node server crashes and restarts, I need redis to completely delete certain prefixed redis keys before they can be repopulated. I am using pm2 and cluster with 1 instance running, so it automatically restarts after a crash. I need this command to run before everything is back up and running.

Thanks
Kind regards

**Comment by stockholmux** [comment]
`redis-cli` isn't part of node.js and isn't in the scope of this module. Maybe take your query to stackoverflow?

**Comment by peppies** [comment]
stackoverflow banned me because i didn't ask good enough questions for them.
