### ISSUE TITLE
[BUG] LREM does not pass the number of removed items to the callback.

### ISSUE THREAD

**Issue by vijayanandnandam** [NodeRedis/node_redis#1330]
Node Version: v8.1.2
Node Redis Version: 2.8.0
Redis version: 4.0.8

Steps to replicate

In redis console

```
127.0.0.1:6379>  lpush test 'hello'
(integer) 1
127.0.0.1:6379> lrange test 0 1
1) "hello"
```

Script (redis.js)
```
const redis = require("redis")
const redisClient = redis.createClient("redis://127.0.0.1:6379")
redisClient.lrem('test', 0, 'hello', function(number){
  console.log(number)
})
```
run with `node redis.js`
Expected output of the script the to print the no of removed items
Actual Output is `null`

Test in redis console to confirm removal of the item from list
```
127.0.0.1:6379> lrange test 0 1
(empty list or set)
```

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by dirkbonhomme** [comment]
The first argument in the callback is the error object, which is null on success.  This should work:
```
redisClient.lrem('test', 0, 'hello', function(error, number){
  console.log(number)
})
```

**Comment by vijayanandnandam** [comment]
@dirkbonhomme thanks. This is working
