### ISSUE TITLE
Expiry of a hashmap on set

### ISSUE THREAD

**Issue by codeblooded** [NodeRedis/node_redis#1333]
* **Version**: node_redis 2.8.0
* **Platform**: not version specific, but I'm running v9.11.1
* **Description**: I'm not aware of a way to specify an expiration for a key which is a hashmap in node_redis. In Redis, you can specify the 'expire' command with any key, including one that references a hashmap. When you try the following in node_redis, it's malformed:

```javascript
redis.hmset(accessToken, ['userId', userId], 'EX', 1209600)
```

**Comment by dirkbonhomme** [comment]
Redis only supports to set a key value + ttl on simple keys: SETEX

If you want to expire a hashmap or other type, you need to explicitly call EXPIRE on the key:

```
HMSET accessToken userId 123456
EXPIRE accessToken 1209600
```

You can only set a TTL on a hashmap key, not its fields. Unfortunately..

This is a limitation of Redis and not this library :)
