### ISSUE TITLE
scan command cannot return all matched keys?

### ISSUE THREAD

**Issue by joyfin** [NodeRedis/node_redis#1334]
I used scan command to get all matched keys, but when the cursor equals zero,  i found that the number of key did not equals the number it should be .
for example, there are 10,000,000  keys which match the pattern "scanTest*"，then i executed scan command util the cursor equals zero, but i can't get all the 10,000,000 keys, few keys missed by scan. and also , i did't add or delete key when executing scan command.
but, if the number of keys is less than  10,000,000, like 10,000 ,  all the keys can be return by scan.
 I am so confused about this, someone can tell me why was that? thanks in advance !

**Comment by stockholmux** [comment]
How do you know you have 10,000,000 keys that match `scanTest*`? I'm guessing there is some miss measurement somewhere. 

If you've confirmed that you're actually not getting a full iteration, highly unlikely that this is a problem with 'node_redis' since it's not really doing anything but dumping out the results from Redis itself.

**Comment by joyfin** [comment]
Actually, I inserted the 10,000,000 keys into db firstly, then I scanned those keys.
In my program, I scan the keys with option count 1000, then deleted the result(keys) of scanning using pipeline, and loop the two steps util cursor equals zero. 
It's ok when the number of key is not pretty much, but not ok with number over 10,000,000.
So I think in the progress of scanning and deleting, the key space was shrinking and rehashing, 
the algorithm "reverse binary iteration" may be cannot cover the full iteration.

**Comment by stockholmux** [comment]
Can you share your test case for this?

**Comment by joyfin** [comment]
sure, here is the code: how I scan and delete:
`@Test
    public void scanAndDel() {
        //I have already inserted 10,000,000 keys into db
        String cursor = "0";
        ScanParams scanParams = getScanParams("scanTest*", 1000);
        int totalCount = 0;//number of scanned keys

        Pipeline pipeline = jedis.pipelined();
        try {
            do {
                ScanResult<String> scanResult = jedis.scan(cursor, scanParams);
                cursor = scanResult.getStringCursor();
                totalCount += scanResult.getResult().size();
                
                //delete keys using pipeline
                for (String key : scanResult.getResult()) {
                    pipeline.del(key);
                }
                // check if any exception throw
                List<Object> response = pipeline.syncAndReturnAll();
                Iterator<Object> iterator = response.iterator();
                while (iterator.hasNext()) {
                    Object o = iterator.next();
                    if (o instanceof Throwable) {
                        System.out.println("exception happened, " + o);
                    }
                }
            } while (!"0".equals(cursor));//loop
        } catch (Exception e) {
            //ignore
        } finally {
            jedis.close();
        }
        
        //totalCount did not equals 10,000,000
        System.out.println("scanned key count = " + totalCount);
    }`

**Comment by dirkbonhomme** [comment]
That does not look like node.js code

**Comment by BridgeAR** [comment]
Seems like it is the java client.
