### ISSUE TITLE
[QUESTION] how can make redis fail when executing hgetall query

### ISSUE THREAD

**Issue by spolat** [NodeRedis/node_redis#1335]
Hi everyone I'm writing mocha unit tests for my server. How can I get redis hgetall query error for below code. I've tried close the connection before execute but there's nothing firing.

    redisClient.hgetall(`${anyValue}`, (err, reply) => {
       if (err) {
           // I want to get here
       }
       return done(reply);
    });

**Comment by stockholmux** [comment]
Try [RedFi](https://github.com/openfip/redfi). You can inject an error that way.

**Comment by spolat** [comment]
@stockholmux thanks for reply. I will check it.

**Comment by stockholmux** [comment]
I'm going to go ahead and close this since it's not really an issue.
