### ISSUE TITLE
redis event handler function is losing class reference

### ISSUE THREAD

**Issue by rash805115** [NodeRedis/node_redis#1337]
* **Version**: "redis": "~2.8.0",
* **Platform**: Node.js v8.11.1 on Mac 10.13.4
* **Description**: Call to `on()` method losing reference of class.

Hello. In my application below I am subscribing to different redis events.
For all events, I want to call my router which has the logic to route the request based on nature of events. As you can see in my `redis.js` file, I am registering a function to the receive those events.
```
redisSubscriber.on('pmessage', test.route) <-- Function is an instance of class Test
```

When node-redis calls my `route()` method, it is loosing its object reference i.e. it is not able to access `this`. To illustrate this, I am trying to access `this.message` from the `route()` method which has been called by node-redis on receiving an event.

```javascript
// File - test.js
class Test {
  constructor () {
    this.message = 'hello'
  }

  route (pattern, channel, message) {
    console.log(this.message) // Output: undefined
    console.log(pattern + ' ' + channel + ' ' + message) // Output: __keyevent@*__:set __keyevent@0__:set key
  }
}

module.exports = Test
```

```javascript
// File redis.js
const Redis = require('redis')

let redis = Redis.createClient({
  host: 'localhost',
  port: 6379
})
let redisSubscriber = redis.duplicate()

let Test = require('./test')
let test = new Test()

redisSubscriber.on('pmessage', test.route)
redisSubscriber.psubscribe('__keyevent@*__:set')
redisSubscriber.psubscribe('__keyevent@*__:del')
redisSubscriber.psubscribe('__keyevent@*__:expired')

// Allow redis-subscriber to subscribe to all events.
setTimeout(function () {
  // When I set this key, a set event is generated.
  redis.set('key', 'value', function (error) {
    if (error) throw error

    // Allow set event to propagate, then quit redis.
    setTimeout(function () {
      redisSubscriber.unsubscribe()
      redisSubscriber.quit()
      redis.quit()
    }, 100)
  })
}, 100)
```

**Comment by stockholmux** [comment]
The callback is bound to the client instance. In your case, I think it's a misunderstanding of what classes afford in a prototypal inheritance. So, not an issue with the module (thus the close)

To solve the problem you'll need to bind your callback (e.g. `redisSubscriber.on('pmessage', test.route.bind(test))`).

Just a tip - there are some major issues with how you've coded the `redis.js` example (`psubscribe` is variadic - no need to call 3x times - just past all the patterns in) and the `setTimeout` should be a callback on `psubscribe` the first time.

**Comment by rash805115** [comment]
Thank you @stockholmux for your help 🥇 
I now understand the `new` operator and will fix my code.

Regarding your tip (thank you again!), this is how I wrote it now.
**I did them in 3 lines because of readability issues. My assumption was that doing a "mega" regex patterns vs dividing them into multiple simple patterns have same performance impact. Is this not the case?**

```javascript
redisSubscriber.on('pmessage', test.route.bind(test))
redisSubscriber.psubscribe(/^(__keyevent@\*__:set|__keyevent@\*__:del|__keyevent@\*__:expired)$/, function () {
  redis.set('key', 'value', function (error) { ... }
})
```

**Comment by rash805115** [comment]
From documentation I always used to see the term `pattern`, hence misunderstood it as regex pattern. Anyways, I tried your command and all my tests work, so I am sure this works, but I have a question.

In callback, why is second argument always the last event it subscribed to? Should't it be a count or an array of all events it subscribed to?

```javascript
redisSubscriber.psubscribe('__keyevent@*__:set', '__keyevent@*__:del', '__keyevent@*__:expired', function (error, count) {
  console.log(error) // output: null
  console.log(count) // output: __keyevent@*__:expired
  if (error) throw error
})
```

**Comment by stockholmux** [comment]
Try `console.log(arguments);` in the callback - I think you'll find that enlightening.

**Comment by rash805115** [comment]
I am sorry for making this a NodeJS classroom 🔢 but I didn't get what you were trying to tell me.

For a **non-arrow** function it printed the same thing.
```javascript
redisSubscriber.psubscribe(event1, event2, ... , function () { console.log(arguments) })
// Output: { '0': null, '1': '__keyevent@*__:expired' }
```

For an **arrow** function it printed an empty object, but that was expected because the arguments object is a local variable available within all (non-arrow) functions only.
```javascript
redisSubscriber.psubscribe(event1, event2, ... , () => { console.log(arguments) })
// Output: {}
```

**Comment by BridgeAR** [comment]
@rash805115 
> In callback, why is second argument always the last event it subscribed to?

That is a bad implementation in node_redis but it is a breaking change to fix that. That is the reason why it is like that at the moment.

Arrow functions do not have arguments so what you get is the arguments of the outer scope.
