### ISSUE TITLE
All of function work as asynchronous?

### ISSUE THREAD

**Issue by hyunsooda** [NodeRedis/node_redis#1339]
Hello, I am korean student.
I am writting code with your library.

let num;
db.get('mykey', (err, reply) => {
   num = reply;
    console.log(reply);  // success
});
console.log(num); // undefined

All of function work as asynchronous?
Is there a method that can write as above?

**Comment by ashoksahoo** [comment]
You can't you have to use callbacks, promises, or async await. 
https://github.com/NodeRedis/node_redis#promises
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
