### ISSUE TITLE
ERR wrong number of arguments for 'sadd' command

### ISSUE THREAD

**Issue by SPY-Coder** [NodeRedis/node_redis#1340]
Hi
My source is LUA
I face with this error while applying
lua-redis.lua:381: redis error: ERR wrong number of arguments for 'sadd' command
What is the solution?

**Comment by stockholmux** [comment]
Impossible to tell what the problem is from this - but it sounds like you're somehow missing a argument on the SADD command inside your Lua.

Regardless, that is an error logged _from_ redis/lua so it's not an issue with the module.

**Comment by rainy-me** [comment]
for anyone who encounters this issue: `sadd` command needs at least one member. So `client.sadd(key, [], callback)` will throw this error.
