### ISSUE TITLE
scard does not works

### ISSUE THREAD

**Issue by throrin19** [NodeRedis/node_redis#1343]
* **Version**: 

- node_redis : `2.8.0`
- redis : `4.0.9`

* **Platform**: 

Node.JS `8.11.1` on macOS `10.13.4`

* **Description**: 

the method `client.scard()` don't call the callback :

```
// callback not called
client.scard(key, num => console.log(num));
```

**Comment by BridgeAR** [comment]
@throrin19 the callback is always called. However, you likely only receive `null` because you only print the first argument and node_redis uses the error first callbacks as pretty much everything in the Node.js landscape. So the result is actually the second argument passed to the function.
