### ISSUE TITLE
Add documentation for WATCH ( optimistic locks )

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [NodeRedis/node_redis#1349]
* **Version**:  2.8.0
* **Platform**:  Node 10.1.0
* **Description**:  Add documentation for watch

Background
-----

I have an atomic operation and I need to use a lock to prevent other clients from reading an unstable value. 

Solution
----

According to the official documentation, the solution for this is to use `WATCH` together with `MULTI`: 

 - https://redis.io/topics/transactions
 - https://redis.io/commands/watch

Now, the usage of `MULTI` is documented and I have a general idea on how I can use it. 

```
var redis = require( "redis" );
var bluebird = require( "bluebird" );
var client = redis.createClient();
var multi = client.multi();

multi.hsetAsync( "test", "array", "[1, 2]" );
multi.hgetAsync( "test", "array" );
multi.execAsync( ).then( console.log ); // [ 0, "[1, 2]" ]

```

I understand that this is the correct implementation of multi. First **i need** to create a client, and then I create a multi query.

I understand that `multi` and `client` share the same interface, but it is also not clear what benefits ( if any ) I have from using `hgetAsync` instead of `hget` in a `multi` query, since I assume that all that multi does is adding said requests to a queue synchronously ( therefore I shouldn't need the Async vartiant ).

Upon calling `multi.execAsync( )` the execution of the query will happen **atomically**.

But I don't get how `WATCH` is supposed to enter here. I couldn't find any reference to it in the documentation, not anything regarding the optimist lock system that REDIS has. 

Questions
----

So I have the following questions:

1. Is `WATCH` supported with `MULTI` ?
2. If so, can you share a code snippet ?
3. Does it make sense in this example to use `multi.hgetAsync( "test", "array" );` instead of `multi.hget( "test", "array" );` ?

Request
---

I understand that the projects idea is not to replicate REDIS documentation, but I believe it would be beneficial to have at least one usage example of the optimistic lock system REDIS now provides.

**Comment by Fl4m3Ph03n1x** [comment]
I have found the answers to my questions, and I also have a few code snippets I would like to add to the documentation:

https://stackoverflow.com/a/50734554/1337392

What do you guys think?

**Comment by stockholmux** [comment]
Generally, we have taken the stance of not documenting techniques and commands that are generally just Redis related, not node_redis related. Although, I have questioned this recently as it seems a good percentage of questions we get are from people who assume this module _is_ redis and the README is the canonical source of info about the whole platform (to be clear, it's _not_ and it shouldn't be).

That being said, transactions are tricky and can be non-intuitive when translating from `redis-cli` to a client application. I'd entertain a PR on this, if you're willing to write it. A couple of issues with the MDN/stackoverflow snippet

```
r.watch('foo'); //<-- this is a bad practice. Without a callback, your watch can fail silently

r.get('foo', function(err, result) {
  
  // meanwhile, by the time we get to the next exec(),
  // someone else has modified foo ... <-- this is hard to simulate with this script.

  r.multi()
    .set('foo', "some heavy computation")
    .exec(function(err, results) {
      // Here we find that err is null
      // and results is also null <--- nb, NOT an empty list       
    });
});
``` 

Perhaps a tweaked version that uses two `clients` to show it in action:

```
let clients = {};
clients.watcher = redis.createClient({ ... } );
clients.alterer = clients.watcher.duplicate();

clients.watcher.watch('foo',function(err) {
  if (err) { throw err; }
  //if you comment out the next line, the transaction will work
  clients.alterer.set('foo',Math.random(), (err) => {if (err) { throw err; }})
  
  //using a setTimeout here to ensure that the MULTI/EXEC will come after the SET.
  //Normally, you would use a callback to ensure order, but I want the above SET command
  //to be easily comment-out-able.
  setTimeout(function() {
    clients.watcher
      .multi()
      .set('foo','abc')
      .set('bar','1234')
      .exec((err,results) => {
        if (err) { throw err; } 
        if (results === null) {
          console.log('transaction aborted because results were null');
        } else {
          console.log('transaction worked and returned',results)
        }
        clients.watcher.quit();
        clients.alterer.quit();
      });
  },1000);
});
```

**Comment by Fl4m3Ph03n1x** [comment]
Ahhh, sure I would love to help.
What is the process here? Which files would you have me change?

**Comment by stockholmux** [comment]
@Fl4m3Ph03n1x Just the `README.md` file. For the repo, make your changes to that file and submit a pull request and I'll merge it.

**Comment by Fl4m3Ph03n1x** [comment]
Alright, updated the docs and created a PR:

https://github.com/NodeRedis/node_redis/pull/1352

Let me know if my style is to your liking or if there is something that needs to be fixed.

**Comment by Fl4m3Ph03n1x** [comment]
Hey, any news on the PR ? 
Is there anything you need me to change?

**Comment by stockholmux** [comment]
merged!

**Comment by fasiha** [comment]
Did this documentation change for `WATCH` get rolled back?

**Comment by stockholmux** [comment]
@fasiha No, it's (here)[https://github.com/NodeRedis/node_redis#optimistic-locks]

**Comment by fasiha** [comment]
@stockholmux ahh, I was foolishly looking at the [npmjs page](https://www.npmjs.com/package/redis), which hasn't been published in two years, doh. Sorry for troubling you.
