### ISSUE TITLE
feature req: Redis Streams

### ISSUE THREAD

**Issue by gebrits** [NodeRedis/node_redis#1351]
Is support for the new [Redis Streams](https://redis.io/topics/streams-intro) on the roadmap?

**Comment by stockholmux** [comment]
Command support is handled by an external module (redis-commands) that is itself used by node_redis. I've submitted [redis-commands PR #20](redis-commands/pull/20) which adds all 5.0/RC1 commands (which includes streams). 

In the meantime, you can manually add in the steams commands very easily with the `add_command` function. To use this function, run it on the redis module object itself (_not_ the `client` object):
```
const redis = require('redis');
redis.add_command('xadd');
let client = redis.createClient({ /* your connection */ });
client.xadd(/* arguments */);
```

**Comment by gebrits** [comment]
Awesome. Thanks

**Comment by dkrieger** [comment]
Is there an ability to have this command accept an object like hmset, and/or have xread(group)/xrange return an object like hgetall? Or would that require forking / waiting for the feature?

**Comment by stockholmux** [comment]
@dkrieger Yeah, you'd need to wait for the feature or fork it.

**Comment by tux-00** [comment]
Redis RC5 is out since 1 month, is there any progress on this feature ?

**Comment by stockholmux** [comment]
Streams are now supported because of an update in redis-commands.

**Comment by clodio** [comment]
i do not understand, with the redis 2.8.0 i still have the error.

i also tried without success the exemple https://github.com/NodeRedis/node_redis/blob/master/examples/streams.js

`var redis = require('redis');

redis.add_command('xadd');

redis.add_command('xgroup');

redis.add_command('xreadgroup');`

Error on   client1.xadd('mystream', '*', 'field1', 'm1', function (err) {})

`{ ReplyError: ERR unknown command 'xadd'

    at parseError (C:\node\simple-nodejs\node_modules\redis-parser\lib\parser.js:193:12)

    at parseType (C:\node\simple-nodejs\node_modules\redis-parser\lib\parser.js:303:14)

  command: 'XADD',

  args: [ 'mystream', '*', 'field1', 'm1' ],

  code: 'ERR' }`
