### ISSUE TITLE
Timeout on redis set

### ISSUE THREAD

**Issue by akashaman** [NodeRedis/node_redis#1355]
* **Version**: redis version 2.7.1
* **Platform**: node version 6.10.3 on mac 10.13.2
* **Description**:
I have a cluster of redis, based on the key i try to set and get the value from one particular client.
In case my one of the machine is down, I would like to set and get from some other machine.
In my ts file I am trying something like this
			**redisCluster[index].set(key,value,function(err :any,reply :any){
				if(!err){
                                     // success condition	
				} else {
                                    // get an updatedIndex and use 
                                   redisCluster[updatedIndex].set(key,value,function(err :any,reply :any){
                                      }
				}**
However, when I am testing and bringing a machine down, the set does not return a callback even when the machine is down. Is there a way to configure a timeout on set operation so that I can get an err after timeout has happened and try set on some other redisCluster?

**Comment by stockholmux** [comment]
This client library (alone) doesn't support cluster - are you using [redis-clustr](https://github.com/gosquared/redis-clustr)?

**Comment by BridgeAR** [comment]
Closing due to a lack of response.
