### ISSUE TITLE
Module-specific commands with multi()

### ISSUE THREAD

**Issue by axelpale** [NodeRedis/node_redis#1357]
* **Version**: node_redis 2.8.0 and redis 4.0.10
* **Platform**: Node.js 7.1.0 on macOS 10.13.5
* **Description**:

I am trying to multi-exec [ReJSON](https://oss.redislabs.com/rejson/) commands like below:

    client.multi([
      ['JSON.SET', cellId, jsonpathtile, item],
      ['JSON.SET', cellId, jsonpathstack, '[' + item + ']', 'NX'],
      ['JSON.ARRAPPEND', cellId, jsonpathstack, item]
    ]).exec((err, resp) => {
    ...

However this throws 

    TypeError: Cannot read property 'apply' of undefined
         at new Multi (/Users/xeli/myproject/node_modules/redis/lib/multi.js:18:30)
         at RedisClient.multi (/Users/xeli/myproject/node_modules/redis/lib/individualCommands.js:25:17)
         ...

Running commands individually with `client.send_command` works fine. Seems like `node_redis` tries to find a function `JSON.SET` instead of applying something similar to `send_command` when `multi` array format is used.

I expected that the `multi([array])` allows sending raw commands the API might not provide.

I also tried:

    client.multi()
      .send_command('JSON.SET', [cellId, jsonpathtile, item])
      .send_command('JSON.SET', [cellId, jsonpathstack, '[' + item + ']', 'NX'])
      .send_command('JSON.ARRAPPEND', [cellId, jsonpathstack, item])
      .exec((err, resp) => {
      ...

But that did not work either, throwing:

    TypeError: redb.multi(...).send_command is not a function

Any workaround to this?

**Comment by axelpale** [comment]
The solution was to add the following lines:

    redis.add_command('JSON.SET')
    redis.add_command('JSON.ARRAPPEND')

Maybe this requirement could be better documented under [multi](https://github.com/NodeRedis/node_redis#clientmulticommands) or [add_command](https://github.com/NodeRedis/node_redis#redisadd_commandcommand_name)?

**Comment by stockholmux** [comment]
@axelpale The other option is to use the [ReJSON](https://github.com/stockholmux/node_redis-rejson) bindings. It basically just adds all the commands in so they are available as functions both in the standard client object and `multi`.

I'm going to close this now, but I think the real solution here is to make a multi-friendly `send_command` function. I've looked into it but I don't think it's exactly straight-forward. Do-able, just would take effort. Feel free to open a feature request if you agree.
