### ISSUE TITLE
keys() returning keys with prefix: 

### ISSUE THREAD

**Issue by ashishrp** [NodeRedis/node_redis#1362]
```
let redis = require('redis')
let client = redis.createClient({url:'url:port', prefix:'myapp'})
```

- keys() is returning resluts with prefix:'myapp'
- but get/del is not supported with that prefix
- keys() should return without prefix (from client initialization)

keys('*myprefix*') output `[ 'myapp:myprefix-somedynamickey' ] `

* **Version**: node_redis:2.8.0 and redis version latest build from github repo
* **Platform**:  Node.js 8.11.3 Ubuntu 16.04

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by stockholmux** [comment]
This isn't a native functionality of Redis and the prefix option in node_redis only affects key arguments. The `KEYS` command doesn't have a key argument so prefix won't work (and it's not something we plan on implementing as we only minimally provide functionality over native Redis functionality).

It would be relatively trivial to make this functionality with `map` but it doesn't belong in the node_redis module.
