### ISSUE TITLE
Is it possible to set expire time while set hash keys using hset?

### ISSUE THREAD

**Issue by bdavid68** [NodeRedis/node_redis#1364]
I want to set expire date to hash key while using `hset` function.
Is it possible?

**Comment by stockholmux** [comment]
You can expire the entire key with `pttl` or `ttl` but you can't expire individual hash fields. 

If you need it to be atomic on `hset` then do a `multi`,`hset`,`ttl`,`exec` sequence.

This is a native functionality of Redis. Good luck!
