### ISSUE TITLE
About SSH

### ISSUE THREAD

**Issue by uniorder** [NodeRedis/node_redis#1365]
Could you tell me how to use SSH for redis connection? I have no idea, very thanks.

**Comment by stockholmux** [comment]
[See the Readme](https://github.com/NodeRedis/node_redis#rediscreateclient), but effectively you specify your `key`, `cert` and `ca` as strings in your `options` object until `tls`.

**Comment by uniorder** [comment]
I know how to do, thank you.

**Comment by offaxis** [comment]
> I know how to do, thank you.

Hi, 
Can you give us an example please ?
