### ISSUE TITLE
multi and fail

### ISSUE THREAD

**Issue by kiko35** [NodeRedis/node_redis#1366]
Hello I read this example:

client.multi([
    ["mget", "multifoo", "multibar", redis.print],
    ["incr", "multifoo"],
    ["incr", "multibar"]
]).exec(function (err, replies) {
    console.log(replies);
});

and I was wondering if the command  ["mget", "multifoo", "multibar", redis.print] is executed correctly but ["incr", "multifoo"] failed. Is there a rollback and everything is cancelled?

Thanks

**Comment by stockholmux** [comment]
Redis has no concept of rollbacks, and this module only provides what Redis provides.

The MULTI/EXEC model is pretty specific. The [redis docs](https://redis.io/topics/transactions#errors-inside-a-transaction) describe the model better than I would ever be able to.

**Comment by kiko35** [comment]
Thanks
