### ISSUE TITLE
Unable to read data from redis 

### ISSUE THREAD

**Issue by jatincr7** [NodeRedis/node_redis#1373]
getting data from redis :-{"success":1,"msg":"{\"menus\":[{"success":1,"msg":"{\"menus\":[{\"id\":2,\"name\":\"Companies\",\"url\":\"#/company\",\"menu_func\":\"\"},{\"id\":3,\"name\":\"Customers\",\"url\":\"#/administration\",\"menu_func\":\"4\"},{\"id\":4,\"name\":\"Users\",\"url\":\"#/administration\",\"menu_func\":\"0\"},{\"id\":5,\"name\":\"Roles\",\"url\":\"#/administration\",\"menu_func\":\"1\"},{\"id\":6,\"name\":\"Policies\",\"url\":\"#/administration\",\"menu_func\":\"2\"},{\"id\":7,\"name\":\"Groups\",\"url\":\"#/administration\",\"menu_func\":\"3\"},{\"id\":8,\"name\":\"Automation\",\"url\":\"#/automation\",\"menu_func\":\"\"},{\"id\":9,\"name\":\"Tags\",\"url\":\"#/administration\",\"menu_func\":\"5\"},{\"id\":10,\"name\":\"Commands\",\"url\":\"#/administration\",\"menu_func\":\"6\"},{\"id\":11,\"name\":\"Profile\",\"url\":\"#/profile\",\"menu_func\":\"\"},{\"id\":12,\"name\":\"Visualization(Beta)\",\"url\":\"#/administration\",\"menu_func\":\"7\"},{\"id\":13,\"name\":\"Documentation\",\"url\":\"#/documentation\",\"menu_func\":\"7\"}]}"}
data from api response :-1: 
{"success":1,"msg":{"menus":[{"id":2,"name":"Companies","url":"#/company","menu_func":""},{"id":3,"name":"Customers","url":"#/administration","menu_func":"4"},{"id":4,"name":"Users","url":"#/administration","menu_func":"0"},{"id":5,"name":"Roles","url":"#/administration","menu_func":"1"},{"id":6,"name":"Policies","url":"#/administration","menu_func":"2"},{"id":7,"name":"Groups","url":"#/administration","menu_func":"3"},{"id":8,"name":"Automation","url":"#/automation","menu_func":""},{"id":9,"name":"Tags","url":"#/administration","menu_func":"5"},{"id":10,"name":"Commands","url":"#/administration","menu_func":"6"},{"id":11,"name":"Profile","url":"#/profile","menu_func":""},{"id":12,"name":"Visualization(Beta)","url":"#/administration","menu_func":"7"},{"id":13,"name":"Documentation","url":"#/documentation","menu_func":"7"}]}}

**Comment by stockholmux** [comment]
@jatincr7 Please provide some code that is causing this. We can't help if you don't provide some sort of context.

**Comment by jatincr7** [comment]
function getCache(key, callback) {

    clientredis.on('error', ((err) => {
        console.log(err.stack)
    }))

    if (key) {
        clientredis.get(key, function (err, response) {
           console.log(response)
            callback(err, response);
        })
    }

}


function setCache(key, value, callback) {

    clientredis.on('error', ((err) => {
        console.log(err.stack)
    }))

    if (key) {
      
        clientredis.set(key,JSON.stringify(value), function (err, response) {
            console.log('Cache Added with Key'+':'+key)
        
            callback(err, response);
           
        })
    }

}



function deleteCache(key, callback) {

    clientredis.on('error', ((err) => {
        console.log(err.stack)
    })) 

    if (key) {
        clientredis.del(key, function (err, response) {
            callback(err, response);
        })
    }

}
function manageCache(operation, key, value = null, rid = null, rvalue = null) {

    var cacheResult = '';
    getCache(key, function (err, result) {
        if (result) 
            cacheResult = result;    
            console.log(cacheResult)    
    });  

    if (operation == 'add') {

        if(cacheResult){
            var inputData = new Array();
            inputData.push(cacheResult);
            inputData.push(value);
            setCache(key,inputData,((err,data)=>{
                if(!err){
            console.log('Added Cache with key'+':'+key+'Data'+data)
                }

            }))
        }else{

        setCache(key,value,((err,data)=>{
            if(!err){
                console.log('Cache added with this key'+''+key+''+'first time')
            }
        }))
        } 
        
    }
    if(operation=='get'){
        if(cacheResult){

            console.log('Getting cache Result'+cacheResult)
        }
    
    }

    if (operation == 'delete') {
        console.log('Caching operation on delete')

        if(cacheResult){
            console.log(cacheResult)
            console.log('hii')
            console.log('rid'+''+rid+''+'rvalue'+rvalue)
            let id1=result.id
            var deleteRow=cacheResult.filter(item => item.id == !id1)
            console.log(deleteRow)
            console.log(deleteRow)
            setCache(key,deleteRow,((err,data)=>{
                if(!err){
                    console.log('Cache deleted!& updated Cache with data'+data)
                }

            }))
                 
        }
        
    }


    if (operation == 'update') {

        if(cacheResult){
            
            cacheResult.filter(item => item.id == !rvalue)
            
            var inputData = new Array();
            inputData.push(cacheResult);
            inputData.push(value);
            setCache(key, inputData,  ((err, response)=> {
            console.log('existed cache with Operation: ' + operation + '--' + key + ' has been modified.');
           
        }))
        
    }

  
}

}








 app.get("/getMenuData", function (req, res) {
        
        // deleteCache('MenuData',((err,data)=>{
        //     console.log('Cache Deleted')
        // }))

        
        
        getCache('MenuData',((err,result)=>{
            if(data){
                //console.log(result)
            console.log('Sending Data from Cache')
               // console.log(data)
               console.log(result)
                res.json({ success: 1, msg:result});
            }
        else{
    
        
        if (con == null)
            con = db.openCon(con);

        var obj = {};

        obj.menus = '';

        var sql = '';
        var assignedmenus = '';

        if (req.session.policyId != undefined && req.session.policyId != "" && req.session.policyId != '0' && req.session.policyId != null) {


            con.query("SELECT assigned_menus from policy where id = ? ", req.session.policyId, function (err, result) {

                if (!err) {
                    assignedmenus = result[0].assigned_menus;

                    //if(assignedmenus == "")
                    //	sql = "SELECT id, name, url, menu_func from menus where is_deleted = 0 order by menu_order asc";

                    if (assignedmenus != "") {

                        sql = "SELECT id, name, url, menu_func from menus where is_deleted = 0 and id in (" + assignedmenus + ") order by menu_order asc";

                        con.query(sql, function (err, result) {

                            if (err) {
                                res.json({ success: 0, error: err.stack });
                            } else {

                                if (result.length > 0) {
                                    obj.menus = result;
                                }
                                manageCache('add','MenuData',obj)
                                 console.log('menu data Cache')
                            
        
                                res.json({ success: 1, msg: obj });
                            }

                        });

                    } else {
                        setCache('MenuData',data)
                        console.log('menu data Cache')
                        res.json({ success: 1, msg: obj });
                    }

                }

            });

        } else {


            sql = "SELECT id, name, url, menu_func from menus where is_deleted = 0 order by menu_order asc";

            con.query(sql, function (err, result) {

                if (err) {
                    res.json({ success: 0, error: err.stack });
                } else {

                    if (result.length > 0) {
                        obj.menus = result;
                    }
                     setCache('MenuData',obj)
                     console.log('menu data Cache')
                    res.send({ success: 1, msg:obj});

                }
            
            
            });

        }
    }
    }))
    });

**Comment by stockholmux** [comment]
First, `clientredis.on('error', ...)` - no need to have that multiple times.
Second, in `manageCache` you're not handling asynchrony. `cacheResult` will always be `''` as the code will continue executing and not wait for the callback. Also, you should handle errors.

You'll need to refactor this code to account for asynchrony - not an issue with the module. Good luck!
