### ISSUE TITLE
Ability to subscribe to variable changes

### ISSUE THREAD

**Issue by lElectrico** [NodeRedis/node_redis#1374]
I apologize if this issue was created before.

Well, I currently have a server and a client, this server is doing some set(); with some json data. How can my nodeJs client detect wether this data changes asynchronously?

For example: the server sets up this key/data: "player.1"/"{username:"lElectrico", mail:"some@email.com"}, my Client has it, then the server changes it no matter why and now it's "player.1"/"{username:"NotlElectrico", mail:"notsome@email.com"}, how can my Client know about this change?

Thank you,
Ken.

**Comment by davalapar** [comment]
https://redis.io/topics/notifications

https://github.com/NodeRedis/node_redis/issues/573
