### ISSUE TITLE
Redis connection failed

### ISSUE THREAD

**Issue by xyboox** [NodeRedis/node_redis#1375]
* **Version**: What node_redis and what redis version is the issue happening on?
node-redis@0.1.7
redis@2.8.0

* **Platform**: What platform / version? (For example Node.js 0.10 or Node.js 5.7.0 on Windows 7 / Ubuntu 15.10 / Azure)
NodeJS v8.12.0 on Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-135-generic x86_64)

* **Description**: Description of your issue, stack traces from errors and code that reproduces the issue
Randomly get this error: 
Redis connection to 127.0.0.1:6379 failed - write EPIPE at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' 

Any idea where to look for the issue?

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by stockholmux** [comment]
This looks like it's a connection issue - double check all the ports are open and stuff.

-K

**Comment by xyboox** [comment]
@stockholmux thanks, thanks, that much I figured, I was interested about the specifics of the cause ( if anything retraceable from the error message ). I guess is not possible though...

**Comment by stockholmux** [comment]
@xyboox Nope. That's an error generated by Node.js. Sorry.

**Comment by doghappy** [comment]
The same error in [Stackoverflow](https://stackoverflow.com/questions/34090370/redis-connection-to-redis-abc-abc-failed-write-epipe)
