### ISSUE TITLE
NodeRedis don't exit process when using .end .quid

### ISSUE THREAD

**Issue by FelipeBarrosCruz** [NodeRedis/node_redis#1376]
In my test suite I need to up a redis connection and when all tests is done I need to close the connection and free the event loop of redis connection strem.
The methods are list dosn't free the event loop.
I solve with: process.exit(0)

Some other way to do that?

**Comment by stockholmux** [comment]
I think you want [`client.quit()`](https://github.com/NodeRedis/node_redis#clientquitcallback).
