### ISSUE TITLE
Try if Redis server is running

### ISSUE THREAD

**Issue by juriansluiman** [NodeRedis/node_redis#138]
I have a node.js server starting at boot with Ubuntu's `upstart`. Because the node.js server starts before Redis is up and running, `redis.createClient()` throws an exception: 

```
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Redis connection to 127.0.0.1:6379 failed - ECONNREFUSED, Connection refused
    at Socket.<anonymous> (/var/www/php-jobs/node_modules/redis/index.js:88:28)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:830:27)
    at EventEmitter._tickCallback (node.js:126:26)
```

Of course I try to wrap it in a try/catch statement. The start of my server:

```
var redis  = require("redis");

function initializeRedis(callback) {
    (function createClient(){
        var client;
        try {
            client = redis.createClient();
        } catch (e) {
            setTimeout(createClient, 1000);
        }
        callback(client);
    })();
};

initializeRedis(function(client) {
  // Do things with client
});
```

However, this doesn't make any difference, I still got an exception. What can be the case and how can I make sure my server waits before Redis is there?

**Comment by t3ndai** [comment]
Has any of this been handled! I'm trying to catch the errors in a try catch block. But, it's not working.

**Comment by 12mse0306** [comment]
const client = redis.createClient({
  host: process.env.redis_hostname,
  port: process.env.redis_port
})
client.on('error', (error) => {
  logger.error(error.message);
})
client.on('connect',()=>{
  logger.info('Successfully connected to redis');
})


![image](https://user-images.githubusercontent.com/25304253/43071388-4b652878-8e90-11e8-8540-17b3352042f9.png)
So this will keep on polling to connect to redis server and when it finds a connection it will automatically connect

**Comment by domajor** [comment]
[master] Starting Cryptonote Node.JS pool version v2.0.0
(node:2240) UnhandledPromiseRejectionWarning: Error: The client is closed

I'm so tired, I have no hope :( I'm using Ubuntu Server 20
