### ISSUE TITLE
Client unref does not keep process alive

### ISSUE THREAD

**Issue by alewaros** [NodeRedis/node_redis#1382]
* **Version**: 2.8.0
* **Platform**: Node 10.12.0 on macOS 10.14
* **Description**: Running the sample code from `client.unref()` does not produce the expected behavior of printing the value nor throwing an error before closing the process. Adding a timeout keeps the process alive long enough to log the value.

In the documentation there is the line:

> exit immediately after the get command finishes

Does it mean finishing the execution of the command or the overall completion of it?

```js
import redis from 'redis'

const client = redis.createClient()

client.unref();
client.get("foo", function (err, value) {
    if (err) console.log(err);
    console.log(value);
});

// Removing this line allows the value to be printed
// setTimeout(() => {}, 2000)
```

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by tlhunter** [comment]
By convention, the `.unref()` methods implemented in the Node API and many npm modules simply removes the reference from a reference counter that keeps track of whether or not a process should end or not.

Are you asking if the command is sent to the server or not? I could see that being undefined behavior. Try running the redis CLI, then running the `MONITOR` command, and then running this script. You'll then see if the server receives the command or not.

**Comment by BridgeAR** [comment]
@tlhunter thanks for answering!

@alewaros the `unref` command is likely not what you expect it to be and you likely just want to remove it.
