### ISSUE TITLE
send_command not working with some commands

### ISSUE THREAD

**Issue by may215** [NodeRedis/node_redis#1384]
Ubuntu 16.04, Digitalocean
Node: 8.11.3
redis: ^2.8.0

I am trying to run this command and I am getting wired results of true and undefined, can you please tell me how to run this command?

client.send_command("scan 0 count 10", [], function (err, replies) {
    console.log(replies);
});

**Comment by stockholmux** [comment]
@may215 the first argument is the command (`scan`) and the rest would go individually in the second argument array.
