### ISSUE TITLE
Maximum number of open connections reached

### ISSUE THREAD

**Issue by exotfboy** [NodeRedis/node_redis#1387]
```
const redis = require('redis');
let client = redis.createClient(process.env.redis_url);
client.get(key, function (error, data) {
  console.info("result with key:" + key + " res: " + data + " err:" + error)
  if (error) {
    return callback(error);
  }
  if (data) {
    return callback(null, data);
  }
}
```
When I run using the above codes, I get message like this:
> result with key: xxx res: Maximum number of open connections reached. err:null

There are two questions I can not make sure:

1.  Why the `error` object in the callback is null event it throw a err?
So  I have no idea to know if the query is success or not.

2. This error occured at the first time I connection the redis
Which means there should not be too many requests to redis-server, what happened.

BTW, I am using redis in docker with version of 5.0.1, this is the output from docker console when it started:

> cache    | 1:C 13 Nov 2018 03:18:53.419 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> cache    | 1:C 13 Nov 2018 03:18:53.419 # Redis version=5.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
> cache    | 1:C 13 Nov 2018 03:18:53.419 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
> cache    | 1:M 13 Nov 2018 03:18:53.421 * Running mode=standalone, port=6379.
> cache    | 1:M 13 Nov 2018 03:18:53.421 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> cache    | 1:M 13 Nov 2018 03:18:53.421 # Server initialized
> cache    | 1:M 13 Nov 2018 03:18:53.422 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> 

And this is the docker-compose.yaml:

```
version: "3"
services:
  app:
      links:
        - redis
      build: ./
      ##other config omitted
  redis:
      image: redis
      container_name: cache
      expose:
      - 6379
```

**Comment by tlhunter** [comment]
Maybe you have background processes connected to Redis (e.g. runaway Node processes). If you connect using the CLI utility and run `info clients` what is the output?

The connection error might technically happen outside of your `.get` call. Redis probably is delaying the command until a connection is established. Try adding the following to get connection errors:

```javascript
let client = redis.createClient(process.env.redis_url);
client.on('error', (e) => {
  console.error('connection error', e);
});
client.on('connect', (e) => {
  // or wait until connection happens then run commands
});
```

**Comment by BridgeAR** [comment]
Everything is actually working as intended. @exotfboy you seem to have the string `Maximum number of open connections reached.` as value saved in Redis with this specific key. You can verify that by using the debug mode.

**Comment by BridgeAR** [comment]
@tlhunter thanks a lot for looking into this as well.
