### ISSUE TITLE
multiple createClient bad?

### ISSUE THREAD

**Issue by bearinld004** [NodeRedis/node_redis#1393]
just curious im namespacing my database and doing multiple create client like so.
```
var users = redis.createClient({db: 1});
var tokens = redis.createClient({db: 2});
```
im doing this because its cleaner than doing select db and a callback to get or set. but im not sure of this being an okay pattern, maybe i missed something. Im new to redis.

**Comment by stockholmux** [comment]
Generally, numbered DBs are frowned upon as they don't scale well. Additionally, having multiple clients creates more overhead (extra connection on both the client and the server side).

Being that this is more of advice, I'm going to close out this issue.
