### ISSUE TITLE
Support for redis 5?

### ISSUE THREAD

**Issue by hmpmarketing** [NodeRedis/node_redis#1397]
Hi all,

When will this package be updated to support version 5? I have tried the zpopmax command but it gives a zpopmax is not a function

**Comment by gkorland** [comment]
Which version of redis-commands are you getting? 
It seems like command was added 6 months ago as part of v1.4.0
https://github.com/NodeRedis/redis-commands/commit/651d1592b7103cf045e0b0be0ca0532a19e6bfe9

**Comment by hmpmarketing** [comment]
Hi @gkorland 

Using npm show redis-commands version gives me 1.4.0

**Comment by gkorland** [comment]
it just worked for me, can you please add the error you're getting?

**Comment by hmpmarketing** [comment]
campaign_data = await redis.zpopmaxAsync(`zaplaylist:1234`).then(function(campaign_data) {
      return campaign_data
  });

Gives me a redis.zpopmaxAsync is not a function (Im using bluebird to promisify)....FIY, the above works for other redis commands just fine (like redis.hgetallAsync() for example)

**Comment by hmpmarketing** [comment]
Hi, thanks for your reply @stockholmux 

Here is the code in question:

`    
var redis = redisclient.createClient({
	host:rd.host,
	port:6379
});

Promise.promisifyAll(redis);

campaign_data = await        redis.zpopminAsync(`zaplaylist:${req.body.account_id}`).then(function(campaign_data) {
      return campaign_data
    }); `

Error: UnhandledPromiseRejectionWarning: TypeError: redis.zpopminAsync is not a function

FYI, all other redis functions work just fine with promisifyAll(). Running Redis 5.0.2 local. I have tried the other NPM package iosredis and the above function works as expected

**Comment by stockholmux** [comment]
Looks like you had a cached redis-commands package - the node_redis package has "use latest" flag for redis-commands, so it will grab a potentially out-of-date version from the dependency graph. Glad it works now.
