### ISSUE TITLE
Suggestion: Support for null 'EX' expiration and time arguments when setting keys?

### ISSUE THREAD

**Issue by ncarbon** [NodeRedis/node_redis#1398]
* **Version**:  Node v8.9.4 Redis v2.8.0
* **Platform**: Mac OS Mojave
* **Description**: I am currently doing both regular key set and expiring key sets. Instead of having something like this 
```
if(expiration was provided) {
    client.set('key', 'value', 'EX', 10,  (err, reply) => {
   ...
   });
} else {
   client.set('key', 'value', (err, reply) => {
   ...
   });
}
```

would be nice if you could just pass in null value for 'EX', and 10 when it's not the case that you want the key to expire, that way you're not repeating your code.

I tried passing in null values but I get this error message:

> Deprecated: The SET command contains a "null" argument.
This is converted to a "null" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The SET command contains a "null" argument.
This is converted to a "null" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by stockholmux** [comment]
We do support the `EX` argument. Your error message is unrelated - you are passing in a null value :)
