### ISSUE TITLE
exists function is sometimes not working

### ISSUE THREAD

**Issue by JangJeongHyeon** [NodeRedis/node_redis#1400]
I use redis server on local desktop or remote test server.

i wanna set the key when is not exists on redis server.

so i'm check key exists as follow code
### connect function
``` javascript
// Redis Connection Pool
let pool;

// Redis Connect
export const connect = async () => {
  try {
    if (!pool) {
      pool = await redis.createClient({
        host: RedisConf.connect.name,
        port: RedisConf.connect.port,
        db: 0
      });
    }
  } catch (err) {
    console.log(`Redis Connect Error - ${err}`);
  }
  return pool;
};
```

### exists function
``` javascript
export const exists = async pKey => {
  const rds = await connect();
  let existsResult;
  try {
    existsResult = await rds.exists(pKey);
    console.log(existsResult);
  } catch (err) {
    console.log(`Exists Command Error - `, err);
  }
  return existsResult;
};
```

### using above code on my custom middleware module
``` javascript
// is write in side of async function
 const redisKey = `${RedisConf.keyName.app}:${authKey}`;
    // Check Is In Redis Server
    let isRedisExists = await RedisUtil.exists(redisKey);
    isRedisExists = Boolean(isRedisExists);
    console.log(`isRedisExists => ${isRedisExists} => ${!isRedisExists}`);
    try {
      if (!isRedisExists) {
        console.log(`redis Set Process => start`);
        // Do something
      ]
    }catch(err){
    // Do something
   }
```

when i set new using by key exists function, and that sometimes return true value, even not stored on my redis server (local or remote test server)

### My Console Result
![image](https://user-images.githubusercontent.com/12607304/49708254-362a1900-fc72-11e8-9442-2f07b1de2426.png)

### My Local Redis Server
![image](https://user-images.githubusercontent.com/12607304/49708269-48a45280-fc72-11e8-8bd7-5fe6dc42c9f5.png)

How can i solve above problem ??

**Comment by tlhunter** [comment]
You might have a race condition in your code. For example, if multiple requests happen at once (e.g. you load a webpage, which loads a few resources, they might generate parallel requests).

Depending on your use case you might need SETNX instead of SET, or you might want to chain your commands using the `.multi()` command.
https://redis.io/commands/setnx
https://redis.io/commands/multi

This might help too:
https://thomashunter.name/posts/2017-07-13-redis-and-node-part-3-atomicity-with-multi

**Comment by stockholmux** [comment]
I think @tlhunter is correct here regarding the race condition. 

Also, it looks like you're creating a connection each time - that adds to the complications and is generally not required, needed, or preferred.

**Comment by JangJeongHyeon** [comment]
@tlhunter @ @
