### ISSUE TITLE
XADD with MAXLEN arg

### ISSUE THREAD

**Issue by RJPhillips01** [NodeRedis/node_redis#1406]
Hi there,

I cannot run .XADD command and specify MAXLEN argument with * argument. Redis documentation here - https://redis.io/topics/streams-intro  - shows this cli command (which works)

XADD mystream MAXLEN 2 * value 1

If I do something like this:

redisclient.xadd('mystream ','*', 'value','1', function (err) {
        if (err) {
            return console.error(err);
        }
    });

then this works

but if I change the '*' to 'MAXLEN 2 *' then it doesn't work. I've also tried inputting as an array - e.g. 

['*','MAXLEN 2'] but this doesn't work either.

Thanks, Rich.

**Comment by stockholmux** [comment]
Try `client.xadd('mystream','MAXLEN','2','*','value','1',...)`.

**Comment by RJPhillips01** [comment]
Many thanks - I'll give it a try.

**Comment by BridgeAR** [comment]
Closing as resolved.
