### ISSUE TITLE
how can I get the redis return

### ISSUE THREAD

**Issue by luanjinlong** [NodeRedis/node_redis#1410]
if I create a function like this,I find I can not get the redis data. so , I want to know how can I get the callback data. thank you
````
function lrangeRedis(to, key, start = 0, end = -1) {
    // 将聊天语句存入 redis
    return client.lrange(key, start, end, function (err, data) {
        if (!err) {
            return data
        }
    })
}
````

**Comment by tuananh** [comment]
@luanjinlong  you can either use callback to get data back or just use async/await.

**Comment by luanjinlong** [comment]
@tuananh  I do not know how to ge the callback data. I can only get the data in the callback. but I want to get the data outside the callback . thank you

**Comment by tuananh** [comment]
try the example in the readme

```
const {promisify} = require('util');
const getAsync = promisify(client.get).bind(client);

async myFunc() {
    const res = await getAsync('foo');
    console.log(res);
}
```

**Comment by stockholmux** [comment]
@luanjinlong As others have written, you'll need to manage the variable scope either through something like `async`/`await` or a global variable. This, however, isn't a node_redis issue, so you'll need to seek out the many resources on how to manage this common pattern in Javascript in general. That being said,  I think we can close out this issue.
