### ISSUE TITLE
Set expiration time, clear multiple keys by custom prefix

### ISSUE THREAD

**Issue by foo123** [NodeRedis/node_redis#1412]
Two questions:

NOTE: Having more examples in the repository would be very helpful (eg the ones I mention below).

1. Set expiration time for a key when a key is set with set command, how to do?

2. I would like to clear multiple keys which share a custom prefix, how to do that exactly? Should I list keys `prefix*` and delete or is there alternative?

Thank you

**Comment by stockholmux** [comment]
1. You have some options to do that but there is no automatic way to do so on a module level. For individual commands you can do `SETEX` for string type keys OR use `MULTI`/ (some command) / `TTL` / `EXEC`.
2. Prefix delete is a classically hard problem to solve in Redis. In general, you shouldn't rely on keyspace prefix iteration in Redis. You can achieve it by `SCAN` and `UNLINK` but it's not atomic and will require several passes.

**Comment by foo123** [comment]
Is the expire command `EXPIRE` or `TTL` or both can be used?

Right now I have the following in my code (analog versions of code from my original php codebase that uses Redis):

```javascript
    RedisCache[PROTO].put = function( key, data, ttl, cb ) {
        ttl = +ttl;
        this.connect().redis.multi()
            .set(this.prefix+key, _.serialize([_.time()+ttl, data]))
            .expire(this.prefix+key, ttl)
            .exec(function(err, res){
                if ( 'function' === typeof cb ) cb(err, res);
            });
    };

    RedisCache[PROTO].clear = function( cb ) {
        var self = this;
        this.connect().redis.keys(this.prefix+'*', function(err, keys){
            if ( err || !keys || !keys.length )
            {
                if ( 'function' === typeof cb ) cb(err, err ? false : true);
                return;
            }
            var multi = self.redis.multi();
            for(var i=0,l=keys.length; i<l; i++)
            {
                multi.del(keys[i]);
            }
            multi.exec(function(err, res){
                if ( 'function' === typeof cb ) cb(err, res);
            });
        });
    };

```

Please advise..

**Comment by stockholmux** [comment]
Sorry. I just edited it. `EXPIRE` is correct, my mistake.

In your code, the `.put` is fine. In the `.clear`, you shouldn't use `KEYS` - it's for debugging only. Read up on `SCAN` - much safer to use. Finally, use `UNLINK` instead of `DEL` - it's faster.

**Comment by foo123** [comment]
Ok thanks for the quick answer will check SCAN and UNLINK (I guess I will have to do so in my php codebase as well)

Thanks again
