### ISSUE TITLE
Need help with llen command

### ISSUE THREAD

**Issue by yiwong2001** [NodeRedis/node_redis#1415]
* **Version**: node 11.8.0
* **Platform**: Mac
* **Description**:   I am new to use redis. I am testing to insert a few elements to list and get its length.

var redis = require("redis"),
client = redis.createClient();
var key = "data:key";
  client.lpush(key,"element_1");
  client.lpush(key,"element_2");
  client.lpush(key,"element_3");
  client.lpush(key,"element_4");
  console.log(client.LLEN(key));

it always print out false for me. 

Can you explain if I am wrong there? thanks

**Comment by stockholmux** [comment]
You need to add callbacks.
