### ISSUE TITLE
error:ERR value is not an integer or out of range code:

### ISSUE THREAD

**Issue by loretoparisi** [NodeRedis/node_redis#1416]
I get the error `error:ERR value is not an integer or out of range code:` when doing client.set.
The error returned contains
```javascript
{
  "command": "SET",
  "args": [
    "1fd24e820c01a0695048558632dfb832", "VERY_LONG_TEXT",
    "EX",
    null
  ],
  "code": "ERR"
}
```

where `VERY_LONG_TEXT` is a string of ~80KB characters

**Comment by BridgeAR** [comment]
@loretoparisi the problem is the third argument as it's set to `null`.

**Comment by loretoparisi** [comment]
@BridgeAR thank you! So it seems it was the cache expire!
