### ISSUE TITLE
Ability to drain client command_queue immediately after execution (and not after CB)

### ISSUE THREAD

**Issue by shaharido1** [NodeRedis/node_redis#1422]
* **Version**: node redis 2.8.0, redis server 5~
* **Platform**: nodejs 8.9~ on ubuntu.

Hey, 
I have a strong back pressure on my Redis client (thousands of set operations a second). speed is more important then 100% delivery - so it's ok to drop some if necessary.  

I've noticed that when using batching, the client.command_queue is not drained after execution, but only after the execution CB. 
e.g. 
batch = client.batch()
// gather set operations//
batch.exec(()=> console.log(client.command_queue_length)) //here
console.log(client.command_queue_length) //and not here

this makes sense to ensure delivery to the server - but in my case it causes memory leak. 
because the response from the server is delayed, the queue is getting bigger and bigger, and after a while makes node crush (heap memory issue).

I'm wondering if there's a way to send the set operations, then immediately drain the queue - regardless of if and when the server responds (save the time of the return trip of "ok" messsages)?  
Following question - is there a max/optimal batch size? 

thank you (:

**Comment by BridgeAR** [comment]
You may use the [`CLIENT REPLY`](http://redis.io/commands/client-reply) command in this case. It should be exactly what you require. In that case the commands are called as `fire and forget`.
