### ISSUE TITLE
multiple subscription callbacks for single published message?

### ISSUE THREAD

**Issue by jchowdown** [NodeRedis/node_redis#1428]
* **Version**: node_redis v2.8.0 redis server v2.8.17
* **Platform**: Node.js v0.10.48 on MacOs 10.13.6
* **Description**: 
I'm using StackExchange.Redis (2.0.571) to publish a single message (a block of json) from a C# client. 

> 
	    void PostSomeStuff(string id, bool ok)
	    {
		    var res=new Payload
		    {
			    id=id,
			    pid=Program.PID,
			    ok=ok
		    };
		    var body=JsonConvert.SerializeObject(res);
		    Program.WriteDebug("attempting to publish "+body);
		    m_redisHelper.Database.Publish("foo", body);
	    }

Logging:
>
	   attempting to publish {"id":"5ca6cb21506b9e3b5cc29670","pid":29761,"ok":true}

On the subscriber side I have a "message" callback that prints out some logging and unsubscribes the subscriber from the channel. 

> 
	var onDone = function() {
		self.redis_sub.unsubscribe("foo");
		// some other stuff here
	};

>
	self.redis_sub.subscribe("foo");
	self.redis_sub.on("message",function(channel,message) {
		var res = JSON.parse(message)||{};
		var id = res.id || 'NONE';
		var pid = res.pid || 'NONE';
		var ok = res.ok || false;
		log("DDD",uid,{id:id,ok:ok,pid:pid});
		onDone();
	});

Results:
>
[log] DDD uid=1000001 id=5ca6cb21506b9e3b5cc29670 ok=true pid=29761
[log] DDD uid=1000001 id=5ca6cb21506b9e3b5cc29670 ok=true pid=29761
[log] DDD uid=1000001 id=5ca6cb21506b9e3b5cc29670 ok=true pid=29761
[log] DDD uid=1000001 id=5ca6cb21506b9e3b5cc29670 ok=true pid=29761

Most of the time I get one invocation of my callback but sometimes I get 2,3, and even 4 invocations. Has anyone seen this before? I didn't think that >1 calls were possible because I immediately unsubscribe from the channel on receiving the first message.

Thanks,
Jeff

**Comment by jchowdown** [comment]
DFE issue :(

**Comment by BridgeAR** [comment]
I can not tell how I do not know what happens but it is absolutely possible that the client sends multiple messages (e.g., if the client listens on the same channel multiple times) and the unsubscribe is just fired async. Until it is received and processed by redis, multiple calls could already be send by the server.

**Comment by jchowdown** [comment]
this is a DFE error because each time I call sub.on(...) it's adding a callback. The more requests I handle the more times my callback will be invoked :)
