### ISSUE TITLE
hGet goes to deadlock on second call.

### ISSUE THREAD

**Issue by gotyet9** [NodeRedis/node_redis#1429]
Below is my implementation of node redis implementation:

```
async setKey(key, data) {
    try {
      const flatteredData = JSON.stringify(data);
      return this.cacheStore.hmset(key, key, flatteredData);
    } catch (error) {
      return error;
    }
  }
```

```
getByKey(key) { // eslint-disable-line consistent-return
    return new Promise((resolve, reject) => {
      this.cacheStore.hget(key, key, (err, res) => {
        if (err) {
          reject(err);
        } else {
          resolve(JSON.parse(res));
        }
      });
    });
  }
```

```
async getAll() {
    const cache = await this.cacheStore.getByKey('organizations');
    if (cache) return cache;
    const organizations = await this.db
      .collection('organizations')
      .find({})
      .toArray();
    this.cacheStore.setKey('organizations', organizations);
    return organizations;
  }
```

 ```
async getMasterData(){
    const data1 = await this.getAll();
    const data2 = await this.getAll();
    console.log('Passed the worst barrier');
  }
```

Now the issue is **getMasterData** when called never prints 'Passed the worst barrier' :(.
For second time await it never returns back from **this.cacheStore.getByKey('organizations')** and goes in deadlock forever.
No error and no response either.
God knows what I'm doing wrong. This is what I actually want to achieve. 

If I run the same **this.getAll()** in the loop without any await it works perfectly.

Also if I remove data2 await. Still, it works fine.

What am I doing wrong here?
Please let me know. Any help will really be appreciated.
Thanks

**Comment by asilvas** [comment]
you're probably seeing an uncaught promise rejection.

`resolve(JSON.parse(res));` is very suspect.

**Comment by stockholmux** [comment]
Closing as per @asilvas response.
