### ISSUE TITLE
when to support cluster and pipleline?

### ISSUE THREAD

**Issue by GeniusBrother** [NodeRedis/node_redis#1436]

**Comment by stockholmux** [comment]
For cluster take a look at [Redis-clustr](https://www.npmjs.com/package/redis-clustr) which works with this module.

This module effectively auto-pipelines due to node.js being event-loop/async by nature. If you want to create an explicit pipeline, use `client.batch()`.

**Comment by GeniusBrother** [comment]
Could I think auto-pipelines equivalent to client.batch()? or what situation should they apply to? @stockholmux

**Comment by stockholmux** [comment]
It's only a semantic difference. `client.batch()` behaves like `client.multi()` (you get all your results at once, it can be easier to write JS against, etc.).
