### ISSUE TITLE
client.del return 0

### ISSUE THREAD

**Issue by loretoparisi** [NodeRedis/node_redis#1437]
The `client.del` api returns `0` when trying to delete a cache key. I have tried other clients and the cache keys are correctly deleted, thus returning `1`.

```javascript
self.client.del(key, function (err, res) {
                // res is null when the key is missing
                if (err) self.logger.error("RedisStore.unset err %@", err);
                else self.logger.debug("RedisStore.unset %@:%@", key, res);
                return callback(err, res);
            });
```

**Comment by BridgeAR** [comment]
This should definitely work properly. Did you delete the entry before running your code?

**Comment by ussserrr** [comment]
If this is still somehow relevant, the `key` should be non-absolute but relative to the prefix you specified on creation.
