### ISSUE TITLE
Node js crashes when Redis Server goes down

### ISSUE THREAD

**Issue by suryas18** [NodeRedis/node_redis#1438]
Hi,

* **Version**: redis 2.8.0  redis server version 4.0.11
* **Platform**: Ubuntu 18.0.1 LTS VM
* **Description**: I have implemented the logic for redis connection, key retrieval and key value assignment operations using redis 2.8.0 in a Node-Red function node which runs on top of Node JS.I was able to accomplish the above mentioned operations but I was encountered with nodejs crash when redis server goes down(after successful connection) while the application was running.At the same time I could catch the errors when a host cannot be reached.Please see the below code structure implemented.The error block event handler is not catching the disconnection error.Please suggest a workaround for the same.

try{
    
var redis = context.global.redis;
var path = context.global.path;
var fileName = path.basename(msg.filePath);
var host = flow.get("host");
var port = flow.get("port");
var expirationIntervalInSeconds = flow.get("expirationIntervalInSeconds");
var logMessage;
var connectionUrl = flow.get("connectionUrl");
const client = redis.createClient({"host":host,"port":port,"url":connectionUrl});

//handle errors
client.on('error', function (error) {
    try{
        
    console.log("Error occurred " + error.toString());
   
    }catch(exception){
      
     console.log("Exception occurred while handling error for filename");  
     console.log(exception.toString());
        
    }
    
});

client.on("connect", function (error,result) {
    
    try{

    console.log("connected");   

client.get(fileName, function (error, reply) {
    
try{

console.log("calling get on "+ fileName);

if(reply === null){
    
client.set(fileName, "VAL",'EX',expirationIntervalInSeconds,function (error, response) {

try{   
    
node.send(msg);

}catch(exception){
    
    console.log(exception.toString());   
    
    
}finally{
    
releaseConnection(client);    
}

});

    }else{       
     
    releaseConnection(client);
       
        
    }
}catch(exception){
    
  console.log(exception.toString());
    
}

});

}catch(exception){    
   
    
}
});

}catch(exception){
    
 console.log(exception.toString());
    
}finally{
    
}

function releaseConnection(client){
    
    client.quit(function (error, reply){
        
        try{
        
        console.log("Ended connection");            
     
        }catch(exception){        
      
        console.log(exception.toString());
            
        }finally{
            
        }
    });
    
    
}

Regards
Surya

**Comment by RomanSolianik** [comment]
similar issue

**Comment by stockholmux** [comment]
(Dis)Connection errors are orthogonal to reply errors.  Reply errors come from the Redis server (e.g. incorrect syntax, etc.) - don't depend on this for detecting connection issues. Additionally, @suryas18, I think you're structuring callback code incorrectly (use `if (err) { ... }` rather than `try`...`catch`.)

To properly handle connection issues, use `retry_strategy` options in `createClient`.
