### ISSUE TITLE
Option to not automatically connect client to server

### ISSUE THREAD

**Issue by Benjamin-Dewey** [NodeRedis/node_redis#1441]
**Feature request**
- Add an `autoConnect` field to the client `options` object which defaults to `true`
- Add a `start()` method on the client which opens the connection or no-ops if it is already open

**Justification**
In event driven interfaces proper design stipulates that you should be able to set all of your event handlers _before_ it is possible for such events to occur. The current behavior of automatically opening a connection to the redis server when creating a client violates this rule; we need to create a client before we can set its event handlers, but the very act of creating a client can trigger events such as the `ready` or `connect` events. Getting your handlers on these events to fire is now a race condition of whether or not your code is able to set them before the event occurs.

Take the example below...

```
const client = redis.createClient();

// RACE CONDITION: if the 'ready' event occurs before the next
// line of code executes, then myEventHandler will not fire

client.once('ready', myEventHandler);
```

What we need instead is something like this...

```
const client = redis.createClient({ autoConnect: false });

client.once('ready', myEventHandler);

client.start();
```

**Comment by jaamison** [comment]
I understand your thought process, but if you look at the source, createClient() calls node's native net.createConnection() under the hood, which is an explicitly asynchronous operation. The runtime is guaranteed to finish executing the current function to completion before returning to the event loop.

In other words, your first example above is not a race condition like you've suggested. THIS would cause a race condition:

    const client = redis.createClient();
    
    getSomeExternalAsyncDataThatYouNeed(function(){
      client.once('ready', yourEventHandler);
    });

**Comment by Benjamin-Dewey** [comment]
>The runtime is guaranteed to finish executing the current function to completion before returning to the event loop.

Let me make sure I understand correctly. In my first example `main()` is pushed on the stack, then `createClient()` is pushed and popped, then `once()` is pushed and popped, then `main()` is popped, and now the stack is clear so the event loop can push the ready event handler onto the stack which it could not do until now, so no race condition. Am I describing your explanation correctly?

**Comment by jaamison** [comment]
>  In my first example main() is pushed onto the stack, then createClient() is pushed and popped, then once() is pushed and popped, then main() is popped and now the stack is clear 

Yup.

> and now the stack is clear so the event loop can push the ready event handler onto the stack

Nope. Once the stack is clear, (and only once the stack is clear) will events emitted by the client object be processed. So on the next event tick after main() returns (ie the callback will already be bound to the ready event), the "ready" event emitted by the client will be processed.
