### ISSUE TITLE
Redis Client always connecting to local

### ISSUE THREAD

**Issue by gjackson12** [NodeRedis/node_redis#1446]
* **Version**: 2.8.0
* **Platform**: Node.js v10.16.0 on macOS High Sierra
* **Description**: I'm attempting to use options to connect to a redis instance at a specific host and port. When I provide the options while creating the client it still attempts to look for redis on my localhost (the default conifg). 

`const client = redis.createClient({
	host: 'core_redis_1',
	port: 6379
});`

I am getting the following error:
`events.js:183, throw er; // Unhandled 'error' event`
`Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED`

**Comment by stockholmux** [comment]
This is probably related to a hostfile, DNS or firewall issue. Try to connect using the same exact info with redis-cli: `$ redis-cli -h core_redis_1 -p 6379` and troubleshoot from there. 

I'm going to close this issue as it's probably not an issue with the library but rather your configuration. If you continue to have problems, reopen or start a new issue with more details.

**Comment by burtontanner** [comment]
@stockholmux im seeing the same issue but I am able to ping with redis-cli. What did you do to fix this?

**Comment by burtontanner** [comment]
I don't think host is supported anymore. I can pass anything and it will still connect to localhost.
```  const redisClient = redis.createClient({
    legacyMode: true,
    host: 'asdfasdfasdf',
    port: 6379,
    password: env.get('REDIS_PASSWORD')
  })```

**Comment by leibale** [comment]
legacyMode does not support v3 config, try this instead:

```
createClient({
  legacyMode: true,
  socket: {
    host: 'asdfasdfasdf',
    port: 6379,
    password: env.get('REDIS_PASSWORD')
  }
});

**Comment by burtontanner** [comment]
This ended up working for me
```  const redisClient = redis.createClient({
    legacyMode: true,
    url: `redis://:passwordHere@$hostHere:portHere`
  });

**Comment by devodii** [comment]
I struggled with this for some weeks, and this was how i solved that problem:
- install redis v3.1.2,
- then... create the client like so:
   ✅ ` const client = redis.createClient({
          password: redis_password
          host: redis_host,
          port: redis_port,
      });`
   please, do not add the credentials in the socket objec i.e: 
   ❌!   `const client = createClient({
        socket: {
          host: redis_host,
          port: redis_port,
        }
          password: redis_port,
        });`
