### ISSUE TITLE
how can i add options for redis-client???

### ISSUE THREAD

**Issue by huenchao** [NodeRedis/node_redis#1448]
i wanna add --raw to support chinese ?? how can i add "--raw" for redis-client???

**Comment by huenchao** [comment]
--raw            Use raw formatting for replies (default when STDOUT is not a tty) 
  --latency        Enter a special mode continuously sampling latency. 
  --slave          Simulate a slave showing commands received from the master. 
  --pipe           Transfer raw Redis protocol from stdin to server. 
  --bigkeys        Sample Redis keys looking for big keys. 
  --help           Output this help and exit 

I wanna use  --raw  option。

**Comment by stockholmux** [comment]
`--raw` is an option for redis-cli so it's impossible map directly to the node.js client. Chinese works works without any options, so you shouldn't need any extra options.

```
const redis = require('redis');
const client = redis.createClient();

client.set('chinese','赖剑清',(err) => {
        if (err) throw err;
        client.get('chinese',(err,results) => {
                if (err) throw err;
                console.log(results);
                client.quit();
        });
});
```

**Comment by pkxpp** [comment]
dos显示乱码，话说lz咋解决的？
