### ISSUE TITLE
Reply error when using the PUB/SUB system and bluebird promissifyAll

### ISSUE THREAD

**Issue by lsmenicucci** [NodeRedis/node_redis#1452]
* **Version**: node_redis: 2.88.0, redis: 2.4.5 (64bit)
* **Platform**: Node 10.16.0
* **Description**: 
I'm having an issue while using the promissified version of node_redis by bluebird. The issue occurs when I call both `client.setAsync` and `client.subscribeAsync` from a `Promise.all`. The code follows along:
```javascript
import redis from 'redis';
import { promisifyAll } from 'bluebird';
promisifyAll(redis);

client = redis.createClient();

Promise.all([
  client.setAsync("key","value"),
  client.subscribeAsync("channel_name"),
])
  .then( () => {
    console.log("All operations are done");
  }).catch( error =>{
    console.log("An error has ocurred");
  })
```
And I receive the error message:
```javascript
ReplyError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context
      at parseError (node_modules\redis-parser\lib\parser.js:193:12)
      at parseType (node_modules\redis-parser\lib\parser.js:303:14)
```

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by knoxcard** [comment]
Have you tried?

https://github.com/luin/ioredis

**Comment by alastaircoote** [comment]
Promise.all doesn't guarantee execution order, I don't think. So I suspect your subscribe call is being run before your set call, and you can't run set while in subscriber mode. Try `client.setAsync().then(() => client.subscribeAsync())`

**Comment by BridgeAR** [comment]
@alastaircoote is indeed correct.
