### ISSUE TITLE
how to calculate nearest X,Y coordinate using from user Joy using redis .I have used node-redis .

### ISSUE THREAD

**Issue by Runa-Redapple** [NodeRedis/node_redis#1459]
{ status: 'closed', 'users:5d7f3917bfc9c320eae14baf:id': '5d7f3917bfc9c320eae14baf', 'users:5d7f3917bfc9c320eae14baf:name': 'Joy', 'users:5d7f3917bfc9c320eae14baf:position:X': '406.9941482694788', 'users:5d7f3917bfc9c320eae14baf:position:Y': '647.8162975185139', 'users:5d7f3917bfc9c320eae14baf:playerScale:X': '0.1', 'users:5d7f3917bfc9c320eae14baf:playerScale:Y': '0.1', 'users:5d7f3917bfc9c320eae14baf:texture': '0', 'users:5d7f3917bfc9c320eae14baf:playerAngle': '0', 'users:5d7f3917bfc9c320eae14baf:playerSpeed': '100', 'users:5d7f3917bfc9c320eae14baf:type': 'USER', 'users:5d7f3917bfc9c320eae14baf:totalUserKill': '0', 'users:krzbm41hpw47jy42:id': 'krzbm41hpw47jy42', 'users:krzbm41hpw47jy42:name': 'DUXMIF', 'users:krzbm41hpw47jy42:position:X': '297.9611648827057', 'users:krzbm41hpw47jy42:position:Y': '563.8852984680458', 'users:krzbm41hpw47jy42:playerScale:X': '0.1', 'users:krzbm41hpw47jy42:playerScale:Y': '0.1', 'users:krzbm41hpw47jy42:texture': '1', 'users:krzbm41hpw47jy42:playerAngle': '127.99640517059484', 'users:krzbm41hpw47jy42:playerSpeed': '100', 'users:krzbm41hpw47jy42:type': 'AI', 'users:krzbm41hpw47jy42:totalUserKill': '0', 'users:dg42ekr7x6mf2ckt:id': 'dg42ekr7x6mf2ckt', 'users:dg42ekr7x6mf2ckt:name': '5Q2IBX', 'users:dg42ekr7x6mf2ckt:position:X': '513.94114776204', 'users:dg42ekr7x6mf2ckt:position:Y': '661.162340155979', 'users:dg42ekr7x6mf2ckt:playerScale:X': '0.1', 'users:dg42ekr7x6mf2ckt:playerScale:Y': '0.1', 'users:dg42ekr7x6mf2ckt:texture': '1', 'users:dg42ekr7x6mf2ckt:playerAngle': '98.5896738842123', 'users:dg42ekr7x6mf2ckt:playerSpeed': '100', 'users:dg42ekr7x6mf2ckt:type': 'AI', 'users:dg42ekr7x6mf2ckt:totalUserKill': '0', 'users:ho2bekwy2llh65mt:id': 'ho2bekwy2llh65mt', 'users:ho2bekwy2llh65mt:name': 'D8I5CA', 'users:ho2bekwy2llh65mt:position:X': '513.94114776204', 'users:ho2bekwy2llh65mt:position:Y': '661.162340155979', 'users:ho2bekwy2llh65mt:playerScale:X': '0.1', 'users:ho2bekwy2llh65mt:playerScale:Y': '0.1', 'users:ho2bekwy2llh65mt:texture': '1', 'users:ho2bekwy2llh65mt:playerAngle': '114.86708867842093', 'users:ho2bekwy2llh65mt:playerSpeed': '100', 'users:ho2bekwy2llh65mt:type': 'AI', 'users:ho2bekwy2llh65mt:totalUserKill': '0' }

**Comment by DanielSeehausen** [comment]
Hi @Runa-Redapple 
thank you for raising the issue. 
Is this a general request for how this can be done, given the data set?
This question may be better posted to a platform like StackOverflow.

If this is a bug report, or feature request, would you be able to provide more detail?

**Comment by BridgeAR** [comment]
@Runa-Redapple as suggested, please open an issue on StackOverflow. I suggest not to post anything about your user data and to use a generic example code to ask the question.
