### ISSUE TITLE
Upgrade redis-parser to 3.0

### ISSUE THREAD

**Issue by sookoll** [NodeRedis/node_redis#1462]
* **Version**: 2.8.0
* **Platform**: Node.js 12.4 on OSX
* **Description**: hiredis dependency is removed from redis-parser 3.0. hiredis is abonded project and do not compile on Node 12. node_redis is using redis-parser 2.6, so it is not usable in Node 12.

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by knoxcard** [comment]
https://github.com/NodeRedis/node_redis/pull/1454

**Comment by knoxcard** [comment]
@sookoll - try ioredis instead, it's easy, you dont have to change much code at all.

https://github.com/luin/ioredis

**Comment by Salakar** [comment]
This is live on master now and a release is coming soon, so will go ahead and close this issue, thanks
