### ISSUE TITLE
is this library still active ?

### ISSUE THREAD

**Issue by rvillane** [NodeRedis/node_redis#1476]
Hello, just curious if this library is still considered active, no new versions have been released in more than 2 years and multiple PR's are waiting to be merged.

thanks

**Comment by stockholmux** [comment]
@rvillane still active. The way the module is structured, there are several parts that have changed upstream (and are incorporated automatically). 

One thing to consider, however, is that Redis 6 will bring RESP3 (new protocol) so, things will likely change around that time.
