### ISSUE TITLE
Events for streams

### ISSUE THREAD

**Issue by fgarcia** [NodeRedis/node_redis#1479]
I am doing a blocking XREAD

    send_command(
       'XREAD',
       ['BLOCK', 0, 'STREAMS', 'mystream', '$'], 
       (err, data) => { ... }

The callback works fine, but I cannot find a way to wait until this blocking command is ready. I wonder if there is (or should be) some type api event to know when a blocking command is ready to receive inputs.

**Comment by stockholmux** [comment]
@fgarcia `XREAD`...`BLOCK` doesn't receive anything - it just holds until data is ready (e.g. someone `XADD`s). It will fire the callback at this point. 

I'm going to close this as I don't think there is an issue with the client lib, but feel free to ask further questions.
