### ISSUE TITLE
Get TTL of a key 

### ISSUE THREAD

**Issue by slicerahul** [NodeRedis/node_redis#1481]
How do we get the TTL of a keys which is present in the redis. 
For example if we do `redis.set("redisTestKey1", "value", "EX", 5*60 );`
Then how can we get TTL of `redisTestKey1` which is 5*60?
Thanks.

* **Version**: latest
* **Platform**: Ubuntu 18, Node.js 10

**Comment by stockholmux** [comment]
Take a look at the [TTL command](https://redis.io/commands/ttl) which works just like the `set` command as far as the library is concerned. 

No issue with node_redis, so closing this issue.

**Comment by slicerahul** [comment]
Thanks @stockholmux . Sorry that I added this as an issue, its more of question. Im using node node_redis and wanted to ask if it exposes any function which gives TTL of a key. Thanks anyways.
