### ISSUE TITLE
Unable to connect to remote redis server when local redis service is down

### ISSUE THREAD

**Issue by pratts** [NodeRedis/node_redis#1482]
* **Version**: What node_redis and what redis version is the issue happening on?
node-redis : 2.8.0
redis : Redis server v=3.2.12

* **Platform**: What platform / version? 
Node version : v10.18.0
NPM version : 6.13.4
Centos 7, Linux localhost 3.10.0-1062.9.1.el7.x86_64

* **Description**: Description of your issue, stack traces from errors and code that reproduces the issue
I have redis server installed on 2 systems. 127.0.0.1 and 192.168.0.21. I have configured the node project on local machine(127.0.01) and trying to connect to the other system.
When the redis service is running on my machine, I can connect to other system. There is a failure when redis-server on my machine is down.
I can access the redis on the other machine and there are no selinux or firewall related issues.
Below mentioned is the stack trace:
`{ Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }`

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
It would be necessary to know exactly what's passed through to the redis client to know if everything is working properly. As such you could activate the debug mode.

Just looking at the error it's clear that the client connects to the default localhost entry and not to `192.168.0.21`. Please check your configuration and setup again.
