### ISSUE TITLE
Version 2.8.0 is released in 2017, why not release the latest commit

### ISSUE THREAD

**Issue by ZhangDianPeng** [NodeRedis/node_redis#1486]
Version 2.8.0 is released in 2017, why not release the latest commit。

**Comment by szagi3891** [comment]
It seems that this repository is already dead.

**Comment by stockholmux** [comment]
It's not dead. We're working through some coordination issue, but I can assure you that we will continue to develop this repo.

**Comment by szagi3891** [comment]
That's cool But I will believe when I see :p
