### ISSUE TITLE
Redis Multi Exec 'del' data is persistent a few miliseconds sometimes

### ISSUE THREAD

**Issue by ibudisteanu** [NodeRedis/node_redis#1491]
I am having an issue with node_redis. I just spotted it right now. I am using multi exec 'del' and sometimes my data is still persistent a few milliseconds sometimes (not always). Like, I can do a `get` and my data gets returned and not deleted? Any reason why?

node_redis: 2.8.0
Version: Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=7785291a3d2152db
Platform: ubuntu

**Comment by ibudisteanu** [comment]
I updated to version 5.1.0 and still the same issue. My data has a delay and is not removed instant from the database...

**Comment by ibudisteanu** [comment]
I even removed multi and just used bluebird and this happens as well.

**Comment by stockholmux** [comment]
@ibudisteanu post your code, please. I'm 99% sure this has to do with asynchrony and some details in how MULTI/EXEC works intentionally behind the scenes.

**Comment by ibudisteanu** [comment]
@stockholmux Thank you so much for the answer. You were right, there was a bug in my code for some reason .filter and Promise.all doesn't work very well. I fixed by replacing .filter.

Thank you so much again for your time!
