### ISSUE TITLE
Add example script showing how to run a command with several modifiers.

### ISSUE THREAD

**Issue by simonprickett** [NodeRedis/node_redis#1688]
Add an example script that shows how to run a command with several modifiers.  Use the `SET` command twice as follows:

```bash
127.0.0.1:6379> set mykey myvalue ex 60 get
(nil)
127.0.0.1:6379> set mykey newvalue ex 60 get
"myvalue"
```

Pay attention to [the guidelines](https://github.com/redis/node-redis/tree/master/examples) for adding an example here when doing this.  Name your file `command-with-modifiers.js` or `.ts` if using TypeScript, and your function `commandWithModifiers`.

This is part of our participation in Hacktoberfest 2021. Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by rohan201** [comment]
I would like to work on this issue, can you pls assign me

**Comment by simonprickett** [comment]
@rohan201 yes, thanks!  Please be sure to check out the README in the examples folder, and use Node Redis 4 (`npm install redis@next`) - see `package.json` in the examples folder.
