### ISSUE TITLE
lpop command with count, produces an error

### ISSUE THREAD

**Issue by tmalo** [NodeRedis/node_redis#1700]
When using [lpop](https://redis.io/commands/lpop) using the optional count parameter, I have the following error : 

`ERR wrong number of arguments for 'lpop' command
`
my code 

```
  return new Promise((resolve, reject) => {
    client.lpop('emailAttendee', 5, (err, items) => {
      if (err) {
        reject(err)
        return
      }

      console.log(items)
      const data = items.map((item) => {
        return JSON.parse(item)
      })
      resolve(data)
    })
  })

```

**Comment by brunobastosg** [comment]
Actually there is a method called `lPopCount` which you should be using in this case.

**Comment by olejorgenb** [comment]
Would been nice if there was some sort of error message when supplying `count` to `lPop`. Easy 5-30min save for every person trying this. (AFAICS `lPop("my-list", 10)` currently behaves as if 10 was not there, popping one element)
