### ISSUE TITLE
v4.0.0 missing getBuffer command

### ISSUE THREAD

**Issue by ellik95** [NodeRedis/node_redis#1848]
I use v4.0.0 and when I dockerize my app, `getBuffer` is currently missing from `node_modules` commands folder.
Below is my `package.json` and `Dockerfile` accordingly.

**package.json**:
```
{
	"name": "repo-name",
	"version": "0.0.1",
	"description": "",
	"main": "dist/index.js",
	"scripts": {
		"start": "node dist/index.js",
		"build": "rimraf ./dist && mkdir ./dist && tsc"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"redis": "4.0.0"
	}
}
```

**Dockerfile**:
```
FROM node:lts-alpine3.14

WORKDIR /usr/src/app

RUN npm install -g typescript

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080 8080

#Build to project
RUN npm run build

# Run node server
CMD npm run start
```

I did a research and I saw that tag `redis@4.0.0`  had these dependencies in `package.json`: 
```
"@node-redis/client": "^1.0.0",
"@node-redis/json": "^1.0.0",
"@node-redis/search": "^1.0.0"
  ```
So in the docker container, version `1.0.2` of the dependencies was installed instead (which has no longer this command).

I changed my `package.json` so as to override these dependencies and now the `getBuffer` command exists:
```
{
	"name": "repo-name",
	"version": "0.0.1",
	"description": "",
	"main": "dist/index.js",
	"scripts": {
		"start": "node dist/index.js",
		"build": "rimraf ./dist && mkdir ./dist && tsc"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"@node-redis/client": "1.0.0",
		"@node-redis/json": "1.0.0",
		"@node-redis/search": "1.0.0",
		"redis": "4.0.0"
	}
}
```

This is a breaking change and should not have been removed in `v4.0.2`. Maybe you should note it somewhere in case someone else faces the same problem.

**Environment:**
 - **Node Redis Version**: 4.0.0

**Comment by leibale** [comment]
the `.getBuffer` "command" was added in v4.0.1 and removed in v4.0.2 in favor of a more generic solution:
```javascript
await client.get(
  client.commandOptions({ returnBuffers: true }),
  'key'
);

await client.hGetAll(
  client.commandOptions({ returnBuffers: true }),
  'key'
);
```

**Comment by ellik95** [comment]
Yes, but this caused a problem for me that I was using v4.0.0 which had the `.getBuffer` command. It suddenly was crashing in my deployment.

**Comment by leibale** [comment]
The problem is that the `redis` package depends on `@node-redis/client` but the version is not locked, therefore `npm install redis` will install `@node-redis/client@1.0.2` (instead of `@node-redis/client@1.0.0`). I'll make sure to lock the versions in the next release, in the meantime you can `npm i -S @node-redis/client@1.0.1`. Sorry about it.
