### ISSUE TITLE
Connection error triggers both error event and my callback

### ISSUE THREAD

**Issue by shermany** [NodeRedis/node_redis#199]
If I cannot connect to my redis server, the error handler I registered for the "error" emitter will be called. However, the callback you are supposed to supply with your redis command ALSO follows the Node.js pattern of passing an error object.

Assuming I follow the example on your page:

``` javascript
var redis = require("redis"),
    client = redis.createClient();

client.on("error", function (err) {
    console.log("Error " + err);
});

client.hkeys("hash key", function (err, replies) {
    console.log(replies.length + " replies:");
```

Should I not be checking `err` in the callback? In my code, I do, however this triggers me to double error handle, which is not desired behavior. 

It would seem to me that either a) only one of the error handling mechanisms should be used, or b) some sort of direction should be given as to the proper way to manage this. As is pointed out in your readme, 

'Note that "error" is a special event type in node. If there are no listeners for an "error" event, node will exit.'

As I am coding a server that I do not wish to exit if it can be avoided, I need to handle the error emitter. This would imply that I should check for non-null'ness of the err object, but use it only to avoid taking action that assumes the operation succeeded. Then only do actual error handling in the event listener.

Thoughts?

**Comment by BridgeAR** [comment]
In case of a connection loss the error is emitted and returned in the callback, if you do not use the retry_strategy option. If you use the option, only the callback is going to receive that error and reconnecting is tried without emitting an error.

You should still listen to the error event, as there are other failures that might occur besides that one.
