### ISSUE TITLE
TIME() returning a date in 1970 rather than current timestamp

### ISSUE THREAD

**Issue by v-flashpoint** [NodeRedis/node_redis#2001]
According to the Redis docs, TIME() should show the current server time, as a timestamp since the Unix epoch, and the number of microseconds that have elapsed: https://redis.io/commands/TIME

However, doing client.time() returns a date in 1970, not the current time.

Sample code:

```
const redis = require('redis');
const client = redis.createClient();
client.connect();

 client.on('connect', function() {
    console.log('Connected!');
	client.TIME().then(function(reply){
		console.log(reply);
	});
});
```

Output: 1970-01-20T01:05:44.873Z { microseconds: 880958 }

Linux `date +%s` returns 1645544389, which is the current date/time

**Environment:**
 - **Node.js Version**: 14.19.0
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.4
 - **Platform**: Ubuntu 20.04.3 LTS

**Comment by simonprickett** [comment]
Looking into this, code is here https://github.com/redis/node-redis/blob/3eb99dbe8378a347dd42a1ff87c89327e989443f/packages/client/lib/commands/TIME.ts#L9

**Comment by simonprickett** [comment]
It's missing a multiply by 1000 when creating the new date.
