### ISSUE TITLE
Connect retries don't stop after .quit()

### ISSUE THREAD

**Issue by gtracy** [NodeRedis/node_redis#212]
I'm assuming this is not as designed, but perhaps there is some other pattern I should use.

var redis = require("redis"),
    client = redis.createClient();

client.on("error", function(err) {
    logme.error("Redis error : "+err);
    client.quit();
});

My expectation is that the client dies, but the error event continues to be emitted for the connection retries. How can I kill the retries? It may be an ok state in some cases.

**Comment by BridgeAR** [comment]
This is indeed an interesting issue. I did not think about this before.

@NodeRedis/contributors @dirkbonhomme what do you think about calling `end(true)` if the connection is down while calling quit?

**Comment by dirkbonhomme** [comment]
@BridgeAR That's indeed the behavior I'd expect to happen. I think in real world applications, you will never call quit() before all callbacks have been handled anyway. So when calling quit() in your app code, you've probably already taken care of either success callbacks or dealing with reconnects.

**Comment by BridgeAR** [comment]
The question in that case is if this should be handled as bugfix / patch version or as a bc / major...

In most cases I'd say it's a bugfix but the behavior is changed in a way that might break someones code (have a look at the tests in the PR).

**Comment by dirkbonhomme** [comment]
According to the docs it says 

> If you want to exit cleanly, call client.quit() to send the QUIT command after you have handled all replies.

This implies that quit() will always send a QUIT command. Changing its behavior when a connection is down might indeed break some code.

I don't _expect_ this to break any existing apps though, but does change a bit to how it's documented.

**Comment by BridgeAR** [comment]
I added further documentation for the quit command and as it is the recommended way to close the connection I'd say it should be fixed. I'm still wondering how many complains are going to come if this is released in the next minor though...
Not using the offline queue is going to be a bugfix without bc, as there's no other command that could be handled in the meanwhile.
Using the offline queue someone might rely on some commands to be handled on a reconnect, even though this would be a bit weird.

I know that there are quite a few people using the library without waiting for all commands to be handled before closing the connection (e.g. using it with a queue). But even in that case I'd see it as a bugfix...
