### ISSUE TITLE
node_redis / examples / file.js is not working

### ISSUE THREAD

**Issue by yxa** [NodeRedis/node_redis#215]
the file given back from redis is not the same as the one stored (data corruption)

node version :  0.6.16
redis server version: 2.4.13
osx: 10.7.3

using this file: 
https://secure.gravatar.com/avatar/f2602cabcccbe70f6e73e0c86379921d?s=140&d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-140.png

original file size: 5457
 % file original.jpg 
original.jpg: JPEG image data, JFIF standard 1.01, comment: "CREATOR: gd-jpeg v1.0 (using IJ"

file size after getting it back from redis: 9996
% file duplicate_original.jpg            data

redis reports the serialized length to : 5438

**Comment by BridgeAR** [comment]
Fixed with ddbb94b598ea204d3aeb7c4a79ec6900d037bde8
