### ISSUE TITLE
return_buffers and detect_buffers don't work as expected.

### ISSUE THREAD

**Issue by LeonidRosin** [NodeRedis/node_redis#2172]
I'm create Redis client:
`c = createClient(6379, "127.0.0.1", { 'return_buffers': true });`
or 
`c = createClient(6379, "127.0.0.1", { 'detect_buffers': true });`
, but 
`let a = c.get() `
returns a _js string_, which skews the binary data.

**Environment:**
 - **Node.js Version**: v16.15.1
 - **Redis Server Version**: Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=6d95e1af3a2c082a
 - **Node Redis Version**: redis@4.1.0
 - **Platform**: Debian 11

**Comment by leibale** [comment]
You are using the v3 api with v4, try this instead:
```javascript
await client.get(
  client.commandOptions({ returnBuffers: true }),
  'key'
);
```
https://github.com/redis/node-redis#redis-commands

**Comment by LeonidRosin** [comment]
Thanks!!!!!!!!!!!!!! This works great.
