### ISSUE TITLE
hmset broken

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [NodeRedis/node_redis#218]
When passed an object of arrays, `HMSET` screws up in strange ways...

``` JavaScript
  var client, redis;

  redis = require('redis');

  client = redis.createClient();

  client.hmset('foo', {
    a: [0, 0, 0]
  });

  client.hmset('foo', {
    a: [0, 0, 0],
    b: [0, 0, 0]
  });

  client.hmset('foo', {
    a: [0, 0, 0],
    b: [0, 0, 0],
    c: 'bar'
  });
```

`redis-cli monitor`

> 1337435337.689485 "hmset" "foo" "a" "0" "0" "0"
> 1337435337.689667 "hmset" "foo" "a" "0,0,0" "b" "0" "0" "0"
> 1337435337.689744 "hmset" "foo" "a" "0,0,0" "b" "0,0,0" "c" "bar"

N.B. It only breaks if the last key of the object is an array.

This was a real PITA to find. I presume something is broken somewhere deep inside all the voodoo of RedisClient.prototype.hmset (https://github.com/mranney/node_redis/blob/9e76387f59b12e2f3590687ac4aba37e0247305a/index.js#L879)

**Comment by BridgeAR** [comment]
This is not supported and returns a warning by now. If you want to provided arrays as keys, please convert them to a string before passing them to the node_redis client.
