### ISSUE TITLE
syncCommand? 

### ISSUE THREAD

**Issue by aliasone** [NodeRedis/node_redis#219]
I'd like to use node_redis to set up a [sync](https://github.com/antirez/redis/blob/unstable/src/replication.c#L83) client and parse the incoming representation of the `command` and `args` into strings/json. Is this possible?

Thanks!

**Comment by BridgeAR** [comment]
This is not possible with node_redis. That command is actually only meant to be used internally in Redis not not that a client uses that command. And neither the hiredis parser, nor the js parser is able to handle the response of the sync command.
