### ISSUE TITLE
Not accepting boolean values in 4.2.0  (breaking change from 4.1.0)

### ISSUE THREAD

**Issue by MatanYemini** [NodeRedis/node_redis#2202]
After doing this: https://github.com/redis/node-redis/pull/2139

You have basically killed the option to put boolean values as part of the `hSet` command, causing BREAKING CHANGES (set part changes -> get part changes).

There are other ways to solve the bugs you have presented. I would be happy to discuss @leibale 
Please let me know if I can help in any way.

As a side note,
Doing BREAKING CHANGES as part of a minor update - seems weird for this widely used package. This change should be reverted and added as part of possible 4.x -> 5.x OR at least document it well IMHO.

Thanks,
-m

**Comment by leibale** [comment]
even though using booleans "worked" in 4.1.0 (it just stringified them), it wasn't an intended behavior (https://github.com/Tyris/node-redis/blob/master/packages/client/lib/commands/HSET.ts#L5 this never changed)
@guyroyse @simonprickett WDUT?

**Comment by MatanYemini** [comment]
@leibale Haha :) 

I thought it was intended!  It just was a bit hurtful to some pain when doing a minor update (someone was needed to manually update it all) 

Let me know if you want to open a ticket on it, I will take
