### ISSUE TITLE
Very bad performance in pub/sub

### ISSUE THREAD

**Issue by leobgm** [NodeRedis/node_redis#2437]
### Description

I'm using Redis in NodeJS to implement a publish / subscribe structure.
One Node process publishes data to a Redis channel:

    spawn.stdout.on('data', (data) => {
       publisher.publish(`customChannel`, data);
    });

And I receive it in another Node process(es):

    let start = Date.now();
    let checked = false;
    
    subscriber.subscribe(`customChannel`, (data) => {
      if(checked === false) {//check receiving speed
        check = true;
        console.log(`Took ${Date.now() - start} ms to get data.`);
      }
    }, true);

I expected it to be ultra fast while it's in memory. But here's the results!

> Took 5639 ms to get data.
> 
> Took 4406 ms to get data.
> 
> Took 6184 ms to get data.

If I request data from other side of the earth I get it faster LOL.

What is published is 64kb data chunks read from spawn `stdout`, and that's coming fast. So it's not from that part.

### Node.js Version

16.14.0

### Redis Server Version

7.0.9

### Node Redis Version

4.6.5

### Platform

Ubuntu 20.04

**Comment by leibale** [comment]
Can you please share code that reproduce the issue so I'll be able to debug it?

**Comment by leibale** [comment]
I tried to reproduce it using:

```javascript
// publisher.mjs:
import { createClient } from 'redis';

const client = createClient();

client.on('error', err => console.error(err));

await client.connect();

setInterval(async () => {
    await client.publish('channel', Date.now().toString());
}, 10);
```

```javscript
subscriber.mjs
import { createClient } from 'redis';

const client = createClient();

client.on('error', err => console.error(err));

await client.connect();

await client.subscribe('channel', message => {
    console.log(`Took ${Date.now() - Number(message.toString())} ms`);
}, true);
// (using "buffer mode" because this is what you are using in your example
```

and this is the logs I get:

```
Took 1 ms
Took 0 ms
Took 1 ms
Took 0 ms
Took 1 ms
Took 0 ms
Took 1 ms
```
