### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by paddybyers** [NodeRedis/node_redis#246]
I want to connect to a Redis port over TLS that's sitting behind stunnel. I have a very simple patch that seems to do the job: 

https://github.com/paddybyers/node_redis/commit/6494a8f218e3c557ebef380e75dd94ff216e2ded

Let me know if you think this is useful and I'll do a PR. If you have any thoughts about a good way to do self-contained tests (ie that don't require stunnel already to be running) then I'm happy to do those as well.

**Comment by BridgeAR** [comment]
TLS support has finally landed and will be released with v.2.4 :)
