### ISSUE TITLE
zRangeWithScores doesn't seem to work with { REV: true }

### ISSUE THREAD

**Issue by chabwino** [NodeRedis/node_redis#2554]
### Description

When I use this code, everything works fine:
```
const scores = await redis.zRangeWithScores(key, '0', '999').then((res) => res.reverse());
```

But when I use this, it always fails with error "[ErrorReply: ERR syntax error]":
```
const scores = await redis.zRangeWithScores(key, '0', '999', { REV: true });
```

I use Windows redis port, but there is no matter because when I use Linux redis I get the same error.
Configuration 1 (dev): Node v19.4.0, Redis 5.0.14.1, Node Redis v4.6.7, platform Windows.
Configuration 2 (prod): Node v19.0.1, Redis 6.0.16, Node Redis v4.6.7, platform Linux (Debian).

The code is correct according to the typings: ZRangeOptions accepts REV value.

### Node.js Version

19.4.0

### Redis Server Version

5.0.14.1

### Node Redis Version

4.6.7

### Platform

Windows

**Comment by leibale** [comment]
The `REV` option was added in Redis 6.2, see [here](https://redis.io/commands/zrange/)
