### ISSUE TITLE
detect_buffers implementation broken for multi/exec

### ISSUE THREAD

**Issue by souravchandra** [NodeRedis/node_redis#263]
Hi,
I created redis client using options detect_buffers = true.
But if I invoke multi/exec operation on redis , the return type is not as expected.
For example i did in my code:
redis.multi()
multi.del('')
multi.expire(...)
multi.sadd(...)
multi.smembers(...)
multi.exec()
Earlier when I did not use detect_buffers the type of reply for last command was array but now it comes as string.

**Comment by BridgeAR** [comment]
This is fixed in newer versions
