### ISSUE TITLE
Redlock support

### ISSUE THREAD

**Issue by SerhiiPostupaiev** [NodeRedis/node_redis#2692]
### Motivation

Hello,

Recently, I encountered a scenario that requires Redlock algorithm utilization to implement a logic in one of my projects and it turned out node-redis did not have built-in support for Redis locks. As there were no appropriate up-to-date solutions I have decided to implement a custom solution, which is the adaptation of the existing Redlock algorithm implementation designed for the ioredis library - https://github.com/mike-marcacci/node-redlock.

Do you think it is a good idea to submit PR with the adapted Redlock implementation so node-redis could potentially support it?
I will prepare all the documentation and tests and add them to the PR along with the code itself.

My main concern is that the node-redis GitHub repo has some closed Redlock-related issues (see, [1](https://github.com/redis/node-redis/issues/687) and [2](https://github.com/redis/node-redis/issues/1096)). In one of them, the reviewer said "This is not a question about node_redis, see Redlock docs and get the info there".
So my question is will my PR even be considered to merge if it corresponds to all the requirements or do the authors of the node-redis consider the Redlock as a separate feature that should be implemented and maintained separately in a view of the separate library with node-redis as a dependency?

**Comment by rawnsley** [comment]
I'm not a member of this repository, but I can safely say they would not consider adding Redlock support when it can (and should) be done using another library such as node-redlock. It appears that node-redlock [dropped support for node-redis](https://github.com/mike-marcacci/node-redlock/pull/84) a couple of years ago, but I could not tell you why ([and I'm not the only one that wants to know](https://github.com/mike-marcacci/node-redlock/issues/163)). That is the correct place to submit your PR.

**Comment by nhuanhoangduc** [comment]
I migrated from `ioredis` to `redis`.
Github repo: [https://github.com/nhuanhoangduc/node-redlock-v5](https://github.com/nhuanhoangduc/node-redlock-v5)
Npm: [https://www.npmjs.com/package/@hoangducnhuan/redlock](https://www.npmjs.com/package/@hoangducnhuan/redlock)
