### ISSUE TITLE
hmset can not hold udefined keys

### ISSUE THREAD

**Issue by yuri-karadzhov** [NodeRedis/node_redis#287]
> a
{ c: '1', d: '2', e: undefined }
> cl.hmset('w', a)
true
> node_redis: no callback to send error: Error: ERR wrong number of arguments for HMSET

/var/www/node_modules/redis/index.js:511
            throw err;
                  ^
Error: Error: ERR wrong number of arguments for HMSET
    at HiredisReplyParser.RedisClient.init_parser (/var/www/node_modules/redis/index.js:260:27)

**Comment by slidenerd** [comment]
Has this issue been resolved?

**Comment by stockholmux** [comment]
It's deprecated at throws a warning at the currently. Next big update cycle we may throw an full blown error, but it's a braking change.
This normally only comes up for me if I have a bug in my implementation, so it's valuable to throw for debugging purposes.
