### ISSUE TITLE
Subscribe client exception on reconnect after database select

### ISSUE THREAD

**Issue by alistairjcbrown** [NodeRedis/node_redis#314]
We have a function which creates redis clients and then configures them; selects the database, binds an error event handler, etc. 

However, if the returned client is then used as a subscriber, a reconnection to redis will cause a global exception. This is caused because the `RedisClient.prototype.on_ready` function attempts to use the command `select` which causes the following exception in the `RedisClient.prototype.send_command` function:

    "Connection in pub/sub mode, only pub/sub commands may be used"

The solution I have used is to pass a flag into the client creation function as to whether the client will be used as a subscriber and not to select the database if this is true.

Hopefully this issue will be useful to anyone else who has encountered this issue. Perhaps clients which are used as subscribers could remove the database attribute as it is not required?

**Comment by BridgeAR** [comment]
This is fixed on newer versions
