### ISSUE TITLE
Disabling automatic re-subscribe?

### ISSUE THREAD

**Issue by noffle** [NodeRedis/node_redis#320]
I've noticed that when I have multiple live subscriptions (via `node_redis`) to a running `redis-server` instance and then kill the server, the client seems to automatically resubscribe to all channels it had previously been subscribed to when the server is brought back online.

I'm not overly knowledgeable in Redis, but I am assuming that this something the client is doing. If so, is there any way to disable the auto-resubscribe functionality?

**Comment by BridgeAR** [comment]
This is implemented in newer versions
