### ISSUE TITLE
auto prefix key names

### ISSUE THREAD

**Issue by janhancic** [NodeRedis/node_redis#323]
I've looked but I haven't found a way to automatically prefix all key names with some value.

For instance in phpRedis there is the [setOption](https://github.com/nicolasff/phpredis#setoption) which you can use like this:

    $redis->setOption ( Redis::OPT_PREFIX, 'my_prefix' );

This will cause all keys to be automatically prefixed with "my_prefix" before they are sent to Redis.

Does this client support something like this?

**Comment by BridgeAR** [comment]
@mesrob-axs would you still be up for a pull request? :) That would be really great

**Comment by BridgeAR** [comment]
This feature has finally landed and is going to be released in v.2.4 :)

**Comment by janhancic** [comment]
Sweet! Shame I don't work at the place using this anymore to test it out :)
