### ISSUE TITLE
should HGET return `null` or `undefined` if the hash key is not set?

### ISSUE THREAD

**Issue by redchair123** [NodeRedis/node_redis#333]
question is fairly self-explanatory

**Comment by BridgeAR** [comment]
If the key is set to `null` or `undefined` it is going to be saved as corresponding string. This prints a warning from v.2.5 on and returns a error in v.3.
The return value is going to be `null` if no key is found.

If the key is not set at all and only a field is set, it is going to return a error that not enough arguments are set for the command.
