### ISSUE TITLE
connect ECONNREFUSED issue

### ISSUE THREAD

**Issue by Inter-Dev** [NodeRedis/node_redis#365]
Hi guys,

I use redis with an (redis) sentinel environment.

When one server went away, i still get reconnection messages.

How can i handle unavailable redis instances?

Please explain how to handle with instances who have gone away, can't find any hints in the documentation.

**Comment by BridgeAR** [comment]
Either this had nothing to do with node_redis or is fixed now as there should not be any reconnect messages after a failure, since a while back.
