### ISSUE TITLE
Use colon ( : ) as separator when joining keys.

### ISSUE THREAD

**Issue by chakrit** [NodeRedis/node_redis#386]
I believe `:` is the convention the redis community uses to namespace keys.

From my experiments, this module supports passing in an array as keys which will automatically be joined... but with a comma instead `,`

Why is this? Is it because keys were joined with `.join` without specifying the character?

Has there been a discussion or an issue raised as to why `,` was picked? accidental or not?

And is there any chance of this being changed? (fixed?) Maybe in a 0.9.0, so as not to break existing users? Or maybe make it configurable via the createClient options hash?

Reference: http://stackoverflow.com/questions/6965451/redis-key-naming-conventions

**Comment by BridgeAR** [comment]
I actually consider this a bug and this is fixed so far, that from v.2.5 on this is going to return a warning and from v.3 on this is going to return a error.
