### ISSUE TITLE
Reconnecting in pub/sub while using auth

### ISSUE THREAD

**Issue by VilemP** [NodeRedis/node_redis#388]
Hi,

first - appologies - I am pretty new to Redis and Node as well. 
We are using pub/sub in our new app which connects to redis using auth command.

It seems there might be an issue in this scenario:

1) successfully connected to redis using auth
2) subscribing to channel
3) then the connection to Redis is lost (e.g. restart) and comes alive again
4) client tries to reconnect using auth command
5) client is still in pub/sub mode and throws an error : throw new Error("Connection in pub/sub mode, only pub/sub commands may be used");

I think it migh be related to:
```javascript
  if (command === "subscribe" || command === "psubscribe" || command === "unsubscribe" || command === "punsubscribe") {
        this.pub_sub_command(command_obj);
    } else if (command === "monitor") {
        this.monitoring = true;
    } else if (command === "quit") {
        this.closing = true;
    } else if (this.pub_sub_mode === true) {
        throw new Error("Connection in pub/sub mode, only pub/sub commands may be used");
    }
```
as the command might be 'auth' while still in pub_sub_mode

I am not 100% sure this is the case, but we are seeing this error and can't figure out any other reason.

**Comment by BridgeAR** [comment]
This is fixed in newer versions
