### ISSUE TITLE
multi.hmget not working when passing in an array of hash keys.

### ISSUE THREAD

**Issue by Jezternz** [NodeRedis/node_redis#389]
Hi,
I am using the latest version of node-redis on npm (0.8.2 https://npmjs.org/package/redis),
Anyway when I call the below commands everything is peachy:
```
redisClient.hmget('{key}', ['{hashkey1}', '{hashkey2}']) => [val1, val2]
redisClient.hmget('{key}', '{hashkey1}', '{hashkey2}') => [val1, val2]
multi.hmget('{key}', '{hashkey1}', '{hashkey2}') => [val1, val2]
```
But when I call hmget with multi and feed an array of keys as the second paramater (below), all I get back is null.
```
multi.hmget('{key}', ['{hashkey1}', '{hashkey2}']) => [null]
```
As this is all through my code, this is rather inconvenient, it would be great if you could fix this and update npm, as I will have to revert to an older version until this is fixed.

Cheers

**Comment by BridgeAR** [comment]
This is fixed in newer versions

**Comment by katopz** [comment]
So what final function look like? I saw
```js
            it('returns strings for keys requested', function (done) {
                client.hmget('hash key 2', 'key 1', 'key 2', function (err, reply) {
                    assert.strictEqual(true, Array.isArray(reply));
                    assert.strictEqual(2, reply.length);
                    assert.strictEqual('val 1', reply[0]);
                    assert.strictEqual('val 2', reply[1]);
                    return done(err);
                });
            });
```
but not this anywhere
```js
client.hmget('hash key 2', ['key 1', 'key 2'], function (err, reply)  {}
```
In my case `['key 1', 'key 2']` is need because it will be vary and I can't find the way to make it work.
Thanks

**Comment by Celadora** [comment]
@katopz I was able to use the following patter to accomplish what you are looking for:

`
  // set up multi
  var multi = client.multi();

  // add each key to pipe
  for(var i = 0; i < keys.length; i++) {
    multi = multi.hgetall(keys[i]);
  }
  // execute multi
  multi.exec(function (err, replies) {
    if(err) console.error(err);
    else console.log(replies);
  });

`

I hope this helps you!

**Comment by coderroggie** [comment]
@katopz this is a day or two late, but i was struggling with the same problem and ended up being able to use the spread operator to make this work properly. 

```
client.hmget('hash key 2', ...['key 1', 'key 2'], function (err, reply)  {}
```

Hope that helps.
