### ISSUE TITLE
Lists get condensed into a comma-separated string on retrieval

### ISSUE THREAD

**Issue by stickfigure** [NodeRedis/node_redis#390]
Here's what I see in a node session:

> logger = function(err, results) { console.log(JSON.stringify({err: err, results:results})); }
[Function]
> r.rpush("abc", ["foo", "bar"], logger)
true
> {"err":null,"results":1}
> r.lrange("abc", 0, -1, logger)
true
> {"err":null,"results":["foo,bar"]}

Notice that results are ["foo, bar"] instead of ["foo", "bar"]. This seems like a bug of some sort - certainly not what I expected.

My package.json has:
    "redis": "0.8.x",
    "hiredis": "0.1.x",

**Comment by vskarich** [comment]
Spent a few hours tonight scratching my head over this---almost it to production without realizing it what was happening. +1 to better documentation about this issue.

**Comment by BridgeAR** [comment]
Not fixed => reopening

**Comment by BridgeAR** [comment]
This got closed by #838
