### ISSUE TITLE
Connecting to unexisting ip hangs up forever

### ISSUE THREAD

**Issue by gagle** [NodeRedis/node_redis#393]
This simple script hangs up forever. None of the callbacks are called.

Also, if I boot the machine with ip .182 I get ECONREFUSED errors every second, which is fine, but I don't need to re-try, any way to disable the re-connection tries?.

```javascript
var redis = require ("redis");
var client = redis.createClient (6379, "192.168.1.182");

client.on ("error", function (error){
	console.log (error);
});

client.on ("ready", function (){
	console.log ("ready");
});
```

---

EDIT: Ok, I've found how to avoid the re-connection tries. You have to set the option max_attemps to 1 (missing in the docs):

```javascript
redis.createClient (port, ip, { max_attempts: 1 });
```

But now I get 2 times the same console output because the stream emits a "close" event (line 87).

```text
[Error: Redis connection to 192.168.1.112:6379 failed - connect ECONNREFUSED]
node_redis: Couldn't get Redis connection after 1 attempts.
node_redis: Couldn't get Redis connection after 1 attempts.
```

Solution: comment the line 442 (I don't want output messages)

But it still hangs up if the ip doesn't exist. Basically you need to add a socket timeout (using the connection_timeout option which is also missing in docs), call to `self.on_error ("connect ETIMEDOUT")` and destroy the socket.

---

Concluding:
If you use max_attemps no console message is printed.
If you use connection_timeout the socket is destroyed after connection_timeout milliseconds.
If you don't use connection_timeout the socket is not destroyed and hangs up forever. It's like knocking on a door of a deserted house. You'll never receive an answer because there's no one on the other side.

I've uploaded a request with the solution.

**Comment by BridgeAR** [comment]
Fixed on master
