### ISSUE TITLE
connect EMFILE exception when closing connections

### ISSUE THREAD

**Issue by whoatemydomain** [NodeRedis/node_redis#433]
Given the following code :

var redis = require('redis');

var count = 2000; 
var clients = [];
for(var i=0;i<count;i++) {
	clients.push(redis.createClient());
}

for(var i=0;i<count;i++) {
	clients[i].quit();
}

I get the following error:
Error: Redis connection to 127.0.0.1:6379 failed - connect EMFILE
    at RedisClient.on_error (/.../node_modules/redis/index.js:148:24)
    at Socket.<anonymous> (/.../node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:88:17)
    at Socket._destroy.self.errorEmitted (net.js:329:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

I suspect is got to do with the max open files limit on mu ubuntu box. However, I would have thought I'd get the error on creating the clients not quitting.I know this is more of a question that an issue but comments would be appreciated. Thanks.

**Comment by BridgeAR** [comment]
@whoatemydomain @goldalworming I tried to reproduce this and was not able to with Ubuntu 15.10. I'm also wondering where the error is actually emitted. Are you sure the quit results in the error? To verify this, would you be so kind and add a callback to the quit and check for errors returned? That way it's certain where the error originates from.

What NodeJS version / Ubuntu version (`uname -a`) did you use?

**Comment by haozxuan** [comment]
I got this error in my production env; this is my version:
node: 4.4.3
node_redis:2.6.0-0

and i check redis server log by DBA, this is result:
![Uploading 1.png…]()

![Uploading 2.png…]()



redis server is normal, and redis client is ok. so i am very confused;

and ,this is my connect pool, i sub error even, but not emit, however, this error crash my process;

`
Redis.connect = function (port, ip, next) {
    var connectId = ip + port,
        RedisClient;

    redisPool[connectId] = redisPool[connectId] || {};

    if (redisPool[connectId].sta === "OK") {
        next(null, redisPool[connectId].connect);
    } else {
        redisPool[connectId].next = redisPool[connectId].next || [];
        redisPool[connectId].next.push(next);
        
        if (redisPool[connectId].sta != "BUSY") {
            redisPool[connectId].sta = "BUSY";

            RedisClient = redis.createClient({
                url            : "redis://" + ip + ":" + port,
                password       : redisPwd[ip],
                retry_strategy : function (options) {
                    console.error('node_redis connection %s is false, options is ', connectId, options);

                    if (options.error.code === 'ECONNREFUSED') {
                        if (redisPool[connectId].next) {
                            for(var i in redisPool[connectId].next) {
                                redisPool[connectId].next[i]('The server refused the connection');
                            }
                        }
                        // End reconnecting on a specific error and flush all commands with a individual error
                        return new Error('The server refused the connection');
                    }
                    if (options.total_retry_time > 1000 * 60 * 60) {
                        if (redisPool[connectId].next) {
                            for(var i in redisPool[connectId].next) {
                                redisPool[connectId].next[i]('Retry time exhausted');
                            }
                        }
                        // End reconnecting after 1h and flush all commands with a individual error
                        return new Error('Retry time exhausted');
                    }
                    // reconnect after 3s or later
                    return Math.max(options.attempt * 100, 3000);
                }
            });

            RedisClient.on('connect', function () {
                console.log('RedisClient connection %s is established.', connectId);
                redisPool[connectId].sta = "OK";
                redisPool[connectId].connect = RedisClient;

                for(var i in redisPool[connectId].next) {
                    redisPool[connectId].next[i](null, RedisClient);
                }
                redisPool[connectId].next = [];
            });

            RedisClient.on('reconnecting', function (obj) {
                console.error('node_redis connection %s is reconnecting', connectId, obj);
            });

            RedisClient.on('error', function (err) {
                console.error('node_redis connect %s is false, err is', connectId, err);
            });

            RedisClient.on('end', function () {
                delete redisPool[connectId].sta;
                delete redisPool[connectId].connect;
                console.error('node_redis connect %s is end.', connectId);
                return next(true);
            });

            RedisClient.on('warning', function (err) {
                console.error('node_redis connect %s is warning, err is', connectId, err);
            });
        }
    }
};`

**Comment by haozxuan** [comment]
and，this time crash again...
