### ISSUE TITLE
script exists SHA should return proper arguments

### ISSUE THREAD

**Issue by 3rd-Eden** [NodeRedis/node_redis#436]
It currently returns a pointless array with returned value from the redis server:

```js
redis.script('exists', sha, function (err, result) {
 // the result:
 // arguments { '0': null, '1': [ 1 ] }
});
```

What I would have expected is that `result` would hold the value `0` or `1` depending on what redis returned not an array where I would have to look for the first value.

Redis server responses:

```
SCRIPT EXISTs 1e29fabb9c911e8c38ba56a8f1135e062d39d3a4
1) (integer) 1
SCRIPT EXISTS e0e1f9fabfc9d4800c877a703b823ac0578ff8dba
1) (integer) 0
```

Server details:

```
redis_version:2.9.3
redis_git_sha1:cb598cdd
redis_git_dirty:0
arch_bits:64
multiplexing_api:kqueue
```

**Comment by gblock0** [comment]
+1

**Comment by BridgeAR** [comment]
This is fixed in newer versions.
