### ISSUE TITLE
Why isn't selected_db part of options

### ISSUE THREAD

**Issue by hpeinar** [NodeRedis/node_redis#442]
Why isn't it possible to pass in selected_db so node_redis would select db on_connect?

I think selected_db should be part of options and on_connect should check it like auth_pass and make the db selection when it's there. But I'm happy to know why it wouldn't be a good idea / or shouldn't be done.

**Comment by xpepermint** [comment]
+1

**Comment by jesucarr** [comment]
+1. I don't think adding another option would be too much if it helps reduce the logic in a library that uses node_redis, where the redisClient can be configured by the user
