### ISSUE TITLE
Subscribe callback is invoked twice per subscription after reconnection

### ISSUE THREAD

**Issue by jweyrich** [NodeRedis/node_redis#458]
Doing a `subscribe()` upon `ready` causes the `subscribe` callback to be invoked twice instead of once after a reconnection. However, doing `subscribe()` upon `connect` works as expected - the callback is invoked only once. What's the deal? Am I doing something wrong?

Code snippet:

	var redisSubscriber = redis.createClient(config.port, config.host);
	redisSubscriber.auth(config.pass);
	redisSubscriber.on('error', function (err) {
		console.error("[redis-subscriber] " + err);
	}).on('connect', function () {
		console.log("[redis-subscriber] Connected");
		redisSubscriber.subscribe('channel1');
	}).on('close', function (why) {
		console.log("[redis-subscriber] " + why);
	}).on('ready', function () {
		// redisSubscriber.subscribe('channel1');
	}).on('subscribe', function (channel, count) {
		console.log("[redis-subscriber] Subscribed to %s, %d total subscriptions", channel, count);
	});

Output:

	[redis-client] Connected
	[redis-subscriber] Connected
	[redis-subscriber] Subscribed to channel1, 1 total subscriptions
	[redis-client] Error: Redis connection to 10.2.0.1:6379 failed - connect ECONNREFUSED
	[redis-subscriber] Error: Redis connection to 10.2.0.1:6379 failed - connect ECONNREFUSED
	[redis-client] Error: Redis connection to 10.2.0.1:6379 failed - connect ECONNREFUSED
	[redis-subscriber] Error: Redis connection to 10.2.0.1:6379 failed - connect ECONNREFUSED
	...
	[redis-client] Connected
	[redis-subscriber] Connected
	[redis-subscriber] Subscribed to channel1, 1 total subscriptions
	[redis-subscriber] Subscribed to channel1, 1 total subscriptions

**Comment by BridgeAR** [comment]
@jweyrich sorry for the closed issue without ever receiving a response.

The re-subscription is intended but you're able to disable that with the `disable_resubscribing` option in newer versions.
