### ISSUE TITLE
Incorrect responses to SISMEMBER command request

### ISSUE THREAD

**Issue by paulbjensen** [NodeRedis/node_redis#461]
We've been encountering some weird behaviour with SISMEMBER queries.

To give context, we're using 0.8.3, and it's being utilised in a library called "chassis.io" here: https://github.com/axisto-live/chassis.io

The library is a wrapper to engine.io, and handles supporting RPC/PubSub with an express app. The line to SISMEMBER is called here:

https://github.com/axisto-live/chassis.io/blob/master/lib/pubsub.js#L129

We have this dataset in that set:

    smembers chassis_51d1342347618a7120002412

    1) "gqpiuA0e1PFl8-aHAAL6"
    2) "h3xzHb0a7YwPT51YAG3Y"
    3) "a_AJeBrYepWHpoZDAAFR"
    4) "gbJMUM_rIUCyg-YkAAAA"
    5) "SH6uQ_ISoncuX2pCAGvp"
    6) "uQVMuKh35GlYlXYDAABj"
    7) "ZY08C2iRaT0G1al-AAFJ"
    8) "I5S4a1wjYM0MOcaNADBs"
    9) "Bg1Xqx82SyOEPo_DAAAm"
   10) "seREqLFC394vlxcXAAAM"

And if we perform this query in redis-cli, we get this result:

    sismember chassis_51d1342347618a7120002412 XH_6OKzZ2Nn5HjktAAAj
    0

However, the node-redis npm response logged out from Redis (err, result values from line 129 mentioned above) is this:

    err: null , result: [ 'CaEyCwR56Yhg5JW1AAAB',
      'H58nute2c9hbeJnSAC_r',
      'ODMVcs9xIKGn2wNYAAFI',
      '68S4sm9p28GxnZfiAAAN',
      'QQaqEUZ3gpJs3MJFAAAg',
      '3BeEepIoCHzWPE06AAAC' ]

The values are not found in the set list, and interestingly, subsequent queries to SISMEMBER with different variations of "chassis_***" return the same response.

**Comment by BridgeAR** [comment]
as no one has ever responded so far: This should not be an issue in newer versions but I can't verify this as the mentioned library is using a outdated node_redis version.

There is definitely no issue with sismember in node_redis as it just returns the result as it is.
