### ISSUE TITLE
Support of set with options

### ISSUE THREAD

**Issue by michaelwittig** [NodeRedis/node_redis#462]
http://redis.io/commands/set supports options like XX. Is it possible to use them? I tried 

``` javascript
client.set(key, value, "PX expiry", function (err) {});
client.set(key, value, {PX:  expiry}, function (err) {});
```

which does not work.

**Comment by emilhem** [comment]
Could this be clarified with regards to expiry (like http://redis.io/commands/expire) in the documentation for node_redis?
