### ISSUE TITLE
Parsing the response into the right format with eval

### ISSUE THREAD

**Issue by julien51** [NodeRedis/node_redis#466]
Hi!
We use eval in one of our scripts. The script returns an Multibulk which should (at least we expected!) be translated into a JS object, rather than an array. For some reason eval yields an array. We assume that's because node_redis has no way to know exactly what to expect from an eval. Is there a way to tell it that it's going to be a hash?

**Comment by BridgeAR** [comment]
I would be open for a pull request for this.
