### ISSUE TITLE
calling end while reconnecting can cause traceback

### ISSUE THREAD

**Issue by bpytlik** [NodeRedis/node_redis#476]
Here's a program (in coffee-script) that reproduces the issue:
```coffee
redis = require("redis")

rc = redis.createClient(25002)

rc.on("error", () ->
    setTimeout((() ->
        rc.end()), 500
    )
)
```
You may have to play with the timing a bit to get the problem to happen on your system.

To reproduce, start a redis server running on port 25002. Start the program above, then kill the redis server, the following stack trace should appear:
>events.js:72
>        throw er; // Unhandled 'error' event
>              ^
>Error: connect ECONNREFUSED
>    at errnoException (net.js:900:11)
>    at Object.afterConnect \[as oncomplete\] (net.js:891:19)

(I'm using node v0.10.11.)

I'm not sure if this is a bug in underlying socket code or a problem in how node_redis is using the socket, but either way, it would be nice if node_redis could catch/hide this error.

**Comment by BridgeAR** [comment]
This is fixed in node_redis > v.2.0
