### ISSUE TITLE
client connected to slave thinks the server is ready before it actually is

### ISSUE THREAD

**Issue by bpytlik** [NodeRedis/node_redis#479]
If a slave's link with its master is down or if it's the middle of syncing with its master, a client connecting to the slave shouldn't consider the slave "ready".

I think the fix is to adjust the on_info_cmd function so that it checks whether the server is a slave and looks at the appropriate fields.

**Comment by bpytlik** [comment]
This issue still exists in the master branch, please reopen this issue or provide a reason for closing it.

**Comment by danielbprice** [comment]
I agree, why is this closed?

**Comment by BridgeAR** [comment]
@bpytlik @danielbprice could either of you open a pull request to fix this or add a test case? :)
