### ISSUE TITLE
RedisClient should record where it was created

### ISSUE THREAD

**Issue by bpytlik** [NodeRedis/node_redis#480]
If you're using a program which has created multiple RedisClient instances, when one fails, you often get an error that looks like this:
>     Error: Ready check failed: undefined
>      at RedisClient.on_info_cmd (/home/brock/sm-reboot/proto/opt/dssd.com/lib/node_modules/redis/index.js:347:35)
>      at Command.callback (/home/brock/sm-reboot/proto/opt/dssd.com/lib/node_modules/redis/index.js:395:14)
>      at RedisClient.flush_and_error (/home/brock/sm-reboot/proto/opt/dssd.com/lib/node_modules/redis/index.js:140:29)
>      at RedisClient.connection_gone (/home/brock/sm-reboot/proto/opt/dssd.com/lib/node_modules/redis/index.js:451:10)
>      at Socket.<anonymous> (/home/brock/sm-reboot/proto/opt/dssd.com/lib/node_modules/redis/index.js:94:14)
>      at Socket.EventEmitter.emit (events.js:95:17)
>      at TCP.close (net.js:465:12)

The problem is that this error provides no information about which client failed. Displaying information about the port and server the client was connected would help (as is shown when a connection is refused or reset), but if there are multiple clients, you're still stuck. What I've done when debugging these issues is to change the constructor so that it stores the stack when the RedisClient is created:
```javascript
this.__stack = new Error().stack
```
Then, when an error happens, I append the stack to the error message. That at least allows me to figure out which client is having the issue.

**Comment by bpytlik** [comment]
This problem still exists and is one of several reasons I monkey patch this library before using it. Please reopen this issue. A potential fix is included in the issue filed...

**Comment by BridgeAR** [comment]
@blainsmith I'll open this one as it has been reported as not fixed.

@bpytlik would you be so kind and open a pr for this?

**Comment by BridgeAR** [comment]
@bpytlik Adding the stack won't work if all clients are created in the same spot. But there's a connection_id on each client that is a unique client numbers. 

Would adding that number to an error solve your issue?

**Comment by bpytlik** [comment]
I think a number would definitely be helpful, but not as useful as the stack trace, and both together would be better than either in isolation.

For the number to be useful, we'd have to either have a way to preemptively print out the creation location of every client along w/ its number (so that the number would be meaningful) or we'd need the issue to be reliably reproducible, which isn't always the case.

In a testing environment, the number would be useful. In a production setting, the creation stack is far more useful.

**Comment by BridgeAR** [comment]
We have quite a lot options already, otherwise I'd have suggested to add a new one to be able to print the connection_id on creation of a client. Besides the connection_id I'd also add the PID, as there might be more than one node instance running (and the PID is always useful, even without logging that information on startup).

I'll add this in one of the next minors to all regular node_redis errors.

**Comment by BridgeAR** [comment]
Closing this as v.2.6 contains good error stacks in development and debug mode. Therefore it's from now on possible to receive the information you needed.
