### ISSUE TITLE
Is pipelining supported with this library?

### ISSUE THREAD

**Issue by waygee** [NodeRedis/node_redis#481]
Does this library support Redis pipelining?  Didn't see any explicit documentation for it, thought I'd ask.  If so, can an example be provided?

**Comment by diegoaguilar** [comment]
How does it manage when to *stop* pipelining?

**Comment by brycebaril** [comment]
@diegoaguilar if you send all of the commands in the same JS tick (synchronously) they will all be pipelined. Once you're out of that JS tick and the socket is able to flush, those commands will be sent. 

Beyond that there is not currently manual control of pipelining.

**Comment by BridgeAR** [comment]
@diegoaguilar what @brycebaril said. Plus from version 2.2.0 on both .multi and .batch are going to auto pipeline all commands until .exec is called.

**Comment by diegoaguilar** [comment]
So, apart from promisifying, is there any way to receive responses all in one?

**Comment by BridgeAR** [comment]
I'm not sure I understand what you mean with receive all in one? If you use .multi or .batch you'll collect all commands until you use .exec. All commands will be released in that moment and you'll receive your return value in .exec after all commands returned successful all in one result array.

**Comment by diegoaguilar** [comment]
Yeah, that's what I meant somehow, I wanted a way to perform bulk operations and with out having to use promises, manage whole responses in one.
