### ISSUE TITLE
Value String Coercion In .hmset Is Too Naive: '[object Object]' Ends Up Being the Value

### ISSUE THREAD

**Issue by JohnPostlethwait** [NodeRedis/node_redis#488]
Maybe I am generally using this incorrectly, but I have objects that I am storing that I do not necessarily know the structure of. Sometimes these objects have values that are themselves objects. It appears that these values have .toString() called on them, making the value '[object Object]' when actually stored.

I am currently traversing the object myself before using hmset, and forcing the objects to be string representations of the object, but I feels too one-offed and I feel this tool should probably take care of that for me...

**Comment by unlucio** [comment]
@JohnPostlethwait I'm having the same issue so I'm probably wrong as well: what were you doing wrong?

**Comment by BridgeAR** [comment]
@unlucio hmset will accept objects that do not have any nested objects and arrays.
