### ISSUE TITLE
Permanently select database?

### ISSUE THREAD

**Issue by jockster** [NodeRedis/node_redis#491]
Can I permanently select a database for development usage, so that all following queries are run against that database - without having to be wrapped inside a `select` call like below?

    client.select(3, function() { 
      client.stuff...
    });

I had a look at the docs, but maybe I have just missed it.

**Comment by LoicMahieu** [comment]
@jockster Prefixing made easy with https://github.com/linus/refix

**Comment by BridgeAR** [comment]
Prefixing is on the ToDo-List and will be in one of the upcoming versions.
