### ISSUE TITLE
Question about pipelining

### ISSUE THREAD

**Issue by happyByNature** [NodeRedis/node_redis#492]
Hello!

Just wanted to precise one thing about pipelining.

According to redis documentation, pipelining is when we do MANY requests in ONE write, like:

```
*3\r\n$3\r\nSET\r\n$4\r\nkey1\r\n$4\r\nval1\r\n
*3\r\n$3\r\nSET\r\n$4\r\nkey2\r\n$4\r\nval2\r\n
```

Then, server process them and return common response. That approach helps to gain in performance, because of decreasing network roundtrips.

But, when I did some analysis of node_redis, in my opinion, when we did something like:

```
client.set(key1, val1);
client.set(key2, val2);
```

node_redis generates & writes (to redis-server connection) for EACH of these commands... so there is no pipelining how redis-devs is understanding that...

Am I correct?

**Comment by BridgeAR** [comment]
From v.2.2 on both .multi and .batch are pipelining better than before and reduce RTT further.
