### ISSUE TITLE
How to clean multi queue correctly?

### ISSUE THREAD

**Issue by happyByNature** [NodeRedis/node_redis#493]
Hello!

Let say, I have a node.js server script, that accepts connections & does something...
During that activity it should collect (queue) some commands and exec what is queued once a second.

``` js
    var redis  = require("redis"),
        client = redis.createClient(), multi;

    // start a separate multi command queue
    multi = client.multi();


setInterval(function...
    // drains multi queue and runs atomically
    multi.exec(function (err, replies) {
        console.log(replies);
    });
, 1000);

var server =  ....
server.on('data', function() {
  ....
  // queues some commands to redis!
    multi.incr("incr thing", redis.print);
    multi.incr("incr other thing", redis.print);
)
```

Certainly, I need to clean my queue after exec, so that each 1 second queue will exec only once,, but will it be correct to do that in exec callback? 

Because, if the queue will be added, before I get the callback called, and I will clean that in callback (by calling multi = client.multi()), then I will lose new data (that was added) ?

**Comment by BridgeAR** [comment]
@EugenyPavlenko both .multi and .batch are from now on pipelining the commands better and work faster that way.
