### ISSUE TITLE
Plans for 1.0.0

### ISSUE THREAD

**Issue by brycebaril** [NodeRedis/node_redis#504]
I've been working up a set of things I'm planning on doing in order to release the next major version of node_redis, 1.0.0

There will be some breaking changes, but it should get the library in a better place for both maintainability and extensibility.

1. Move the repository to a Github Org.  -- this will only change the location, and the old location should redirect
2. Split the parser into a separate module
3. redo the tests to isolate unit tests vs regression tests & generally separate tested areas
4. Implement the new SCAN functionality
5. (this is the big one) remove the offline_queue and connection retry support from the core library.

That last one is the big breaking change, but I feel it needs to be done for a few reasons:

1. If extracted, the same behavior could be done via an external module.
2. The way that Redis works, I feel (and antirez agrees) this idea is fundamentally flawed. The Redis server saves some state for redis clients, and reconnections in the middle of a command stream cannot guarantee the same behavior as if there was no interruption.
3. So long as this library controls connection retries, any Sentinel or Cluster implementation cannot be in a separate module. This is important for encouraging modularity in the library, and allowing different implementations of sentinel/cluster support.
4. there are long-standing bugs with the current implementation
5. Most of the option-related feature requests right now involve different settings related to this feature. If it can be re-implemented in separate modules, different use-cases can be more easily constructed without option-bloat.

I would like to get this done by the end of this year, and would absolutely appreciate help! Very soon I will start to push work-in-progress branches for some of the above work, and would welcome any help!

Also, feel free to provide comments/feedback on this plan here.

**Comment by saltukalakus** [comment]
+1 for sentinel support
