### ISSUE TITLE
Redis generic pool returning null values without any errors

### ISSUE THREAD

**Issue by kaustubhagrawal2000** [NodeRedis/node_redis#507]
Hello
Please help me with this.
I am sorry if this issue is already being solved..
But I am using redis generic-pool and when I use this pool to get  my session data which is stored in redis I get NULL value randomly without any error.

redis.get(err,value) 
here both ERR and VALUE are null.

**Comment by momomo** [comment]
Still there 2020. hset returns null. second call seems to set it. wtf.
