### ISSUE TITLE
connection refused - on-connect doesn't wait for server

### ISSUE THREAD

**Issue by QuinDennis** [NodeRedis/node_redis#519]
Debian Squeeze - node-forever and redis

I have an /etc/init.d script which starts the app on startup.

Per documentation, on-connect or on-ready wait for redis server.  My node app auto-starts but won't connect.  I've added my own delays, but still no go.

================app.js=================
var http = require('http');
var https = require('https');

setInterval(simLoop, 3000);
var client, redis;
var waitToStart = 5;

function simLoop() {
  waitToStart--;
  if (waitToStart > 0) {
    console.log('waiting to start ' + waitToStart);
    return;
  }
  try {
    if (redis == null)
      redis = require("redis");
    if (client == null) {
      client = redis.createClient();
      client.on("error", function(err) {
        console.error("Error connecting to redis ", err);
      });
    }
    getData();
  } catch (e) {
    return;
  }
}

=========================app log file======================
# tail simErr.log
Error connecting to redis  [Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED]
Error connecting to redis  [Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED]
Error connecting to redis  [Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED]
Error connecting to redis  [Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED]

**Comment by BridgeAR** [comment]
The client is going to retry to connect to redis until either a hard timeout is reached or redis is back online. The errors just tell you that redis is not reachable yet.
