### ISSUE TITLE
Emit errors instead of throwing uncatchable errors

### ISSUE THREAD

**Issue by indexzero** [NodeRedis/node_redis#522]
Anywhere that you are throwing errors on the `nextTick` those errors should be emitted on the client instance.

* https://github.com/mranney/node_redis/blob/master/index.js#L586-L588
* https://github.com/mranney/node_redis/blob/master/index.js#L558-L565
* https://github.com/mranney/node_redis/blob/master/index.js#L567-L571

**Comment by BridgeAR** [comment]
This was just fixed on master by #816
