### ISSUE TITLE
Possible monitoring bug

### ISSUE THREAD

**Issue by miguelmota** [NodeRedis/node_redis#532]
Application code:
```
client.monitor(function(err, res) {
  console.log('Entering monitoring mode');
});

client.on('monitor', function(time, args) {
  console.log(time, args);                                                  
});

client.keys('User:*', function(err, keys) {
  console.log(keys);
});
```

Console output:
```
Entering monitoring mode

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object User:12,User:22,User:15,User:2,User:20,User:14,User:4,User:6,User:1,User:16,User:10,User:17,User:11,User:13,User:19,User:5,User:23,User:3,User:18,User:21,User:7,User:8 has no method 'split'
    at RedisClient.return_reply (/Users/moogs/workspace/node_modules/redis/index.js:704:46)
    at HiredisReplyParser.<anonymous> (/Users/moogs/workspace/node_modules/redis/index.js:312:14)
    at HiredisReplyParser.EventEmitter.emit (events.js:95:17)
    at HiredisReplyParser.execute (/Users/moogs/workspace/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/Users/moogs/workspace/node_modules/redis/index.js:535:27)
    at Socket.<anonymous> (/Users/moogs/workspace/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)

```

Module code in question (index.js):
```
 699     } else if (this.monitoring) {
 700         len = reply.indexOf(" ");
 701         timestamp = reply.slice(0, len);
 702         argindex = reply.indexOf('"');
 703         args = reply.slice(argindex + 1, -1).split('" "').map(function (elem) {                                  
 704             return elem.replace(/\\"/g, '"');
 705         });
 706         this.emit("monitor", timestamp, args);
 707     } else {
```

**Comment by ralucas** [comment]
Seen this issue as well.  Any work around or fix, outside of nixing monitoring?

**Comment by ralucas** [comment]
So, is no one else experiencing this issue?

**Comment by blainsmith** [comment]
If your client is up to date I will reopen this issue and look into it. Were we trying to clean up stale issues. What version are you running?

**Comment by ralucas** [comment]
Running 0.12.1, so that should be up-to-date.

**Comment by blainsmith** [comment]
Actually after re-reading this and referencing the docs you cannot send any commends on the same client connection after you set up monitoring. However, you can make another client connection to issue normal commands.

See https://github.com/NodeRedis/node_redis#monitor-mode

**Comment by ralucas** [comment]
Oh, wow, totally glossed over that.  Thank you for pointing that out!  Best!

**Comment by blainsmith** [comment]
No worries!

**Comment by BridgeAR** [comment]
@ralucas I guess this could be implemented as feature. Would you be up to add a command that creates a new redis instance, fires the monitor command and returns the instance afterwards? That way this would not be an issue anymore.

**Comment by ralucas** [comment]
@BridgeAR Yes, that sounds like a great project.  I'll take a look and see what I can do.  Cheers!

**Comment by BridgeAR** [comment]
:+1:

**Comment by BridgeAR** [comment]
@ralucas monitor mode was actually broken and not properly implemented before. This is fixed on master and therefor this feature is not required anymore, as the monitoring client is from now on working as it should while also monitoring.
