### ISSUE TITLE
Pipelining

### ISSUE THREAD

**Issue by dmitry-saritasa** [NodeRedis/node_redis#539]
Hi Guys,

how to enable pipelining in node_redis programmatically? 

I saw documentation says it's happen automatically in most cases - and I wand to understand is there a way to force it from the application code programmatically in node_redis

[ec2-user@devops ~]$ redis-benchmark -n 100000 -t set,get -P 16 -q -h 10.0.1.10
SET: 199600.80 requests per second
GET: 193050.19 requests per second

[ec2-user@devops ~]$ redis-benchmark -n 100000 -t set,get  -q -h 10.0.1.12
SET: 14098.41 requests per second
GET: 13743.82 requests per second

it's more than 10 times difference on Redis node.

thanks,
Dmitry

**Comment by BridgeAR** [comment]
@Vizwind @saritasa both .multi and .batch use pipelining as thought about from version 2.2 on.
