### ISSUE TITLE
createClient function doesn't copy auth_path

### ISSUE THREAD

**Issue by hikasiru** [NodeRedis/node_redis#542]
I'm using node.js express.io and redis(ver 0.10.0). using password

Trying to use redis socket store, i met ERR operation not permitted

source code:

    var redisInfo = {
	host : '127.0.0.1',
	port: 6379,
	password: 'redis password' 
    };

    var redis_pub= redis.createClient(redisInfo.port, redisInfo.host); 
    redis_pub.auth(redisInfo.password);
    var redis_sub= redis.createClient(redisInfo.port, redisInfo.host);	
    redis_sub.auth(redisInfo.password);
    var redis_client= redis.createClient(redisInfo.port, redisInfo.host);	
    redis_client.auth(redisInfo.password);

    var redisStore = new express.io.RedisStore({
	redisPub: redis_pub,
	redisSub: redis_sub,
	redisClient: redis_client
    });

So, index.js line No. 1103 should be change like this, isn't it?

    exports.createClient = function (port_arg, host_arg, options) {
    var port = port_arg || default_port,
        host = host_arg || default_host,
        redis_client, net_client;

    net_client = net.createConnection(port, host);

    redis_client = new RedisClient(net_client, options);

    redis_client.port = port;
    redis_client.host = host;
    ////////////////////////////////////////////////////
    if (options && options.auth_pass !== undefined) {
    	redis_client.auth_pass = options.auth_pass; 
    }
    ////////////////////////////////////////////////////
    return redis_client;
};

Thanks. :)

ps. I wrote redis and moved to node_redis.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
This is fixed in later versions
