### ISSUE TITLE
Multi replies don't map correctly to indicies if server doesn't support command (eval)

### ISSUE THREAD

**Issue by aaaidan** [NodeRedis/node_redis#555]
Firstly, sorry about the awkward title for this issue!

If you run a multi which contains an eval command, connected to version of redis server that doesn't support it (appfog, for example runs 2.2), it will not be part of the replies array, and subsequent replies will be in the "wrong index".

    multi.incr("foo");
    multi.eval(myScript);
    multi.get("bar");
    multi.exec(function(err, replies) {
      // running on redis 2.2...
      replies[0]; // result of incr foo
      replies[1]; // result of get bar... Expected eval!
      replies[2]; // undefined... Expected get bar!
    });

Perhaps I'm misunderstanding how this is supposed to work, but I expected the whole multi to fail (since eval fails to run) but it'd be nice if the reply for eval was `undefined` or something, so that subsequent commands still "map" to the expected indicies.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@aaaidan this is indeed something that should be handled. Would you be so kind and try the hiredis parser and see if the result differs?

I know this is long ago but I try to go through all the tickets and check if there are still some open issues that I could fix.

**Comment by BridgeAR** [comment]
At least newer redis versions return an error on not yet supported commands in multi. I'm uncertain what 2.2 returned.

**Comment by aaaidan** [comment]
@BridgeAR Throwing an error makes a lot more sense to me than silently mangling the replies array. ;) I'm happy for this issue to stay closed.
