### ISSUE TITLE
Best practices for number of connections

### ISSUE THREAD

**Issue by dirkbonhomme** [NodeRedis/node_redis#558]
I was wondering what the best strategy would be to connect to a Redis server during the execution of a script:
- Create one instance and share that across all code that requires Redis (= 1 connection to Redis)
- Create different instances for read, write and polling requests (= 3 connections to Redis)

Are there any performance gains from having multiple connections?

Apart from that, would it make any difference to have a separate connection for code that relies a lot on BRPOPLPUSH?

Thanks

**Comment by ankitchaudhury** [comment]
I am developing a common caching service which will be used by many micro services(Clients for me). How many number of connections should I create? Is 1 connection per application sufficient?

**Comment by BridgeAR** [comment]
One connection is perfect. The performance will always be the same no matter if you use more than one client.
