### ISSUE TITLE
streaming client?

### ISSUE THREAD

**Issue by AaronSikes** [NodeRedis/node_redis#562]
Hey @mranney,
We're storing some data in redis which we are basically passing straight through node to the browser. It's in a redis hash with ~120k key/value pairs. The values are ~500 bytes each. A client.hvals call can take 40 seconds to come back - but using the redis-cli it takes ~0.2 seconds.
 I was thinking I would tackle this by creating a stream interface which can interpret the redis protocol and stream json. Is this something you'd be interested in integrating, or should I start a separate project? Or does a simpler solution come to mind?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@brycebaril did you finish your refactoring for this yet?

**Comment by BridgeAR** [comment]
@AaronSikes would you still be up for a pull request? I guess using .batch will already process everything quite fast but there likely still room for more.

**Comment by AaronSikes** [comment]
Sorry, haven't been using redis for a while, or even node that much. Don't have the attention available to pick this up right now

**Comment by BridgeAR** [comment]
@AaronSikes too bad. Thx for the reply though.

I personally do not have the time to implement this right now without the help of others. Therefor I'm closing this until someone brings the issue up again. Maybe we'll include the scanstream library from @brycebaril in the NodeRedis org and improve that to also handle other commands.
