### ISSUE TITLE
Doesn't timeout properly when server is unreachable

### ISSUE THREAD

**Issue by celesteking** [NodeRedis/node_redis#587]
```
 var r = require('redis').createClient(null, '1.2.3.4', {connect_timeout: 1000}); r.on('ready', function(){ console.log('ready!'); }).on('error', function(err){ console.log('error: ' + err)});
```
It doesn't timeout after 1 second. It does timeout after unknown amount of time with:
> error: Error: Redis connection to 1.2.3.4:6379 failed - connect ETIMEDOUT

I think it should follow the docs and error out after specified timeout.

**Comment by michelsalib** [comment]
I also got the same issue, my config is the following:
```js
var client = redis.createClient(conf.port, conf.host, {
    connect_timeout: 100,        // abandon connection after 100ms
    retry_max_delay: 100,        // no impact, will not wait more than 100ms between reconnections attemps
    max_attempts: 1,             // only 1 connection attempt
    enable_offline_queue: false, // no offline queue, must wait for online mode
    no_ready_check: true         // we don't check for redis ready state, let's query the redis directly
});
```

But instead of failing after 100ms, it fails after a full second. Anyone found a fix for that?

**Comment by bgSosh** [comment]
Similar issues here.

**Comment by raviv** [comment]
+1

**Comment by chrisbaldauf** [comment]
+1

**Comment by bgSosh** [comment]
Any news on this?

**Comment by chrisbaldauf** [comment]
I wound up switching to [ioredis](https://github.com/luin/ioredis), which appears to handle the connection timeouts properly and aside from the client creation, be a drop in replacement for my use case.

**Comment by bgSosh** [comment]
That looks interesting - I'll take a closer look, thanks.

**Comment by BenHall** [comment]
To reproduce I paused a Redis Docker container but still seeing long timeouts

**Comment by jbergknoff** [comment]
Is this issue resolved? I experience the behavior described above. The connection fails after about 2 minutes, despite `connect_timeout` of 5000. I am using version 2.2.5.

**Comment by BridgeAR** [comment]
@jbergknoff this should definitly be resolved. Do you have a reproducable case? And how do your current options look like?

**Comment by jbergknoff** [comment]
Hm, interesting. A slightly modified code snippet from the original post here reproduces the issue:

```javascript
 var r = require('redis').createClient({host: '1.2.3.4', connect_timeout: 1000}); r.on('ready', function(){ console.log('ready!'); }).on('error', function(err){ console.log('error: ' + err)});
```

The change is in the arguments to `createClient`. The original snippet unintentionally falls back on the default host (127.0.0.1) because `typeof null` is `object` (https://github.com/NodeRedis/node_redis/blob/afc4989495245e683ce70a234c55046a51e73c08/index.js#L1243). If the host is the bogus 1.2.3.4 then this hangs for 2 minutes. If the host is 127.0.0.1 then it works as expected. Any insight into that?

**Comment by BridgeAR** [comment]
@jbergknoff thx for pointing that out! I'm looking into it right now.

**Comment by BridgeAR** [comment]
@jbergknoff fixed on master

**Comment by jbergknoff** [comment]
Great, thanks @BridgeAR! Any ETA on next release to npm?

**Comment by BridgeAR** [comment]
Later today
