### ISSUE TITLE
Callback errors are handled as a node_redis error

### ISSUE THREAD

**Issue by pablo-cabrera** [NodeRedis/node_redis#591]
Hello,

Any error that is thrown from within a callback function, is handled as a node_redis error. 
When this happens, if you have an on("error"), you will not only listen to internal node_redis errors but also your own errors.

```js
var client = redis.createClient(host, port);

client.on("error", function (e) {
    console.log("onError: " + e.toString());
});

client.get(key, function (err, data) {
    throw new Error("Error from callback!");
});
>>> onError: Error: Error from callback!
```

The thing is that there isn't anything wrong with node_redis itself, and I would like to have errors thrown from within the callback to actually stop the application, and not be swallowed by redis client.

**Comment by BridgeAR** [comment]
This was fixed on master by #816
