### ISSUE TITLE
createClient() is painful with env vars

### ISSUE THREAD

**Issue by aj0strow** [NodeRedis/node_redis#621]
For 3rd-party redis hosting it's nice to create the client with an environment variable. It kinda sucks to do that with the current `createClient(port, host, { auth stuff })`.

For example, **[mjackson/then-redis](https://github.com/mjackson/then-redis#usage)** kills it with usability. Would be happy to PR let me know.

**Comment by BridgeAR** [comment]
We support the redis url since v.1.0 and we might implement more environment variables to use directly.

**Comment by aj0strow** [comment]
@BridgeAR thank you, it's a nice improvement!!
