### ISSUE TITLE
On Azure Redis - ECONNRESET - operations fail without reconnect attempt

### ISSUE THREAD

**Issue by BobDickinson** [NodeRedis/node_redis#628]
I have a fairly straightforward implementation of redis working more or less as expected, with one major exception.  In my production environment, using Microsoft Azure redis, there is a pretty bad failure mode.  I'm using the actual Azure redis service (as opposed to running my own redis in an Azure VM or something).

If I make a request after a few minutes of inactivity, it fails in the following way (I have debug_mode on, and everything not in square brackets below is console output):

[client.get]

send xxx.redis.cache.windows.net:6379 id 1: *2
$3
get
$36
772e1696-e333-4adb-b04a-3e0e15d0cffa

send_command buffered_writes: 0  should_buffer: false

[20 seconds elapses]

Redis connection to xxx.redis.cache.windows.net:6379 failed - read ECONNRESET

[client.get calls back with error: "Error: Redis connection to xxx.redis.cache.windows.net:6379 failed - read ECONNRESET"]

["error" event fires: "Error: Redis connection to xxx.redis.cache.windows.net:6379 failed - read ECONNRESET"]

Redis connection is gone from error event.

["end" event fires]

Retry connection in 255 ms
Retrying connection...
Stream connected xxx.redis.cache.windows.net:6379 id 1
Using default parser module: javascript
Sending auth to xxx.redis.cache.windows.net:6379 id 1
send xxx.redis.cache.windows.net:6379 id 1: *2
$4
auth
$44
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=

send_command buffered_writes: 0  should_buffer: false
net read xxx.redis.cache.windows.net:6379 id 1: +OK

Auth succeeded xxx.redis.cache.windows.net:6379 id 1
checking server ready state...
send xxx.redis.cache.windows.net:6379 id 1: *1

So there is a bunch of stuff going on.  The main issue is that there is a long wait time (10-20 seconds) on the attempted get, and then the get fails.  Then for some reason it decides to wait some more before reconnecting, then the reconnect succeeds, but too late to be of any real use at that point (having already returned failure before ever attempting to reconnect).

I specified Azure in the issue because when I do this same test with a local redis server (local meaning on a different dev machine on the LAN) and I force the server to drop the connection, the client code does exactly what you would expect (immediately responds to the reset connection and attempts reconnect, succeeding as soon as the server is back up).  It might be worth noting that my local test redis server is running on Mac OS and the Azure redis server runs on Windows.  My test environment is also running Node on Windows.

In the Azure redis case, I can leave the client idle for 30 minutes (by which time I know the server has dropped the connection), but the client does not detect it (no reconnect attempt, no error or end callbacks, just nothing at all happening).  Until I try to actually do something on the connection, in which case we have the long timeout and subsequent failure of the call.

If it was just the failure to attempt reconnect, maybe I could work around it, but the 10-20 seconds of hanging around to figure out the connection has been reset before failing would make that approach a non-starter anyway.

I'm not really sure what else I can do to debug this.  Any guidance would be appreciated.

**Comment by BenHall** [comment]
I've had a similar issue. I was able to reprodcue it using Docker and pausing a Redis container. Node_redis queues the callbacks until you unpause the container which in my case is not ideal.

**Comment by BridgeAR** [comment]
@BenHall @weull @BobDickinson are you still experiencing this? We have Windows support now and if you still experience any difficulties @bcoe might look further into it.

**Comment by BridgeAR** [comment]
As I'm not using Windows please feel free to add a PR for this. But until then I can't improve the keep alive logic further.

**Comment by kamoljan** [comment]
@BridgeAR We are experiencing the same issue.
What the solution?

**Comment by shapeofarchitect** [comment]
@BobDickinson  @mranney  and @BridgeAR it seems that in 2020 and this is still happening , I can confirm that node_redis has a consistent behavior on the connection error, reset, reconnect. IN my case as well I have clients using tls and 6380 port to connect and it almost in all clients I am using giving me below errors. 

`{"requestContext":{"tenantId":"1","traceId":"5343478d-7b7c-470c-a740-4cxxxxxxxxxxxxx","errorMessage":"UnknownRedisError","errorType":"CON06","errorName":"RedisError","loggerName":"RedisClient"}`

`[Nest] 17   - 11/05/2020, 1:33:36 AM   [CryptoModule] Object:
{
  "errorCode": "ECM01",
  "errorName": "RedisError",
  "message": "Redis connection error",
  "statusCode": 0,
  "exception": "Ready check failed: Redis connection lost and command aborted. It might have been processed.",
  "trace": "AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.\n    at RedisClient.flush_and_error (/usr/src/app/node_modules/redis/index.js:297:23)\n    at RedisClient.connection_gone (/usr/src/app/node_modules/redis/index.js:602:14)\n    at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:345:10)\n    at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:222:14)\n    at Socket.emit (events.js:314:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
 +2ms`

I am fairly certain that this comes when azure Redis sees client inactivity so it just close the connection abruptly unless node_redis log each ACK/FIN of tcp socket. Is there any solution, feedback , workaround yet ?
