### ISSUE TITLE
Connection bug moving to 0.11.0

### ISSUE THREAD

**Issue by tomasz-jomedia** [NodeRedis/node_redis#632]
We're connecting to redis locally and it worked fine in 0.10.x. We've moved towards 0.11.0 and we're getting the following error:
```
Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED
    at RedisClient.on_error (/home/drm/stage1-786290/releases/master_tmp/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/home/drm/stage1-786290/releases/master_tmp/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
```

Our config is this:

```
config.redis            =
{
        port: 6379,
        host: 'localhost',
        option:{}
}
```

Same code works fine when we downgrade to 0.10.3.

**Comment by tDo** [comment]
Sorry for the late response. The connection error still remains in the 0.12.x branch for me. Well to finally provide some code:

```javascript
...
var options = {
        connect_timeout: 1000,
        enable_offline_queue: false
    };
this.clientCommands     = redis.createClient(this.port, this.ip, options);
this.clientCommands.once("error", function(msg) { deferred.reject(new Error(msg)); });
```

Tested on both a linux-environment as well as a windows environment on the redis 2.8.x stable branches. Maybe this helps a bit to identify the possible reason...

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
If this is still an issue, please reply again. But this should likely be fixed.
