### ISSUE TITLE
Connect to Redis via SSL

### ISSUE THREAD

**Issue by murdockcrc** [NodeRedis/node_redis#650]
I am using Azure Redis Cache, which offers the option to connect via SSL. Is SSL supported in this package? I manage to connect via the non-SSL port, but as soon as I change the RedisOptions to try connecting to the SSL port, the connection fails with the following error:

"Error: Redis connection to xxx.redis.cache.windows.net:6380 failed - read ECONNRESET
at RedisClient.flush_and_error "

**Comment by carlosfaria94** [comment]
The solution is to enable non-SSL port in Azure

https://azure.microsoft.com/en-us/documentation/articles/cache-nodejs-get-started/

**Comment by johnarnold-bechtel** [comment]
In case anyone else comes here from google, it looks like this should be supported now:

https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-nodejs-get-started#connect-to-the-cache

**Comment by ntziolis** [comment]
> In case anyone else comes here from google, it looks like this should be supported now:
> 
> https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-nodejs-get-started#connect-to-the-cache

It took me a second to see what exactly the difference was, hence calling it out here for others to find. The key difference is providing the name of the redis host as part of the tls object:
```ts
{
  auth_pass: REDISACCESSKEY,
  tls: {servername: REDISHOSTURL}
}
```

**Comment by RUDDHIKA** [comment]
@ntziolis Thanks it helped a lot.
