### ISSUE TITLE
Does node_redis take advantage of pipelines?

### ISSUE THREAD

**Issue by rahst12** [NodeRedis/node_redis#661]
Hi,
   I thought that if I installed hiredis, I would take advantage of the pipelining that Redis offers.  We've run a test of node vs java.  Java is outperforming node by an order of magnitude for a large smembers queries (~150,000).

   I haven't found anything specific showing an example of how I can make use of this in node_redis.  Any suggestions would be appreciated.  (And my apologies if an "issue" wasn't the best place for this..)

Thanks

Info: http://redis.io/topics/pipelining

**Comment by BridgeAR** [comment]
Pipelines will be included in a future release.
