### ISSUE TITLE
Client takes very long to callback when connection is lost

### ISSUE THREAD

**Issue by sharathprabhal** [NodeRedis/node_redis#667]
Running the following code in the console

```
var redis = require('redis');
var client = redis.createClient();
var i = 0;
var setValue = function (key, value, cb) {
	client.set(key, value, cb);	
};

client.on('error', function (err) {
	//console.error('redis error', err);
});

setInterval(function () {
	i ++;
	(function(r) {
		console.time('set' + r);
		setValue('test-redis-foo', 'bar', function (err) {
			//if (err) { console.log('set error', err); }
			console.timeEnd('set' + r);
		});
	})(i);
}, 1000);

````

returns the following response

```
set1: 0ms
set2: 0ms
set3: 0ms
set4: 300ms
set5: 37ms
set6: 289ms
set7: 1416ms
set8: 415ms
set9: 3029ms
set10: 2028ms
set11: 1027ms
set12: 27ms
set13: 0ms
set14: 1ms
set15: 0ms
set16: 1ms
set17: 0ms
```

At `set4`, the client lost connection to the redis server since I manually shut down the server. I turned it back ON at `set13`.

If I am unable to reach my cache at any point, I want my server to behave as though the cache item did not exist. However, this introduces unnecessary delay.

Is there a way around this?

A simple fix was to modify my setValue as follows

```
var setValue = function (key, value, cb) {
	if (client.connected) {
		client.set(key, value, cb);		
	} else {
		cb({msg: 'No connection'});
	}
};
```

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
