### ISSUE TITLE
Redis connection gone from end event.

### ISSUE THREAD

**Issue by LoicMahieu** [NodeRedis/node_redis#676]
I wanted to post this message on a user group or a mailing list but I didn't find anything, especially for node-redis.

For several days, I received `Redis connection gone from end event.` error from some nodejs applications.
What exactly mean this exception ? Maybe it's a network issue ?
I found these links
https://groups.google.com/forum/#!topic/redis-db/5meMdHuJAQI
https://code.google.com/p/redis/issues/detail?id=372#c3
That explains a problem related to `maxclients`. Is it my case ?

```
redis 2.8.6
node-redis 0.12.1
```

Redis info :
# Server
redis_version:2.8.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d44fe9286f5a5985
redis_mode:standalone
os:Linux 2.6.32-27-pve x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.6.3
process_id:11973
run_id:acd7b66d57a5eac8f0df532cb5f178b2aeca45f0
tcp_port:6379
uptime_in_seconds:20457496
uptime_in_days:236
hz:10
lru_clock:870477
config_file:/etc/redis/slave.conf

# Clients
connected_clients:175
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Stats
total_connections_received:126218792
total_commands_processed:439637652
instantaneous_ops_per_sec:21
rejected_connections:0
sync_full:8
sync_partial_ok:0
sync_partial_err:0
expired_keys:2167019
evicted_keys:0
keyspace_hits:29194286
keyspace_misses:564730
pubsub_channels:2
pubsub_patterns:0
latest_fork_usec:1551

Thanks

**Comment by glasseyes42** [comment]
Started seeing this periodically in our production system (which handles thousands of messages a minute so I don't think this is load related). Can take a few days and suddenly logs are full of this. Curiously its only recently started, no changes to code or versions (redis or client) in a good couple of months.

**Comment by givan** [comment]
We're having the same issue. In last 24 hours, we're getting 19,251 of these events. And it has been going like this for a while. We're able to recreate the connection after that, but I wonder why is that happening. I had our network operations look into tpcdumps to make sure it's not related to network packet loss, and they confirmed it's not hardware related. Also, as you can see from our logs, the error occurs almost periodically every 5 minutes (here it's only shown the last 4 hours with that error):

https://www.dropbox.com/s/1txa04uv386nk71/Screenshot%202015-02-05%2000.06.59.png?dl=0

Using redis-client 0.12
Client host os - CentOS 5.6
Redis server v=2.8.9 sha=00000000:0 malloc=jemalloc-3.2.0 bits=64 build=8ef9bbd7e542f69f

**Comment by tanzim** [comment]
We had some code that (under simulated network failure) would go into an infinite loop getting items from a redis queue, erroring and retrying the same operation and eventually redis reporting ```Redis connection gone from end event.``` The workaround was to break up the call stack when the error happened so that de-queueing doesn't happen in a tight loop. Fixed/masked the issue for us at least.

**Comment by Leask** [comment]
Is there any progress for this issue?

**Comment by erinspice** [comment]
PRs accepted! We're all volunteers.

**Comment by sunnychow** [comment]
@erinspice : May I know which PR is accepted?  Thanks.

**Comment by liujb** [comment]
Is there any progress for this issue?

**Comment by Leask** [comment]
Use `ioredis` instead. It's awesome.

**Comment by liujb** [comment]
hi, everybody.
I have solved this problem. when your createClient must add option no_ready_check. like
var client = redis.createClient(redisConf.port, redisConf.host, {no_ready_check: true});

**Comment by erinspice** [comment]
Thanks, @liujb.

@sunnychow, I and some others have just recently gained access to the repo. We are still working out the process. However, I think we agree that we will accept any PR which is backward-compatible and consistent with how Redis works. Soon we will replace the test suite with a more standard Mocha suite that will be easier to extend, and at that time, it will be much easier for people to report issues with failing tests and PRs with passing tests.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by markthethomas** [comment]
Sad to have to re-open this so soon, but I've been experiencing the same error using latest stable node-redis (0.12.1) and redis 2.8.1. I seem to get the error every 10 minutes or so  when we're running our node app in a staging docker container (debian:jessie is base image). 

Is this likely to be something related to the redis instance we use? It's regularity seems to indicate a timing-related issue, maybe a timeout or TTL. We've only just noticed it (just started using a redis-backed queue recently). In checking into this error, I've seen some solutions that recommend using something like `client.ping()` on an interval, but this seems to be only a half-measure. Any thoughts/insight would be greatly appreciated. 

Thanks!

````
Error: Redis connection gone from end event.
    at RedisClient.flush_and_error (/var/www/app/current/node_modules/redis/index.js:149:13)
    at RedisClient.connection_gone (/var/www/app/current/node_modules/redis/index.js:486:10)
    at Socket.<anonymous> (/var/www/app/current/node_modules/redis/index.js:114:14)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback [as _tickCallback] (node.js:381:11)
````

**Comment by erinspice** [comment]
@markthethomas Might you be able to write a failing test?

**Comment by markthethomas** [comment]
I'll see what I can do. I've created a related [issue](https://github.com/Automattic/kue/issues/696) in Kue, the module that utilizes node-redis and seems to be throwing the error

**Comment by Rukeith** [comment]
Is this issue be fixed?
Even though I use the no_ready_check: true, I still have this issue.

**Comment by markthethomas** [comment]
I haven't seen this recently and had trouble writing a failing test -- may have been related to my connection?

**Comment by BridgeAR** [comment]
The error was not really descriptive earlier. From version 2. on that error should not occur if you did not close the redis client by yourself. Earlier it was also thrown to often, as it could occur while reconnecting and that flushed the offline queue and returned that error.

This won't happen anymore and is resolved in v.2. I really recommend using v.2 as it fixed a lot of issues that people could have run in to.

**Comment by marco-c** [comment]
I haven't dug into it much yet, but we're seeing a similar failure: https://github.com/mozilla/platform-status/issues/405.

**Comment by BridgeAR** [comment]
@marco-c please open a new issue for this. Please also check if this is also happening with v.2.5.3 as you already have updated to the 2.6 pre-releases. I do have the feeling that the quit command itself returns that error as "last" command that ends the connection server side and the client gets the fin package and emits the end event before the quit result got properly handled. So this is likely a race condition and not happening all the time? To verify this, please check what error properties the error has (I only see the stack in the log).

A bit off-topic: the returned error message seems confusing and I'll try to fix that by renaming the error to something more obvious.

**Comment by marco-c** [comment]
Thank you, I don't know why we were using a pre-release version :smile: 
Switching to 2.5.3 fixed the issue.

**Comment by BridgeAR** [comment]
@marco-c thanks a lot for reporting it, that regression would have almost slipped through :smile:
