### ISSUE TITLE
read ETIMEDOUT errors on pub/sub subscription.

### ISSUE THREAD

**Issue by bgSosh** [NodeRedis/node_redis#680]
We are using the pub/sub functionality of redis.  We are getting lots of errors like this:

Redis connection to xxxx:xxxx failed - read ETIMEDOUT

AFAIK, there's nothing I can add to the connection settings to help with this.  

Any idea why this is happening?

**Comment by simonlast** [comment]
What's the status on this? I'm getting a similar issue using ElastiCache Redis.

**Comment by Muqito** [comment]
I get the same issue here :/ I want a status aswell or what I can do to make this go away.

Thanks in advance

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
This is very likely not fixed => reopening

**Comment by BridgeAR** [comment]
@bgSosh @Muqito @simonlast could any of you write a test for this?

**Comment by Krisa** [comment]
Happens to me too, especially every time after some inactivity (like a few minutes). Is there some way, to either?
- extend the timeout (to like forever :) )
- send somehow a ping to keep the connection alive
- reconnect automatically on timeout

If that may help, I'm using amazon:
```
Error: Redis connection to ec2-54-225-132-156.compute-1.amazonaws.com:18149 failed - read ETIMEDOUT 
Error: Redis connection to ec2-54-225-132-156.compute-1.amazonaws.com:18149 failed - read ETIMEDOUT
    at exports._errnoException (util.js:860:11)
    at TCP.onread (net.js:544:26) 
```

**Comment by Amitosh1** [comment]
i am also facing same issue with node-redis 0.7.2 and redis version 3.0.4 it happens around every 6-8 hour we have setup redis ping for every minute.

**Comment by Krisa** [comment]
Has anything changed on that? It seems like now the connection gets lost every 5 minutes but is recreated (automatically) immediately (within half a second). That's one of my log (the first line is an `end` event, the second is the `reconnecting` event, the third is the `connect` event):
```
2015-12-07 12:50:59.082 - redis connection ended??
2015-12-07 12:50:59.286 - !!redis reconnecting { '0': { delay: 200, attempt: 1 } }
2015-12-07 12:50:59.509 - redis is now connected!
```

As said, I get now that every 5 minutes.

**Comment by BridgeAR** [comment]
@Amitosh1 node_redis 0.7.2 is not supported anymore and I highly recommend to use the newest version instead.

@Krisa this indicates some issues with your network. The socket loses it's connection to the server and is destroyed and recreated as soon as the socket connects to the server again.

**Comment by Krisa** [comment]
@BridgeAR I would believe an issue on my network, but the problem is that:
1- this happens every 5 minutes and 1 second with the regularity of a swiss clock
2- this happens both on my local computer (and network) and on Heroku

I'm fine to lose the connection for half a second every 5 minutes, and I'm especially happy that it reconnects so quickly but I'd like to understand whether it's expected and somehow I fear it's not the case.

Oh, and another thing like other people already mentioned before. If I "ping" regularly Redis (e.g. `redis.set('ping', 'pong');`, then I can't see any lost of connection.

**Comment by Krisa** [comment]
That being said, I can't see anymore this ETIMEDOUT issue (which I had too instead of this "auto-reconnect")

**Comment by BridgeAR** [comment]
@Krisa this is weird. What Node.js version do you use and may I see a code-snipped from you?

**Comment by Krisa** [comment]
@BridgeAR I'm using node v5.1.1
I have created a small snippet to reproduce the problem:
```javascript
'use strict';
const redis = require('redis'); 

var redisOptions = {
    url: 'redis://xxxxxxxxxxxxxxxxxxxxxxxxx.compute-1.amazonaws.com:xxxxx',
    retry_max_delay: 10000
};

var redisCache = redis.createClient(redisOptions.url, redisOptions);

redisCache.on('error', function(e) {
    console.error(new Date(), 'redis error', e);
});

redisCache.on('reconnecting', function() {
    console.warn(new Date(), 'redis reconnecting', arguments);
});

redisCache.on('connect', function() {
    console.log(new Date(), 'redis is now connected!');
});

redisCache.on('end', function() {
    console.error(new Date(), 'redis connection ended??');
});
```

which produces following output:
```
$ node test
Tue Dec 08 2015 11:30:24 GMT+0100 (CET) 'redis is now connected!'
Tue Dec 08 2015 11:35:25 GMT+0100 (CET) 'redis connection ended??'
Tue Dec 08 2015 11:35:25 GMT+0100 (CET) 'redis reconnecting' { '0': { delay: 200, attempt: 1 } }
Tue Dec 08 2015 11:35:25 GMT+0100 (CET) 'redis is now connected!'
Tue Dec 08 2015 11:40:26 GMT+0100 (CET) 'redis connection ended??'
Tue Dec 08 2015 11:40:26 GMT+0100 (CET) 'redis reconnecting' { '0': { delay: 200, attempt: 1 } }
Tue Dec 08 2015 11:40:26 GMT+0100 (CET) 'redis is now connected!'
```

**Comment by Krisa** [comment]
Adding following to the snippet above "solves" the problem:
```javascript
setInterval(function() {
    redisCache.set('ping', 'pong');
}, 1000 * 60 * 4);
```

**Comment by Krisa** [comment]
Sorry for that, I just found out, that this is caused actually by the Redis instance itself, and not by this module: https://devcenter.heroku.com/articles/heroku-redis#timeout

**Comment by BridgeAR** [comment]
@Krisa thanks for digging into this and reporting back :+1:
