### ISSUE TITLE
Double-wrapping of args leads to bogus "ERR wrong number of arguments for 'eval' command" 

### ISSUE THREAD

**Issue by dshelepov** [NodeRedis/node_redis#682]
Version 0.12.1

I'm calling `redisClient.eval` with an array of args (doesn't matter which), but no callback.  The LUA script passed in must not be cached by Redis for the bug to trigger.  The library will first try EVALSHA, fail, and then go back to regular EVAL.  It will run the callback originally passed into `self.evalsha` (index.js, around line 1200):

    self.evalsha(args, function (err, reply) {
        if (err && /NOSCRIPT/.test(err.message)) {
            args[0] = source;
            eval_orig.call(self, args, callback);
        } else if (callback) {
            callback(err, reply);
        }
    });

To recap, at this time `args` contains my eval arguments, and `callback` is `undefined`.

`eval_orig.call()` will be routed to `RedisClient.prototype["eval"]`, defined as so (index.js, line ~990):

    RedisClient.prototype[command] = function (args, callback) {
        if (Array.isArray(args) && typeof callback === "function") {
            return this.send_command(command, args, callback);
        } else {
            return this.send_command(command, to_array(arguments));
        }
    };

Because we will fail `typeof callback === "function"` check, we'll get to the `else` clause.  `arguments` at this point contains 2 values: `arguments[0]` is the `args` collection from the previous stack frame, and `arguments[1]` is `callback`, which is `undefined`.  `to_array(arguments)` will convert `arguments` into an array of two members, the first of which is going to be the `args` array.  This seems wrong, and as the request propagates to Redis, "Error: ERR wrong number of arguments for 'eval' command" is generated" is thrown.

The workaround (possibly the correct fix) is to insert an `else if` clause into the second snippet, like so:

    RedisClient.prototype[command] = function (args, callback) {
        if (Array.isArray(args) && typeof callback === "function") {
            return this.send_command(command, args, callback);
        } else if (Array.isArray(args)) {
            return this.send_command(command, args);
        } else {
            return this.send_command(command, to_array(arguments));
        }
    };

This is the same issue as #321, but since that one is more than 2 years old, I'm going to open it again just to highlight that yes, the bug is still present and live, and can be easily encountered in production.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
This got fixed in v.2.0 and I highly recommend updating to that version as it fixed most issues people ran into.
