### ISSUE TITLE
client.sync() produces persistent/repeating command queue state error

### ISSUE THREAD

**Issue by danorton** [NodeRedis/node_redis#698]
Scenario:

&gt; **client.server_info.versions**
[ 2, 8, 18 ]
&gt; **client.sync()**
true
error event - undefined:undefined - Error: node_redis command queue state error. If you can reproduce this, please report it.
error event - undefined:undefined - Error: node_redis command queue state error. If you can reproduce this, please report it.
error event - undefined:undefined - Error: node_redis command queue state error. If you can reproduce this, please report it.
error event - undefined:undefined - Error: node_redis command queue state error. If you can reproduce this, please report it.
error event - undefined:undefined - Error: node_redis command queue state error. If you can reproduce this, please report it.
error event - undefined:undefined - Error: node_redis command queue state error. If you can reproduce this, please report it.
error event - undefined:undefined - Error: node_redis command queue state error. If you can reproduce this, please report it.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
I can't reproduce any queue state errors with 2.0 but there's a protocol error returned if I use another command after using sync. The js parser does not throw the error without returning buffers though => reopening.

@danorton is that correct behavior?

**Comment by BridgeAR** [comment]
The sync command is only used internally in redis and should not be used in any client. The command is used while syncing a slave to the master but this is done from redis itself.

The client can't handle the data returned from the sync command as it does not return valid RESP data (the newline is missing).
