### ISSUE TITLE
"Redis connection gone from end event" with twemproxy

### ISSUE THREAD

**Issue by silentroach** [NodeRedis/node_redis#704]
We use [TwemProxy](https://github.com/twitter/twemproxy) for sharding and it doesn't support "info" command, so we get "Redis connection gone from end event" immediately on connect.

It will be better to avoid "info" command call to check the connection is ready.

**Comment by mranney** [comment]
Unfortunately, redis-server has a strange behavior while loading a database from disk where it'll accept connections, but will block all work. The ready check give users some choice about how to handle that scenario.

What I'd prefer to see is some way to detect that we were behind twemproxy. Does it fail the INFO command in some unique way that makes it obvious we are talking to twemproxy?

**Comment by silentroach** [comment]
No, just drops the connection :(

```
Stream connected server:6370 id 1
Using default parser module: javascript
checking server ready state...
send server:6370 id 1: *1
$4
info

send_command buffered_writes: 0  should_buffer: false
Redis connection is gone from end event.
Retry connection in 255 ms
```

**Comment by mranney** [comment]
That is really annoying. Thanks for looking in to that.

Is there some other command we can send that will tell us for sure we are talking to haproxy?

**Comment by silentroach** [comment]
Seems like there is no way to detect it.
Why not just try to get some random key?

**Comment by brycebaril** [comment]
Are you using the `no_ready_check` option? This will inhibit sending the `INFO` command.

From the README:

* `no_ready_check`: defaults to `false`. When a connection is established to the Redis server, the server might still
be loading the database from disk.  While loading, the server not respond to any commands.  To work around this,
`node_redis` has a "ready check" which sends the `INFO` command to the server.  The response from the `INFO` command
indicates whether the server is ready for more commands.  When ready, `node_redis` emits a `ready` event.
Setting `no_ready_check` to `true` will inhibit this check.

**Comment by silentroach** [comment]
Yes, I use it now

**Comment by brycebaril** [comment]
If using `no_ready_check` isn't enough, I'm sure that it wouldn't be difficult to add an option (as much as I hate option bloat) that lets you specify an alternate command to run to check readiness -- the check is only performed in two places. If you're interested, give it a shot!

**Comment by mranney** [comment]
Any chance the twemproxy project would be amenable to implementing their own INFO command? That would solve this problem in a general case, once and for all.

**Comment by silentroach** [comment]
Twemproxy is about sharding by key between many servers so it is impossible to get info that can be different on each server.

**Comment by BridgeAR** [comment]
@silentroach please try version 2.0. That should likely fix your issue or at least print a better error message then before.

**Comment by silentroach** [comment]
Will try in a few days, thank you

**Comment by BridgeAR** [comment]
Ping @silentroach

**Comment by silentroach** [comment]
```bash
$ NODE_DEBUG=redis ./test
Hiredis parser not installed.
Stream connected twemproxy:6370 id 1
Using default parser module: javascript
connected
Checking server ready state...
Send twemproxy:6370 id 1: *1
$4
info

send_command buffered_writes: 0
Redis connection is gone from end event.
Retry connection in 200 ms
Retrying connection...
Stream connected twemproxy:6370 id 1
Using default parser module: javascript
connected
Checking server ready state...
Send twemproxy:6370 id 1: *1
$4
info
```
