### ISSUE TITLE
It is not possible to handle net.createConnection errors

### ISSUE THREAD

**Issue by xytis** [NodeRedis/node_redis#728]
There is no possible way to register `'error'` listener before `net.createConnection` is called.
This means that during initial connection appropriate code will never see errors like 'ECONNREFUSED' These errors will always get propagated to global scope, that means there is only one way to write a node.js app which can be started before redis server is to register global unhandled exception handler...

Possible solution: 
Pass event handlers to constructor via `options` hash

**Comment by grimborg** [comment]
Any news on this? Crashing when redis is unavailable is excessive. For now I'm switching to [ioredis](https://github.com/luin/ioredis), which doesn't have this problem.

**Comment by BridgeAR** [comment]
@grimborg do you have a reproducible test? I can't reproduce such an error.

**Comment by xytis** [comment]
To reproduce this error -- simply try connecting to invalid redis uri.

**Comment by BridgeAR** [comment]
@xytis In mocha the test works properly:
```js
client = redis.createClient('redis://test');
client.on('error', function (err) {
    console.log(err);
    done();
});
```
```
 { [Error: Redis connection to test:6379 failed - getaddrinfo ENOTFOUND test test:6379]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'test',
  host: 'test',
  port: 6379 }
```
What version do you use?

**Comment by xytis** [comment]
Try doing ECONNREFUSED. By specifying a valid connectable Url.

**Comment by xytis** [comment]
And, notice that the bug was opened waaaaaaaaay back. It might be that things got fixed eventually.

**Comment by BridgeAR** [comment]
@xytis ECONNREFUSED errors are catched by attached error handlers. Using a valid Uri results in reconnection attempts if the connection can't be established. If you want to prevent this, you'll have to use the `connect_timeout` option.

And even though this issue is very old, the way how this is handled did not really change in the meanwhile.

Could you provide me with a test case?

**Comment by BridgeAR** [comment]
Ping @xytis

**Comment by xytis** [comment]
I no longer can reproduce this error. It might have been a change in underlying `net.createConnection`, and I do not recall which version of Node I used when I encountered this problem.

**Comment by BridgeAR** [comment]
@xytis Thanks a lot for the info :)
