### ISSUE TITLE
Undocumented return type if Key doesn't exist?

### ISSUE THREAD

**Issue by r3wt** [NodeRedis/node_redis#731]
So what does `response` contain if the key doesn't exist? 

I'm trying to read in a PHP session from redis and unserialize it with PHPunserialize library, but if the session doesn't exist, unserializing it throws an exception. so what is the return type for a key that doesn't exist? `undefined`? `null` ? something else? ive had to temporarily wrap it in a try/catch block until i can figure it out

```js
function getClientSession(s_id){
	var key = "PHPREDIS_SESSION:"+s_id;
	var o;//the session object
	redis.get(key,function(error,res){
		if(error){
			return false;
		}
		try{
		o = PHPunserializer.unserializeSession(res);	
		}
		catch(e){
			return false;
		}
	});
	return o || false;
}
```

**Comment by m-reiniger** [comment]
It will return null.

You can easily check with:

```
if (res) {
    // do smth with res
}
```

Also note that your last line: 
```
return o || false;
```
will always return false because redis.get is async and o will be null at the time you return it.

**Comment by r3wt** [comment]
So how can I return the session object

**Comment by m-reiniger** [comment]
I don't mean to be rude, but that is actually basic javascript knowledge and here is not the place for a how to on javascript callbacks. 

But for starters you should read into how javascript callbacks (the internet is full of it) work and while you are at it, take a look at promises too. :)

**Comment by blainsmith** [comment]
@r3wt You have a async problem with your code. Your `getClientSession` function is returning faster than `redis.get()` is getting the value, hence this function will always return `false`.

Definitely look into javascript callbacks and promises and that will solve your issue.
