### ISSUE TITLE
Retry dies if constructor was used.

### ISSUE THREAD

**Issue by greim** [NodeRedis/node_redis#735]
[edit] The basic problem I'm having is that my process dies occasionally due to an un-handleable exception originating in this library. Below is the root cause of the error, as far as I can tell.

`createClient()` adds a `connectionOption` property to the client as a side effect ([index.js#L1272](https://github.com/mranney/node_redis/blob/master/index.js#L1272)), which is presumed by the `connection_gone()` method. ([index.js#L535](https://github.com/mranney/node_redis/blob/master/index.js#L535))

Some libraries (e.g. [redis-sentinel](https://github.com/ortoo/node-redis-sentinel/blob/master/index.js#L64)) appear to use the `new RedisClient()` constructor directly, in which case a `connectionOption` property is never added. So during retry ([index.js#L521-L538](https://github.com/mranney/node_redis/blob/master/index.js#L521-L538)) an options arg is passed to `net.createConnection()` containing no port which causes an uncaught exception to bubble up and crash the process.

At least, that's what I *think* is happening. Here's the exception trace.

```
net.js:901
throw new RangeError('port should be > 0 and < 65536: ' + port);
^
RangeError: port should be > 0 and < 65536: 0
at Socket.connect (net.js:901:13)
at Object.exports.connect.exports.createConnection (net.js:92:35)
at null._onTimeout (/foo/node_modules/redis/index.js:535:27)
at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by greim** [comment]
(0.12 on Linux)

**Comment by aphorise** [comment]
I'm experiancing similar symptoms. Can this also be related to the ```redis``` npm?

**Comment by bcoe** [comment]
@greim it looks like this has been fixed upstream in redis-sentinel, do you think there's any work we should do on our end for this?

The problem is, if `net.Socket` was used externally and passed into node-redis:

```
var netClient = new net.Socket();
var cclient = new redis.RedisClient(netClient);
cclient.stream.connect(config.PORT, config.HOST[ip]);
```

It's actually fairly hard to introspect the options that were used to create the socket connection.

**Comment by BridgeAR** [comment]
No response => closing
