### ISSUE TITLE
Redis command "pubsub numsub" replies with 1 even when there are more subscribers

### ISSUE THREAD

**Issue by imegory** [NodeRedis/node_redis#740]
I am comparing two results: 1. By issuing "pubsub numsub channel_name" from redis-cli; and 2. using node_redis with the same command (e.g., redisCLient.pubsub('numsub', channel_name, function(){...})).

In a particular case I am testing: by using redis-cli I am getting 2, and via node_redis I am getting 1.

FYI: when the result is 0, I am getting 0 using either method.

**Comment by BridgeAR** [comment]
@imegory it would be great if you'd provide a test case for this.
