### ISSUE TITLE
Error Error: ERR unknown command 'config'

### ISSUE THREAD

**Issue by b96705008** [NodeRedis/node_redis#743]
When I create a node redis client using elasticache with redis (aws), it trigger this problem.
Is there already any solution to this issue?

**Comment by BridgeAR** [comment]
The following should work without any issues:

```js
client.CONFIG('GET', '*max-*-entries*', function(err, value) {
    console.log(err, value);
});
```

If you still experience difficulties, please reopen the issue including your code, as it's difficult to tell what's wrong without your code.

**Comment by yiurenma** [comment]
I use the redisClient on windows10, I face the same problem as the title showing. I just input the host , port and password for the config.  And then the problems shows. There is no code related to it . Could you pls kindly suggest where the wrong is ?

**Comment by BridgeAR** [comment]
The error is returned by Redis and it seems like your used Redis server does not expose the config command (e.g. it's renamed or not exposed at all). If it's the "info" command that fails, please use the `noReadyCheck` option.

**Comment by ilyashev** [comment]
I'm seeing the same problem when trying to connect to Redis on Heroku. Is there any known workaround?

**Comment by pikitgb** [comment]
@ilyashev did you found a solution to this issue ? I'm facing the same problem with Kue in Heroku

**Comment by stockholmux** [comment]
@ilyashev and @pikitgb Most cloud vendors don't support CONFIG or other admin commands.

**Comment by zanemcca** [comment]
For those on Elasticache I used this guide https://aws.amazon.com/premiumsupport/knowledge-center/elasticache-redis-keyspace-notifications/ and it worked.
