### ISSUE TITLE
problem with String append

### ISSUE THREAD

**Issue by smiley-boy** [NodeRedis/node_redis#760]
var redis = require("redis"),
        client = redis.createClient();

         var c = "hello 
          world";

         client.append("ssttring", c, redis.print);

dosen't work but if I change the line break with \n it works

**Comment by brycebaril** [comment]
As far as I can tell this just looks like an error with mishandled multi-line strings in JavaScript. Will need more information (what is the error/incorrect behavior) to diagnose further.
