### ISSUE TITLE
does node_redis solve this problem?

### ISSUE THREAD

**Issue by ORESoftware** [NodeRedis/node_redis#763]
I am using the standard core Cluster NPM module

It works great for HTTP requests. But with Redis pub/sub over TCP, each and every slave process will respond to the request, which is bad - the issue is described here:

https://github.com/antirez/redis/issues/1137

does node_redis have a solution to this problem?

**Comment by brycebaril** [comment]
Nope, as of yet this library does not have built-in cluster support.

**Comment by BridgeAR** [comment]
If node_redis is going to implement cluster support this is going to be published in the changelog. Since this is not likely to happen soon I'll close this issue.

**Comment by ORESoftware** [comment]
ok sure np thanks
