### ISSUE TITLE
Issue publishing to channel with multiple clients

### ISSUE THREAD

**Issue by oninea** [NodeRedis/node_redis#766]
When publishing to a channel with multiple clients subscribing from it, some of the clients inexplicably stop consuming from the channel. For those clients that get 'stuck', the connection remains established but no messages reach the client anymore. In fact, the output buffer for those connections keep growing until they eventually get dropped by the hard limit.

Multiple clients are subscribing this way:
```
var client = redis.createClient(port,host);
var sub_count = 0;
client.on("message", function(channel, message){
	sub_count++;
	console.log(channel + ' [' + sub_count + '] : ' + message);
});
client.subscribe('some_channel');
```
A single publisher publishes this way:
```
var client = redis.createClient(port,host);
for(var i = 1; i <= 1000; i++) {
	client.publish('some_channel','hello');
}
```
It is important to note that using redis-cli to publish the same amount of messages to the channel does not cause the subscribing clients to get 'stuck'. It is only when node-redis is used to publish that this issue surfaces.

The versions used are:
```
$ redis-server --version
Redis server v=2.8.14 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=a048aae8ec6d710c

$ node --version
v0.12.4

$ npm list redis
└── redis@0.12.1
```

**Comment by BridgeAR** [comment]
@oninea I can't reproduce this. Could you write a small test for it? :)

**Comment by BridgeAR** [comment]
As I can't reproduce this, I guess this is either already fixed or there was something else wrong.

The sentence about "the output buffer [...] keep[s] growing" seems to me that you mean the parser output, so I guess you used the js parser and there was an error.
The parser got a main refactoring in the meanwhile and does very likely not have any issues left anymore.
