### ISSUE TITLE
multi.exec is slow

### ISSUE THREAD

**Issue by rain1017** [NodeRedis/node_redis#767]
multi.exec is slow even if I only call 1 set

set  32000/s
multi (with one set) 12000/s

**Comment by bcoe** [comment]
@rain1017 this sounds odd, could you share some sample code that's causing this issue for you?

**Comment by simontabor** [comment]
This *might* be quite a simple one...

Running a single command `SET key value`... sends just that to redis.

Wrapping it with a multi means that immediately increases to 3 commands. You're seeing a 2.6x reduction in speed by sending 3x the commands (a `MULTI` and an `EXEC` along with the `SET`).

To prevent this slowdown in the past, I've added a check to read the multi queue length, and if it's only one command just execute that without the multi (it would be fairly easy to add this to node_redis)

**Comment by stockholmux** [comment]
@simontabor Makes sense and cool solution. +1

If this was optimized my the module, I imagine the response would have to emulate a multi bulk response (e.g. wrapping it in an array), but otherwise this would be amazing for some of my use cases.

**Comment by BridgeAR** [comment]
Closing this as we can't do a lot to speed this up. I'll slightly optimize statements and check IRHydra2 if I find the time for it but this has no high priority right now. There is a feature request to handle a single multi operation as a normal set. This might be a good solution for you if it'll be implemented at some point @rain1017

**Comment by BridgeAR** [comment]
@rain1017 .exec is going to be very fast from v.2.2.0 on if you use it for multiple commands. If you do not need any transactions you can also use .batch from v.2.2.0 on (it'll be released in the next 24h).
