### ISSUE TITLE
Requiring a callback for  Redis sub.subscribe()

### ISSUE THREAD

**Issue by ORESoftware** [NodeRedis/node_redis#770]
Hi guys:

I put this question on SO and got a nice answer:
http://stackoverflow.com/questions/30946799/redis-pub-sub-same-process-listening-to-one-channel/

frankly, it is my firm belief that your library (and many many others) should require a callback for a subscribe call

that means this should throw an error:

```javascript
var redis = require('redis');
var client  = redis.createClient();
client.subscribe('my_channel'); //error
```

again and again and again and AGAIN, there are libraries that deceive us by looking synchronous but being async. I have fallen prey to the same thing many times, so either I am completely stupid or you have a human factors problem on your hands.

IMO, you should require a callback like this:

```javascript
client.subscribe('my_channel', function(channel,count){

});
```

if users want their own events, then they can add it like so:

```javascript
client.subscribe('my_channel', function(channel,count){
    ee.emit(client + 'is subscribed to' + channel);
});

ee.on('client is subscribed to channel'....)
```

what do you think?

**Comment by ORESoftware** [comment]
Also, when I do put in a callback to the subscribe call:

```javascript
  rcSub.subscribe('redis_channel@test_overall_health',function(hello,channel,count){
                    log.info(hello,'rcSub is subscribed to channel:',channel,'with a count of:',count);
                    rcPub.publish('redis_channel@test_overall_health', JSON.stringify(message));
                });
```

the parameters that come back do not seem to follow the principal of least surprise, in other words, I have no idea what they are or which order they should be in etc.

**Comment by dirkbonhomme** [comment]
The way in which callbacks are used and the order of arguments is very well documented in the readme (or the redis docs) and are pretty consistent throughout this project afaik. Once you know how to use one command, it's fairly easy to predict how other commands work.

Always assume that all IO operations in Node.js are async and thus either return a promise or expect a callback. In this case there's absolutely no reason for subscribe() to require a callback.

**Comment by ORESoftware** [comment]
it should require a callback. you are completely misunderestimating the amount of pain and suffering in the whole community due to async functions appearing synchronous. not everybody has time to look up the api for every library. nor is it always obvious what may be sync or async.

take a look at this question:

http://stackoverflow.com/questions/30946799/redis-pub-sub-same-process-listening-to-one-channel

LET ME GIVE YOU AN EXAMPLE

some functions look async but are in fact sync, they register a callback, and then move on

however, with this library, the call has to go down the network and make it's way to Redis, and then return with the response. Clearly, it's an async function. It should be obvious to everyone with a brain.
But it's not.

all you need to do is this:

var noop = function(){};
rcSub.subscribe('redis_channel@test_overall_health',noop);


what happens when someone does this

```javascript
var redis = require('redis');

var publisher = redis.createClient(),
    subscriber = redis.createClient(),
    message = 'testing123';

subscriber.subscribe('redis_channel@test_overall_health');

subscriber.on('message', function (channel, message) {
    console.log(channel, message);
});

///a long block of synchronous code

subscriber.on('subscribe', function (channel, count) {
    publisher.publish('redis_channel@test_overall_health', message);
});
```

in that case, the long block of code will prevent the on('subscribe') event from being captured, because from my knowledge Redis does fire and forget

it's too late anyway, the damage is done and backwards compatibility will not allow you to require the callback. good luck. if I ever write a library like this I will require the callback.

**Comment by dirkbonhomme** [comment]
> you are completely misunderestimating the amount of pain and suffering in the whole community

I consider myself to be "part of this community" for quite a while now and have never seen someone act so offensive about something that's considered a best practice in the Node.js/JS world. IO calls are by their very nature async and callbacks are more often than not optional.

This is especially true when we look at Redis: none of the commands that describe an action (subscribe, add, incr ..) require a callback simply because I don't always care if they've been executed successfully.

You could argue that calls like get, hget etc should require a callback as they return some value but even that is up for debate. This library is set up to be quite "command agnostic" which means that it will treat all Redis commands in a similar way:
- first arguments are sent to Redis
- the last argument is the optional callback, if its type is a function.

I'm sure you mean well but this is the second library I follow where you create a ticket and criticize the very basics of the library. Please create a more constructive ticket next time and I'm sure that whoever maintains the repository will listen and maybe even update their codebase :)

**Comment by ORESoftware** [comment]
apologies for being offensive. I get worked up about this. we are talking about hours of my life and others people's lives spent less productively than otherwise. 

anyway back to the topic

that was my point here. not all I/O calls are fully async

let me give you an example:

```javascript
var bool = null;

function Async(callback){
bool = true;  //registers something synchronously/immediately
setTimeout(function(){
callback('done');
}
}

function Async(callback){
setTimeout(function(){
var value = 3;
callback(value);
}
}
```

I am sure you see the difference. IMO the latter cases MUST require a callback. I am not saying this is your fault. Node.js got it wrong by not enforcing this type of thing.


Also, you did not comment on this scenario:


```javascript
var redis = require('redis');

var publisher = redis.createClient(),
    subscriber = redis.createClient(),
    message = 'testing123';

subscriber.subscribe('redis_channel');

subscriber.on('message', function (channel, message) {
    console.log(channel, message);
});

///***a long block of synchronous code***

subscriber.on('subscribe', function (channel, count) {
    publisher.publish('redis_channel', message);
});

```

I doubt people will make that mistake very often, but it could happen.

**Comment by ORESoftware** [comment]
one thing the Node.js community could do is print warnings if no callback is passed. I just don't see a good reason why the subscriber.on is separate from the subscribe() function, why keep it separated?

**Comment by dirkbonhomme** [comment]
One use case would be that 1 part of the code is responsible for the `subscriber.subscribe(..)` call while many different parts can listen on incoming data by using `subscriber.on('message', ...)` without having to worry about being subscribed or not.

If you require the callback, you are forced to use your own event emitter or some workaround.

**Comment by ORESoftware** [comment]
a couple thoughts. 

(1) there is no reason why you couldn't fire the call back and fire the event - I mean, what do you do if someone passes a callback into the subscribe function? do you not fire the event or do you? or does not even accept a callback...?
(2) I think it's better to stick to the callback format, and have people implement an event-emitter on their own, if they need one. usually event-emitters are overkill.

usually we just need the callback. eventemitters are for when you need two or more places in the code to see the message. most of the time we just need one, and that's why callbacks are more common. I am not super familiar with event emitters- it could be they have other advantages.

**Comment by ORESoftware** [comment]
feel free to close this...maybe if you get another comment/complaint about it you can reconsider, but I don't really wish to be all that irritating.

**Comment by brycebaril** [comment]
Hi @ORESoftware -- sorry about your confusion, but generally it is not a great practice in Node to assume a callback in a function signature matches 1:1 with asynchronous behavior.

e.g.:
```
function foo(data, cb) {
  // calls callback synchronously
  cb()
}

foo("abcd", function () { /* this is not asynchronous */ })
```

I understand what you're getting at about the potential for confusion between synchronous, asynchronous, and mixed sync/async being hard for developers, but I'm not convinced that requiring callbacks would help the issue or that this library should be some sort of agent for change on something that you acknowledge is a complaint with the broader ecosystem.

Best practice here, however, is to provide a callback to `subscribe` as the error handling for asynchronous events is done in the callback. If an error occurs without a callback an `unhandledException` will be thrown. In full applications, all node_redis commands should rightfully have callbacks.

There are a large class of scripts that use this library though which are simple maintenance or non-critical tools for querying or updating state. I think that the callback being optional was primarily a way to simplify the creation and overhead of creating simple things like that.

**Comment by ORESoftware** [comment]
Ok, I agree. All I can ask is this: all you need to do is to have your examples using the callback. People need to know that the subscription is async. You don't need to require the callback, if it's returning an event emitter. However to your point of error handling being in the callback, I am not sure about this lib, but usually that's handled in an on('error') event handler right?

**Comment by gggauravgandhi** [comment]
@ORESoftware 
I was also looking a way to do some work on subscribe/unsubscribe callback,  we can achieve using events.
Try following code, do let me know if requires more explanations.

```
var redis = require('redis');

var publisher = redis.createClient(),
    subscriber = redis.createClient();

subscriber.subscribe('random');

subscriber.on('message', function (channel, message) {
    console.log(channel, message);
});

subscriber.on('subscribe', function (channel, count) {
	console.log("Sub done");
	publisher.publish('random', 'Subscribed done, waiting for unsubscribe !');
	subscriber.unsubscribe('redis_channel@test_overall_health');
});

subscriber.on('unsubscribe', function (channel, count) {
	console.log("Unsub done")
});
```
