### ISSUE TITLE
redis.createServer fails on CircleCI builds if you don't have {no_ready_check:true} options

### ISSUE THREAD

**Issue by jamiis** [NodeRedis/node_redis#774]
Sorry I don't have more info but this bug took me all day to find. I don't even know if it's a bug but it should probably be documented somewhere

**Comment by mranney** [comment]
Yeah, this is a bummer. I don't know the details of this one, but some environments really do not like the ready check. I wish we didn't need that, but I'm not sure how else to know if a connection has a valid redis-server that's not loading the snapshot.

**Comment by BridgeAR** [comment]
@jamiis this should be fixed by 025c65c614929a26ab90033c4c7a5ecd312487c4. Would you be so kind and verify that? Besides: could you give me some insight into your setup? I'd like to have a test for this and without any further info it's difficult to go on.

**Comment by kevinburkeshyp** [comment]
@jamiis @mranney does this reproduce itself every time? we're running into an issue where maybe 1 out of every 1000 FLUSHALL commands to CircleCI times out with no error message.

**Comment by jamiis** [comment]
@mranney @kevinburkeshyp @BridgeAR unfortunately I moved companies and don't have access to that env anymore
