### ISSUE TITLE
createClient(options) example in README.md is incorrect

### ISSUE THREAD

**Issue by Downchuck** [NodeRedis/node_redis#781]
https://github.com/NodeRedis/node_redis#overloading

This shows createClient(options) as an option, but the example does not reflect it, as it still shows host and port as arguments. Are those options?

**Comment by Downchuck** [comment]
Would be nice to allow "port" and "host" as options in the connection object.

**Comment by stockholmux** [comment]
I think that section (among many) of the `README.md` is a little unclear, but maybe not incorrect. 

You can definitely use `redis.createClient({ ... options... })` and it will connect with the default redis connection (127.0.0.1 / 6379) and apply options.

As an example:
```
var
  redis   = require("redis"),
  client  = redis.createClient({return_buffers : true});

console.log(client.connectionOption);
console.log(client.options);
client.quit();
```

Will result in:
```
{ port: 6379, host: '127.0.0.1', family: 4 }
{ return_buffers: true,
  socket_nodelay: true,
  socket_keepalive: true }
```

If you omit `{return_buffers : true}` then the the second object logged will not have `return_buffers`.

As for port/host in the options object, it isn't a bad idea, but I think that would be a feature request - it may be some time before the team gets to anything like that. 

Does this answer your question?

**Comment by Downchuck** [comment]
You're right, it's simply unclear -- it apears from the code that
supporting a host/port argument would be trivial task .

**Comment by stockholmux** [comment]
@Downchuck We modified the README for clarity - hope it helps!

**Comment by dealslama** [comment]
How can I pass multiple host, port in creatclient method , I;ve a cluster
