### ISSUE TITLE
[Question] Redis Replication

### ISSUE THREAD

**Issue by MrMMorris** [NodeRedis/node_redis#784]
Pardon my sysadmin ignorance, but if I have a Redis master/slave setup, is it possible to point the node client to multiple instances like with mongo urls? or do you handle that some other way?

Thanks!

**Comment by raydog** [comment]
The client doesn't handle multiple connections automatically. What were you wanting to do with multiple connections? If you were wanting to send some queries to go to the master, and some to the slave, that can easily be done with 2 clients. However, if you were wanting this to behave more like mongo WRT failover behavior, you should look into [redis-sentinel](http://redis.io/topics/sentinel).

**Comment by MrMMorris** [comment]
@raydog but would I be able to use sentinel with node_redis?

**Comment by raydog** [comment]
You would be building node_redis clients using information from sentinel. There are several projects that would help you do that. My favorite is [simple-sentinel](https://github.com/Vungle/simple-sentinel), but do note: I am pretty biased source on that, since I wrote it. :P
