### ISSUE TITLE
Issues Cleanup

### ISSUE THREAD

**Issue by blainsmith** [NodeRedis/node_redis#792]
@NodeRedis/contributors @NodeRedis/owners I started sifting through some of the open issues to clean them up. I wanted to get on everyone's radar about how we should start, especially with some of the really old ones that are still open.

Anything older than 6 months just delete? I wanted to make sure some of the issues are covered by recent releases, but it looks like the releases are a outdated as well, but thats another topic. Looks like we are on track to get the test suite/CI/releases on the right path anyway.

**Comment by simontabor** [comment]
I think anything older than 6 months is a good idea - unless it should obviously still be open. 

Otherwise, if the issue is still... an issue... the original reporter can re-open it, or it'll be reported again (hopefully).

**Comment by stockholmux** [comment]
Sounds good to me.

Perhaps a boilerplate response about re-opening if it is still an issue? With so little activity for so long, some people have been patiently waiting and a random closing without explanation would be hard to swallow.

**Comment by blainsmith** [comment]
Yes, a boilerplate would be good. Something like:

"In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly."

**Comment by erinspice** [comment]
Sounds great to me.

**Comment by blainsmith** [comment]
Ok, don't hate me if I spammed the crap out of anyone haha. I got us down to 28 open issues that have been created within the last 6 months. Hopefully this alleviates some of the issue anxiety! :stuck_out_tongue_winking_eye:
