### ISSUE TITLE
redis.js.org

### ISSUE THREAD

**Issue by blainsmith** [NodeRedis/node_redis#795]
I got confirmation that redis.js.org was added and is now pulling the README for a documentation site. One downside I see is since its a [javascript file](http://ricostacruz.com/flatdoc/) pulling in the contents we won't get much SEO cred. There are some other options out there for generating sites so its Google-able. One option is https://github.com/millermedeiros/mdoc. Then we can trim down the README to the highlights and direct people to the doc site for more detailed info.

At least we have a doc site running on GitHub pages. http://redis.js.org

**Comment by bcoe** [comment]
@blainsmith this looks great to me :+1:

I've added it as the project's website -- if you're ever bored would love to get this setup for [yargs](https://github.com/bcoe/yargs) too.

**Comment by blainsmith** [comment]
Not a prob @bcoe! Would be happy to. I'll make an issue of there for us to collaborate on it.
