### ISSUE TITLE
possbile to bundle redis client in the browser

### ISSUE THREAD

**Issue by kulicuu** [NodeRedis/node_redis#797]
Hi, I've been doing R&D on web-apps, and wanted to look into what it would take to bundle this redis-client module into a webpack-built browser application.

I had some idea that maybe, given the pub/sub capabilities and the Lua capabilities, that a redis/disque system could serve in the place of a realtime/websockets-esque web-server.  
(serving the static assets constituting the app would be handled by an eviscerated server or even pure-CDN)

So, I'm adding this partly as a feature request, but also just looking for feedback on what it would take to implement, potential problems etc.

Hiredis seems to be an obstacle but I'm not sure how much of one.

[edit]  found this
http://stackoverflow.com/questions/6311984/connecting-directly-to-redis-with-client-side-javascript

**Comment by kulicuu** [comment]
https://github.com/luin/ioredis/issues/136

**Comment by stockholmux** [comment]
Yep. I was going to suggest Webdis. Porting this module would be counter-productive but a syntax compatible front-end library would be cool (and I don't think exists).
