### ISSUE TITLE
let's release version 1.0.0 of node_redis

### ISSUE THREAD

**Issue by bcoe** [NodeRedis/node_redis#803]
Given the recent hard work the community has put into node_redis, I think we're in a good position to push a release out the door.

How do people feel about labeling this `1.0.0` to help minimize disruption to existing node_redis users (we've moved a few bits around)?

The major client-facing features going out the door with this release are:

https://github.com/NodeRedis/node_redis/pull/658 thanks @kuwabarahiroshi, this pull gives `createClient` URL-parsing functionality a pretty killer feature in my opinion.

https://github.com/NodeRedis/node_redis/commit/208b7874bf62344da9a0b39cb85189058830e718 thanks  @BridgeAR, fixes a regression with `createClient`.

https://github.com/NodeRedis/node_redis/pull/749 thanks @danielbprice, fixes a long standing bug that would have caused node_redis to crash when reconnecting in monitoring mode.

Along with these client-facing features, there has been a lot of work done on the node_redis tests:

@erinspice and @bcoe moved the test-suite over to mocha from a hand-rolled approach:

https://github.com/NodeRedis/node_redis/pull/793

this should make it much easier for future contributors to jump into the codebase.

We've also got tests running again on the newest builds of iojs :tada:

https://github.com/NodeRedis/node_redis/pull/800

Any other new features that we should pay homage to in the changelog? any objections to bumping node_redis to `1.0.0` and adhering to modern thought leadership with regards to semver moving forward?

CC: @brycebaril, @blainsmith, @mranney

**Comment by brycebaril** [comment]
Sounds good to me

**Comment by erinspice** [comment]
Great work, everybody!

**Comment by bcoe** [comment]
How does this sound to everyone?

https://github.com/NodeRedis/node_redis/pull/804/files

If everyone is cool with it, I'll release this to a `next` tag on npm and test with some of my projects.

**Comment by blainsmith** [comment]
:+1: and thanks for the commit mention haha.

I am excited to be apart of this. Good work everyone! High fives all around!

**Comment by erinspice** [comment]
LGTM.

**Comment by bcoe** [comment]
@erinspice @brycebaril @blainsmith give this a shot:

`npm install redis@next`

If it passes smoke tests, let's promote `next` to `latest` sometime early in the week.

**Comment by raydog** [comment]
1.0.0 sounds good. There was also #733, which fixed multi/exec behavior with detect_buffers enabled. (Not to get too self-promotey... :P)

**Comment by bcoe** [comment]
@raydog :+1: I'll amend the changelog.

**Comment by bcoe** [comment]
`redis@1.0.0` is released: https://www.npmjs.com/package/redis

**Comment by kuwabarahiroshi** [comment]
Documentation for Heroku Redis and Redis Cloud was successfully updated :-)
https://devcenter.heroku.com/articles/heroku-redis#connecting-in-node-js
https://devcenter.heroku.com/articles/rediscloud#using-redis-from-node-js

but not yet RedisToGo
https://devcenter.heroku.com/articles/redistogo#using-with-node-js
