### ISSUE TITLE
redisClient.quit() silently breaks the application

### ISSUE THREAD

**Issue by akshayjha28** [NodeRedis/node_redis#810]
I am using then-redis.

The issue is on quiting a connection after all the tasks are done. The code breaks silently without any notification or logs.

It stops the application to run.

Please help

**Comment by brycebaril** [comment]
To quit after all tasks are done what you want is `client.unref()` -- It will discount the client's connection from the refcounter and thus when it is the only continuation left, allow your application to exit.

**Comment by akshayjha28** [comment]
Using the unref() METHOD gives error - undefined is not a function.

I believe it is a version issue

I am using then-redis package.
version : 1.3.0

**Comment by brycebaril** [comment]
You may want to ask here: https://github.com/mjackson/then-redis

**Comment by EugeneKrimpson** [comment]
You need to upgrade your version of Redis to access the commands used by Redis to close connections.

**Comment by BridgeAR** [comment]
Closing as it does not seem to be an issue with node-redis.

**Comment by akshayjha28** [comment]
HI
I have changed my package from then-redis to node_redis.

As per the documentation it says end() and quit() methods are available but I am not able to find them in any file of the package

Please can you help

**Comment by BridgeAR** [comment]
The .end function is in the index.js file and.quit is a redis command. Those are added to the redisClient by default.
