### ISSUE TITLE
Module for message passing and queueing via pop/push on Redis lists

### ISSUE THREAD

**Issue by objectiveSee** [NodeRedis/node_redis#827]
I wrote a module that blocks asynchronously until something is pushed into a Redis lists. This can be used as a messaging queue between servers or processes. You can "watch" Redis keys for something to pop. Here is an example usage of the module.

Let me know if this module is something you would like to see published on npm. Also let me know if something similar exists!

```js
var redisKeysToWatch = ['message_queue', 'secret_message_queue'];
var looper = new RedisLooper(redisClient, redisKeysToWatch);

looper.startWithCallback(function(channel, value) {
	// called each time BLPOP() returns with data. Channel = name of key that BLPOP was called on.
});
```

**Comment by BridgeAR** [comment]
@objectiveSee I'm not aware of something like that existing, but I did not check either.

If you already wrote that module, why not publish it? If someone thinks it's useful, that great, if not, that should not be an issue as you already did most of the work.
