### ISSUE TITLE
Problem with module in NodeJS 4.0.0

### ISSUE THREAD

**Issue by NikSmith** [NodeRedis/node_redis#828]
Hello. I have some problem with redis v1.0.0 and NodeJS 4.0.0
I use module in my app, but when I require redis in my code and this give me  process is terminate and return message:

Process finished with exit code 139

**Comment by brycebaril** [comment]
Are you using the hiredis module? If so, make sure you are on version `v0.4.1` and have run `npm rebuild` after upgrading Node.

**Comment by NikSmith** [comment]
Yes, problem was in hiredis module. Thank you.
