### ISSUE TITLE
How to verify which database is in use

### ISSUE THREAD

**Issue by silverbucket** [NodeRedis/node_redis#833]
The README very briefly (in an example comment) mentions that, in order to select which database to use, you can use the `client.select(dbnum, callback)` function. I've tried to do this, but still when I access client.server_info I don't see any properties which indicate I'm on anything but database `0`.

In fact the only thing that seems database related is the `db0` property:
`db0: 'keys=270,expires=0,avg_ttl=0'`

```
{ redis_version: '3.0.1',
  redis_git_sha1: '00000000',
  redis_git_dirty: '0',
  redis_build_id: 'bf58331b4c8133f5',
  redis_mode: 'standalone',
  os: 'Darwin 14.5.0 x86_64',
  arch_bits: '64',
  multiplexing_api: 'kqueue',
  gcc_version: '4.2.1',
  process_id: '17542',
  run_id: 'e83620c6f490767c17f9ed97dfa81f1cbb1a0b1c',
  tcp_port: '6379',
  uptime_in_seconds: '2553',
  uptime_in_days: '0',
  hz: '10',
  lru_clock: '15943383',
  config_file: '/usr/local/etc/redis.conf',
  connected_clients: '3',
  client_longest_output_list: '0',
  client_biggest_input_buf: '0',
  blocked_clients: '0',
  used_memory: '1180576',
  used_memory_human: '1.13M',
  used_memory_rss: '2355200',
  used_memory_peak: '1248544',
  used_memory_peak_human: '1.19M',
  used_memory_lua: '35840',
  mem_fragmentation_ratio: '1.99',
  mem_allocator: 'libc',
  loading: '0',
  rdb_changes_since_last_save: '27',
  rdb_bgsave_in_progress: '0',
  rdb_last_save_time: '1442006670',
  rdb_last_bgsave_status: 'ok',
  rdb_last_bgsave_time_sec: '0',
  rdb_current_bgsave_time_sec: '-1',
  aof_enabled: '0',
  aof_rewrite_in_progress: '0',
  aof_rewrite_scheduled: '0',
  aof_last_rewrite_time_sec: '-1',
  aof_current_rewrite_time_sec: '-1',
  aof_last_bgrewrite_status: 'ok',
  aof_last_write_status: 'ok',
  total_connections_received: '242',
  total_commands_processed: '750',
  instantaneous_ops_per_sec: '3',
  total_net_input_bytes: '37302',
  total_net_output_bytes: '480365',
  instantaneous_input_kbps: '0.10',
  instantaneous_output_kbps: '4.04',
  rejected_connections: '0',
  sync_full: '0',
  sync_partial_ok: '0',
  sync_partial_err: '0',
  expired_keys: '0',
  evicted_keys: '0',
  keyspace_hits: '54',
  keyspace_misses: '0',
  pubsub_channels: '0',
  pubsub_patterns: '0',
  latest_fork_usec: '379',
  migrate_cached_sockets: '0',
  role: 'master',
  connected_slaves: '0',
  master_repl_offset: '0',
  repl_backlog_active: '0',
  repl_backlog_size: '1048576',
  repl_backlog_first_byte_offset: '0',
  repl_backlog_histlen: '0',
  used_cpu_sys: '0.75',
  used_cpu_user: '0.35',
  used_cpu_sys_children: '0.01',
  used_cpu_user_children: '0.01',
  cluster_enabled: '0',
  db0: 'keys=270,expires=0,avg_ttl=0',
  versions: [ 3, 0, 1 ] }
```

**Comment by simontabor** [comment]
have you tried using `client.selected_db`?

**Comment by silverbucket** [comment]
Hi @simontabor, just tried `client.selected_db` and it's set to `null`

**Comment by simontabor** [comment]
that'll mean the database in use is 0, so basically `var database = client.selected_db || 0;` should work fine

**Comment by silverbucket** [comment]
@simontabor So you change the database by setting a property? You don't call the `client.select` method?

**Comment by silverbucket** [comment]
I tried setting that property, with the same results. I'm unclear how setting a property would automatically select a different database though. This is one area of this module that has little to no documentation. Just this brief mention of a `client.select` method in the README:
```
// if you'd like to select database 3, instead of 0 (default), call
// client.select(3, function() { /* ... */ });
```

Which I tried to use, the callback is called, but nothing in `server_info` indicates we're on anything other than database 0.

**Comment by simontabor** [comment]
No, but the property is how to verify what database is in use. Use `client.select` to select the database still.

This should explain things...

```js
console.log(client.selected_db); // null (using db0)
client.set('key', 'val');

client.select(1, function() {
  console.log(client.selected_db); // 1
  client.set('key', 'val');
});
```

by setting a key in each database, db1 will now show up in the `info` response (`redis-cli info`).

I'm not too sure why you need to get what database is selected, to ensure that db1 is selected your code can be as simple as...

```js
client.select(1);
client.set('key', 'value');
```

**Comment by silverbucket** [comment]
Whenever I create a connection, and it doesn't seem to depend on whether I use `client.select` or not, the value of `client.selected_db` is never anything other than `null`.

```javascript
var client = redis.createClient(port, host, options);
console.log(client.selected_db); // null

client.on('error', function (err) {
  console.log('error: ', err);
});

client.on('ready', function () {
  console.log(client.selected_db); // null
  client.select(7, function (err) {
    console.log(client.selected_db); // null
    ...
  });
});
```

**Comment by silverbucket** [comment]
Ah, nevermind I spoke too soon. I just reviewed what I'd written and noticed a typo in the tests versus what I wrote here. It seems to work now (at least, `selected_db` is no longer null) Thanks!
