### ISSUE TITLE
error handling inside the callback?

### ISSUE THREAD

**Issue by McFarts** [NodeRedis/node_redis#859]
```
redis.hgetall('user:2', function(err, user) {
					if(user){
													socket.send('SERVER You are already connected from another location.');
													socket.close();
													throw(user.username+' is trying to login from two locations at the same time.');	
					}
 
 
});
```

I have `try` and `catch` blocks outside of the `hgetall`, but the throw is not being caught, and giving a fatal error.

Any idea how the functions inside the redis can have error catching?

I really don't want to use try/catch on every single hgetall function.

**Comment by BridgeAR** [comment]
@McFarts the redis call is async so you can't catch something from inside of the callback by wrapping the call into a try catch block.

You'll have to handle the error individually per callback that you create. But you might reuse the same callback to you only have to write that function once as in:

```js
var hgetallCallback = function (err, res) {
    if (res) {
        socket.send('SERVER You are already connected from another location.');
        socket.close();
        return;
    }
};

redis.hgetall('user:2', hgetallCallback);
// Somewhere else
redis.hgetall('user:5', hgetallCallback);
```

And don't throw if you do not have to. Just call the next function or stop going on from that point.

**Comment by McFarts** [comment]
Oh wow, that is a good idea.

Ha, thank you so much.
