### ISSUE TITLE
Does this model support  GEO  operation ?

### ISSUE THREAD

**Issue by pangguoming** [NodeRedis/node_redis#865]
when i run the function like:
 client.geoadd("mycity:21:0:location", "13.361389","38.115556","COR", redis.print);

i get the error: TypeError: undefined is not a function

Does this model support  GEO  operation ?

**Comment by BridgeAR** [comment]
node_redis supports .geoadd from version 2 on. Do you still use an older version?

**Comment by shahidmau** [comment]
How to use geoadd command? can you please provide example? I am using code

`client.geoadd("hotels 12.4844774 41.9184129 test1", redis.print);`

> ReplyError: ERR wrong number of arguments for 'geoadd' command

**Comment by BridgeAR** [comment]
You only provide a single argument and the string has to be split into three arguments.

**Comment by pangguoming** [comment]
ok,i got it

**Comment by aswin-ideas2it** [comment]
Following command creates a sorted set with given key-value. But I need unique id for each place name.Only scores and indexes are available in this geoadd. could you provide example with unique identifier for each place except score and index?? 
client.geoadd("GeoLocation:locations",  [151.19990000000007, -33.8863, [place_name]]
