### ISSUE TITLE
argument mutation - breaking old code

### ISSUE THREAD

**Issue by palamccc** [NodeRedis/node_redis#866]
v2.0.0 is mutating arguments, i think its anti-pattern, can you avoid it ?

    var fields = ["a","b","c"];
    hmget("key", fields, function(err,ret){
      console.log(fields); //prints ["key","a","b","c"]
    })

**Comment by BridgeAR** [comment]
I can't reproduce that.

**Comment by BridgeAR** [comment]
Hm, you are actually right. This is something I did not think about earlier. I'll fix it tomorrow. Can't find the time today.
