### ISSUE TITLE
Multi.hmset doesn't convert key to string

### ISSUE THREAD

**Issue by simontabor** [NodeRedis/node_redis#867]
https://github.com/NodeRedis/node_redis/blob/master/index.js#L994 runs after tmp_args is defined, so the code is useless.

https://github.com/NodeRedis/node_redis/blob/master/index.js#L967 is probably how it should be.

I think the statement just needs to be moved above tmp_args... correct?

**Comment by erinspice** [comment]
Looks like it.

**Comment by BridgeAR** [comment]
I dislike that behavior as you can see in [line 965](https://github.com/NodeRedis/node_redis/blob/master/index.js#L965) but it's fixed for now.
