### ISSUE TITLE
Error: node_redis command queue state error.

### ISSUE THREAD

**Issue by ile** [NodeRedis/node_redis#869]
I'm getting this error:

```
Error: node_redis command queue state error. If you can reproduce this, please report it.
  at RedisClient.return_reply (/data/derby-examples/node_modules/redis/index.js:659:19)
  at RedisClient.<anonymous> (/data/derby-examples/node_modules/redis/index.js:285:18)
  at doNTCallback0 (node.js:407:9)
  at process._tickCallback (node.js:336:13)
```

How to reproduce:

- Clone this https://github.com/derbyjs/derby-examples
- `npm install`
- make sure there is only `redis@2` installed in the tree root (remove others or use `npm@3` which may do this for you)
- `cd directory`
- `node server.js`
- Click the menu items on top - this should produce the error

In other words, the error happens in a [DerbyJS](http://derbyjs.com/) apps (all of them, `directory` is one of them and can be used as an example).

**Comment by BridgeAR** [comment]
The dependencies used seem to be really old. Hiredis 0.2.0 tried to compile while I ran `npm install` and the supported node_redis dependency from derby-starter is 0.12. So Switching to a new version won't help but all those outdated dependencies down the line have to be updated first (and there will very likely be breaking changes while doing so).

**Comment by ile** [comment]
I'm running hiredis 0.4.1 in another app and the same thing happens there.

I can make an updated example though.

**Comment by BridgeAR** [comment]
If you could write a standalone example, that would be great.

**Comment by BridgeAR** [comment]
Ping @ile

**Comment by ile** [comment]
Sorry I totally forgot this, I will try to do it soon, maybe tomorrow.

**Comment by psirenny** [comment]
@ile I ran into this as well in a derby app, were you able to create a standalone example?

**Comment by BridgeAR** [comment]
Derby removed the redis as dependency, so this should not be an issue anymore. Even though it would have been nice to know where that queue state error came from :)
