### ISSUE TITLE
Why so much memory using by node

### ISSUE THREAD

**Issue by prohalexey** [NodeRedis/node_redis#870]
var redis = require("redis"),
     client = redis.createClient();

for(var i =0 ; i < 1000000; i++){
     client.publish('channel_1', 'hello!');
}

after code is executed, node.js process allocate 1,2GB of memory; nothing happen; GC does not reduce allocated memory. if it will be 2 million messages or 4x500000, node crashes with memory error.

Node: 0.8.* ,  after this i trying 4.1.1 , but nothing changed
redis: 2.8 , work good 1Mb allocated memory.

**Comment by brycebaril** [comment]
This code synchronously creates a large number of strings `channel_1`, `"hello!"`, and functions and appends all of those to an array that grows to be 1e6 elements long.

If you select a number high enough, Node will be allocating too much JS heap and pass the V8 1.5gb limit.

Garbage collection can't run until these things aren't referenced anymore, which won't be until after the callbacks have fired for each of these functions.

Your best bet is to spread these out over multiple event-loop hops by doing something like batches of ~100 at a time.

**Comment by jdegger** [comment]
Just a general question about the behavior which relates to this.

 If I were to execute

```javascript
var redis = require("redis"),
    client = redis.createClient();

for (var i = 0; i < 1000000; i++) {

    // please note the 0ms timeout here
    setTimeout(function() {
        client.publish('channel_1', 'hello!');
    }, 0);

}
```
Would that give Node(-redis) the chance to run GC in between of cycles?

**Comment by BridgeAR** [comment]
@jdegger this should work, yes.

**Comment by BridgeAR** [comment]
After looking at it again, this is actually likely not going to work, as you create all timeouts sync with the same timeout. They might/should therefor be called in the same tick and this would result in just the same as @brycebaril already mentioned.
