### ISSUE TITLE
hgetall returns buffers?

### ISSUE THREAD

**Issue by mattador1** [NodeRedis/node_redis#871]
I have using this library for redis for solid amount of time I didn't change the node redis library version.
But when I go hgetall I get an object with fields which I can access, but the problem is that values of this fields are buffers? And in Redis values are strings, and in past I was getting strings and now I'm getting buffers. Only thing I changed is that redis isn't on same machine as app, so the latency in bigger. Why I don't get string? thank you.

**Comment by BridgeAR** [comment]
@mattador1 please provide me with some detail of your code. I tested this and everything works as it should in version 2.0. do you provide the values as buffers? If so, the return value will also be a buffer if you detect buffers.

**Comment by mattador1** [comment]
All ok i set return buffers flag..and I forgot about that small detail :)

Sorry
