### ISSUE TITLE
ZSCORE is not a function

### ISSUE THREAD

**Issue by nelsonic** [NodeRedis/node_redis#872]
before I "upgraded" to v2 of this module `zscore` used to work as [*expected*](http://redis.io/commands/ZSCORE). has it been removed?

**Comment by BridgeAR** [comment]
I just checked it and I can't reproduce any issues. The function is still present and the [redis example](redis.io/commands/ZSCORE) is working properly.
Could you please provide me with some of your code?

**Comment by nelsonic** [comment]
Hi @BridgeAR thanks for investigating.
Please See: https://travis-ci.org/nelsonic/arana/builds/82587176#L678-L681
Which refers to: https://github.com/nelsonic/arana/blob/8c239cf3a0b2c50e22b5213f66b8a4c70c741b21/lib/work_queue.js#L27
which calls `redisClient.zscore` which apparently is not a function anymore!!

**Comment by BridgeAR** [comment]
@nelsonic redisClient is not the connected client in your case, since you forgot to call the returned function from [redis-connection](https://github.com/nelsonic/arana/blob/8c239cf3a0b2c50e22b5213f66b8a4c70c741b21/lib/work_queue.js#L2).

**Comment by nelsonic** [comment]
Thanks again @BridgeAR I owe you one for spotting that bug! :+1:
