### ISSUE TITLE
spop gives wrong number of arguments

### ISSUE THREAD

**Issue by baao** [NodeRedis/node_redis#883]
I'm trying to use spop command to get multiple set members at once, similar to 

        let chain =  redis.multi();
        chain.spop('myset')
        .spop('myset')
        .spop('myset')
        .spop('myset')
        .spop('myset');
        chain.execAsync();
    
I think the quantity to pop addition to the command is pretty new (supported since redis > 3.0), can we expect to see support for this in node_redis in the near future?

Thanks!

**Comment by BridgeAR** [comment]
@baao this is already supported. As soon as you use a redis version that supports that command it'll also work in node_redis.
