### ISSUE TITLE
lrange is slow for large ranges

### ISSUE THREAD

**Issue by KyleAMathews** [NodeRedis/node_redis#885]
Fetching ~25,000 items takes around ~23 seconds or almost one second / 1000 items. Which seems incredibly slow. Looking at `top`, node.js is pegged at 100% cpu the entire time. I'm on node 0.10.40.

**Comment by KyleAMathews** [comment]
Hmmm... and I just tried only loading 1000 items and fetching that took 177ms... so there's a 5x slowdown somewhere between loading 1000 and 25,000 items.

**Comment by KyleAMathews** [comment]
Fetch time increases linearly until around 3000 items then turns exponential.

**Comment by BridgeAR** [comment]
@KyleAMathews I guess you use the js parser? If so, please try the hiredis parser as this should be a duplicate of #875.

**Comment by KyleAMathews** [comment]
Woah, that is tons faster. Dropped to 312ms for loading the ~25k items.

I guess I've always just used node-redis for simple gets/sets so hadn't run into situation where I really needed hiredis so forgot about it.

Thanks @BridgeAR!
