### ISSUE TITLE
Deleting list contents not working

### ISSUE THREAD

**Issue by diegoaguilar** [NodeRedis/node_redis#888]
I'm trying to delete a list keys by:

	redisClient.del('users:top:data:', function(err,result) {
		console.log(err,result);
	});

However it's returning 0 as result, the list exists, I also tried by `.lrem('users:top:data', 0, -1)` but got not results. None of these made the list get deleted or its elements dropped off.

**Comment by BridgeAR** [comment]
Redis does not support this. You have to provide a list of keys that you want to delete.

**Comment by BridgeAR** [comment]
However, if you really want to use this in production (I do not recommend it as it has likely side effects on heavy load) you can use EVAL and run del on wildcards.

This might work:
EVAL "return redis.call('del', unpack(redis.call('keys', ARGV[1])))" 0 prefix:*

**Comment by simontabor** [comment]
In production you should recursively SCAN the keys and delete them.

Both scan and del are blocking commands, but scan allows us to set a count so the server isn't blocked for too long at a time - tweak this value to optimise the block time vs round-trips

So...
```js
function scanDel(cursor, cb) {
  redis.scan(cursor, 'MATCH', 'users:top:data:*', 'COUNT', 100, function(err, resp) {
    if (err) return cb(err);
    var nextCursor = resp[0];
    var keys = resp[1].length;
    // no next cursor and no keys to delete
    if (!nextCursor && !keys.length) return cb(null);

    redis.del(keys, function(err) {
      if (err) return cb(err);
      if (!nextCursor) return cb(null);
      scanDel(nextCursor, cb);
    });
  });
}

scanDel(0, function(err) {
  // done!
});
```

**Comment by diegoaguilar** [comment]
@simontabor you're telling me that `SCAN` is better than a simple `DEL` in order of performance? Btw this list is really small, around 100 elements.

**Comment by simontabor** [comment]
You aren't able to run a simple `DEL` when you don't know the individual keys.

The EVAL example from @BridgeAR is using `redis.call('keys', ARGV[1])`- `keys` isn't a command that should be used in production.
