### ISSUE TITLE
reconnect doesn't work

### ISSUE THREAD

**Issue by wjjboy** [NodeRedis/node_redis#890]
when i use connect-redis 2.5.1 and node-redis 1.0.0 my app can reconnect redis server.
but when i update  connect-redis 3.0.0 and node-redis 2.2.3,the reconnect doesn't work.
is there some option change?

**Comment by BridgeAR** [comment]
This is an issue with connect-redis and the attempts option. I'll open a merge request there to fix that issue.

**Comment by BridgeAR** [comment]
@wjjboy connect-redis 3.0.1 was just released with the change and fixes your issue :)

**Comment by wjjboy** [comment]
3q
