### ISSUE TITLE
Redis keeps fire 'reconnecting' events

### ISSUE THREAD

**Issue by eli-zehavi** [NodeRedis/node_redis#892]
Hi,

I have node servers that connect to a Redis cluster on AWS (Elasticache).
There are times in the day which there is a huge latency from these servers. 

- The only type of commands these instances do (but do a lot) is sismember of some sets (some sets have ~50K items).
- On each instance, there are two workers (2 CPU's) under the cluster module.
- At peaks, there are ~40K sismember commands per minute (but I use the multi command to do only one round-trip per request, each request has in average 3 sismembers commands).
- At the same time, the 'reconnecting' events keep firing without stop in all our instances at the same time.
- These reconnecting attempts cause the node process to use the whole instance memory and then the load balancer removes it from service.

I've tried to use node 0.12.7, v.4.1.0, v4.1.1 and v4.2.0 but no success. I'm using node-redis v2.2.1. It keeps happening every day. 

Is this a problem with the Redis server itself, or with the code?

Thanks,

**Comment by BridgeAR** [comment]
The reconnecting event should only fire if node_redis is not connected to the redis server (e.g. connection lost). As soon as the client is able to reconnect the reconnection attempts should stop. Are you sure you use the old clients instead of creating new ones if a connection is lost?

If you could show me some code I might be able you help you better.

**Comment by eli-zehavi** [comment]
Hi @BridgeAR,

I have only one js file that creates the connections, it connect only at startup and then all other places in code that need Redis require this module:

<code>
api.master = redis.createClient(config.redis.master.port, config.redis.master.host);
</code>

Simple as that!

Is there any reason that the client will keep reconnecting constantly beside a problem in the Redis server?

**Comment by BridgeAR** [comment]
So you export the `api.master` and only use that connection?

And no, there should not be any reason besides a problem with the redis server to reconnect.

**Comment by eli-zehavi** [comment]
Yes, only one connection.

Of course, as I said I'm using the cluster module, 2 workers per instance, which open 2 separate connections. Do you know about any problems when using Redis client with the cluster module?

Or.... Any other ideas?

Thanks,

**Comment by BridgeAR** [comment]
I'm not aware of any issues but I never tried it. Did everything work with node_redis 1.0.0? There was a change in the way how we handle reconnections in v.2.
Besides that: What cluster module do you use? I can imagine that the cluster module has issues with node_redis v.2. I want to implement native cluster support in near future but still will still take a bit until that's done.

**Comment by eli-zehavi** [comment]
Hi, I jumped from node_redis v0.x directly to v2.x. There were problems with v0.x, too, so I don't think that changing the version to v1.x will help :/

**Comment by BridgeAR** [comment]
I also recommend using the newest version, I just wanted to find out what the issue might be and therefor if it would have worked with a older version I could have checked what changed.

I guess the main issue is the cluster module not working as expected.

**Comment by eli-zehavi** [comment]
Hi @BridgeAR, I've configured the cluster code to run only 1 worker, but the latency issues still occur. I also use hiredis as suggested in another issue page. Do you have another idea for these latencies?

Thanks,

**Comment by eli-zehavi** [comment]
@BridgeAR, when there are latencies there are huge TLSWrap objects in the node heap snapshot. Could it be because of node_redis, or it definitely something else?

**Comment by eli-zehavi** [comment]
I have a newrelic monitoring on my app, I pulled out some slow requests from their logs, we can see here there is a huge latency when talking to redis:

![redis-latency](https://cloud.githubusercontent.com/assets/10067209/10658938/5592b0c2-78a4-11e5-8faf-4f4b6725bff9.png)

**Comment by BridgeAR** [comment]
@eli-zehavi node_redis does not have inbuilt TLS support yet (2.3 is going to have it built in). So those objects are likely not coming from node_redis. And if the issue is that there's no connection between redis and node_redis you can't rely on the latency provided. All commands will be pushed into a offline queue and fired when the connection has been reestablished. That's why you likely see such huge latency.

I'm actually thinking about refactoring the offline queue to return an error that no connection could be established after a certain time has passed without any connection.

**Comment by eli-zehavi** [comment]
@BridgeAR, thank you for your response. After reading that you're pretty sure the TLSWrap objects have nothing to do with node_redis, to eliminate redis-server side problem I've created a script to check my redis server connection timing from some instances during the latencies, and the log files showed that the problem is not with the redis server.

After some load testing on qa, today we've figured out that the latency problems were probably because of many requests (~120K per minute on peaks) that our application need to send to another server. We've changed the architecture a bit and in QA there were no latencies again. Tonight (UTC) we will test on production. I'll close this issue, hope no latencies will occur.

Thank you very much for your professional and fast responses & support.

**Comment by BridgeAR** [comment]
@eli-zehavi you're welcome. I'm glad I was able to help.

**Comment by bibliata** [comment]
Sorry to jump on this a whole decade later, but this also occurs with current Redis version 

root:~# redis-cli --stat

38250349 9.86G 223 0 623 (+7) 767 LOAD
38562520 9.94G 224 0 631 (+8) 775 LOAD
38874990 10.02G 237 0 637 (+6) 793 LOAD
39185006 10.09G 236 0 642 (+5) 796 LOAD
39506536 10.17G 235 0 654 (+12) 806 LOAD
39830487 10.25G 232 0 665 (+11) 813 LOAD
Reconnecting…
1129125 336.97M 1 0 9 (+-656) 10 LOAD
1664863 472.34M 1 0 17 (+8) 17 LOAD
2286036 660.19M 2 0 23 (+6) 22 LOAD
2807568 792.65M 1 0 27 (+4) 25 LOAD

Any workaround? 
The total file is ~27Gb and worked until the last Redis update
//THANKS
