### ISSUE TITLE
Options defaulting to empty was removed

### ISSUE THREAD

**Issue by tfemiani** [NodeRedis/node_redis#893]
In the most recent closed PR, defaulting of `options` to `{}` was removed. (see https://github.com/NodeRedis/node_redis/pull/891/files#diff-168726dbe96b3ce427e7fedce31bb0bcL36)

This causes the following line to fail when options is not supplied:
`JSON.parse(JSON.stringify(options))`

The error looks like..
```
undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at new RedisClient (/Users/tfemiani/src/platapi/api-cart/node_modules/fakeredis/node_modules/redis/index.js:39:20)
```

**Comment by tfemiani** [comment]
@BridgeAR - FYI

**Comment by BridgeAR** [comment]
True, I did not take into account that someone might not use the redis own .createClient function. Thanks for pointing that out. I'll release a new version in a few minutes.
