### ISSUE TITLE
Zscan command gives issue

### ISSUE THREAD

**Issue by vabnirvana** [NodeRedis/node_redis#896]
Hi,

I want to use 'ZSCAN' command but it throws the following.

Error:
Redis Error { [Error: ERR syntax error] command: 'ZSCAN', code: 'ERR' }

Code:
 connection.zscan(key , 0 , {match : value + "*"} , function(err,data){
                        if(err){
                            console.log("Redis Error",err);
                            return err;
                        }else
                            cb(null,data);
                    });

Please guide me as to the proper usage of this. Thanks.

**Comment by BridgeAR** [comment]
@vabnirvana The following should work:
```js
client.zscan(key, 0, 'MATCH', value + '*', callback);
```
The object notation is only supported for HGETALL.

**Comment by vabnirvana** [comment]
The result is ["0" , []] always empty array in all cases.

**Comment by BridgeAR** [comment]
I just wrote a test for it and it works as it should for me. Please check your key or pattern to really match your entries.
