### ISSUE TITLE
Multi Callback not triggered

### ISSUE THREAD

**Issue by KeKs0r** [NodeRedis/node_redis#899]
I am using Kue and trying to figure out, why one of its functions is not callling the callback.

It turns out, that they are utilizing multi within that function:
```javascript
Job.prototype.remove = function( fn ) {
  var client = this.client;
  var chain= client.multi();
    chain.zrem(client.getKey('jobs:' + this.state()), this.id);
    chain.zrem(client.getKey('jobs:' + this.type + ':' + this.state()), this.id);
    chain.zrem(client.getKey('jobs'), this.id);
    chain.del(client.getKey('job:' + this.id + ':log'));
    chain.del(client.getKey('job:' + this.id));
    var handler = function( err ) {
//            events.remove(this);
      events.emit(this.id, 'remove', this.type);
      if( !exports.disableSearch ) {
        getSearch().remove(this.id, fn);
      } else {
        fn && fn(err);
      }
    }.bind(this);
    chain.exec(handler);
  return this;
};
```
I debugged it, and the only thing I see is that within the exec implementation, that this also never triggers the callback:

```javascript
    // TODO - make this callback part of Multi.prototype instead of creating it each time
    return this._client.send_command("EXEC", [], function (err, replies) {
        // Never called
     }
```

**Comment by BridgeAR** [comment]
@KeKs0r kue uses a old version of node_redis and this part was refactored quite a bit in newer versions.

Do you have a standalone example that does not work? I can't promise to look into it soon as I'm really busy these days but if, I'll check and try to fix it in kue.

**Comment by KeKs0r** [comment]
@BridgeAR Thanks for the note. I just issued the exact same commands with my the current node_redis client and it works. So it seems to be fixed, but just not in the version kue is using. I am gonna open an issue there.
