### ISSUE TITLE
return_buffers with pub/sub is broken since 2.2.0, detect_buffers - since 2.0.0

### ISSUE THREAD

**Issue by komachi** [NodeRedis/node_redis#911]
I wrote a simple code to demonstrate the bug. As return_buffers works in 2.1.0, var msg is not a buffer in 2.2.0 and later (it's just a string). Same with detect_buffers, but it's broken since 2.0.0.

```js
var redis = require('redis');
var bufferEquals = require('buffer-equals');
var pub = redis.createClient();
var sub = redis.createClient({return_buffers: true});
var sub2 = redis.createClient({detect_buffers: true});
var buff = new Buffer('testtest');
sub.subscribe('test', function() {
  pub.publish('test', buff);
});
sub.on('message', function(pattern, msg) {
  console.log('return_buffers');
  if (Buffer.isBuffer(msg) && bufferEquals(buff, msg)) {
    console.log('it\'s a buffer and it\'s correct');
  } else if (Buffer.isBuffer(msg)) {
    console.log('it\'s a buffer, but damaged');
  } else {
    console.log('it\'s not a buffer');
  }
});
sub2.subscribe('test2', function() {
  pub.publish('test2', buff);
});
sub2.on('message', function(pattern, msg) {
  console.log('detect_buffers');
  if (Buffer.isBuffer(msg) && bufferEquals(buff, msg)) {
    console.log('it\'s a buffer and it\'s correct');
  } else if (Buffer.isBuffer(msg)) {
    console.log('it\'s a buffer, but damaged');
  } else {
    console.log('it\'s not a buffer');
  }
});
```

It breaks socket.io-redis, as you can see here socketio/socket.io-redis#17

``return_buffers`` and ``detect_buffers`` works as expected with ``get`` and most likely other commands, so the problem is probably related only to pub/sub.

**Comment by BridgeAR** [comment]
@komachi return_buffers can be fixed but detect_buffers can't. The used mechanism is that it checks the input for a buffer and returns a buffer for that arg if one is present in the client that actually also sent the command.
If you publish a message it'll pop up for any subscribed client and that client has no idea about the input type. Before 2.0 detect_buffers did not work properly either, so it just behaved differently wrong ;) (At least if I'm not horribly missing something).
