### ISSUE TITLE
connection.spec.js tests doesn't use different connection options

### ISSUE THREAD

**Issue by epoberezkin** [NodeRedis/node_redis#915]
It doesn't use options supplied by helper.allTests - all test runs use default settings

**Comment by epoberezkin** [comment]
My bad... not broken

**Comment by epoberezkin** [comment]
although point 1 still seems to apply. Unless I am missing something.

**Comment by BridgeAR** [comment]
The tests are redundant but otherwise this is nothing bad. The connection.spec does not need any provided options from that function. As long as the test suite does not take very long it's not of big concern in my opinion. But feel free to remove the redundancy if you want to.

**Comment by epoberezkin** [comment]
Redundancy is fine. I was a bit confused originally. 

By redundancy do you mean that it essentially runs the test with the same options multiple times?

The only confusing thing here that it creates impression (from the test log) that it uses multiple connection options, so it would be cleaner not to use helper.allTests here.

But I agree it is not critical.
