### ISSUE TITLE
Promisify broken!

### ISSUE THREAD

**Issue by jhohlfeld** [NodeRedis/node_redis#916]
Hello everyone,

I am using node_redis 2.2.5

I think the promisification might break in this version. Follwing the README.md brought no success:

```javascript
var redis = require('redis');
bluebird.promisifyAll(redis.RedisClient.prototype);
```

I also tried using the approach as seen in https://github.com/NodeRedis/node_redis/issues/606#issue-35954745:

```javascript
var Promise = require("bluebird");
Promise.promisifyAll(require("redis"));
var db = redis.createClient...
db.getAsync(key).then()
...
```

And finally:

```javascript
var redis = bluebird.promisifyAll(require('redis'));
```

However, I could not use the .then() interface at all:

```javascript
// var redis = require('redis');
// bluebird.promisifyAll(redis.RedisClient.prototype);
var redis = bluebird.promisifyAll(require('redis'));
var client = redis.createClient(_options.redisUrl);
client.hgetall(_hash).then( /*...*/ );
```

The VM simply keeps saying _TypeError: client.hgetall(...).then is not a function_. Is there a problem with the current implementation of _node_redis_ or am i just too stupid to do it right?

cheers

Jakob

**Comment by jhohlfeld** [comment]
I have to add, the current tag [v.2.3.0](https://github.com/NodeRedis/node_redis/tree/v.2.3.0/) seems to have this error as well.

**Comment by BridgeAR** [comment]
@jhohlfeld please use `client.hgetallAsync(_hash).then(res => {});` as described in the [readme](https://github.com/NodeRedis/node_redis/blob/master/README.md)
