### ISSUE TITLE
Dead code in RedisClient.send_command

### ISSUE THREAD

**Issue by VanTanev** [NodeRedis/node_redis#918]
There following line seem to do nothing:
https://github.com/NodeRedis/node_redis/blob/42e979b1af844abb815469dceff6b37e05e3e210/index.js#L735

**Comment by BridgeAR** [comment]
True indeed. There is a typo in that line and it's covered by a later line that should be removed instead after fixing this. Thx for pointing this out.

**Comment by VanTanev** [comment]
Thanks for your quick reaction.
Have a great day :)
