### ISSUE TITLE
Another createClient overload?

### ISSUE THREAD

**Issue by Janpot** [NodeRedis/node_redis#919]
I would like to propose another overload for the `createClient` method. One that accepts another client to copy its parameters from.

```
var client1 = redis.createClient();
var client2 = redis.createClient(client1);
```

This would help library authors that accept a client as input to clone it to do things like pubsub.

**Comment by simontabor** [comment]
I quite like this idea, but could you not use

```js
var client1 = redis.createClient();
var client2 = redis.createClient(client1.address);
```

Of course, this wouldn't copy the other options (or database) which could be quite useful.

**Comment by BridgeAR** [comment]
Sounds reasonable. But I suggest to add a new function instead of overloading createClient further or add a options to the options object. But the later might be more confusing. Using `client.clone(options)` would also allow to override some old options and copy all others.

**Comment by BridgeAR** [comment]
This will be released with v.2.4
