### ISSUE TITLE
Question about Blop in redis client

### ISSUE THREAD

**Issue by TidyHuang** [NodeRedis/node_redis#921]
Not sure if it suitable to raise a question here.

I am using API createClient to connect redis server and use blpop API to watch an list message. It seems everything goes fine. However, after the server restart, the client can't be notified when the block list change while the client can get the reconnecting message.

Any ideas please. 

Code:

--------------------------------
rclient = redis.createClient(port, host);

rclient.on('reconnecting', onReconnecthandle);
rclient.on('error', onErrorhandle); 
rclient.on('end', onEndhandle);

rclient.blpop('my_list', 0, function(err, data) {
});

--------------------------------

**Comment by BridgeAR** [comment]
The net keep alive function should detect that redis is down and report this to the client. I'm uncertain how well this works though with a blocking command pending.

**Comment by simontabor** [comment]
Hey @TidyHuang, are you saying that after a reconnection, the blpop command doesn't give you any data (if it was waiting)? For me it calls back with an error (`UNCERTAIN_STATE`), so you'd need to re-issue the command after reconnection.

**Comment by TidyHuang** [comment]
Thanks @BridgeAR and @simontabor for your watching!
@simontabor , Yes.  the blpop command can't get any data.   Since I a newer to Node, I am not quite understand why I need re-issue the command after reconnection?  I assume the redis client created by API "createClient" didn't change even after the reconnection, so the function call blpop should be called.

**Comment by BridgeAR** [comment]
@TidyHuang yes, right now you have to send the command again after the connection is lost. This is necessary due to the fact that we can't guarantee that the command did not alter anything in the meanwhile.

I'll add a option to resubmit the command after a reconnect for all non altering commands and or all commands in general. That you everyone is able to decide on their own what to favor.

**Comment by TidyHuang** [comment]
@BridgeAR , Got it, thanks a lot.
