### ISSUE TITLE
Plan for cluster support

### ISSUE THREAD

**Issue by SeongJongJeon** [NodeRedis/node_redis#922]
Is there any plan for cluster support?
Redis 3 has been stable version

**Comment by BridgeAR** [comment]
Duplicate of #574. I would like to add cluster support, but I do not have the time right now to do it on my own. Please use https://github.com/gosquared/redis-clustr in the meanwhile.

**Comment by geoyws** [comment]
It's been 3 years and still no cluster support... :(
