### ISSUE TITLE
multi sadd problem when arg is string type

### ISSUE THREAD

**Issue by europelee** [NodeRedis/node_redis#930]
'use strict';

var redis  = require('redis');
var client = redis.createClient();
var multi = client.multi();

var gwId = 'n+BpEu54evG+wbv2ql+jaQ==';
var mIdSet = new Array();
mIdSet.push(gwId);

var mSet = new Array();
mSet.push('owner', 'eu');

//multi.sadd('multi:test'+':'+'eu'+':'+'post', gwId, client.print);//if I use gwId string directly, 'undefined' add!
multi.sadd('multi:test'+':'+'eu'+':'+'post', mIdSet, client.print);//if I use mIdSet,  'undefined' not added!
multi.hmset('multi:test2'+':'+gwId, mSet, client.print);
multi.exec(function(err, ret) {
        console.log(ret);
        client.quit();
});

so i guess  arg will be converted into a array in multi internal, but why  a 'undefined' added int arg-array when arg(string type) converted?

**Comment by BridgeAR** [comment]
@europelee what node_redis version do you use?

**Comment by BridgeAR** [comment]
You use `client.print` instead of `redis.print`, so the function is undefined.

**Comment by europelee** [comment]
oh, my gosh! you are right, thanks!

**Comment by BridgeAR** [comment]
You're welcome :)
