### ISSUE TITLE
del command not working on v2.4.x

### ISSUE THREAD

**Issue by adrai** [NodeRedis/node_redis#933]
When updating to v2.4.x deleting a key seams not to work anymore...

to reproduce just: set, del, get

sorry I'm on my mobile...

**Comment by BridgeAR** [comment]
What exactly are you doing? Our tests pass and I can't reproduce this.

**Comment by adrai** [comment]
works: https://travis-ci.org/adrai/sessionstore/builds/87406290
does not work: https://travis-ci.org/adrai/sessionstore/builds/96574277
my tests: https://github.com/adrai/sessionstore/blob/master/test/sessionStoreTest.js#L213

**Comment by BridgeAR** [comment]
I can't reproduce the failure on my local machine either. I also checked if the key has been removed and it works properly.

**Comment by BridgeAR** [comment]
The reason why this is failing for you is, that you pass options.prefix to redis and this is a supported option from 2.4 on. So you double prefix your keys and your clear function does not work as it should anymore.

**Comment by adrai** [comment]
Ohhh, thx and sorry.

**Comment by BridgeAR** [comment]
@adrai anytime
