### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by BridgeAR** [NodeRedis/node_redis#944]
Hey there,

node_redis became an organization a few months ago. Since then, several people have made wonderful contributions to the project, and a lot of amazing work has been done. There's still a lot of work to do, but the project is again moving forward at a great pace.

Recently I've had it on my mind that I'd like to do a bit of house cleaning in the organization. I'd like to give developers, both new and old, the opportunity to continue working on node_redis. I'd also like to give @NodeRedis/contributors no longer interested in the project a chance to bow out.

Here's what I'm proposing, over the next seven days I'd like everyone who's interested in continuing to collaborate as a core member of the node_redis organization to reply to this thread.

If you're new to the project, and would like to be a core maintainer also please don't hesitate to reply to this thread.

My goal is to make sure that folks who interact with the node_redis organization have a clear idea of a core group of individuals they can reach out to who are highly involved with the project.

**Comment by simontabor** [comment]
I'd love to continue to be a collaborator. Unfortunately I'm going to be very busy for a while as I've just founded a company, but after things settle down a bit I can continue to jump on some issues/discussions and hopefully find time to implement and maintain cluster functionality soon.

**Comment by stockholmux** [comment]
I'm into continuing.

**Comment by bcoe** [comment]
@BridgeAR I'd love to continue contributing, I've been buried under the workload of npm and a few other OSS projects lately (`yargs`, `nyc`) but `node_redis` is close to my heart.

**Comment by blainsmith** [comment]
Same with me. Busy as well given the new company starting. We use redis heavily so I'd love to continue to try and give back.

**Comment by BridgeAR** [comment]
Thanks a lot for wanting to keep the project running. I removed the maintainers who did not reply back.
