### ISSUE TITLE
 endlessly reconnection despite the max_attempts configuration

### ISSUE THREAD

**Issue by jerep6** [NodeRedis/node_redis#945]
Hello,

When the connection is lost between nodejs client and redis, the library is trying to reconnect indefinitely despite the "max_attempts" configuration. 

My quick debug shows that in the "retry_connection" function, the "self.attempts" variable is always equal to 1. Likewise, the "self.delay" variable which is always set to its initial value, which is setted in "initialize_retry_vars".

Please see below the instructions to reproduce the problem.

Thanks !
Bests

var redis = require('redis');
// Create client
var client = redis.createClient({
  host: 'localhost',
  port: 6379,
  max_attempts: 0,
  retry_delay: 800
});

client.on('reconnecting', function (data) {
  console.log('reconnecting', JSON.stringify(data));
  // output : reconnecting {"delay":200,"attempt":1}
});

client.on('error', function (err) {
  console.log('error');  
});

client.on('ready', function () {
  console.log('ready');
});

OUTPUT:
error { [Error: Redis connection to localhost:6379 failed - read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error { [Error: Ready check failed: Redis connection lost and command aborted in uncertain state. It might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
error { [Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
reconnecting {"delay":200,"attempt":1}

error { [Error: Redis connection to localhost:6379 failed - read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error { [Error: Ready check failed: Redis connection lost and command aborted in uncertain state. It might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
error { [Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
reconnecting {"delay":200,"attempt":1}

error { [Error: Ready check failed: Redis connection lost and command aborted in uncertain state. It might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
error { [Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
reconnecting {"delay":200,"attempt":1}

error { [Error: Ready check failed: Redis connection lost and command aborted in uncertain state. It might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
error { [Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
reconnecting {"delay":200,"attempt":1}

error { [Error: Ready check failed: Redis connection lost and command aborted in uncertain state. It might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
error { [Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.] code: 'UNCERTAIN_STATE', command: 'INFO' }
reconnecting {"delay":200,"attempt":1}

**Comment by BridgeAR** [comment]
Please check the docs: 
```
max_attempts: 0; By default client will try reconnecting until connected.
Setting max_attempts limits total amount of connection tries.
Setting this to 1 will prevent any reconnect tries.
```
The main problem here is the name of the variable. It says: "max attempts" instead of "max reconnection attempts". I might deprecate the old name for v.3.0.
