### ISSUE TITLE
client.zmemrangebyrank doesn't seem to exist

### ISSUE THREAD

**Issue by jhiver** [NodeRedis/node_redis#949]
client.send_command("zmemrangebyrank", [ args... ], callback) # works though

**Comment by BridgeAR** [comment]
Seems like you have a typo in the command name. It should be `zremrangebyrank`. You should always get an error back from redis using `.send_command('zemrangebyrank', args, cb)`.

**Comment by jhiver** [comment]
Total typo -sorry 'bout that :-)
