### ISSUE TITLE
`RedisClient(stream, options)` does not work anymore, reimplement it

### ISSUE THREAD

**Issue by FGRibreau** [NodeRedis/node_redis#950]
`RedisClient(stream, options)`  does not work anymore. This ticket is here to re-implement socket support.

Proposal:

- `redis.createClient({socket:socket})`
- `option = clone(option);` will erase socket value, thus I will have to find another way.
- `create_stream` should then be renamed or a least take into account `options.socket`

[edit] the issue was not about `redis.createClient(unix_socket, options)`  but about `RedisClient(stream, options)`

**Comment by BridgeAR** [comment]
May I ask for the use case?
The former behavior was never documented and therefor not officially supported.

**Comment by FGRibreau** [comment]
Hello @BridgeAR :)

Thanks for your quick response! Well it [has always been documented](https://github.com/NodeRedis/node_redis/pull/951/files#diff-04c6e90faac2675aa89e2176d2eec7d8R172) and officially supported.

I don't think it's a good idea to override an external method from a vendor library, moreover it's not "future proof" as we should keep our overrided method with node-redis internal implementation (see the code below):


```js
RedisClient.prototype.create_stream = function () {
// our own code to set "this.stream

this.stream.once(connect_event, function () {
        this.removeAllListeners("timeout");
        self.on_connect();
    });

    this.stream.on('data', function (buffer_from_socket) {
        // The buffer_from_socket.toString() has a significant impact on big chunks and therefor this should only be used if necessary
        debug('Net read ' + self.address + ' id ' + self.connection_id); // + ': ' + buffer_from_socket.toString());
        self.reply_parser.execute(buffer_from_socket);
    });

    this.stream.on('error', function (err) {
        self.on_error(err);
    });

    /* istanbul ignore next: travis does not work with stunnel atm. Therefor the tls tests are skipped on travis */
    this.stream.on('clientError', function (err) {
        self.on_error(err);
    });

    this.stream.once('close', function () {
        self.connection_gone('close');
    });

    this.stream.once('end', function () {
        self.connection_gone('end');
    });

    this.stream.on('drain', function () {
        self.drain();
    });

    if (this.options.socket_nodelay) {
        this.stream.setNoDelay();
    }

    // Fire the command before redis is connected to be sure it's the first fired command
    if (typeof this.auth_pass === 'string') {
        this.do_auth();
    }
```

**Comment by FGRibreau** [comment]
Before this PR on master:

```
1425 passing (2m)
8 pending
10 failing
```

after this PR:

```
1425 passing (2m)
8 pending
10 failing
```

no regression were introduced @BridgeAR

**Comment by BridgeAR** [comment]
This is indeed not very specific but it was not possible to pass a stream as option but what is meant by this option is the unix socket connection string e.g. `'/tmp/redis.sock'`. Only the RedisClient class had a second option that allowed passing the stream. But this was not documented before.

I actually decided not to change the .create_stream function so it is supported to mock that function. I'm still not sure what use case you have for it though. I can't think of a logical use case besides faking the redis stream to mock redis. And in this case I'll be open to open a PR for any library that wants to do this.

**Comment by FGRibreau** [comment]
> This is indeed not very specific but it was not possible to pass a stream as option but what is meant by this option is the unix socket connection string e.g. '/tmp/redis.sock'. Only the RedisClient class had a second option that allowed passing the stream. But this was not documented before.

You are right, my mistake! In fact it was possible but only using node-redis v0.12.1 [RedisClient constructor](https://github.com/NodeRedis/node_redis/blob/v0.12.1/index.js#L36) since it was and always is publicly accessible :)

> I actually decided not to change the .create_stream function so it is supported to mock that function

Indeed, but the issue is (as I demonstrated above) that in order to support the use-cases below the developer would have to copy/paste some code from create_stream implementation to match node-redis current implementation and that's not a good idea for maintainability issues, I'm sure you will understand ^^

Some use-cases from the top of my head:

- using node-redis with a reverse-proxy with its own authentication scheme in front of a redis cluster (delegate the socket creation and authentication handling to the developer before using it in node-redis).
- using node-redis along with a socket-like (something that don't rely on nodejs net/tls implementation but implements its interface)
- I can't disclose here our specific use-case but I sent you an email with details :)
- a lot of other cases that node-redis can't and should not handle but still need to be open for extension
