### ISSUE TITLE
[Q] Autoexpire keys matching a regex after a certain limit on number is reached

### ISSUE THREAD

**Issue by MrDHat** [NodeRedis/node_redis#954]
This is probably, more of a redis question than node-redis.

I have a use case where I want to store only certain amount of keys with a specific prefix.
For ex: I want only 100 keys to be active at a time matching `user:*`. Rest of them should be evicted following FIFO or LRU.

Is it possible to do this?

**Comment by BridgeAR** [comment]
Hm, you would either have to solve this in your code / write a lib that does that or you might want to use the redis built-in [LRU](http://redis.io/topics/lru-cache). There is not specific option for the prefix in the later case though.
