### ISSUE TITLE
Example code for SCAN is buggy and can mislead users

### ISSUE THREAD

**Issue by VanTanev** [NodeRedis/node_redis#957]
[The example code](https://github.com/NodeRedis/node_redis/blob/7922d4eb8552b287b30a18a744c9ab27674c12e5/examples/scan.js#L19-L32) has the `if (cursor === '0')` check before the check for results, even though a `cursor ` of zero does not mean no results. It means that this is the last iteration, and there might still be results to process. 

The check for number of results should be before the check for cursor end.

It might be worth driving home the point that results and `cursor` vary independently, giving 4 distinct possibilities. I tried to llustrate it with an async processing function.
```javascript
function(err, res) {
  if (err) throw err;

  // Update the cursor position for the next scan
  cursor = res[0];
  var results = res[1];

  if (results.length !== 0) {
    // process results
    someAsyncProcessor(results, function(err) {
      if (err) throw err;

      if (cursor !== '0') {
        // next iteration
        return scan();
      } else {
        // end scan
        return;
      }
    })
  } else {
    // no need to invoke the async processor when no results
    if (cursor !== '0') {
      return scan();
    } else {
      // end scan
      return;
    }
  }
}
```

**Comment by BridgeAR** [comment]
I never really looked through the examples but I would be glad if you could open a PR to fix them :)

**Comment by VanTanev** [comment]
@BridgeAR OK, will add some comments to my code and open a PR later in the week, once work lets up a bit ;)

**Comment by BridgeAR** [comment]
:+1:
