### ISSUE TITLE
URL doesn't support db number

### ISSUE THREAD

**Issue by jheusala** [NodeRedis/node_redis#958]
I was trying to set database in the URL but it was still using default database `0`.

Options I tried were:

* http://redis://x.y.z.174:6380/15
* http://redis://x.y.z.174:6380/15?db=15

...both still used database `0`

My redis was 2.4.2, although one dependency is using version 2.3.0... however my own code where this didn't work should use 2.4.2 version.

**Comment by BridgeAR** [comment]
The `db` option is supported from v.2.5 on.

I made a made a mistake by merging some part of the next release to early. I have very limited time right now, but it'll be out soon, it just needs some more polishing.

**Comment by fiznool** [comment]
This is [now fixed on master](https://github.com/NodeRedis/node_redis/commit/a4285c156c5b8964d92a36bd7f361a6f40e2449a).

Is there an ETA for another npm release to fix this issue?

**Comment by BridgeAR** [comment]
I just released [2.5.0-1](https://github.com/NodeRedis/node_redis/releases/tag/2.5.0-1)
