### ISSUE TITLE
MSGPack vs JSON for key data storage?

### ISSUE THREAD

**Issue by McFarts** [NodeRedis/node_redis#964]
Do you know which would be faster?

I know json.parse is native, so it's superfast already, but msgpack holds less bytes and thus, less data needs to be stored & retrieved when using `get`.

**Comment by BridgeAR** [comment]
This question has nothing to do with this library. Please only ask questions about node_redis here.

If you want to compare this, please google for a jsperf comparison.

**Comment by McFarts** [comment]
Yes it does have to do with this library because we can store that type of data inside Redis.
