### ISSUE TITLE
return_buffers option doesn't affect eval/evalsha commands

### ISSUE THREAD

**Issue by bsnote** [NodeRedis/node_redis#979]
```
var client = redis.createClient({return_buffers: true});

client.eval('return 1', 0, function(error, reply) {
  console.log(typeof reply);  // prints "number"
});
```

**Comment by BridgeAR** [comment]
Numbers are not returned as buffers in general. I would like to have numbers being returned as buffers to make sure we support numbers bigger than 32bit but the [hiredis](https://github.com/redis/hiredis-node) parser does not support this right now and the js-parser tries to stay compatible to it.
