### ISSUE TITLE
zrange gets the entire set instead of specified range

### ISSUE THREAD

**Issue by mengfoobar** [NodeRedis/node_redis#983]
Hi, I encountered a bug when using **zrange**. If I specify a range, for some reason it retrieves the entire set instead of just the ones in range. This is the call I made:

`            RedisClient.zrange("timestamp", 0, 100,function(err,result){
                console.log(result);
                resolve(true);
            })`

The full set is: 

![selection_009](https://cloud.githubusercontent.com/assets/15919186/13208432/dccd0f40-d8e6-11e5-8026-4cc3b1ccc8d0.png)

The result is:
`Successfully connected to Redis server budget DB
[ '56c26b8b33d008e101020026',
  '56c26b8b33d008e101020040',
  '56c26b8b33d008e101020030' ]
`
As shown, only the first id should be returned.

Can someone look into it to see if there is a bug?

**Comment by stockholmux** [comment]
I think that you are looking for 'zrangebyscore' rather than 'zrange'.

**Comment by BridgeAR** [comment]
The returned set is going to be from range 0 - 100. This is no bug in node_redis. Please check [zrange](http://redis.io/commands/ZRANGE)

**Comment by mengfoobar** [comment]
@stockholmux  thanks! did not know that was an option
