### ISSUE TITLE
Cannot require redis : "Cannot find module 'hiredis'"

### ISSUE THREAD

**Issue by Vloz** [NodeRedis/node_redis#985]
When i require('redis'); it throws me a 
`Cannot find module 'hiredis' @ modules.js:341`

Tried to `npm i hiredis` but then i get another MODULE_NOT_FOUND error:
`Cannot find module '***/node_modules/hiredis/build/hiredis.node' @ module.js:341`

hiredis.node is actually under build/**Release**/ folder.

Am i doing something wrong?

**Comment by BridgeAR** [comment]
@Vloz what node_redis version do you use? And what build system?

**Comment by Vloz** [comment]
@BridgeAR I m using 4.1. 
I dunno what you exactly stand for "build system" (i m new to node), i m using npm with plain javascript files (without gulp/grunt/ts) and the hiredis package is autobuilt with Make.

I run the file this way:
`node --debug-brk=6373 --nolazy web/server.js `

Content of server.js:
```
var redis = require("redis");
//that's it
```

I m working on Manjaro Linux and i did install the [hiredis client library](https://www.archlinux.org/packages/community/x86_64/hiredis/)

**Comment by Vloz** [comment]
Thats' probably related to my use of vscode since it works with `node debug`, i ll check further sorry. :S

**Comment by BridgeAR** [comment]
Sorry I misunderstood what you did earlier.

`npm i hiredis` should not throw that error and should install hiredis-node without any issues. You do not have to built hiredis on your own.

**Comment by BridgeAR** [comment]
I'm sorry but I doubt that I can help you any further with this.

**Comment by Vloz** [comment]
My debugger was actually set to break even on caught exceptions (like the one @ index.js:25)...
Everything runs fine... I m really sorry. :S
Thank you for your work! ;)
