### ISSUE TITLE
Empty documentation page

### ISSUE THREAD

**Issue by bschwind** [NodeRedis/node_redis#992]
Result from going to [http://redis.js.org/](http://redis.js.org/)

<img width="1440" alt="screen shot 2016-02-29 at 11 44 39 am" src="https://cloud.githubusercontent.com/assets/458432/13384551/045f0920-deda-11e5-808e-b50d5b13572f.png">

Seems an API limit was reached with github?

**Comment by stockholmux** [comment]
Looks like that is a client-side rate limit, so the error would only be affecting you or your IP. Seems to be working for me over a couple of different IPs for me. I'm going to go ahead and close this issue.

**Comment by BridgeAR** [comment]
@bschwind I guess you use a proxy that is used by a massive number of people. 

This is limited by github itself. Check https://developer.github.com/v3/#rate-limiting and to see your current limit: https://api.github.com/rate_limit

**Comment by bschwind** [comment]
I see, thanks for the quick response! This was on a company network in Tokyo so I'll do some investigating.
