### ISSUE TITLE
Please work on next version on a feature branch, so that README is accurate

### ISSUE THREAD

**Issue by fiznool** [NodeRedis/node_redis#996]
Currently the README docs do not represent what is available when you `npm install redis`.

IMO it would be cleaner to work on the next version on a separate branch, and keep `master` as whatever was last released. This is so that users coming to Github and reading the README aren't viewing docs for features that are not yet available.

I've just been stung by this, thinking that I could use the `db` parameter on the Redis URL, when this isn't yet available on the current npm release (2.4.2).

Thanks!

**Comment by BridgeAR** [comment]
This is definitly right and it was a mistake to merge the things as they were. But there was more to do until I felt it is right to releae that. Right now there is a 2.5 branch and I have to fix some tests not running on windows and add some more docs but besides that everything is looking good and this is going to be released very soon.

**Comment by fiznool** [comment]
Great, thanks! 😀

**Comment by BridgeAR** [comment]
[2.5.0-1](https://github.com/NodeRedis/node_redis/releases/tag/2.5.0-1) is out :)
